### ISSUE TITLE
Issue with "git submodule update"

### ISSUE THREAD

**Issue by nejt** [LiskHQ/lisk#1]
git submodule update
Cloning into 'public'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is *#*#*#*#*#*#*#
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:LiskHQ/lisk-ui.git' into submodule path 'public' failed

**Comment by MaxKK** [comment]
You created a ssh key pair with a password? Check out this:

http://askubuntu.com/questions/311558/ssh-permission-denied-publickey

**Comment by nejt** [comment]
Works with generated key pair.
