### ISSUE TITLE
How to debug not responding app.js?

### ISSUE THREAD

**Issue by c2h2** [LiskHQ/lisk#1023]
Sorry, not very familiar with node.js. But I really like to try out.

I followed README to install everything with ubuntu 16.04.

```
> node app.js

NOTICE:  view "blocks_list" does not exist, skipping
NOTICE:  view "full_blocks_list" does not exist, skipping
NOTICE:  view "trs_list" does not exist, skipping
NOTICE:  trigger "protect_mem_accounts" for relation "mem_accounts" does not exist, skipping
NOTICE:  function revert_mem_account() does not exist, skipping
NOTICE:  ALTER TABLE / ADD CONSTRAINT USING INDEX will rename index "peers_unique" to "address_unique"
NOTICE:  function rounds_fees_init() does not exist, skipping
NOTICE:  trigger "rounds_fees_delete" for relation "blocks" does not exist, skipping
NOTICE:  function round_fees_delete() does not exist, skipping
NOTICE:  trigger "rounds_fees_insert" for relation "blocks" does not exist, skipping
NOTICE:  function round_fees_insert() does not exist, skipping
NOTICE:  Calculating fees for rounds, please wait...
```

After that nothing else appears... http://localhost:8000 has nothing.

How do I debug?

**Comment by 4miners** [comment]
@c2h2 I need few details to help you with that issue:
- which branch are you using?
- did you check log file?
- did you start with empty database or did you loaded some snapshot into it?

**Comment by c2h2** [comment]
@4miners master

- master
- not sure which log to check
- emptied pg db

**Comment by 4miners** [comment]
@c2h2 Node can looks like it stuck because by default log output to console is disabled, you can enable it by change `config.json` file and set `consoleLogLevel` to one of following: `info`, `debug`, `trace`, then restart application.
Logs are stored in `logs/lisk.log` file and are enabled by default - so when checking that file you should find there something more.

**Comment by c2h2** [comment]
Thanks! It is syncing Blocks now.

debug says: missing folder '/home/c2h2/lisk-c/public/images/dapps' and some other html. Do I get it from another git?

mkdir -p  '/home/c2h2/lisk-c/public/images/dapps'

**Comment by 4miners** [comment]
@c2h2 You need to init and update sumbodules, then build frontend - look at last two steps of https://github.com/LiskHQ/lisk/tree/master#installation-steps
