### ISSUE TITLE
Wrong logic in loader.__private.sync

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1024]
Following description is outdated, see: https://github.com/LiskHQ/lisk/issues/1024#issuecomment-347911566 for current one.

> There is `async.series` that executes several functions one after another. If first one (`undoUnconfirmedList`) was executed and some of next ones fail - `applyUnconfirmedList` is not executed, so we end with invalid unconfirmed balances. To fix that we need to quarantee that `applyUnconfirmedList` is always executed when `applyUnconfirmedList` execution was successfull.

**Comment by 4miners** [comment]
Calling `modules.transactions.undoUnconfirmedList/applyUnconfirmedList` here is redundant and bad, because we are calling them when apply a block anyway, logic is following:
`__.private.loadBlocksFromNetwork` -> `modules.blocks.process.loadBlocksFromPeer` -> `modules.blocks.verify.processBlock` -> `modules.blocks.chain.applyBlock` -> `modules.transactions.undoUnconfirmedList`

So is safe to remove those calls from `async.series` here. Also at the beginning of sync function we should check if block processing is active and if is - exit sync immediatelly to not interfere with block processing.

**Comment by karmacoma** [comment]
@4miners: 

#### Current (intended) behaviour during sync:

```
transaction pool filled with 25 unconfirmed transactions

undoUnconfirmedList (25 transactions undone)
getPeersBefore
loadBlocksFromNetwork (sync)
  process block
    apply block
      undo unconfirmed transactions list (0 transactions undone)
        apply unconfirmed transactions in block (25 transactions applied)
        apply confirmed transactions in block (25 transactions applied)
      apply unconfirmed transactions list (0 transactions applied)
updateSystem
getPeersAfter
applyUnconfirmedList (0 transactions applied)
```

* 0 transactions re-applied, node waits for new transactions to hit the pool
* During sync transaction pool is/should not be filled with `unconfirmed`
* It is assumed transactions previously in pool were applied by synced blocks (maybe wrong assumption)

Result: **50 transaction applications (unconfirmed/confirmed) per block synced**

---

#### Proposed PR: https://github.com/LiskHQ/lisk/pull/1033 behaviour during sync:

```
transaction pool filled with 25 unconfirmed transactions

getPeersBefore
loadBlocksFromNetwork (sync)
  process block
    apply block
      undo unconfirmed transactions list (25 transactions undone)
        apply unconfirmed transactions in block (25 transactions applied)
        apply confirmed transactions in block (25 transactions applied)
      apply unconfirmed transactions list (25 transactions applied)
updateSystem
getPeersAfter
```

When 25 transactions undone / re-applied are not part of a block synced.

Result: **100 transaction applications (unconfirmed/confirmed) per block synced**

Which would be a double performance hit during block sync.

---

#### Trace

Trace of `undoUnconfirmedList` in `sync`:

https://github.com/LiskHQ/lisk/blob/02ec62c7192f271f3f5dd993dc2a14af1e74da79/modules/loader.js#L623-L626

https://github.com/LiskHQ/lisk/blob/825a84ebd2e41c1dcd734702582c454aa44a9000/modules/transactions.js#L431-L433

https://github.com/LiskHQ/lisk/blob/d77e8a7676fd66c391c4a55e4419f5b4c9c331b5/logic/transactionPool.js#L549-L568

Result: Transactions undone from `unconfirmed` state, but remain on the `unconfirmed` queue.

Trace of `applyUnconfirmedList` in `sync`:

https://github.com/LiskHQ/lisk/blob/02ec62c7192f271f3f5dd993dc2a14af1e74da79/modules/loader.js#L641-L644

https://github.com/LiskHQ/lisk/blob/825a84ebd2e41c1dcd734702582c454aa44a9000/modules/transactions.js#L412-L414

https://github.com/LiskHQ/lisk/blob/d77e8a7676fd66c391c4a55e4419f5b4c9c331b5/logic/transactionPool.js#L527-L529

https://github.com/LiskHQ/lisk/blob/d77e8a7676fd66c391c4a55e4419f5b4c9c331b5/logic/transactionPool.js#L549-L568

Result: Transactions remaining on the `unconfirmed` queue are re-applied with `unconfirmed` state.

---

Obviously with `1.0.0` and the new transaction pool, accounts ledger design, these limitations are gone, as unconfirmed state is done in memory by the pool and do not get applied / undone at database layer. We won't have do this dance anymore.

**Comment by 4miners** [comment]
So instead of removing undo/apply beofre/after sync we will adapt logic to follow intedned behavior (https://github.com/LiskHQ/lisk/issues/1024#issuecomment-347500550). When apply unconfirmed we should add param to transaction object, then when undo unconfirmed - remove that parameter. That will protect us from apply/undo same transaction twice.

**Comment by karmacoma** [comment]
Therefore:

```
undo unconfirmed transactions list
  undo unconfirmed transaction
    if not undone then
       add undone property with value true
apply unconfirmed transactions list
  apply unconfirmed transaction
    set undone property with value false || remove undone property
```

**Comment by karmacoma** [comment]
Setting of `unconfirmed` property should probably occur here:

**In case of `unconfirmed` = true**

https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transaction.js#L832

**In case of `unconfirmed` = false**

https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transaction.js#L865

We should also think about when to delete the property.

**Comment by karmacoma** [comment]
> We need to quarantee that applyUnconfirmedList is always executed when applyUnconfirmedList execution was successful.

Let's not forget that either.

**Comment by 4miners** [comment]
Let's follow the flow once again. Everything begins from
https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transaction.js#L806 which is only called from inside https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/transactions.js#L501
Last one is only called in 2 important cases (we can skip genesis block insertion case):
1) When we applay a block, on transactions that are included in that block:
https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/blocks/chain.js#L364-L365
2) Inside transaction pool https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L753 but that private function is only called from inside of https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L525-L527 which is only called from inside of https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L607 and in loader module https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/loader.js#L633-L635

Apply block case is OK, transaction pool case is also OK, but in `fillPool` those transactions are moved to transaction pool `unconfirmed` queue and then `applyUnconfirmed` is executed. Real issue is imo bad maintenance of `unconfirmed` queue. We have that queue, so why not use it properly?
- Remove https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/loader.js#L615-L618 https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/loader.js#L633-L636
- Move https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L628-L630 to https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L753 function, so transactions will be moved to `unconfirmed` queue after they are applied to unconfirmed states successfully
- When performing https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/logic/transactionPool.js#L547 move processed transactions back to `queued` queue
- Remove https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/blocks/chain.js#L473-L480 as not needed anymore
- *OPTIONAL* Reverse those calls https://github.com/LiskHQ/lisk/blob/7b9c4608d075b82b1e7f4261389f203ef295d53e/modules/delegates.js#L602-L603 

After that behavior will be following:
```
transaction pool filled with 25 unconfirmed transactions

getPeersBefore
loadBlocksFromNetwork (sync)
  process block
    apply block
      undo unconfirmed transactions list (25 transactions undone)
        apply unconfirmed transactions in block (25 transactions applied)
        apply confirmed transactions in block (25 transactions applied)
    apply block
        apply unconfirmed transactions in block (25 transactions applied)
        apply confirmed transactions in block (25 transactions applied)
    [...]
updateSystem
getPeersAfter
```
What do you think @oliver?

**Comment by karmacoma** [comment]
@4miners This is very good 👍

It would obviously require some unit tests on the old transaction pool within changed functions.

I'm hesitant about the reversing of calls in `Delegates.prototype.onBlockchainReady`, as this would constitute a behavioural change. The reason for this ordering was due to the performance cost of transaction application, but maybe this is not required anymore.

**Comment by 4miners** [comment]
Ok, so I will continue with that proposal.
