### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by sdrpa** [LiskHQ/lisk#1030]
Installation on fresh Ubuntu 16.04 following directions from: https://github.com/LiskHQ/lisk fails. 
When I clone https://github.com/LiskHQ/lisk.git and run ```npm install``` the installation breaks:
```
git clone https://github.com/LiskHQ/lisk.git
cd lisk
npm install
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git checkout 4baed373622cc2f081600d2fdad22cfa61aea086
npm ERR! fatal: reference is not a tree: 4baed373622cc2f081600d2fdad22cfa61aea086
npm ERR!
```
```
npm -v
5.3.0
node -v
v6.10.1
nodejs -v
v6.12.0
``` 
Could you help with installation?

**Comment by sdrpa** [comment]
Also tried with guides at: 
https://docs.lisk.io/docs/core-pre-installation-source 
https://docs.lisk.io/docs/core-installation-source-test
fresh Ubuntu 16.04

Here are the steps:

// Create user
```
adduser sdrpa
usermod -aG sudo sdrpa
su - sdrpa
```
// Prerequisites
```
sudo apt-get update && sudo apt-get -y upgrade
sudo apt-get install -y python build-essential curl automake autoconf libtool
sudo apt-get install -y git

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

curl -sL "https://downloads.lisk.io/scripts/setup_postgresql.Linux" | bash -
sudo -u postgres createuser --createdb $USER
sudo -u postgres createdb lisk_test
sudo -u postgres createdb lisk_main
sudo -u postgres psql -d lisk_test -c "alter user "$USER" with password 'password';"
sudo -u postgres psql -d lisk_main -c "alter user "$USER" with password 'password';"

sudo npm install -g bower
sudo npm install -g grunt-cli
sudo npm install -g pm2
```
// Lisk Core	
```
git clone https://github.com/LiskHQ/lisk.git
cd lisk
git checkout testnet-master
npm install

wget https://downloads.lisk.io/lisk-node/lisk-node-Linux-x86_64.tar.gz
tar -zxvf lisk-node-Linux-x86_64.tar.gz
rm -f lisk-node-Linux-x86_64.tar.gz

git submodule init
git submodule update

cd public
npm install
bower install
grunt release
```
// Start 
```
cd .. // to /home/sdrpa/lisk
pm2 start --name lisk app.js // It says 'online'
```

When I run ```pm2 show lisk``` status is "errored"
```less /home/sdrpa/.pm2/logs/lisk-error-0.log``` shows
```
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sdrpa/lisk/app.js:26:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
...
```

```
npm -v
3.10.10
node -v
v6.12.0
```

**Comment by sdrpa** [comment]
I managed to install lisk core on Digitalocean Ubuntu 16.04.3 droplet. Some observations:

I couldn't compile sodium (described in the comment above), I ended up downloading lisk core docker image and extracting/coping node_modules/sodium folder, from the docker image to my installation. I tried with different versions of npm but without success, I couldn't compile sodium.

I lost some time fighting with npm, when I run npm install there would be no modules installed in node_modules. The problem was that I should not try installation on droplet with less then 2GB of memory. Once I upgraded to 2GB/2CPU droplet it just worked.

I also copied start_lisk script from docker to populate test db. (I don't know if it's necessary), but I can connect to mydroplet:7000 and will be exploring lisk.

**Comment by MaciejBaj** [comment]
PR #1046 with [updating node-sodium version commit](https://github.com/LiskHQ/lisk/commit/f7340eebef51edca07f42c9c2ff05870b41366c7) fixes the issue.

**Comment by sdrpa** [comment]
Tested. It compiles with no problems. Thank you.

I suggest also updating lisk repo. index page about the installation procedure (maybe add links pointing to https://docs.lisk.io/docs/core-pre-installation-source, https://docs.lisk.io/docs/core-installation-source-test)

Also, it seems that redis is no longer necessary, is it?

**Comment by karmacoma** [comment]
> I suggest updating lisk repo. index page about the installation procedure (maybe add links pointing to https://docs.lisk.io/docs/core-pre-installation-source, https://docs.lisk.io/docs/core-installation-source-test)

Thanks for the advice, noted.

> Also, it seems that redis is no longer necessary, is it?

It is optional.
