### ISSUE TITLE
Improve peers to db efficiency

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#104]
Currently peers information is separately inserted / updated on every API request hitting the transport module. Under heavy loads, this becomes very inefficient.

**Comment by fix** [comment]
first guess is to remove this
https://github.com/LiskHQ/lisk/blob/462d59882b878180ed39d78ed8dee4c0f1770244/modules/transport.js#L39

and include this function in some "strategic" router.get function. I think on receiving blocks could be a good start.

**Comment by fix** [comment]
linked to #135

One idea is to have 2 lists : the current peers, and the removed one.
This removed list is checked if an unknown peer arrives.

The removed list stores as well the date of removal and a score (like how many times it has been removed). The time and score tells you can retest to connect the peer after score*60s (example) after the last removal. This way bad peers don't pop up often in the networks. If finally the peer is connected, the peer can be removed from the removed list or maybe the score decreased...

**Comment by fix** [comment]
@karmacoma some codes have been implemented (the list of peers that have been removed).

Not sure there are some more strategic implementation to improve things? Also maybe move on to the issue to prevent "lite client" from being recorded to the database.
