### ISSUE TITLE
Use official bignum library

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk#1044]
Hey,

While writing tests for helpers/bignum.js, I saw that the functions fromBuffer() and toBuffer() in there seem to be basically identical to the ones of the official bignum-library:
https://github.com/justmoon/node-bignum/blob/master/index.js

Why not use the original library instead?

**Comment by karmacoma** [comment]
@Tschakki We are using the official library:

https://github.com/LiskHQ/lisk/blob/2fdb0933e834030debcbc64cd37bbb8b51e2b77a/package.json#L35-L37

We should confirm whether the function overrides are indeed identical or not in terms of behaviour.

**Comment by Tschakki** [comment]
After comparing them in detail, I found in fact a difference in the toBuffer() method: 
We use `Buffer.alloc()` instead of `new Buffer` which is better concerning the NodeJS-Docs:
https://nodejs.org/docs/latest/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe

So this issue can be closed.

**Comment by willclarktech** [comment]
Might be worth raising an issue/sending a PR to bignumber. It would be nice to delegate this responsibility to the library we use rather than handling it ourselves. (Or they might even be able to give us a good reason for using `new Buffer` rather than `Buffer.alloc`.)

**Comment by Tschakki** [comment]
This method is not part of the bignumber library, it is part of https://github.com/justmoon/node-bignum
which doesn't seem to be developed further, last commit was 2 yrs ago

**Comment by karmacoma** [comment]
After some discussion with @Tschakki we have decided the current strategy of using the official library and adding these functions is fine. Especially as we recently added unit test coverage here: https://github.com/LiskHQ/lisk/pull/1043
