### ISSUE TITLE
Change dapp store categories

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#105]
To the following:

- Adult
- Business
- Entertainment
- Education
- Finance
- Games
- Miscellaneous
- Multimedia (Music/Video)
- Networking (IoT)
- Social Media
- Science
- Utilities

**Comment by fix** [comment]
"Adult" category could be problematic for countries legislation because it implies an minimum age. I would not do it right now.

**Comment by fix** [comment]
on the same idea, we should likely add some "non reliability" statements about  DApps, ie. this is the responsibility of the DApp owner to comply with legislations.
