### ISSUE TITLE
Merge 1.0.0 into 972-integrate_accounts_and_pool

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1084]
When merging `1.0.0` at c7a509ced092e641d26f88bb8f4bd3e0eea16522 into `972-integrate_accounts_and_pool` at ae5caf4c786bfc5ce0e96117ad9c6995a79ceb4a we get the following conflicted files:

- [x] both modified:   logic/dapp.js
- [x] both modified:   logic/delegate.js
  - Validate if `checkDuplicates`, `checkConfirmed`, and `checkUnconfirmed` functionality is needed and apply new functions based on new database schema.
- [x] both modified:   logic/inTransfer.js
- [x] both modified:   logic/transaction.js
- [x] both modified:   logic/transfer.js
- [x] both modified:   logic/vote.js
- [x] both modified:   modules/delegates.js
- [x] both modified:   sql/delegates.js
  - Adjust `getDelegatesByPublicKeys` to use new table fields.
- [x] both modified:   sql/voters.js
  - Rewrite `getVotersCount` to use new database tables.
- [x] both modified:   test/functional/http/get/transactions.js
- [x] both modified:   test/functional/http/post/0.transfer.js
- [x] both modified:   test/functional/http/post/1.second.secret.js
- [x] both modified:   test/functional/http/post/2.delegate.js
- [x] both modified:   test/functional/http/post/3.votes.js
- [x] both modified:   test/functional/http/post/4.multisig.js
- [x] both modified:   test/functional/http/post/5.dapps.js
- [x] deleted by them: test/functional/shared.js
- [x] deleted by them: test/node.js
- [x] both modified:   test/unit/logic/delegate.js
- [x] both modified:   test/unit/logic/inTransfer.js
  - Replace `mergeAccountAndGet` with `getSender` and adjust logic #994 
- [x] both modified:   test/unit/logic/multisignature.js
  - Replace `mergeAccountAndGet` with `getSender` and adjust logic #994 
- [x] both modified:   test/unit/modules/blocks/process.js
- [x] both modified:   test/unit/modules/blocks/verify.js

These conflicts need to be carefully resolved.

**Comment by LucasIsasmendi** [comment]
- test/unit/logic/outTransfer.js
  - [ ] Replace `mergeAccountAndGet` with `getSender` and adjust logic
