### ISSUE TITLE
Complete missing / pending unit tests of the web socket transport

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1087]
The following files related to the websocket based P2P transport have missing or pending tests. We should write theses tests to complete the coverage. Where it does not make sense, there should be at the very least a test skeleton.

- [x] Pending: https://github.com/LiskHQ/lisk/blob/development/modules/transport.js (https://github.com/LiskHQ/lisk/blob/development/test/unit/modules/transport.js)
  - [x] constructor
    - [x] library
  - [x] __private
    - [x] removePeer
    - [x] receiveSignatures
    - [x] receiveSignature
    - [x] receiveTransactions
    - [x] receiveTransaction
    - [x] checkInternalAccess
  - [x] Transport
    - [x] poorConsensus
    - [x] getPeers
    - [x] onBind
    - [x] onSignature
    - [x] onUnconfirmedTransaction
    - [x] onBroadcastBlock
  - [x] Transport.prototype.shared
    - [x] blocksCommon
    - [x] blocks
    - [x] list
    - [x] height
    - [x] status
    - [x] postSignature
    - [x] postSignatures
    - [x] getSignatures
    - [x] getTransactions
    - [x] postTransaction
    - [x] postTransactions
  - [x] Transport.prototype.internal
    - [x] updatePeer

*EDIT* Some of the items in the checklist were moved to a separate issue https://github.com/LiskHQ/lisk/issues/1645 because they depend on a new feature which is currently being implemented.

**Comment by jondubois** [comment]
I've moved some of the points to a separate issue https://github.com/LiskHQ/lisk/issues/1645 because they depends on the lazy sockets feature https://github.com/LiskHQ/lisk/issues/1472
