### ISSUE TITLE
404 etc should respect Accept header

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1110]
### Expected behavior

Sending a request with the `Accept` header set to `application/json` should return json even for e.g. 404s. We will be doing this in LiskJS: https://github.com/LiskHQ/lisk-js/pull/539

### Actual behavior

404s return `text/html`.

### How to reproduce

`curl -H "Accept: application/json" http://localhost:4000/api/xxx`

**Comment by robladbrook** [comment]
`Content-Type` is used to describe the content type of the resource being sent by either the client or the server. So if I specify a `Content-Type` in a request, I'm telling the server that my request contains a resource of that content type - I am **not** asking the server to respond with that content type.

That's more aligned with what the `Accept` header is meant for.

**Comment by willclarktech** [comment]
Ah yes, thanks. I've opened an issue in lisk-js: https://github.com/LiskHQ/lisk-js/issues/515
