### ISSUE TITLE
Invalidate cached peers in loader.getNetwork before sync

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1161]
### Introduction

`loader.getNetwork` function is being called in 3 situations:
1. `loader.__private.loadSignatures` - once after `peersReady` system event,
2. `loader.__private.loadTransactions` - once after `peersReady` system event,
3. `loader.__private.loadBlocksFromNetwork` - called periodically by `__private.sync` method every 10 seconds (`__private.syncInterval`), maximum 5 times a row each time (`__private.retries`).

Network returned by `loader.getNetwork` will be reset (https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L132), when
`__private.sync` will fail in the following scenario:
During loading blocks from the network process, common amount of failures of one of`modules.blocks.process.getCommonBlock` and `modules.blocks.process.loadBlocksFromPeer` is above 5. 

### Current behaviour
Node posses the knowledge of the majority of Peers staying on the same chain (matching broadhash). Suddenly the majority of Peers receives the block(s) causing any of the successful fork recoveries scenarios resulting in blocks deletion. Node started the `sync` process just after. While getting the peers to sync using `loader.getNetwork` method, peers with the height below the current blockchain height are being discarded (https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L676). The result containing only nodes that didn't perform the fork recovery being in minority is being stored in `__private.network` variable. If `__private.network.height` will be exactly 1 above from the current node height, the result containing the Peers minority only will be returned every time from `loader.getNetwork` function during following `sync` processes (https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L738). This means that the Peers minority will be able to synchronize with only the peers being selected from within the group. Mentioned in introduction error will not take a place - the Peers minority is on the same chain, loading common blocks ends successfully without applying any blocks. Later, when the Peers majority moves on and recovers from the fork, their chain will keep growing. Consensus is being calculated from the updated Peers data. Forging on any of the Peers minority will not be possible, as it will not exceed desired 50% (`constants.minBroadhashConsensus`) of the agreement.
The group will stack on the same height. 

### Expected behaviour
Before (https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L126) proceeding with __private.sync until success recalculation (up to 5 times - `__private.retries`), call `__private.initialize()` function, which resets the previous network result (network.height = 0) and forces getting new peers gathering. Both the Peers majority and minority will be included there.

**Comment by SargeKhan** [comment]
I am wondering if the `findGoodPeers` function will ignore peers on a different chain (& and thus height) even if it's called based on this line: https://github.com/LiskHQ/lisk/blob/development/modules/loader.js#L709

```
		peers = peers.filter(function (item) {
			return item && Math.abs(height - item.height) < aggregation + 1;
		})
```
If the height difference is greater than `aggregation + 1`, we ignore those peers. This does not seem reasonable to me. What do you think?

**Comment by SargeKhan** [comment]
Regarding the `__private.sync` function, the `__private.syncTimer` calls `__private.sync` function using `async.retry` function with retry parameter set to 5. Here:
https://github.com/LiskHQ/lisk/blob/21dd614c44bdeec29c98cce6873ca56378fc7caf/modules/loader.js#L126

While inside the `__private.sync` function, we call `__private.loadBlocksFromNetwork`, which has a `async.whilst` function retries until success five times. This means that in case of error in `__private.loadBlocksFromNetwork`, it will run 25 times. Which should also be solved.
