### ISSUE TITLE
Add peers table migration supporting port to wsPort rename

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1167]
### Current behaviour
After #855 is done every time when application exits and peers list is not empty, following error is thrown: 
```
[ERR] 2017-12-19 16:22:57 | Export peers to database failed - {"error":"ERROR:  column \"wsPort\" of relation \"peers\" does not exist\nLINE 1: insert into \"peers\"(\"ip\",\"wsPort\",\"state\",\"height\",\"os\",\"version"}
```
Dumping peers to database after node shutdown doesn't work anymore.
### Expected behaviour
The database migration to reflect the property http to wsHttp rename is needed. Node should be able to dump peers list to database in order to insert them again during the next start.

**Comment by karmacoma** [comment]
Reopening to resolve error on migration:

```
[log] 2018-01-02 22:29:26 | error - error: ERROR:  column "port" does not exist
[log] 2018-01-02 22:29:26 | error - query: SELECT ip, port, state, os, version, ENCODE(broadhash, 'hex') AS broadhash, height, clock FROM peers
[ERR] 2018-01-02 22:29:26 | Import peers from database failed - {"error":"ERROR:  column \"port\" does not exist\nLINE 1: SELECT ip, port, state, os, version, ENCODE(broadhash, 'hex'...\n
```
