### ISSUE TITLE
Bad/Invalid db pattern

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1189]
For most of the code here: https://github.com/LiskHQ/lisk/tree/development/db

...which exhibits the following pattern - takes parameter `task`.

The idea around database repositories within [pg-promise] is to provide correct, automatic `task` context. Methods inside repositories should not take `task` as a parameter.

[pg-promise]:https://github.com/vitaly-t/pg-promise

---

And I can see that this idea is misunderstood, from the way the repository API is used everywhere in the code.

Here's just one example, of which there are plenty:

**WRONG:**

```js
function updateMemAccounts (t) {
    var promises = [
		library.db.accounts.updateMemAccounts(t),
		library.db.accounts.getOrphanedMemAccounts(t),
		library.db.accounts.getDelegates(t)
	];

	return t.batch(promises);
}
  ```

**RIGHT:**

```js
function updateMemAccounts (t) {
	var promises = [
		t.accounts.updateMemAccounts(),
		t.accounts.getOrphanedMemAccounts(),
		t.accounts.getDelegates()
	];

	return t.batch(promises);
}
```

The same kind of change is needed everywhere, and throw away `task` parameterization from all the repository classes.

**Comment by nazarhussain** [comment]
@vitaly-t Thanks for highlighting this issue. I understood this concept in the right way, and that concept was one of the reason of creating those repositories.  And that's why for all of the methods in the repositories don't have that `task` parameter. e.g. 

https://github.com/LiskHQ/lisk/blob/2bfcc2e85da1c9d88cd2e1e51f399cbd6a1757d1/db/multisignatures.js#L16-L26

The very few methods which are defined with that parameter was just to port old code without any major change in first refactoring cycle. While working through task list of parent issue #302 I would go through refactoring of that code in different cycles.

I keep the issue open for now, and will ask you again to look into that concept after completing parent task #302.

**Comment by vitaly-t** [comment]
Ah, so you are aware of that, very good!

On another note then...

LISK is set to require Node 6.x as the minimum, which means you have access to the proper class syntax, which is so much nicer than the old function style. See how it is done in [the demo(https://github.com/vitaly-t/pg-promise-demo/blob/master/JavaScript/db/repos/users.js) ;)

Also, regarding proper db API usage, I would rewrite this:

```js
return this.db.one(Queries.getMultisignatureMemberPublicKeys, [address]).then(function (result) { 
 		return result.memberAccountKeys; 
 	});
```

into this:

```js
return this.db.one(Queries.getMultisignatureMemberPublicKeys, [address], a => a.memberAccountKeys);
```

**Comment by vitaly-t** [comment]
@nazarhussain On the second review, it doesn't quite look like just a legacy code issue...

Here's an example where invalid use of the repository context will result in a broken transaction:

https://github.com/LiskHQ/lisk/blob/e7522ffd1a8954ee33b7ac7975e926de8e35b9c4/modules/blocks/chain.js#L88

It executes a query inside a transaction against the wrong connection context, with an unpredictable outcome as the result.

**Comment by nazarhussain** [comment]
@vitaly-t Related to https://github.com/LiskHQ/lisk/issues/1189#issuecomment-354960504 Yes indeed we migrate code to ES6, but in another refactoring cycle separately. 

Related to https://github.com/LiskHQ/lisk/issues/1189#issuecomment-354966928 that code block is written even before we introduce repos concept. And our main task #302 is intended to rewrite that specific code block. 

I am really excited to get your feedback, with your help we will make it 100% correct. I will loop you in as I make further progress on it in coming days.
