### ISSUE TITLE
Invalid use of Parameterized Queries

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1190]
https://github.com/LiskHQ/lisk/blob/2bfcc2e85da1c9d88cd2e1e51f399cbd6a1757d1/db/blocks.js#L51

Parameterized queries cannot make use of [Named Parameters]. Unlike regular queries, they are formatted on the server-side by definition, and therefore can only contain the basic `$1, $2...` variables.

This is just one example of it, but I see it in a few places.

[ParameterizedQuery]:http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html
[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters

---

@karmacoma  

I won't be opening any more issues against the database use in LISK, because there would be too many, no point upsetting anybody.

But to give you an idea of how much work may be there, to get it all perfectly right...

Perhaps the biggest public project on GitHub that uses `pg-promise` is [parse-server], for which I got it all right after [30+ PR-s that I did myself](https://github.com/parse-community/parse-server/pulls?q=is%3Apr+author%3Avitaly-t+is%3Aclosed), even though their code was quite good to begin with.

[parse-server]:https://github.com/parse-community/parse-server

**Comment by karmacoma** [comment]
@vitaly-t Thanks for opening this issue. There is no room for upset. We are of course very happy to see you providing advice, consultation on bad/good practices, and we will take any advice you give on board.

We will start by addressing the issues you've opened first.

Thanks 👍
