### ISSUE TITLE
Apply our eslint config

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1207]
Child of #672 
Wait for https://github.com/LiskHQ/lisk/issues/1209
This will touch most files so timing will be important. It may also push us in the direction of substantive changes (which we may or may not want to ignore for now).

This issue should also cover updating the eslint config file, and moving test-specific config into a config file in the test directory.

**Comment by ManuGowda** [comment]
Integrating `eslint-config-lisk-base` to `lisk` results in 

> 38028 problems (29191 errors, 8837 warnings)

out of 38028 problems 

> 19922 errors, 0 warnings potentially fixable with the `--fix` option.

The common errors and warnings are as listed below
- Unexpected var, use let or const instead
- Unexpected unnamed function
- Use object destructuring
- Assignment to function parameter
- Definition for rule 'mocha/no-return-and-callback' was not found
- Variable is assigned a value but never used
- Identifier not in camel case
- There should be no empty line between import groups
- Expected to return a value at the end of arrow function
- Missing trailing comma
- Space is required after/before {/}
- Mixed spaces and tabs
- 'use strict' is unnecessary inside of modules

**Comment by vitaly-t** [comment]
Not to start a flame, but I would love if insisting a space between a function and an opening bracket were thrown away. Right now I have to do inside ES6 classes: `methodName (` instead of just `methodName(`. Somehow, Webstorm screws this one for me every time.

**Comment by willclarktech** [comment]
@vitaly-t Your wish is AirBnB's command: https://github.com/airbnb/javascript/blob/7dab8371c9302cb4c228e652d376a6c2d66db4a3/packages/eslint-config-airbnb-base/rules/style.js#L449

In general, feel free to create issues in our config repo if you'd like to add/remove a linting rule: https://github.com/LiskHQ/eslint-config-lisk-base

**Comment by ManuGowda** [comment]
@willclarktech since the `eslint` integration brings in lot of errors and warnings, I have tried to fix as much I can in this PR https://github.com/LiskHQ/lisk/pull/1438. 

I have turned off following rules and mentioned specifically reasons below.

`These changes can bring behaviour changes in the application`

> "eqeqeq": 0,
> "global-require": 0,
> "guard-for-in": 0,
> "lines-around-directive": 0,
> "new-cap": 0,
> "newline-per-chained-call": 0,
> "no-var": 0,
> "radix": 0,

`These are too many to fix manually so needs everyones participation to fix them`

> "no-console": 0,
> "no-loop-func": 0,
> "no-nested-ternary": 0,
> "no-prototype-builtins": 0,
> "no-restricted-properties": 0,
> "no-restricted-syntax": 0,
> "no-shadow": 0,
> "no-template-curly-in-string": 0,
> "no-throw-literal": 0,
> "no-underscore-dangle": 0,
> "no-unused-expressions": 0,
> "no-use-before-define": 0,
> "no-useless-escape": 0,
> "strict": 0,


`These fix needs thorough check and tests might impact with these changes`

> "camelcase": 0,
> "default-case": 0,
> "no-bitwise": 0,
> "no-else-return": 0,
> "no-multi-assign": 0,
> "no-new": 0,
> "no-param-reassign": 0,
> "no-plusplus": 0,
> "no-restricted-globals": 0,
> "object-shorthand": 0,
> "one-var": 0,
> "prefer-arrow-callback": 0,
> "prefer-destructuring": 0,
> "prefer-rest-params": 0,
> "require-jsdoc": 0,
> "valid-jsdoc": 0,
> "vars-on-top": 0,
