### ISSUE TITLE
Why config.json instead of config.js

### ISSUE THREAD

**Issue by mrv777** [LiskHQ/lisk#121]
From my understanding there isn't a big difference between the two, except that config.js would allow comments to explain varies settings directly in the file.
I know this isn't a big issue, but was curios about the decision.

Absolutely no rush in responding to this :)

**Comment by karmacoma** [comment]
Simply put, JSON is a language-independent data format, JavaScript is a programming language.

Saving the configuration data in a common format is normal practice. It allows the data to be read by other applications such as lisk-rake for example.
