### ISSUE TITLE
Standardize nyc setup

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1217]
~Child of #672~

**Comment by willclarktech** [comment]
@SargeKhan This issue couldn't be completed with the previous wave of standardisation measures because of incompatibility with istanbul-middleware. I'm not sure what the problem with Coveralls is, but it sounds unrelated to this standards-focused issue.

**Comment by MaciejBaj** [comment]
We decided not to use 'nyc'. The usage of `istanbul` and `istanbul-coverage` was cleaned up by #2005 by moving it to devDependencies.
