### ISSUE TITLE
Enforce US English

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1220]
Child of #672 
Some parts of the code are in British English

**Comment by pcdinh** [comment]
> Some parts of the code are in British English
Is it really important?

**Comment by vitaly-t** [comment]
For an application that doesn't support translations or even locales, this should be pretty unimportant :smile:

**Comment by willclarktech** [comment]
This is obviously not of critical importance, but we're trying to increase the level of consistency in the codebase in general, as well as across the Lisk projects.

**Comment by karmacoma** [comment]
Rule, Britannia 🇬🇧
