### ISSUE TITLE
node-gyp requirement should be documented

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1224]
Trying to install on the 1.0.0 branch without node-gyp installed failed with unhelpful errors. This should be included in the installation instructions.

**Comment by Tschakki** [comment]
@willclarktech Why not include it in `package.json`?

**Comment by Nazgolze** [comment]
I did some looking. sodium-native does include it in package.json, so this is no longer an issue. I was able to build this on a system that otherwise does not have node-gyp installed.

I recommend closing this

**Comment by diego-G** [comment]
Thanks @Nazgolze
