### ISSUE TITLE
Wrong use of sinon.stub in unit test case

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1242]
There are 9 occurrences of `sinon.stub` method in unit test cases due to which few test may pass false positive. 

#### Crrrent Usage: 
```
sinon.stub
```

#### Expected Usage: 
```
sinon.stub()
```
Note the missing parenthesis for stub method. Due to which the function are not actually stubbed instead these are assigned to stub generator. 

![screenshot at jan 09 15-41-31](https://user-images.githubusercontent.com/112468/34726274-d48b3f1a-f553-11e7-8b4b-65823507dd05.png)

**Comment by jackson-sandland** [comment]
Hey @nazarhussain - I've opened a PR to resolve this issue against the `1181-atomic-block` branch. 
https://github.com/LiskHQ/lisk/pull/1246

**Comment by nazarhussain** [comment]
The tests which is impacted by this issue are marked skipped for now and can be found https://github.com/LiskHQ/lisk/search?utf8=✓&q=TODO%3A+1242
