### ISSUE TITLE
HTTPS support for HSTS.

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#125]
The node.js server should provide support for HSTS. In order to provide protection against Men-In-The-Middle attack, the server in the HTTPS configuration should provide supoort for HSTS (HTTP Strict Transport Protocol).

Reference
https://www.owasp.org/index.php/HTTP_Strict_Transport_Security

**Comment by fix** [comment]
I don't think that lisk should reproduce all features of a http proxy. I would rather recommend or include nginx config. Otherwise i expect many issues to be fixed.

**Comment by fix** [comment]
@Isabello what do you think of this?

**Comment by Gr33nDrag0n69** [comment]
Using https://www.ssllabs.com/ssltest/analyze.html i scanned a typical wallet install.
By default the score is B. I think there could be some improvements possible.
Using nginx I was able to go to A+.

**Comment by Gr33nDrag0n69** [comment]
I don't say lisk should include all http proxy features but if some are easy to implement wihtout drawback, why not.

**Comment by 5an1ty** [comment]
+1 for the nginx solution. I could probably modify lisk-docker's compose file to include a let's encrypt https proxy, if there's any demand for that?

This should be optional as not everyone has a domain.

**Comment by karmacoma** [comment]
+1 for the nginx (or equivalent) solution.
