### ISSUE TITLE
Inconsistent usage of 'use strict'

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk#1258]
**Expected behaviour:**

When it is agreed on the strict mode, 'use strict' should be on top of every JavaScript file.

**Actual behaviour:**

'use strict' is present in most, but not all of the JavaScript files.

**Possible fix:**

Add 'use strict' to all JavaScript files.

**Comment by willclarktech** [comment]
This issue may be superseded if Babel is added as part of https://github.com/LiskHQ/lisk/issues/672
