### ISSUE TITLE
lisk.sh script is not able to stop a node in the installation phase

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#128]
In the installation script after the coldstart phase is not able to stop the process and get into an infinite while before tunning the database ....

Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz
+ curl -s https://downloads.lisk.io/lisk/test/lisk-Linux-x86_64.tar.gz -o lisk-Linux-x86_64.tar.gz
+ curl -s https://downloads.lisk.io/lisk/test/lisk-Linux-x86_64.tar.gz.md5 -o lisk-Linux-x86_64.tar.gz.md5
++ awk '{print $1}'
++ md5sum lisk-Linux-x86_64.tar.gz
+ md5=6dc38252a7d4c8747bff13e4a3bb0219
++ awk '{print $1}'
++ grep lisk-Linux-x86_64.tar.gz lisk-Linux-x86_64.tar.gz.md5
+ md5_compare=6dc38252a7d4c8747bff13e4a3bb0219
+ [[ 6dc38252a7d4c8747bff13e4a3bb0219 == \6\d\c\3\8\2\5\2\a\7\d\4\c\8\7\4\7\b\f\f\1\3\e\4\a\3\b\b\0\2\1\9 ]]
+ echo 'Checksum Passed!'
Checksum Passed!
+ echo -e 'Extracting Lisk binaries to /opt/lisk//lisk'
Extracting Lisk binaries to /opt/lisk//lisk
+ tar -xzf lisk-Linux-x86_64.tar.gz -C /opt/lisk/
+ mv /opt/lisk//lisk-Linux-x86_64 /opt/lisk//lisk
+ echo -e '\nCleaning up downloaded files'

Cleaning up downloaded files
+ rm -f lisk-Linux-x86_64.tar.gz lisk-Linux-x86_64.tar.gz.md5
+ cd /opt/lisk//lisk
+ echo -e '\nColdstarting Lisk for the first time'

Coldstarting Lisk for the first time
+ bash lisk.sh coldstart
√ Postgresql started successfully.
√ Postgresql user created successfully.
√ Postgresql database created successfully.
Downloading blockchain snapshot...
√ Blockchain snapshot downloaded successfully.
Restoring blockchain...
√ Blockchain restored successfully.
√ Crontab updated successfully.
√ Lisk started successfully.
+ echo -e '\nStopping Lisk to perform database tuning'

Stopping Lisk to perform database tuning
+ bash lisk.sh stop
X Failed to stop lisk.
X Failed to stop lisk.
X Failed to stop lisk.
X Failed to stop lisk.

**Comment by Isabello** [comment]
I think I have the root cause for this identified. Can you give me the output the following after it hangs?

ps -ef | grep node
ps -ef | grep postgres

tail -n10 config.json

**Comment by cezarsn** [comment]
I think that I did found the reason...In my home directory was a directory .forever with his own config.json. After deleting the directory the installation did worked ok. This is the config.json that you are looking for?
