### ISSUE TITLE
Blocks list is being verified against the wrong schema

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1287]
### Expected behavior
The result of `rpc.blocks` is being verified against the proper schema.
### Actual behavior
The result of `rpc.blocks` is being verified against the wrong schema. Blocks forwarded in P2P communication are passed in a merged schema, like:
```
{ 
    b_id: '6524861224470851795',
    b_version: 0,
    b_timestamp: 0,
    b_height: 1,
    b_previousBlock: null,
    b_numberOfTransactions: 103,
    b_totalAmount: '10000000000000000',
    b_totalFee: '0',
    b_reward: '0',
    b_payloadLength: 19619,
    b_payloadHash: '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
    b_generatorPublicKey: 'c96dec3595ff6041c3bd28b76b8cf75dce8225173d1bd00241624ee89b50f2a8',
    b_blockSignature: 'c81204bf67474827fd98584e7787084957f42ce8041e713843dd2bb352b73e81143f68bd74b06da8372c43f5e26406c4e7250bbd790396d85dea50d448d62606',
    t_id: '1465651642158264047',
    t_rowId: 1,
    t_type: 0,
    t_timestamp: 0,
    t_senderPublicKey: 'c96dec3595ff6041c3bd28b76b8cf75dce8225173d1bd00241624ee89b50f2a8',
    t_senderId: '1085993630748340485L',
    t_recipientId: '16313739661670634666L',
    t_amount: '10000000000000000',
    t_fee: '0',
    t_signature: 'd8103d0ea2004c3dea8076a6a22c6db8bae95bc0db819240c77fc5335f32920e91b9f41f58b01fc86dfda11019c9fd1c6c3dcbab0a4e478e3c9186ff6090dc05',
    t_signSignature: null,
    s_publicKey: null,
    d_username: null,
    v_votes: null,
    m_min: null,
    m_lifetime: null,
    m_keysgroup: null,
    dapp_name: null,
    dapp_description: null,
    dapp_tags: null,
    dapp_type: null,
    dapp_link: null,
    dapp_category: null,
    dapp_icon: null,
    in_dappId: null,
    ot_dappId: null,
    ot_outTransactionId: null,
    t_requesterPublicKey: null,
    tf_data: null,
    t_signatures: null 
}
```
The verification (https://github.com/LiskHQ/lisk/blob/development/modules/blocks/process.js#L408) expects the format of block in DB instead.
### Steps to reproduce
Invoke loading common blocks procedure.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
@MaciejBaj I just looked into previous commits and found that initially there was no validation `rpc.blocks` at all. The schema was used

https://github.com/LiskHQ/lisk/blob/daad3f696fe1050b1e926c75c28883b5ca13eff8/schema/blocks.js#L6-L9

Means it was just checking it would be array and don't validate content of the array. What do you think, I revert it to that logic or add extensive schema definition for `rpc.blocks`

**Comment by MaciejBaj** [comment]
I think its OK to have the validation in the place like in other cases. I am not sure about the complexity of that check though - schema of every block will be checked. The other thing is that it will happen anyway during processing of every block individually in `block.objectNormalize`.

**Comment by nazarhussain** [comment]
If the block will be verified again during the processing, we should skip the validation of individual attributes here.
