### ISSUE TITLE
Transactions save side effects

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#1289]
### Expected behavior

Test should pass.

### Actual behavior

Tests fail with the following error: `Invalid public key, must be a string`

### Steps to reproduce

Execute `npm run mocha test/functional/system/blocks/chain.deleteLastBlock.js` on 1.0.0 branch.

**Comment by robladbrook** [comment]
Sounds similar to the bug this fixed: https://github.com/LiskHQ/lisk/pull/1271

**Comment by LucasIsasmendi** [comment]
Yes @robladbrook, same kind of issue
