### ISSUE TITLE
Wrong default values for accounts

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#1293]
### Expected behavior

New account should have following default values.
- missedBlocks = 0
- producedBlocks = 0
- rank = null or 0

### Actual behavior
New account have following default values.
- missedBlocks = "0"
- producedBlocks = "0"
- rank = 1

### Steps to reproduce

Execute `npm run mocha test/functional/system/blocks/chain.deleteLastBlock.js` on 1.0.0 branch.

**Comment by karmacoma** [comment]
Closed in favor of: #1310
