### ISSUE TITLE
Use should or expect consistently in tests

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1295]
Child of #672 
Depends on https://github.com/LiskHQ/lisk-template/issues/75

### Expected behavior

We should use `expect` throughout our codebase. Some helpful regexes can be found here: https://github.com/LiskHQ/lisk/pull/1339#issue-289524636

### Actual behavior

We mix `should` and `expect`.

**Comment by robladbrook** [comment]
@willclarktech @karmacoma would you like me to submit another PR using `expect` or hold off for now?

**Comment by willclarktech** [comment]
@robladbrook If you've got time in the next couple of days that would be great, otherwise we'll do it ourselves.
