### ISSUE TITLE
Add "round ticks" (forwards/backwards) to the same promise chain as Chain.prototype.saveBlock

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1297]
Parent: #302 

Continuation of: #1181 

### Current behavior

```
BEGIN DB TRANSACTION
  Apply unconfirmed transaction
  Apply confirmed transaction
  Insert block
  Insert transaction
  Insert transaction type
COMMIT

BEGIN DB TRANSACTION
  Round tick
COMMIT
```

### Proposed behavior

```
BEGIN DB TRANSACTION
  Apply unconfirmed transaction
  Apply confirmed transaction
  Insert block
  Insert transaction
  Insert transaction type
  Round tick
COMMIT
```

### Code Target

https://github.com/LiskHQ/lisk/blob/development/logic/round.js
https://github.com/LiskHQ/lisk/blob/development/modules/rounds.js

**Comment by nazarhussain** [comment]
@karmacoma After closing #1181 the current behaviour is: 

```
BEGIN DB TRANSACTION
  Apply unconfirmed transaction
  Apply confirmed transaction
  Insert block
  Insert transaction
  Insert transaction type
  BEGIN DB TRANSACTION
      Round tick
   COMMIT
COMMIT
```

**Comment by vitaly-t** [comment]
It is currently on hold, as we have absolutely no tests for that functionality.

**Comment by 4miners** [comment]
@vitaly-t I reasigned it, as I need it fixed for https://github.com/LiskHQ/lisk/issues/1303

Behavior described in https://github.com/LiskHQ/lisk/issues/1297#issuecomment-357358923 is not valid, it still uses different connection handler for `tick` - so round logic don't see block that is already saved to database (in different SQL transaction).
