### ISSUE TITLE
User/Group setup instruction.  Before installing Lisk node.

### ISSUE THREAD

**Issue by qtipwax** [LiskHQ/lisk#130]
Would like to see either (1)instructions or (2)integrate the user and user group into the install script.  
<img width="577" alt="setup" src="https://cloud.githubusercontent.com/assets/12992198/15276653/2ef9db92-1aa3-11e6-92dc-5432abd67c29.PNG">

It's important for a smooth install for this prerequisite to happen first.

**Comment by Isabello** [comment]
I'll take care of this for next release by compiling all prereqs into an easy to follow guide.

**Comment by Isabello** [comment]
This is complete and uploaded to https://lisk.io/documentation?i=lisk-docs/PrereqSetup
