### ISSUE TITLE
Review unit test coverage of blocks modules

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1301]
Parent: #1169 

---

- api (#1395 )
  - [x] constructor
  - [x] __private.list
  - [x] getBlocks
  - [x] onBind
- chain (#1549)
  - [x] constructor
  - [x] saveGenesisBlock
  - [x] saveBlock
  - [x] __private.afterSave
  - [x] deleteBlock
  - [x] deleteAfterBlock
  - [x] applyGenesisBlock
  - [x] __private.applyTransaction
  - [x] applyBlock
  - [x] broadcastReducedBlock
  - [x] __private.popLastBlock
  - [x] deleteLastBlock
  - [x] recoverChain
  - [x] onBind
- process (#1483 )
  - [x] constructor
  - [x] __private.receiveBlock
  - [x] __private.receiveForkOne
  - [x] __private.receiveForkFive
  - [x] getCommonBlock
  - [x] loadBlocksOffset
  - [x] loadBlocksFromPeer
  - [x] generateBlock
  - [x] __private.validateBlockSlot 
  - [x] onReceiveBlock
  - [x] onBind
- utils (#1449 )
  - [x] constructor
  - [x] readDbRows
  - [x] loadBlocksPart
  - [x] loadLastBlock
  - [x] getIdSequence
  - [x] loadBlocksData
  - [x] getBlockProgressLogger
  - [x] aggregateBlocksReward
  - [x] onBind
- verify (#1598)
  - [x] constructor
  - [x] __private.checkTransaction
  - [x] __private.setHeight
  - [x] __private.verifySignature
  - [x] __private.verifyPreviousBlock
  - [x] __private.verifyAgainstLastNBlockIds
  - [x] __private.verifyVersion
  - [x] __private.verifyReward
  - [x] __private.verifyId
  - [x] __private.verifyPayload
  - [x] __private.verifyForkOne
  - [x] __private.verifyBlockSlot
  - [x] __private.verifyBlockSlotWindow
  - [x] verifyReceipt 
  - [x] onBlockchainReady
  - [x] onNewBlock
  - [x] verifyBlock
  - [x] addBlockProperties
  - [x] deleteBlockProperties
  - [x] __private.addBlockProperties
  - [x] __private.normalizeBlock
  - [x] __private.verifyBlock
  - [x] __private.broadcastBlock
  - [x] __private.checkExists
  - [x] __private.validateBlockSlot
  - [x] __private.checkTransactions
  - [x] processBlock
  - [x] onBind

**Comment by LucasIsasmendi** [comment]
- api
  - [ ] constructor
  - [ ] __private.list
  - [ ] getBlocks
  - [ ] onBind
- chain
  - [ ] constructor
  - [ ] saveGenesisBlock
  - [ ] saveBlock
  - [ ] __private.afterSave
  - [ ] deleteBlock
  - [ ] deleteAfterBlock
  - [ ] applyGenesisBlock
  - [ ] __private.applyTransaction
  - [x] applyBlock
  - [ ] broadcastReducedBlock
  - [x] __private.popLastBlock (cover in functional/system/blocks)
  - [x] deleteLastBlock (cover in functional/system/blocks)
  - [ ] recoverChain
  - [ ] onBind
- process
  - [ ] 
- utils
  - [ ] 
- verify
  - [ ]

**Comment by vitaly-t** [comment]
We should review state of things with the tests and perhaps make a new list, where all database operations stand on its own, with a separate test file for each database repository that we now have.
