### ISSUE TITLE
transactions from old testnet getting in

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#131]
This is due to old testnet servers being still propagated through /api/peers while banned

Example: https://testnet.lisk.io/api/transactions/get?id=10029151742617860048

There are a total of 73 transactions from address 14750787360165464176L (aka faucet)
Code to be reviewed:
https://github.com/LiskHQ/lisk/blob/462d59882b878180ed39d78ed8dee4c0f1770244/modules/transport.js#L522

There is no check whether we are not on the same network. Just the version is checked, and if the version does not match the state is never updated.

**Comment by corsaro1** [comment]
old chain testnet 0.2.1 tx inserted in new 0.2.2 chain
https://testnet.lisk.io/api/transactions/get?id=10029151742617860048

**Comment by fix** [comment]
another one:
https://testnet.lisk.io/api/transactions/get?id=259113510405831790

**Comment by Phoenix1969** [comment]
https://testnet.lisk.io/api/transactions/get?id=259113510405831790

**Comment by Devasive** [comment]
This old transaction was sent to my address:
https://testnet.lisk.io/api/transactions/get?id=8926697300494087493

**Comment by punkrock** [comment]
This one to mine:

https://testnet.lisk.io/api/transactions/get?id=8467698347802670163

**Comment by fix** [comment]
related: https://github.com/LiskHQ/lisk-js/pull/3
