### ISSUE TITLE
Grunt release fails due to missing create-bundles script

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1314]
### Expected behavior

The `grunt release` task should build the release successfully.

### Actual behavior

The `grunt release` task fails with the following error:

```
Running "exec:folder" (exec) task

Running "obfuscator" task

Running "exec:createBundles" (exec) task
>> npm
>> ERR! Darwin 17.3.0
>> npm ERR! argv
>> "/usr/local/bin/node" "/usr/local/bin/npm" "run" "create-bundles"
>> npm
>> ERR! node v6.12.3
>> npm
>> ERR! npm
>> v3.10.10
>> 
>> npm ERR! missing script: create-bundles
>> npm ERR! 
>> npm ERR! If you need help, you may report this error at:
>> npm
>> ERR!     <https://github.com/npm/npm/issues>
>> 
>> npm ERR! Please include the following file with any support request:
>> npm ERR!
>> /Users/Oliver/GitHub/LiskHQ/lisk-development/npm-debug.log
>> Exited with code: 1.
>> Error executing child process: Error: Process exited with code 1.
Warning: Task "exec:createBundles" failed. Use --force to continue.

Aborted due to warnings.
```

### Steps to reproduce

Run the `grunt release` task.

### Which version(s) does this affect? (Environment, OS, etc...)

On the `1.0.0` branch.

**Comment by vitaly-t** [comment]
Whoever fixes this, please ping me, I've got more changes incoming for `gruntfile.js`, so it's a blocker for testing the changes.

**Comment by vitaly-t** [comment]
From what I see, running `grunt release` executes its own task `exec:createBundles`, which in turn executes `npm run create-bundles`.

However, our `package.json` doesn't have any `create-bundles` within the `scripts` section, i.e. it was either deleted by mistake or renamed or else?
