### ISSUE TITLE
Transactions endpoint performs OR operand instead of AND over query params

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk#1327]
### Expected behavior
Defining a specific set of senderId and recipientId, we expect the `api/transactions` endpoint to return the list of transactions between those 2 addresses we've defined. for example, I expect 
```
https://node08.lisk.io/api/transactions?recipientId=16495495557188846778L&senderId=2797034409072178585L
```
to return the list of transactions between `2797034409072178585L` and `16495495557188846778L `. but it actually returns all the transactions with `2797034409072178585L` as sender OR `16495495557188846778L` as recipient.

Things get even worse when we define transaction type. Then the result includes not only the transactions above, but also the transaction with `type === 1` and none of the address above as `senderId`. 
say we call:
```
https://node08.lisk.io/api/transactions?recipientId=16495495557188846778L&senderId=2797034409072178585L&type=1
```
in the result we get:
```
        {
            "id": "16247176332132643741",
            "height": 2785641,
            "blockId": "7448409010448274278",
            "type": 1,
            "timestamp": 30074667,
            "senderPublicKey": "e9fa0c00e4e9ddaf1e30592043c7d8677b2e76162b62c634a56410256eb02755",
            "senderId": "1249966176516882092L",
            "recipientId": null,
            "recipientPublicKey": null,
            "amount": 0,
            "fee": 500000000,
            "signature": "50e8d555efc9e4d1bdab52f9ebfbdc80452cb8d68af9632d6568c2bdfe42a8cf96b12da504a46f4bd2d4b6f03ce0ba5dea721400f0d7b44eab7fb47c6915750a",
            "signatures": [],
            "confirmations": 2187945,
            "asset": {}
        },
```
which as you see, senderId is totally irrelevant.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk core v0.9.x

**Comment by robladbrook** [comment]
I don't think this applies to version 1.0.0 because it was fixed by @SargeKhan with this commit: https://github.com/LiskHQ/lisk/commit/caf80eb0421520f312bdf54c597125554ecd6ecb#diff-e1179e44ccc82b715ebffbce24be04c4R123

**Comment by diego-G** [comment]
Solved in https://github.com/LiskHQ/lisk/pull/948
