### ISSUE TITLE
Make unit tests atomic

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1340]
### Expected behavior

Unit tests should be atomic. The execution of one should not affect the result of any other.

### Actual behavior

Some files have non-atomic tests, e.g. https://github.com/LiskHQ/lisk/blob/development/test/unit/helpers/check_ip_in_list.js

This also affects our ability to use sinon sandbox.

**Comment by yatki** [comment]
As we are migrating from mocha to jest, and also we recreated the application structure, we are already on the direction of making tests atomic. So it is ok to close this issue.
