### ISSUE TITLE
Remove unneeded calls to GitHubCommitStatusSetter in Jenkinsfiles

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#1351]
### Expected behavior

Jenkins reports to GitHub as configured in  [lisk-core](https://jenkins.lisk.io/job/lisk-core/configure) and [lisk-core-integration](https://jenkins.lisk.io/job/lisk-core-integration/configure); there is no need to call `GitHubCommitStatusSetter` explicitely.

### Actual behavior

Because of a limitation in the previous versions of `github-branch-source` plugin we were calling `GitHubCommitStatusSetter` with differents parameters in `Jenkinsfile` and `Jenkinsfile.integration` as a workaround.

### Steps to reproduce

Build a PR on Jenkins and look at GitHub: there will be 2 extra checks ("jenkins-ci/func-unit" and "jenkins-ci/integration"). 

### Which version(s) does this affect? (Environment, OS, etc...)

n/a

**Comment by karmacoma** [comment]
Closed by: #1352
