### ISSUE TITLE
The transaction for buying the delegate name does not show a counter party account

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#136]
Every transaction in the blockchain should have a counter party account that do receive the amount. In the interface of 0.2.3 no counterpary lisk address is show when the use buy the right to use a nick name. The user should see the counterpart account and be advice that this address belong to the lisk infrastracture.

9508446494015012957     1634    4856725069091235590     2       35116691        \\x0348........4d4     16379340065696424247L   **\N**      0       10000000000     \\x0693.....b04  \N      \N      \N

**Comment by fix** [comment]
Hi there is no amount sent in a vote/delegate/dapp transaction (ie amount=0). There is only a fee. The fee is then redistributed to the forging nodes in the round, so there is no counterpart.

on a side note, it is possible (ie it is a feature) to send lisk to a cold wallet (ie not known by the network).
