### ISSUE TITLE
Socket.io 'blocks/change' event no longer contains transactions in 1.0.0

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#1364]
### Expected behavior
https://github.com/LiskHQ/lisk/blob/cf4ecbbfdf5fccb606ff5fcb63c50f20abb694f8/modules/transport.js#L390
this event in `0.9.X` contained `transactions`:
```
42[  
   "blocks/change",
   {  
      "version":0,
      "totalAmount":100000000,
      "totalFee":10000000,
      "reward":400000000,
      "payloadHash":"b5fc083df18bac1d264ded51b96b13c715ab645c6e13c9683a15ab0a76a4cc9c",
      "timestamp":52592790,
      "numberOfTransactions":1,
      "payloadLength":117,
      "previousBlock":"14984347274749403445",
      "generatorPublicKey":"e683da7b4fe46164b9db3fd599481ad0630d2d892546c1ac63e59a5acb903140",
      "transactions":[  
         {  
            "type":0,
            "amount":100000000,
            "fee":10000000,
            "recipientId":"16203576129189059835L",
            "timestamp":52592770,
            "asset":{  

            },
            "senderPublicKey":"99f1d6d200ce1d45783e1e5d01f3c392d9e7cb6750226bbf3ec2956745f86543",
            "signature":"20866ea84ff07890c41007142b6aadf2682c740a5b75fba8c6e3630157b7121a709c906b505356f228efc62fc28c5a3a731b677b2b633aa0ff9457cc061ff70b",
            "id":"2138237791321521333",
            "senderId":"12530546017554603584L",
            "relays":2,
            "receivedAt":"2018-01-23T10:06:17.122Z",
            "blockId":"5690089948507302516"
         }
      ],
      "blockSignature":"b36ca1640c64a1bfa7c3e5925e074f58c1e043d455dd263fa2bb6ba64b08e914fe3a0f2096b830993deaf4f972e97b3b4b3bc69c8a5ebbe9d021d7fdb47b7901",
      "height":4259123,
      "id":"5690089948507302516",
      "relays":2
   }
]
```

### Actual behavior
The event in `1.0.0` no longer contains transactions:
```
42[  
   "blocks/change",
   {  
      "payloadHash":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "timestamp":52593050,
      "previousBlock":"6247624240564620830",
      "generatorPublicKey":"ba2ea5e324eeb42fa6f4d1132a1d79911721e8507033bb0abd49715f531877b4",
      "blockSignature":"302b11e5ac647f837f85975b51625b9242c32014d8693d5cbbb6512e0789b1a9c749f6bacee320939ff5eb78be6258c3e869fc89a1be9a1cc85a7b107f923606",
      "height":4122,
      "id":"13515063319774863234"
   }
]
```

The web socket is used in Lisk Nano to get notifications for two things:
- there is a new block - so need to check if displayed transactions have more confirmations. This still works
- there is new transaction relevant to the active account - This is broken. I have to do an additional request for each new block.

### Steps to reproduce

Listen to this WebSocket 

wss://testnet.lisk.io/socket.io/?EIO=3&transport=websocket&sid=YqBT10HpavDssil5AAZH

and compare to the same WebSocket on your local node running 1.0.0

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk core 1.0.0

**Comment by diego-G** [comment]
Behaviour was updated. Default block's properties are being now deleted with the intention of reducing the data on the channel:
https://github.com/LiskHQ/lisk/blob/5a754a5e364637f321a7f276f5c950b88e1aba4a/modules/blocks/verify.js#L513
Another method was enabled for those clients which still need that data: https://github.com/LiskHQ/lisk/blob/5a754a5e364637f321a7f276f5c950b88e1aba4a/modules/blocks/verify.js#L479
The sequence can be better understood as follows: 

`produced block --> broadcast block (reduce properties) --> receive block --> add properties to block`
