### ISSUE TITLE
Add an option for api/transactions to combine parameters with OR

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#1366]
### Expected behavior
`/api/transactions` should support filtering with both `AND` and `OR`.

`/api/transactions?senderId=12530546017554603584L&recipientId=12530546017554603584L`
can still return transactions that have both `senderId` and `recipientId` equal to  `12530546017554603584L`.

But there should be another parameter to tell the api to use `OR`, e.g.:
`/api/transactions?senderId=12530546017554603584L&recipientId=12530546017554603584L&conjuction=or`

#### WHY?

Because the OR case is the basic and most common case used in Nano and Explorer - get me all transactions of a given account means  `senderId OR recepientId`

### Actual behavior
`/api/transactions?senderId=12530546017554603584L&recipientId=12530546017554603584L`
returns transactions that have both `senderId` and `recipientId` equal to  `12530546017554603584L`. There is no way to get transactions that have either `senderId` or `recipientId` equal to  `12530546017554603584L`.

### Steps to reproduce
Run
https://testnet.lisk.io/api/transactions?senderId=12530546017554603584L&recipientId=12530546017554603584L
before and after 1.0.0 is released to testnet. Or do the same with your own node.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core 1.0.0

**Comment by diego-G** [comment]
The real need of the issue was discussed. Following our desire to keep a simple standard API, it is decided to cancel this issue advising to perform the requested operation in the client.

**Comment by slaweet** [comment]
OK. I see the reasoning from the point of view of Lisk Core.
