### ISSUE TITLE
Improve the SQL loader and cleanup loading code

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1372]
This is a follow up (for myself) on this PR, after it's merged: https://github.com/LiskHQ/lisk/pull/1358

Parent: #1306 

---

The following improvements should be made at the same time (in one PR):

- Move all the SQL-loading logic into its own `db/sql/config.js` file, exporting just the SQL-loading function
- Have the SQL loader use the dynamic schema, which should be introduced within `/config.json`
- Have the SQL loader export `{sql, schema}` to be reusable in all repositories

**Comment by karmacoma** [comment]
Closed by PR: https://github.com/LiskHQ/lisk/pull/1375
