### ISSUE TITLE
/api/delegates and /api/blocks don't have 'meta.count' property

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#1377]
### Expected behavior
`/api/delegates` and `/api/blocks` should contain `count` property in `meta` object ([/api/transactions](https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.20#/Transactions/getTransactions) has it) that says how many results are there in total:
```
"meta": {
  "offset": 0,
  "limit": 20,
  "count": 1640
},
```
It is used in Lisk Nano for pagination.

### Actual behavior
`/api/delegates` and `/api/blocks` don't contain `count` property in `meta` object, only this:
```
"meta": {
  "offset": 0,
  "limit": 20
},
```
### Steps to reproduce
Setup devnet Lisk Core 1.0.0 node on http://localhost:4000/ and to to
http://localhost:4000/api/delegates/?offset=0&limit=100
And compare it with 
http://localhost:4000/api/transactions?senderId=537318935439898807L&recipientId=537318935439898807L&limit=20&offset=0&sort=timestamp:desc

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core 1.0.0

**Comment by nazarhussain** [comment]
Closing this issue to continue further brainstorming on https://github.com/LiskHQ/lisk/issues/1461
