### ISSUE TITLE
Invalid query concatenation

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1379]
https://github.com/LiskHQ/lisk/blob/4d80948b6e0697816364f8100d266f6f867a9930/db/repos/accounts.js#L107

[helpers.concat](http://vitaly-t.github.io/pg-promise/helpers.html#.concat) will create 3 separate queries that way, separated by `;`, so the end query will be invalid.

**Comment by robladbrook** [comment]
@vitaly-t I just want to clarify the issue, is the fix to do something like:

```js
AccountsRepo.prototype.upsert = function (params) {
	return this.db.none(Queries.upsert, [params.foo, params.bar, etc]);
};
```

?

**Comment by vitaly-t** [comment]
Yes, there should be a single upsert query.

**Comment by nazarhussain** [comment]
@karmacoma With this PR https://github.com/LiskHQ/lisk/pull/1312 this issue will also be addressed.

**Comment by karmacoma** [comment]
Closed by PR: https://github.com/LiskHQ/lisk/pull/1312
