### ISSUE TITLE
Refactor blocks db repository

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1390]
Parent: #1376

Refactoring the biggest and baddest database repository - blocks.

**Comment by vitaly-t** [comment]
As per this comment: https://github.com/LiskHQ/lisk/pull/1381#discussion_r164394425

Need to fix that, plus check for any other case like that.

@karmacoma Re-opening for now, till that small issue is fixed, to make sure it is not forgotten 😉

**Comment by vitaly-t** [comment]
This was finalized within [PR-1443](https://github.com/LiskHQ/lisk/pull/1443).
