### ISSUE TITLE
Log levels and fork/forged messages

### ISSUE THREAD

**Issue by tharude** [LiskHQ/lisk#140]
It will be good if all messages cluttering the log currently and not related to "forged/received block" are moved to debug or log level, "forged/received" to be left in "info" level and "fork" messages to be moved  to "warn" or "error" levels of log. This can reduce the clutter and writes to disk too.

**Comment by fix** [comment]
Yes this should be done this way. Some care should be done so "production nodes" are optimised.

I am also thinking about erroring out more IP in order to let log analysis detecting attacks for instance.

**Comment by fix** [comment]
i think this is ok in my tests, even i don't remember i pushed something about it... @oliver can you confirm?
