### ISSUE TITLE
Skip non-SQL files when packaging

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1404]
https://github.com/LiskHQ/lisk/blob/1704732171ea0554208f77071fbb769abbba8afc/Gruntfile.js#L66

Currently, the following line copies all files from `db/sql` folder into the release folder `releaseXXX/sql`, while keeping the structure:

```js
util.format('cp -r %s/db/sql %s/sql/', __dirname, version_dir)
```

The only problem is, it copies all files. And we want only SQL files, i.e. `*.sql`, and skip everything else.

I failed to make it work that way, due to my lack of Linux knowledge, so somebody more knowledgeable, please  help out ;) And when done, please make me the reviewer ;)

You should do `grunt release` to test if the change is working correctly ;)

**Comment by robladbrook** [comment]
There are three different approaches I can think of (although there's probably a much more elegant way of doing it).

1) the easiest approach is to just copy all the sql files without preserving directory structure
```
util.format('find %s/db/sql -type f -name "*.sql" -exec cp {} %s/sql/ \\;', __dirname, version_dir)
```

2) you could just copy all the files and then delete anything which isn't a sql file
```
util.format('cp -r %s/db/sql %s/sql/', __dirname, version_dir),
util.format('find %s/sql/ -type f -not -name "*.sql" -exec rm {} \\;', version_dir)
```

3) the most complex solution but provides the most accurate results is to create the target directory structure then copy just the sql files across
```
util.format('find %s/db/sql -type d | sed "s|^.*/db/sql||" | xargs -I {} mkdir -p %s/sql{}', __dirname, version_dir),
util.format('find %s/db/sql -type f -name "*.sql" | sed "s|^.*/db/sql||" | xargs -I {} cp %s/db/sql{} %s/sql{}', __dirname, __dirname, version_dir)
```

**Comment by vitaly-t** [comment]
@robladbrook I went for the last version, and assigned you to review :wink:

https://github.com/LiskHQ/lisk/pull/1418
