### ISSUE TITLE
Round snapshot always fails

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1409]
### Expected behavior
Should be no error there.

### Actual behavior
`
[ERR] 2018-01-25 09:22:20 | Round snapshot failed - {"data":[{"success":true,"result":null},{"success":false,"result":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"}},{"success":true,"result":null},{"success":false,"result":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"}}],"first":{"severity":"ERROR","code":"42P07","file":"heap.c","line":"1067","routine":"heap_create_with_catalog"},"message":"relation \"mem_round_snapshot\" already exists","stat":{"total":4,"succeeded":2,"failed":2,"duration":16}}
`

### Steps to reproduce
Run node, wait for second round to be closed, one block before second round it fails.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by vitaly-t** [comment]
Looks like integrity check fails within the batch, reporting that `"mem_round_snapshot" already exists`.
