### ISSUE TITLE
Automatically enable forging after rebuilding blockchain

### ISSUE THREAD

**Issue by jfernanz** [LiskHQ/lisk#141]
I had to bash lisk.sh restart after the rebuild for the client to forge.

**Comment by mrv777** [comment]
I had the same experience.  Except, I just did a `reload` after the rebuild to get it forging again

**Comment by Isabello** [comment]
This is essentially expected behavior, since your delegate is not registered on the genesis block.

Not sure how it can be fixed since the API call is done upon startup of app.js.

**Comment by mrv777** [comment]
I don't know (or think) this is a solution, but could `reload` be called when `rebuild` finishes?

**Comment by fix** [comment]
Yes somehow the code can handle the end of rebuilding and trying again to enable forging on completion.

**Comment by fix** [comment]
This is still pending i think. The very reason is that when the node start from scratch, it cannot find the account in the database that allow him to forge.

Mostly mitigated with db snapshot

**Comment by samsmith** [comment]
easier when #255 has been implemented ?

**Comment by karmacoma** [comment]
@samsmith: No #255 is a separate issue, mainly related to swapping genesis block while connecting to the same database, which will cause conflict. We will fix, but not huge priority.
