### ISSUE TITLE
Regressions from #1376

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1410]
### Expected behavior
All queries should works.

### Actual behavior
Some queries not works.

### Steps to reproduce
Run app and wait for errors.

## Notice
Reference: https://github.com/LiskHQ/lisk/issues/1376

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by vitaly-t** [comment]
What errors are you getting? Can you give an example?
