### ISSUE TITLE
Separate VCS config file from live config file

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1421]
### Expected behavior

It should be possible to make changes to the config file used when running the application, without polluting the git workspace. It's annoying to constantly have to stash changes to `config.json` before pushing and retrieve them to run tests etc.

For example, in Lisky we store a `defaultConfig.json` in version control, which is copied into a separate file for use by the application.

### Actual behavior

The config file which is used by the application is stored in version control.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by MaciejBaj** [comment]
Hey @willclarktech, we mitigated the issue as part of https://github.com/LiskHQ/lisk/issues/398.

**Comment by willclarktech** [comment]
@MaciejBaj Mitigated isn't the same thing as solved.
