### ISSUE TITLE
Global variables issue with tests - sinonSandbox undefined

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1429]
When we look at the full build log on Jenkins, we can find the following in 3 places there:

```
>> Writing coverage object [/home/lisk/workspace/lisk-core_PR-1428-HQBTX7Y6BIPYZB6VKHFRO43HVOHDOBHDKI2OADFVWUY47O3QQADA/test/.coverage-unit/coverage-65506.json]
[Functional WS tests] >> /home/lisk/workspace/lisk-core_PR-1428-HQBTX7Y6BIPYZB6VKHFRO43HVOHDOBHDKI2OADFVWUY47O3QQADA/test/common/ws/server.js:57
[Functional WS tests] >> 		status: sinonSandbox.stub().callsArgWith(1, {success: true, height: 1, broadhash: testConfig.nethash, nonce: testConfig.nethash}),
[Functional WS tests] >> 		        ^
[Functional WS tests] >> 
[Functional WS tests] >> ReferenceError: sinonSandbox is not defined
[Functional WS tests] >>     at Object.<anonymous> (/home/lisk/workspace/lisk-core_PR-1428-HQBTX7Y6BIPYZB6VKHFRO43HVOHDOBHDKI2OADFVWUY47O3QQADA/test/common/ws/server.js:57:11)
[Functional WS tests] >>     at Module._compile (module.js:570:32)
[Functional WS tests] >>     at Object.Module._extensions..js (module.js:579:10)
[Functional WS tests] >>     at Module.load (module.js:487:32)
[Functional WS tests] >>     at tryModuleLoad (module.js:446:12)
[Functional WS tests] >>     at Function.Module._load (module.js:438:3)
[Functional WS tests] >>     at Module.runMain (module.js:604:10)
[Functional WS tests] >>     at run (bootstrap_node.js:383:7)
[Functional WS tests] >>     at startup (bootstrap_node.js:149:9)
[Functional WS tests] >>     at bootstrap_node.js:496:3
```

This is in the current branch 1.0.0

**UPDATE**

It would appear the following is causing the issue: 

File `test/common/server.js` makes use of global variable `sinonSandbox`, which is set within file `test/setup.js`. However, file `server.js` does not explicitly require `setup.js`, and as a result, when `server.js` happens to execute prior to `setup.js`, there is no global variable `sinonSandbox`.

The fix for this is trivial - adding at the top of file `server.js`:

```js
require('../../setup'); // ensure availability of global variables
```

I've tested it via a full PR, and the fix worked. It now just needs a proper PR.

P.S. Use of the global variables like that is a horrible-horrible idea, and it should be removed completely.

**Comment by willclarktech** [comment]
@vitaly-t Agree that globals are horrible, but globals are kind of the Mocha way. See https://github.com/mochajs/mocha/issues/2765

**Comment by vitaly-t** [comment]
@willclarktech I can live with that, as long as those things stay in tests and not affect the app's code being tested :smile: But it seems that [sometimes they do](https://github.com/LiskHQ/lisk/blob/development/db/index.js#L19).

**Comment by willclarktech** [comment]
Oof, yeah, we had a bunch of issues with rewire in Lisky and/or LiskJS. I'm increasingly of the opinion that whenever rewire seems like a good idea you should refactor your code instead.

**Comment by vitaly-t** [comment]
> whenever rewire seems like a good idea you should refactor your code instead.

👍

**Comment by willclarktech** [comment]
@vitaly-t Do you have an example of a currently open PR that results in these failures?

**Comment by vitaly-t** [comment]
@willclarktech I did yesterday - https://jenkins.lisk.io/job/lisk-core/job/PR-1428

But now it is closed, and I won't have access to Jenkins from where I am for another 4 hours.

I hope that's enough? ;) I can find those errors in the complete logs there ;)

**Comment by willclarktech** [comment]
Yeah, that job is gone I fear. Just trying to establish the scope of this issue.
