### ISSUE TITLE
API call order seems incorrect

### ISSUE THREAD

**Issue by mrv777** [LiskHQ/lisk#143]
When comparing these two API calls, the results should be the same:
`api/delegates?limit=101&orderBy=vote:desc`
`api/delegates?limit=101&orderBy=rate:asc`

However, they are not.  
It looks like the vote field is not being looked at as a number, but rather characters as it thinks 983553069290 > 16546268096697
(guessing it's looking at the first character/digit instead of looking at the whole number)

**Comment by fix** [comment]
code to be changed
https://github.com/LiskHQ/lisk/blob/ddda4bb1cde7245d65c889a6d3c1f1ed8fd60794/modules/delegates.js#L973
