### ISSUE TITLE
Refactor transaction-* database repositories

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1432]
This will be done in two separate PR-s:

 - [x] **Structure/Basic Refactoring**
 - [x] **Logic Refactoring**

### Structure/Basic Refactoring

* Converting into ES6 classes
* Moving simple/static SQL into external repositories
* Improving use of the `pg-promise`  API
* Documentation for code/sql

### Logic Refactoring

* Moving complex/dynamic SQL into external files where possible
* Improving the main underlying logic - `save` operation
* Simplifying the overall class protocol
* Reorganizing files/folders
* Performance optimizations
* Adding tests

For example, all `repos/transactions-*.js` files can possibly be united. They each implement only one specific method `save` - that's an interface/driver pattern, and not repository. At the very least, they can be moved into a single folder, with a simpler protocol.

**Comment by nazarhussain** [comment]
@vitaly-t For now each `transaction-*` file have only `save`, but in future we can and will add more behaviour to it. As per my understanding the `repos` concept is to group similar behaviour together to be used by a standard interface. With saying that we want group each transaction type behaviour separately. That's how we did for `modules` and `logic` as well.

**Comment by vitaly-t** [comment]
> repos concept is to group similar behaviour together to be used by a standard interface

Each repository is meant to represent one business entity, such as a table, and sometimes a business-only entity, with high-level operations. They are not grouped by standard behavior, that's what simple classes do.

**Comment by vitaly-t** [comment]
PR #1721 now completes the last task here.
