### ISSUE TITLE
Improve use of promises

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1437]
This sort of thing is everywhere in the code:

```
return Promise.reject(/* some message or data */);
```

This creates a maintenance nightmare, running into one of those, because such a reject does not carry any stack-tracing information.

In order to make such rejects traceable, the following needs to be done:

* Every manual reject must always wrap the message into the error object, to provide the call stack:

```js
return Promise.reject(new Error(/* some message or data */));
```

It will make it possible for `Bluebird` to trace rejection stack, after being explicitly enabled:

* Globally in the application enable long stack tracing supported by `Bluebird`: http://bluebirdjs.com/docs/api/promise.longstacktraces.html

```js
Promise.config({ 
    longStackTraces: true // Enable long stack traces
});
```

...among other things, just make sure not setting these for production, because long stack traces slow down the performance.

**Comment by vitaly-t** [comment]
@karmacoma Would have been nice having it listed in our coding standards, but we do not really have one.

**Comment by nazarhussain** [comment]
@vitaly-t Right now we throwing errors as plain strings on many places. Its not just with the `Promise` but also with callback approach. And we already have discussed to have full set of possible error scenarios as objects defined in core and then throw those error instances where ever needed. 

@karmacoma I already shared that proposal to you way earlier.

**Comment by nazarhussain** [comment]
@vitaly-t @karmacoma I extracted that proposal from google doc and created this issue for further discussion. 

https://github.com/LiskHQ/lisk/issues/1439

**Comment by karmacoma** [comment]
@vitaly-t Okay duly noted.

Regarding coding standards, we recently established a @LiskHQ/standards team and the initial steps are underway with the application of the `lisk-template` project, a container for the code standards used across the organization.

@nazarhussain Yes, I remember your proposal. Considering we are an open-source project, the best place for it to exist is here on GitHub, so happy to see it finally opened as an issue.

**Comment by vitaly-t** [comment]
The first row of fixes was included with [PR-1443](https://github.com/LiskHQ/lisk/pull/1443), for the `accounts` repository.
