### ISSUE TITLE
multi-sig account creation not confirming

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk#144]
myself, jasmine, and redsn0w all testing the multisig, but no notifications to accounts to signify anything happened, and the account creation does not confirm

https://explorer.lisk.io/tx/9481715993809542448
and
https://explorer.lisk.io/tx/4619380894736481671

**Comment by fix** [comment]
yes, the UX for multisignature is being revamped, it should fix mising/misleading informations

related LiskHQ/lisk-ui#41
