### ISSUE TITLE
Missing error handler for updateMemAccounts

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1446]
https://github.com/LiskHQ/lisk/blob/6cdfef14ebc7afaeb5ae68efcf141e75c7ef2633/modules/loader.js#L487

This block has no `.catch` handler, which is a reliability issue.

I would have put one there myself, but I don't know what should be the correct error handling logic in that specific case.

**Comment by nazarhussain** [comment]
If something happened wrong in loader, the lisk instance should not start. I believe we should simply return that promise 
```
return library.db.task(updateMemAccounts).then(function (res) { 
```

As we already having a `catch` on upper level. 
https://github.com/LiskHQ/lisk/blob/78ad7092da105ec0a40aed4f25ab46a67657c3c8/modules/loader.js#L510-L513

@4miners and @karmacoma can confirm this logic.

**Comment by vitaly-t** [comment]
Whoever takes on this task, please make sure [PR-1443](https://github.com/LiskHQ/lisk/pull/1443) has been merged, as it does a bit of refactoring on that same piece of code :wink:
