### ISSUE TITLE
Semi-Auto Update script

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#145]
I think adding something like `bash lisk.sh update` would be great, update as easy as typing one command to make updates comfortable for every user. It should check for new binary, stop all services, reinstall everything and start new version.
Maybe making it even possible to execute over Lisk web interface with master password and optionally sudo password.

**Comment by karmacoma** [comment]
This feature is already planned. @Isabello has made an initial implementation.

**Comment by Isabello** [comment]
I am working on this feature. Its not currently implemented for production use due to an external dependency (jq) that I am not prepared to enforce.

Allowing Lisk to update over web interface is a bad idea though. There is a real need to be able to check logs on the backend if something goes awry with the installation.

**Comment by karek314** [comment]
Actually, it's safe and possible if we ask user for master password and sudo password. Logs also can be printed, most of users are not experienced with command line. Anyway simple loading indicator in my opinion would be great and more than enough, logs are not necessary in that case - most of users don't need it. In most cases good installation script should proceed without issues, in case something goes wrong, it can be always reinstalled fully manually. It's good idea when we are talking about non-bundled clients like current one. But when normal desktop client will be prepared then its less necessary if binary have self updater like [Sparkle](https://github.com/sparkle-project/Sparkle)

I think it's important thing to do. In decentralised project each node should run latest version of code, some users are lazy to make updates, the best solution should be even auto-updater while starting node.

**Comment by Isabello** [comment]
I don't agree in its safety. Most users don't even know their master DAPP password, either. Asking the user for sudo password from a web interface is also not great. We would be giving privileges to the user running lisk to run code outside of the sandbox as well. 

Maybe in the future we can allow auto updating from lisk.sh but I would not be willing to integrate upgrades from the web wallet due to security concerns.

**Comment by karek314** [comment]
Then the best solution is auto-updater before everything starts. On desktop clients something like **Sparkle** updater would be necessary.

Btw. According to safety while updating over web-interfaces of course it has some pros and cons. But the point is to allow "one click update".

**Comment by Isabello** [comment]
There will be one command upgrades in the future.

**Comment by karek314** [comment]
How about desktop clients ? This is more important for most users.

**Comment by Isabello** [comment]
Not sure on that. I agree auto updating on there would be good but we need to see an implementation for a desktop wallet first.

**Comment by karek314** [comment]
As far i heard, in Crypti it was something like bundled web view + background node - but im not sure about that, i have never used Crypti. Actually i can making OSX client with auto-updater if it's wanted, im pretty sure there are auto-updaters frameworks on other operating systems as well.

The thing is, a lot of people see Lisk as simplicity, i would advise sticking with that while ethereum is terrible in terms of that, tons of non-understandable things for casual users. Lisk shouldn't be more difficult then using any website or popular payment services.

**Comment by Isabello** [comment]
upgrade is implemented at this point, tested as working but will need more improvements, such as copying config.json setup

**Comment by fix** [comment]
What about the status of this issue @Isabello ? I feel we can close it. If there are some issues about the new implementation, it would be better to have a specific issue opened in lisk-build.

**Comment by Isabello** [comment]
Closing it.
