### ISSUE TITLE
ESLint warnings

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1454]
After all the recent merges, we ended up with these ESLint warnings:

```
/Projects/lisk/test/functional/http/post/common.js
  79:2  warning  The number of top-level suites is more than 1  mocha/max-top-level-suites

/Projects/lisk/test/integration/scenarios/network/peers.js
  34:2  warning  The number of top-level suites is more than 1  mocha/max-top-level-suites

✖ 2 problems (0 errors, 2 warnings)
```

It is possible, something got missed during merges, as there were so many of them on Tuesday.

**Comment by willclarktech** [comment]
I don't believe this indicates any problem with merging. Possible solutions are:

1. Add this rule to the list of temporarily ignored rules in `test/.eslintrc.json`
1. Separate suites into separate files
1. Wrap currently top-level suites in a single suite
