### ISSUE TITLE
Possibility to define custom storage directory

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#146]
Would be great to see feature to specify custom storage path for Lisk blockchain and other applications blockchains during installation process.

**Comment by karmacoma** [comment]
This is already possible with `installLisk.sh` our official installation script. @Isabello, please confirm.

**Comment by Isabello** [comment]
Thats correct. Upon install it will prompt you for what folder you would like to install the application to. If you are wanting the database decoupled from the binary install location that poses more challenges and would require some changes outside of installation.
