### ISSUE TITLE
Apply code documentation standards in db/*

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk#1471]
Parent: #1333

**Comment by vitaly-t** [comment]
We do have somewhat now here: https://github.com/LiskHQ/lisk/tree/development/db/sql

**Comment by Tschakki** [comment]
Nice, but it does not fully align with the new JSDoc standards that we now implemented in PR #1380 and #1341, so I will make a few adjustments. :)
One main difference is, that we are grouping files now by location (each folder is a namespace, and classes and modules can be member of that namespace).
