### ISSUE TITLE
Reuse lazy WS connection initialization provided by SocketCluster

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1472]
### Expected behavior
As pointed by @jondubois in the [comment](https://github.com/LiskHQ/lisk/issues/1391#issuecomment-361643206), client WebSocket calls handling might be simplified while using `socket.emit()` instead of `socket.send()`, where `socket` is the result returned by `socketcluster-client.initialize(options)` function. When `autoConnect: false` parameter passed to initialize function, the current functionality responsible for lazy socket connection initialization (`wsRPC.sendAfterConnectionReady`) will be kept. Moreover, the client socket will be linked and stored together with Peer instance, which simplifies the peer state management storing the peer's relevant data in one place - `peersManager.peers` array. Peer lifecycle from the client WS connection perspective will shape as follows:
1. Peer is being added to Peers List. Peer constructor is being called.
2. Peer constructor adds the new field `this.socket = scClient.initialize({autoConnect: false, ...}` to peer instance. The connection hasn't been initialized yet. While storing thousands of peers on Peers List it might have an impact on the overall performance. 
3. Peer has been selected to receive/send the data from/to. RPC is being invoked, which calls the corresponding `socket.emit()` that initializes the connection before the actual `emit()` silently.
4. When the following calls are performed the `emit()` happens without unnecessary connection initialization.
5. When Peer is being removed from Peers List, the client socket connection is being disconnected.

The code changes will demand the corresponding changes in `wamp-socket-cluster` library, in order to listen for the specific events, instead of low level `socket.on('raw')` actions handling.
### Actual behavior
In the current codebase `socket.send()` method of SocketCluster is being used. Managing of lazy connection initialization is being handled by `lisk-core` code on itself (`wsRPC.js` file). As a result peers related data is spread into separate files which can lead to inconsistencies - during peers removal, the connection stored in `wsRPC.clientConnections` is neither being removed nor disconnected. 

### Steps to reproduce
Peer initializes any of RPC procedures.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by jondubois** [comment]
To clarify the goal of this issue:

- Improve code quality and readability of the RPC logic https://github.com/LiskHQ/lisk/issues/1391#issuecomment-361643206
- The current logic for dealing with offline sockets is simplistic; right now if the socket is disconnected, we're waiting for a fixed 1000ms delay for the connection to be establishedbefore sending an RPC.
- We need a better strategy for handling temporarily lost connections and dealing with reconnections.
- We currently have two sources of truth when evaluating the connection state (connected/disconnected) of a peer; it's tracked by SocketCluster client but we also track it separately in `ws_rpc.js`; this is bound to cause issues.
- The socket object is currently decoupled from the Peer object which makes it harder to manage.
- We need a cleaner, more future-proof protocol; right now we're using a custom protocol which is an odd mix of WAMP and SC protocols with custom stuff on top. This makes client-side logic more complex and non-standard.
