### ISSUE TITLE
Jenkinsfile.migration fails due to no such file or directory

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#1474]
### Expected behavior

Build should run successfully.

### Actual behavior

Build fails with the following error:

`cp: cannot stat 'test/data/genesisBlock.json': No such file or directory`

### Steps to reproduce

Run the `Jenkinsfile.migration` build in Jenkins.

### Which version(s) does this affect? (Environment, OS, etc...)

`1.0.0`

**Comment by karmacoma** [comment]
Due to this PR: https://github.com/LiskHQ/lisk/pull/1356

**Comment by ManuGowda** [comment]
This issue has been fixed as part of this PR https://github.com/LiskHQ/lisk/pull/1356/files#diff-4350d4a5ae8922b3ec2f8d22b1867ffe which is already merged into 1.0.0.

**Comment by karmacoma** [comment]
@Nazgolze Pipeline needs to be configured to point to GitHub, rather than as Pipeline script.

**Comment by Nazgolze** [comment]
I see what this is.
So it failed before because we switched to snake case in 1.0 and it was looking for camel case.
So that was fixed.
Now it fails because it's looking for snake case and we have camel case in 0.9.12

I'll have a PR for this soon
