### ISSUE TITLE
Update existing accounts db repo tests to use minimum boilerplate code

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1476]
### Expected behavior
The unit tests should use minimum boilerplate code possible and to be completely isolated. 

### Actual behavior
Currently unit tests for db repos start up the complete application, which is completely unnecessary for those. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by vitaly-t** [comment]
My sentiment exactly, not sure how soon I will get around that.
