### ISSUE TITLE
Move swagger.definitions from onBind to library

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#1487]
### Expected behavior
`swagger.definitions` should be added to private variable `library` and loaded with constructor function
### Actual behavior
`swagger.definitions` are added to main scope, loaded by `onBind` method and assigned to a new variable `definitions`
- `modules/blocks/process`
- `modules/loader`
- `modules/peers`
- `modules/transport`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
@LucasIsasmendi These swagger definitions are passed by application scope after when modules are initialized. I don't see any problem of having definitions  assigned in **onBind**, although module will only be ready to be used after **onBind**

And here is the list of private variables; 
```
var modules;
var library;
var self;
var __private = {};
var definitions;
```
If we need to move ** definitions** to library then why not the **modules** as well? 

I feel more convenient to have seperate dedicated variable related to its purpose.

**Comment by LucasIsasmendi** [comment]
@nazarhussain the functionality of `onBind` across all the code is to initialize **modules** variable with modules content(app components in modules folder) and some times it calls bind. 
In the other hand, `constructor` initializes **library** variable, which contains logic, db, helpers and other components. 
In this case swagger is not a module, is an helper, therefore should be loaded by `constructor` (if we want to follow the current pattern of initialization).

**Comment by nazarhussain** [comment]
If that's some pattern we are following across modules then its ok.

**Comment by MaciejBaj** [comment]
@LucasIsasmendi I don't see any clear benefits of introducing the changes proposed, the good practice in that example is arguable.
