### ISSUE TITLE
Mocha handle done callback and no exclusive tests

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1492]
Child of #1485 
### Expected behavior
Turn on `mocha/handle-done-callback` rule and `done` callback should be handled.
Turn on `mocha/no-exclusive-tests` rule and use `skip` instead of `only` exclusive option.
### Actual behavior
Currently `mocha/handle-done-callback` and `mocha/no-exclusive-tests` turned off for all the tests.
### Steps to reproduce
Turn on `mocha/handle-done-callback` and `mocha/no-exclusive-tests` rule and run `npm run lint`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by willclarktech** [comment]
Reopening, see comment here: https://github.com/LiskHQ/lisk/pull/1503#pullrequestreview-94263851
