### ISSUE TITLE
Only lint staged files in precommit hook

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#1493]
### Expected behavior

Lint errors should prevent commits only if they occur in staged files (using lint-staged).

### Actual behavior

Lint errors in all lintable files will prevent committing.

### Steps to reproduce

`npm run lint`

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by chiptus** [comment]
since this is not assigned to anyone, I'm having a try. if it's ok.

**Comment by chiptus** [comment]
why don't we go with the approach in the lint-staged [readme](https://github.com/okonet/lint-staged#installation-and-setup):

```
{
  "scripts": {
+   "precommit": "lint-staged"
  },
+ "lint-staged": {
+   "*.js": ["eslint --fix", "git add"]
+ }
}
```

**Comment by willclarktech** [comment]
Hi @chiptus, would be great if you took this on. We already have `lint-staged` in place and a `.lintstagedrc`which applies Prettier to some files, so this issue is about modifying the existing structures to apply both Prettier and ESLint to staged files.

**Comment by chiptus** [comment]
ok, I'm on this

**Comment by chiptus** [comment]
Made a pull request, please review

**Comment by chiptus** [comment]
I've seen that when doing push it runs lint on all files again, should we make it run `lint-staged` like precommit, or is that the desired approach?

**Comment by willclarktech** [comment]
@chiptus That's currently desired behaviour, although we're open to reevaluating these processes.

**Comment by chiptus** [comment]
as I understand it, since we are already doing linting on precommit there is no need to do it on prepush.

Additionally linting of none changed files is also redundant IMO, they should have been linted when pushed

**Comment by willclarktech** [comment]
> there is no need to do it on prepush

It's an additional check in case people have added commits using `--no-verify`.

**Comment by chiptus** [comment]
You can also do no-verify on prepush. Another option is to add it to the
check on CI when opening a PR

On Feb 12, 2018 18:57, "Will Clark" <notifications@github.com> wrote:

there is no need to do it on prepush

It's an additional check in case people have added commits using --no-verify
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LiskHQ/lisk/issues/1493#issuecomment-364988320>, or mute
the thread

**Comment by willclarktech** [comment]
@chiptus Sure. The prepush check is not there to prevent people deliberately aiming for non-verified code, and of course we have linting on CI already. It's to prevent people pushing `--no-verify` commits that were only ever intended to be temporary and local.
