### ISSUE TITLE
API: List of delegates cannot be sorted by rate

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk#1498]
### Expected behavior
The following request should return list of delegates sorted by rate:
``http://127.0.0.1:4000/api/delegates/?sort=rate:asc&limit=100``

### Actual behavior
The request returns an error:
```
{
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "errors": [
                {
                    "code": "ENUM_MISMATCH",
                    "message": "No enum match for: rate:asc",
                    "path": []
                }
            ],
            "in": "query",
            "message": "Invalid parameter (sort): Value failed JSON Schema validation",
            "name": "sort"
        }
    ],
    "message": "Validation errors"
}
```

### Steps to reproduce

``http GET http://127.0.0.1:4000/api/delegates/?sort=rate:asc&limit=100``

### Which version(s) does this affect? (Environment, OS, etc...)
Latest 1.0.0

**Comment by nazarhussain** [comment]
@MichalTuleja These are possible sorting enums for this endpoint; 

```
            - username:asc
            - username:desc
            - rank:asc
            - rank:desc
            - productivity:asc
            - productivity:desc
            - missedBlocks:asc
            - missedBlocks:desc
```
So probably that `rate` you are looking for is renamed to `rank`. But I am not sure, as we have both attributes for delegate, **rate** is a static attribute for an account while **rank** is computed runtime.

**Comment by karmacoma** [comment]
Thanks @nazarhussain.

@MichalTuleja Please use `rank` instead as `rate` is a deprecated attribute.
