### ISSUE TITLE
Sending of Lisk to an unknown account is not allowed

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#15]
The sending of Lisk to an unknown account is not allowed:
http://i.imgur.com/ftkNQiL.png

Please allow the input of the belonging public key for accounts which are not yet part of the blockchain.

**Comment by karmacoma** [comment]
Resolved by: https://github.com/LiskHQ/lisk/commit/056de547988b5ccdd58ac47dc6e2cc6f36816995

Thank for you raising the issue 👍
