### ISSUE TITLE
API: Limit of delegates is set to 100

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk#1500]
### Expected behavior
The following query could return list of all active delegates (101):
``http://127.0.0.1:4000/api/delegates?limit=101``

Current limit is set to 100. It is possible to utilize the API in the current state, but it does not make sense to send another query for one remaining active delegate. 

### Actual behavior
The request throws an error message:

```
{
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "errors": [
                {
                    "code": "MAXIMUM",
                    "message": "Value 101 is greater than maximum 100",
                    "path": []
                }
            ],
            "in": "query",
            "message": "Invalid parameter (limit): Value failed JSON Schema validation",
            "name": "limit"
        }
    ],
    "message": "Validation errors"
}
```

### Steps to reproduce
``http GET http://127.0.0.1:4000/api/delegates?limit=101``

### Which version(s) does this affect? (Environment, OS, etc...)
Latest 1.0.0

**Comment by nazarhussain** [comment]
@MichalTuleja You are absolutely right. I integrated swagger to that endpoint in my first week when I joined Lisk, and was not aware of that 101 delegates logic at that time. The fix is very easy just to increase *max* value for *limit* param of particularly this endpoint.
