### ISSUE TITLE
Mocha no synchronous tests

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1501]
Child of #1485
### Expected behavior
```
it('should do foo', function (done) {
    done();
});

it('should do foo', function () {
    return promise;
}
```
### Actual behavior
```
it('should do foo', function () {
    return;
});

it('should do foo', function () {
    callback();
});
```
### Steps to reproduce
Turn on `"mocha/no-synchronous-tests": "off"` and run `npm run lint`
### Which version(s) does this affect? (Environment, OS, etc...)
Pending

**Comment by willclarktech** [comment]
@ManuGowda What's the problem with the first case in the `Actual behavior` section?

**Comment by ManuGowda** [comment]
@willclarktech it's a warning to have return statement within the function body of any mocha test statement. here is the rule info: https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-synchronous-tests.md#rule-details

**Comment by willclarktech** [comment]
@ManuGowda The documentation says it's a warning if there *isn't* a return statement, and doesn't explain why that particular case should raise a warning. I'm guessing because nothing is explicitly returned?

**Comment by ManuGowda** [comment]
Yes I believe so, the errors are because we are not returning anything specifically like a `promise` or return value or in case of async, we should return `await`, basically that rules expect something to be returned.

**Comment by nazarhussain** [comment]
@willclarktech @ManuGowda What to do with `generator` functions in test cases. 

```
it('should use the correct SQL file with no parameters', function*() {
	sinonSandbox.spy(db, 'any');
	yield db.blocks.getGenesisBlock();

	expect(db.any.firstCall.args[0]).to.eql(sql.getGenesisBlock);
	expect(db.any.firstCall.args[1]).to.eql(undefined);
	expect(db.any).to.be.calledOnce;
});
```

Converting such to test blocks to async is not working. Please provide some solution so I can commit and push my code.
