### ISSUE TITLE
Unauthorized try of change account's virgin field from 0 to 1

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1504]
### Expected behavior
N/A

### Actual behavior
Looks like we accidentally changed logic during account logic refactor or some database stuff refactor. For example in logs below - there are no transactions at all, and it still somehow try to set `virgin` field to `1` (maybe it's now kind of default value?) at end of a round. That is not correct behavior. 

```
[inf] 2018-02-05 15:42:50 | Forged new block id: 1434252536084965429 height: 99 round: 1 slot: 5373617 reward:0
[ERR] 2018-02-05 15:42:53 | Discovering new peers failed - No acceptable peers found
[ERR] 2018-02-05 15:42:58 | Discovering new peers failed - No acceptable peers found
[inf] 2018-02-05 15:43:00 | Broadhash consensus now 100 %
NOTICE:  table "mem_round_snapshot" does not exist, skipping
NOTICE:  table "mem_votes_snapshot" does not exist, skipping
[inf] 2018-02-05 15:43:00 | Forged new block id: 2747055006217268682 height: 100 round: 1 slot: 5373618 reward:0
[ERR] 2018-02-05 15:43:03 | Discovering new peers failed - No acceptable peers found
[ERR] 2018-02-05 15:43:08 | Discovering new peers failed - No acceptable peers found
[inf] 2018-02-05 15:43:10 | Broadhash consensus now 100 %
WARNING:  Reverting change of virgin from 0 to 1
[inf] 2018-02-05 15:43:11 | Forged new block id: 3986160213301948265 height: 101 round: 1 slot: 5373619 reward:0
```
### Steps to reproduce
Run node, wait until end of a round. Also application of genesis block fire some of these warnings.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
@4miners @karmacoma  As per my understanding of the code, below is the only place from where we update account `virgin` attribute to `0`

https://github.com/LiskHQ/lisk/blob/7da23971ae74a6f57ba274c215efbb6e06da5817/logic/account.js#L921-L923

Do you guys know any other location in code where we do same?

**Comment by nazarhussain** [comment]
@karmacoma @4miners I noticed this schema for *virgin* attribute; 

https://github.com/LiskHQ/lisk/blob/7da23971ae74a6f57ba274c215efbb6e06da5817/logic/account.js#L507-L510

As its stated above, maximum value of virgin attribute to `32767`. Are we really setting this attribute other than `0` or `1`?
