### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by whitj00** [LiskHQ/lisk#151]
Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz lisk-Linux-x86_64.tar.gz.md5
md5sum: lisk-Linux-x86_64.tar.gz: No such file or directory
md5sum: lisk-Linux-x86_64.tar.gz.md5: No such file or directory
grep: lisk-Linux-x86_64.tar.gz: No such file or directory
grep: lisk-Linux-x86_64.tar.gz.md5.md5: No such file or directory

On ubuntu

**Comment by ByronAP** [comment]
did you try deleting the installer and redownloading it?

**Comment by whitj00** [comment]
multiple times on multiple machines

**Comment by whitj00** [comment]
fixed by automatically setting liskVersion to lisk-Linux-x86_64.tar.gz

**Comment by Isabello** [comment]
This is an issue with file availability on downloads.lisk.io
