### ISSUE TITLE
DB config relies on NODE_ENV instead of path structure

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1511]
### Expected behavior
Application relies on `NODE_ENV` variable to check the actual environment.
### Actual behavior
After #1491 , there is a small regression in: https://github.com/LiskHQ/lisk/blob/0df97f51affe1a688f9ea7e03eb2401eaa793f3c/db/sql/config.js#L19-L20  It was intended for Webpack.

**Comment by vitaly-t** [comment]
I will do this update :wink:
