### ISSUE TITLE
Root eslint rules with zero errors

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1515]
Child of #1485

**Comment by willclarktech** [comment]
@ManuGowda Why does this need to be a child issue instead of being in the original parent issue?

**Comment by ManuGowda** [comment]
@willclarktech I thought it would be a good separation to have as a child issue, at first I wanted to create child issues for each of it, but that would add too many issues, so what I have done here is created a category of issues which can be fixed alon with
