### ISSUE TITLE
Integrate Snyk

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1523]
Snyk helps open source projects to stay secure. It continuously find & fix vulnerabilities in dependencies. 

This enhancement issue will add:
- Snyk as a dependency
- Snyk automatic checks when PRs add something that fails
- NPM scripts to help developers to check security before committing
- `.snyk` policy file to patch or ignore known vulnerabilities

**Comment by willclarktech** [comment]
We already have some setup done in Jenkinsfiles.
