### ISSUE TITLE
Lisk crashes with self-signed ssl certificate

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#154]
I have tried to set up self signed certificate on lisk node, but after restarting with new config lisk crashes with error

```
info 2016-05-25 16:25:25 Removing peer POST http://107.191.47.189:8000/peer/transactions 
info 2016-05-25 16:25:25 Removing peer POST http://40.117.37.59:8000/peer/transactions 
info 2016-05-25 16:25:25 Removing peer POST http://137.116.243.216:8000/peer/transactions 
info 2016-05-25 16:25:25 Removing peer POST http://23.96.28.155:8000/peer/transactions 
info 2016-05-25 16:25:25 Removing peer POST http://23.251.133.83:8000/peer/transactions 
error: Forever detected script was killed by signal: SIGKILL
info 2016-05-25 16:25:31 Lisk started: 0.0.0.0:8000 
fatal 2016-05-25 16:25:31 Domain master { message: 'listen EACCES',
  stack: 'Error: listen EACCES\n    at exports._errnoException (util.js:746:11)\n    at Server._listen2 (net.js:1141:19)\n    at listen (net.js:1184:10)\n    at net.js:1282:9\n    at dns.js:85:18\n    at process._tickDomainCallback (node.js:381:11)\n    at Function.Module.runMain (module.js:503:11)\n    at startup (node.js:129:16)\n    at node.js:814:3' }
error: Forever detected script exited with code: 0
```
I always generate certificates with openssl for private usage nginx web servers without any problem. I have tried few different approaches and certificate paths.
 
`openssl req -x509 -newkey rsa:2048 -keyout key.key -out cert.crt -days 999`

config.json
```
"ssl": {
        "enabled": true,
        "options": {
            "port": 443,
            "address": "0.0.0.0",
            "key": "key.crt",
            "cert": "cert.key"
        }
    },
```

After returning to previous config and restarting, it appears lisk.sh can't handle restarting properly. Sometimes it works and lisk starts, but in some cases i have to force quite lisk and postgresql processes before restarting.
```
lisk_user@develop-desktop:~/lisk-main$ bash lisk.sh restart
X Failed to stop lisk.
X Failed to stop lisk.
X Failed to stop lisk.
X Failed to stop lisk.
X Failed to stop lisk.
√ Postgresql stopped successfully.
√ Postgresql started successfully.
√ Lisk started successfully.
```

**Comment by Isabello** [comment]
Did you follow the install instructions regarding set cap? If you don't
allow node to use 443 as an unpriviledged user it will crash when binding
to the port.

**Comment by karek314** [comment]
Okay, it's working now. I haven't checked instructions. Anyway, why not include
`sudo setcap CAP_NET_BIND_SERVICE=+eip /home/lisk-main/bin/node`
in installation script then ?

**Comment by Isabello** [comment]
Ssl configuration is end user responsibility and set cap should only be
used if iptables to redirect the port from 443 to another port is not
desirable.

Ssl config is also not a requirement to run Lisk. Therefore it's an
optional item of setting up the node.

**Comment by karek314** [comment]
If user run node locally, then it's fine to skip ssl. But in case user would like to host node somewhere in datacenter and use it wherever need. Then it's necessary. I don't see a lot of work with even pre-generating self signed ssl and setting it to config.json. Actually it can be as optional option with installLisk script.
