### ISSUE TITLE
Lisk Freewallet is frozen "sending..."

### ISSUE THREAD

**Issue by awiator83** [LiskHQ/lisk#1544]
Hello,
I have a huge problem. My 5000 Lisks are suspended in my wallet on iPhone. It says it is "sending..." for over a week already. And I reinstalled the app few times already.
The App is called: "Lisk Freewallet, 1.0.31 Version" developed by freewallet.org
I contacted their support and they told me there are ongoing issues with LSK blockchain and a lot of transaction was temporarily suspended. They said it will be completed if possible if not they will be reversed after LSK is back to normal operations.
It is over a week already. Can anyone help me? I just tried to send it from Nano Wallet. What should I do?
Thank you

**Comment by 4miners** [comment]
@awiator83 I didn't notice any issues, Lisk network is operating normally.

**Comment by awiator83** [comment]
What should I do than?

**Comment by JakeSimmons89** [comment]
@awiator83 Does the wallet app give you a transaction Id or is the transaction still pending?

**Comment by awiator83** [comment]
Yes, it does give me Transaction Hash. May it help?

**Comment by JakeSimmons89** [comment]
@awiator83 Can you give us the Transaction id

**Comment by awiator83** [comment]
This is transaction ID: 6300335485286363847

**Comment by JakeSimmons89** [comment]
@awiator83 Sorry but that Transaction Id is not recognized as a legit id. What is your wallet address?

**Comment by awiator83** [comment]
Wallet address is: 13576127361987805485L

**Comment by JakeSimmons89** [comment]
@awiator83 When did you send this transaction ? and also do you have the passphrase for the wallet address or did the application not give you the passphrase?

**Comment by awiator83** [comment]
I send this transaction 2nd Feb 2018.
And I don`t remember to have passphrase. Every time I log after I reinstall the App I need to use my code and password I think. But for sure no passphrase for reinstalling.

**Comment by JakeSimmons89** [comment]
@awiator83 At the time did you send the transaction ?

**Comment by awiator83** [comment]
It shows: Local time of transaciton: 16:31
And I am in Hong Kong time zone.

**Comment by JakeSimmons89** [comment]
@awiator83 did you create the second passphrase before or after you sent this transaction?

**Comment by awiator83** [comment]
I don`t remember creating any passphrase on this wallet ever. And it never asked me for it.

**Comment by JakeSimmons89** [comment]
https://explorer.lisk.io/address/13576127361987805485L

Take a look at this and tell me what looks suspicious

**Comment by awiator83** [comment]
I don`t know what looks suspicious?

**Comment by awiator83** [comment]
Do you know what could happen?

**Comment by JakeSimmons89** [comment]
@karmacoma After taking all this information in and reading this application reviews both on Google play and the app store , I believe this to be a scam wallet as there is many reviews saying they can access or send their Lisk.

**Comment by awiator83** [comment]
This is Freewallet, very popular. Developed by freewallet.org
They have a lot of other wallets. What can I do now?

**Comment by JakeSimmons89** [comment]
@awiator83 Can we take this to https://lisk.chat

**Comment by awiator83** [comment]
Sure. Can you arrange it and let me follow?

**Comment by awiator83** [comment]
I just attached my issue in help desk on the other chat you sent me.
Let me know if you have any other ideas.
Thank you very much for your help!

**Comment by awiator83** [comment]
![img_4722](https://user-images.githubusercontent.com/36300591/36058775-8484930c-0e64-11e8-8660-5e392137b38c.jpg)

Ths is screenshot of my wallet on the iPhone
