### ISSUE TITLE
Limit forging to one passphrase

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk#156]
It would be beneficial to the network to allow only one forging account per node. Instead of an array just a simple k, v pair.

**Comment by ByronAP** [comment]
aka make it harder to make forging pools

**Comment by Isabello** [comment]
Having multiple delegates on a single node poses huge stability risks to
the network. If that node gets banned for passing bad blocks for whatever
reason, all of those delegates are now not forging.

**Comment by slasheks** [comment]
A forging pool is still viable. Examples: N nodes each have 1 delegate enabled or 1 node has enabled forging distributing funds to the members of the pool with fail-over . As it was mentioned above, this configuration of many forging delegates on 1 node can hurt the network, pooling delegate accounts in one node is not optimal and defeats the purpose of a decentralized network.

**Comment by ByronAP** [comment]
Hey I am not for pool forging so if it makes it harder I'm all for it

**Comment by fix** [comment]
not sure about the status of this one @karmacoma

**Comment by karmacoma** [comment]
Closing issue, as we will keep as is for now.
