### ISSUE TITLE
Possible invalid column names in account logic

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1564]
### Expected behavior
To research.
- review consistency
- review if it works
- review error handling (because no errors are thrown)
- review also other column names (globally)
- fix if needed
### Actual behavior
In database coulmn names are: `producedblocks`, `missedblocks`.

In account logic we have following column names:
https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/account.js#L366-L367
https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/account.js#L805-L810
https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/account.js#L829
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

Reference: https://github.com/LiskHQ/lisk/issues/1562

**Comment by 4miners** [comment]
Those fields are converted to camel case by logic in db repos, should be fine.

**Comment by nazarhussain** [comment]
For future reference this that name casting is done by; 

https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/db/repos/accounts.js#L45-L56

Notice the difference in `name` and `prop` attribute.
