### ISSUE TITLE
Npm install fails if snyk is not installed globally

### ISSUE THREAD

**Issue by Slamper** [LiskHQ/lisk#1568]
### Expected behavior

`npm install` should work without any modifications to package.json or preinstalling packages that are not listed in the Readme.md

### Actual behavior
`npm install` fails because it cannot find the `snyk` executable.
This also breaks `lisk-docker`
 
### Steps to reproduce
Use the `lisk-docker` Makefiles to build the `local` version.
`make local`

**Comment by willclarktech** [comment]
Yes, thanks for reporting, this is because `snyk` is listed as a `devDependency`, but the check is run `postinstall` regardless. We should only run this check for development installations.
