### ISSUE TITLE
Fuzzy search for delegates expects alphanumeric strings

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk#1579]
### Expected behavior
Fuzzy search for delegates should work fine with plain numbers and alphanumeric strings.

### Actual behavior
Fuzzy search for delegates does not work with integers.

`http://127.0.0.1:4000/api/delegates?search=1465651642158264047`
The number is a delegate address without L.

```
{
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "errors": [
                {
                    "code": "INVALID_TYPE",
                    "message": "Expected type string but found type number",
                    "path": []
                }
            ],
            "in": "query",
            "message": "Invalid parameter (search): Expected type string but found type number",
            "name": "search"
        }
    ],
    "message": "Validation errors"
}
```

### Steps to reproduce
Run Lisk Core and make the search request.

**Comment by nazarhussain** [comment]
Its a bit tricky one to find in system. For reference who ever work on this ticket. The behavior is handled by these lines of code. 

https://github.com/LiskHQ/lisk/blob/f8b0140cdc57da610495cab656603200031117e6/app.js#L387-L401

Just add `search` in the `ignore` list and it will be fixed.
