### ISSUE TITLE
Search string for fuzzy search in delegates cannot be longer than 20 characters

### ISSUE THREAD

**Issue by MichalTuleja** [LiskHQ/lisk#1580]
### Expected behavior
Fuzzy search for delegates should allow more than 20 characters.

### Actual behavior
Fuzzy search for delegates does not allow more than 20 characters.

Example:
`http://127.0.0.1:4000/api/delegates?search=12668885769632475474L`

```
{
    "errors": [
        {
            "code": "INVALID_REQUEST_PARAMETER",
            "errors": [
                {
                    "code": "MAX_LENGTH",
                    "message": "String is too long (21 chars), maximum 20",
                    "path": []
                }
            ],
            "in": "query",
            "message": "Invalid parameter (search): Value failed JSON Schema validation",
            "name": "search"
        }
    ],
    "message": "Validation errors"
}
```

### Steps to reproduce
Run Lisk Core and make the search request.

**Comment by nazarhussain** [comment]
https://github.com/LiskHQ/lisk/blob/f8b0140cdc57da610495cab656603200031117e6/schema/swagger.yml#L529-L534

**Comment by diego-G** [comment]
Delegates fuzzy search is related to the username not to the address. Therefore maximum length of 20 is correct.
