### ISSUE TITLE
Add unit test coverage for db/repos/migrations

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1589]
Parent: #1484

### Expected behavior
We need 100% coverage for db/repos/migrations

### Actual behavior
Currently there is no coverage for this repo.

**Comment by karmacoma** [comment]
Reopened to address failing tests encountered by: https://github.com/LiskHQ/lisk/pull/1637 and due to reversion to old promise syntax. Failing tests have been skipped for now.

**Comment by nazarhussain** [comment]
@vitaly-t Please looked the skipped tests specifically 

https://github.com/LiskHQ/lisk/blob/1.0.0/test/unit/db/repos/migrations.js#L298

And suggest some pattern/approach to test functions which involving transactions and generator functions.

**Comment by nazarhussain** [comment]
@vitaly-t FYI, based on discussion with @karmacoma I had reverted your changes that was causing failures of test cases. Had created the respective issue https://github.com/vitaly-t/pg-promise/issues/479

You do acknowledge that we love `pg-promise` and more importantly want to write clean and beautiful constructs introduced by you, but we have a principle that ugly code is better than beautiful but non-testable code. 

As soon you fix that particular issue in pg-promise, will introduce the changes again.
