### ISSUE TITLE
101 votes exceeded (2 too many) error: Forever detected script exited with code: 1

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#160]
Node crashed while it wasn't used by client. Just client website opened on blockchain tab. None of those lisk accounts belong to me.

```
log 2016-05-27 12:18:51 GET /api/loader/status/sync from 10.0.0.2 
log 2016-05-27 12:18:51 GET /api/loader/status/sync from 10.0.0.2 
log 2016-05-27 12:18:51 POST /peer/transactions from 138.91.241.131 
log 2016-05-27 12:18:51 GET /peer/height from 76.26.93.255 
info 2016-05-27 12:19:00 Current 20000 
log 2016-05-27 12:19:02 GET /api/loader/status/sync from 10.0.0.2 
log 2016-05-27 12:19:02 GET /api/loader/status/sync from 10.0.0.2 
log 2016-05-27 12:19:03 POST /peer/transactions from 96.127.136.18 
log 2016-05-27 12:19:09 GET /api/loader/status/sync from 10.0.0.2 
log 2016-05-27 12:19:09 GET /api/loader/status/sync from 10.0.0.2 
error 2016-05-27 12:19:09 { message: 'Maximum number of 101 votes exceeded (2 too many).',
  transaction: 
   { id: '5524930565698900323',
     height: 20407,
     blockId: '16820105418178921867',
     type: 3,
     timestamp: 238365,
     senderPublicKey: 'd09b5883f98350934345932d2e030e8478d2dba2985deaef85222cbc315d6421',
     requesterPublicKey: null,
     senderId: '6272272422739160383L',
     recipientId: '6272272422739160383L',
     amount: 0,
     fee: 100000000,
     signature: '18be11b3d5ce002b1f7866b01a87f02fb36ec9a95bf6eb53245b3fddee957c2e1f7618415e2ad02316c61c420bc9be7e3649104caa43d03579d3cbeba161430e',
     signSignature: 'bbfc43aa7fe7def729f4f73f3547f6e57a7a4776fc5a95169b309c5eb5f066e23c87017a12f095ce40c49d848ac1ff210a3c0383a6cf8c7df5f16302d6aa3107',
     signatures: null,
     confirmations: NaN,
     asset: { votes: [Object] } },
  block: 
   { id: '16820105418178921867',
     version: 0,
     timestamp: 238370,
     height: 20407,
     previousBlock: '4143114733638054568',
     numberOfTransactions: 2,
     totalAmount: 0,
     totalFee: 200000000,
     reward: 0,
     payloadLength: 3872,
     payloadHash: '3775d35d05c4c05b7d5063527e90e225d50c821ebd2b892787b75faa0b1cc110',
     generatorPublicKey: '2f872264534a1722e136bddf29a301fa97708f88583130770d54c1d11366e5fc',
     generatorId: '9926064757911337096L',
     blockSignature: 'a1c22b553e495228ec43ee24b450d74c6512064fea5fdcd794cfa33ea8596f053aeb9aa175d9b7a7a8f82e85443d71e5da064733b099a6dfc77c6e48a8b03409',
     confirmations: NaN,
     totalForged: '200000000',
     transactions: [ [Object], [Object] ] } } 
fatal 2016-05-27 12:19:09 System error { message: 'undefined is not a function',
  stack: 'TypeError: undefined is not a function\n    at /home/lisk_user/lisk-main/app.js:3:9921\n    at /home/lisk_user/lisk-main/node_modules/async/lib/async.js:52:16\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:264:21)\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:44:16)\n    at Immediate.immediate._onImmediate (timers.js:418:16)\n    at processImmediate [as _immediateCallback] (timers.js:367:17)' }
info 2016-05-27 12:19:09 Cleaning up... 
info 2016-05-27 12:19:09 Cleaned up successfully 
error 2016-05-27 12:19:09 null 
error: Forever detected script exited with code: 1
```

**Comment by Isabello** [comment]
It looks like you were doing a rebuild operation for memory tables from existing data. That is why you are seeing accounts that aren't yours.

**Comment by karek314** [comment]
That's weird because i didn't. This node was running smoothly for more than 12h. Started normally with `bash lish.sh start` This one crashed, while other nodes still running fine.

**Comment by Isabello** [comment]
That's what current 20000 means there, though.

**Comment by karek314** [comment]
I have not run `bash lisk.sh rebuild` or `bash lisk.sh reload`. That's why it's weird. Im not sure why did that happened. But this is obviously issue here. Anyway even if i do rebuild or reload it's still serious issue.

**Comment by Isabello** [comment]
Upload the full log for review

**Comment by karek314** [comment]
After restarting, node entered the same issue. Im currently rebuilding blockchain.
Here is entire context, not entire log since it's very huge.Trimmed only to necessary data.
At **2016-05-27 17:47:26** i have started rebuilding from scratch
[logs.log.zip](https://github.com/LiskHQ/lisk/files/287112/logs.log.zip)

**Comment by Isabello** [comment]
According to the logs Lisk was restarted with mem_rounds unnapplied and had to rebuild your memory tables.

{"level":"info","message":"Lisk started: 0.0.0.0:8000","timestamp":"2016-05-27 12:05:02"}
{"level":"info","message":"Lisk https started: 0.0.0.0:7000","timestamp":"2016-05-27 12:05:02"}
{"level":"info","message":"Modules ready and launched","timestamp":"2016-05-27 12:05:02"}
{"level":"info","message":"Blocks 20470","timestamp":"2016-05-27 12:05:03"}
{"level":"warn","message":"Detected unapplied rounds in mem_round","timestamp":"2016-05-27 12:05:03"}
{"level":"warn","message":"Recreating memory tables","timestamp":"2016-05-27 12:05:03"}
{"level":"info","message":"Current 0","timestamp":"2016-05-27 12:05:26"}
{"level":"info","message":"Current 5000","timestamp":"2016-05-27 12:11:32"}
{"level":"info","message":"Current 10000","timestamp":"2016-05-27 12:14:27"}
{"level":"info","message":"Current 15000","timestamp":"2016-05-27 12:16:55"}
{"level":"info","message":"Current 20000","timestamp":"2016-05-27 12:19:00"}
{"level":"error","message":{"message":"Maximum number of 101 votes exceeded (2 too many).","transaction":...

**Comment by ddresch** [comment]
Got the same error on my side. Using the official docker image and it was running and doing nothing at least I left the tab open with the GUI and that's it. Then I needed to restart the container and it ended up in this state and error: 'Maximum number of 101 votes exceeded (2 too many).'

**Comment by karek314** [comment]
Temporary solution is to just `bash lisk.sh rebuild` it will rebuild blockchain from network. My node did not entered the same issue up to now. In case docker, you can just delete this container and create new one.

**Comment by ddresch** [comment]
@karek314 thx for your feedback. I killed the container now and it's building the blockchain again. Is there a way to keep the downloaded blockchain and point a new container to it? In the docs the update is also killing the whole container.

**Comment by karek314** [comment]
The problem is corrupted blockchain itself here, that's why rebuild is necessary with current client.
