### ISSUE TITLE
api/delegate orderBy inconsistent results

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#161]
tried https://liskwallet.info/api/delegates?limit=10&offset=10&orderBy=username%20asc
and https://liskwallet.info/api/delegates?limit=10&offset=10&orderBy=username

the ordering never takes place

**Comment by mrv777** [comment]
I think this may have been the same as this which is closed for the next release: https://github.com/LiskHQ/lisk/issues/143

**Comment by ByronAP** [comment]
checking

**Comment by ByronAP** [comment]
nope not the same, ordering by some fields work others don't

**Comment by ByronAP** [comment]
https://liskwallet.info/api/delegates?limit=100&offset=0&orderBy=username:desc <-- does nothing
https://liskwallet.info/api/delegates?limit=100&offset=0&orderBy=username <-- does nothing
https://liskwallet.info/api/delegates?limit=100&offset=0&orderBy=rate:desc <-- works as expected
https://liskwallet.info/api/delegates?limit=100&offset=0&orderBy=rate <-- works as expected
tried a bunch of combinations seems like the only one that fails is username and 
https://liskwallet.info/api/delegates?limit=100&offset=0&orderBy=approval <-- doesn't have the expected behavior as no sorting is done but works if an order direction is specified.
