### ISSUE TITLE
Update pg-promise to 7.5.4

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1616]
### Expected behavior
Maintain `pg-promise` updated. 

Here it is the changelog:
https://github.com/vitaly-t/pg-promise/blob/v.7.5.4/CHANGELOG.md

And tag information:
https://github.com/vitaly-t/pg-promise/releases/tag/v.7.5.4

### Actual behavior
Current dependency version is 7.4.1 https://github.com/vitaly-t/pg-promise/blob/v.7.4.1/CHANGELOG.md

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by vitaly-t** [comment]
Specifically [v7.5.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.7.5.4) makes long transactions safer when connections aren't very reliable.

**Comment by vitaly-t** [comment]
Actually, since it doesn't get into 1.0.0 anyway, then it doesn't matter much.

I have been working on version 8.0.0 lately, it is finished, pending some documentation that I'm updating now, so it will be out soon, and a better upgrade altogether :wink:
