### ISSUE TITLE
Issue when balance <=1

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#162]
Please see 9550345879566156771L you can test it with secret "voice fossil rifle lamp enact control way shift april hundred claim tent" the balance shows as 1 and if the transfer fee is 0.1 this account should be able to send 0.9 however you can not as any amount <1 throws "Invalid LSK amount" and if you enter 1 error "Account has no LISK" is thrown.

**Comment by ByronAP** [comment]
dang it someone sent an additional lsk, grrr

**Comment by ByronAP** [comment]
@karmacoma should this be under UI?

**Comment by karmacoma** [comment]
@ByronAP Yes, definitely a UI issue. There are tests for this in backend already. I will look to why it's happening and resolve asap in lisk-ui. Sorry for the inconvenience.

**Comment by ByronAP** [comment]
moved to ui

**Comment by Crypto2** [comment]
May be a similar issue here, I have a similar problem trying to send funds from an account. Here is the flow that happened:

1. Sent 5 LSK from an account with 9.8 balance, returned success and a TX ID.
2. TX never confirmed, after 15 minutes re-sent. This one did confirm.
3. Tried sending 4 LSK, API returns "Account has no LISK". Seems like it still thinks the TX that didn't confirm went through maybe?

Account balance returned via API and block explorer: 4.80000000

**Comment by Crypto2** [comment]
Any update on this? It's a pretty big issue since when users do withdrawals that don't make it to the blockchain I can't re-send them if that's all they had in their wallet.
