### ISSUE TITLE
Filipino Localization [TAGALOG][REQUEST]

### ISSUE THREAD

**Issue by cordeta** [LiskHQ/lisk#1620]
I would like to propose contributions regarding Filipino Tagalog Localization 

If you may, I would like to request a repo in Translation/tl_PH containing the files that you want me to translate so those future collaborators would be able to see this one.  

Localization would help your platform gain visibility in some countries and at the same time help you engaged in some local investors.

Any response is highly appreciated

**Comment by karmacoma** [comment]
Thanks for the offer @cordeta, but we have no immediate plans to translate the Lisk Core backend application into other languages. This issue should probably be targeted at @LiskHQ/lisk-nano, which features translations in its user interface.

**Comment by cordeta** [comment]
Thank you for your immediate response . I will contact LiskHQ . Thank you for the recommendation
