### ISSUE TITLE
Syntax issue in test util for swagger_spec

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#1622]
### Expected behavior
[https://github.com/LiskHQ/lisk/blob/1.0.0/test/common/swagger_spec.js#L275](https://github.com/LiskHQ/lisk/blob/1.0.0/test/common/swagger_spec.js#L275)
[https://github.com/LiskHQ/lisk/blob/1.0.0/test/functional/http/get/blocks.js#L29](https://github.com/LiskHQ/lisk/blob/1.0.0/test/functional/http/get/blocks.js#L29)

- Parameter of the class input should be `(method, path, responseCode)`
- The usage of this exported function should be used without instantiating.
### Actual behavior

```
module.exports = function(method, path, responseCode) {
	return new SwaggerTestSpec(method, method, responseCode);
};
```
The second input of SwaggerTestSpec suppose to be path.
If we use it with full parameter, it will have wrong behavior.
```
var blocksEndpoint = new swaggerEndpoint('GET /blocks');
```
since it's already instantiating, it should throw `TypeError`, but it seems like it's not . 

### Which version(s) does this affect? (Environment, OS, etc...)
`v1.0.0`

**Comment by nazarhussain** [comment]
Yes it should be:

```
module.exports = function(method, path, responseCode) {
	return new SwaggerTestSpec(method, path, responseCode);
};
```

**Comment by shuse2** [comment]
Also I think, 
`var blocksEndpoint = new swaggerEndpoint('GET /blocks');`
should be
`var blocksEndpoint = swaggerEndpoint('GET /blocks');`
because `swaggerEndpoint` is not constructor, it is returning new instance of `SwaggerTestSpec`.
I feel like it should throw `TypeError` though...
