### ISSUE TITLE
API performance benchmarking

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1623]
Presently, the database API is indifferent as to the priority of calls being made against it, i.e. high-priority calls are mixed with low-priority calls.

By adding support for API priority, we will improve the database API availability, and make database access scale in a way that's weighted and predictable.

---

The first step is to identify priority within the database API - which ones require high availability, and which ones do not, according to:

* Business requirements for each API call, as for importance and frequency
* Relative percentage of time consumed by each API call, versus the frequency of calls

Identifying just 2 levels should be sufficient at first - as low-priority and high-priority ones.

Then we can introduce support for this within the code as explained below.

---

At the moment we create a single `db` object, setting its pool size as this: 

```
min: 10, max: 95
```

This in turn allocates a single connection pool `db.$pool` within the object. What we want is to have 2 connection pools instead, one for low-priority calls, and one for high-priority calls.

In order to achieve this, we create two `db` objects instead, with connection pools configured like this:

* High-priority `dbHigh` object: `min: 10, max: 80`
* Low-priority `dbLow` object: `min: 5, max: 15`

(this is just an approximation) Note that in reality, the value of `min` is utterly unimportant, only `max` is important.

So, our `./db` module would expose two `db` objects, and for every use of the database API, the app will use the `db` object that corresponds to the priority of that API call within the system.

---

Next step after this will be: Use a separate user/password account for each `db` object, as [PostgreSQL supports configuring load priority](https://wiki.postgresql.org/wiki/Priorities) based on the login account, down to memory and CPU usage.

**Comment by nazarhussain** [comment]
That would be a good to have thing. At least for now we don't for-see any such problem due to which we set query level priorities. 

Logically in LiskCore as  a whole every thing can be categorized in two chunks of functionality. 

1. Any SQL used for internal processing (block processing, transaction status) 
2. Any SQL used to provide information to outward (REST API) 

So in principal any thing in category 1 has high priority than 2. And I don't feel that we should go further deep to categorize each query further in those two. 

In future we have plan for modularization of the core. @karmacoma do have more insights on that plan. But as per my thoughts, during that refactoring cycle we will strip out REST API completely to a seperate module started on a seperate process, having its own connection pool. So just configuring connection priority on PostgreSQL level would be good enough. 

With that thought we don't need to refactor/add/update any DB related stuff our code base. Each module will start with its own process, its own connection pool, with its own db username. And rest of the stuff should be configured on PostgreSQL level.

**Comment by 4miners** [comment]
That issue is not a priority right now, and will not be for a little while.

**Comment by MaciejBaj** [comment]
Two points:
> Business requirements for each API call, as for importance and frequency
> Relative percentage of time consumed by each API call, versus the frequency of calls

are extremely beneficial and would include a measurement of DB queries performance, as well as Lisk Core's API follows REST standards - https://github.com/LiskHQ/lisk/issues/1780.
Analysis needs to be performed against a real (Mainnet) dataset - keeping in mind that few queries are performed on tables that might potentially grow indefinitely. 


As the result of the analysis, the full picture of bottlenecks of API endpoints and DB queries will be revealed. 

On top of every query, the Business requirements should be gathered - frequency and importance.

**Comment by nazarhussain** [comment]
Developing custom newrelic tracer compatible to our application, which will gave ability to track performance of active API calls as well as feature to compare with historical data.

**Comment by nazarhussain** [comment]
Based on specs given below I benchmarked all the transactions in system; 

```
Version: 1.0.2
Network: mainnet
Instance Type: Digital Ocean Droplet
CPU: 1vCPU
RAM: 1GB
```


### Web Transactions


Action | Avg (ms) | SD (ms) | Min (ms) | Max (ms)
-- | -- | -- | -- | --
get /delegates/{address}/forging_statistics | 15400 | 1360 | 13000 | 21900
get /delegates | 81700 | 17200 | 294 | 92600
get /transactions | 14500 | 4180 | 1030 | 32900
get /node/status | 14600 | 3250 | 281 | 23600
get /blocks | 3190 | 2770 | 6.66 | 13100
get /votes | 408 | 344 | 4.55 | 2660
post /transactions | 2530 | 3670 | 52 | 56300
get /voters | 557 | 376 | 7.71 | 4910
get /delegates/forgers | 241 | 292 | 9.25 | 1760
get /accounts | 206 | 149 | 33.2 | 1050
get /node/transactions/{state} | 39 | 65.5 | 3.25 | 768
get /peers | 50.4 | 52.7 | 7.15 | 474
get /node/constants | 27 | 73.4 | 1.74 | 911
get /node/status/forging | 16.4 | 12.2 | 7.39 | 34.6


### Background Jobs


Action | Avg (ms) | SD (ms) | Min (ms) | Max (ms)
-- | -- | -- | -- | --
delegatesNextForge | 56800 | 207000 | 3.36 | 1370000
loaderSyncTimer | 566000 | 395000 | 364000 | 1370000
peersDiscoveryAndUpdate | 3900 | 4170 | 2080 | 25200
transactionPoolNextBundle | 607 | 9390 | 0.11 | 235000
broadcasterNextRelease | 142 | 505 | 0.143 | 4860
calculateConsensus | 89.7 | 306 | 0.809 | 2950
transactionPoolNextExpiry | 475 | 1410 | 0.176 | 9060


@MaciejBaj @diego-G @4miners @ManuGowda

**Comment by nazarhussain** [comment]
BTW While doing the benchmarking found this fact worth investigating further. 

![screenshot at sep 13 10-17-52](https://user-images.githubusercontent.com/112468/45476120-6ed35880-b73e-11e8-9e50-19d61c4d5e4e.png)

See there is pattern in the maximum time a CPU tick take. There is an tremendous increase seems in regular intervals.
