### ISSUE TITLE
Update Socketcluster dependencies to major version 10

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1631]
### Expected behavior

Maintain inside dependencies updated. 

### Actual behavior
```
socketcluster          =9.2.0  →  =10.0.1
socketcluster-client   =9.0.3  →  =10.1.1
```

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by jondubois** [comment]
The `socketcluster-client` upgrade is non-breaking.
The `socketcluster` upgrade only has a single breaking change but it shouldn't affect Lisk since we don't use that feature at the moment. If any issues, see https://github.com/SocketCluster/socketcluster/releases/tag/v10.0.0

**Comment by jondubois** [comment]
EDIT: There is one breaking issue with the client: We should rename the `connections` property of the client socket to `clients`. https://github.com/SocketCluster/socketcluster-client/releases/tag/v10.0.0
