### ISSUE TITLE
Drop forked and unused dependencies

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1632]
### Expected behavior

Install just the useful dependencies and minimise the need to maintain forked repositories.

### Actual behavior

`json-sql` was forked to be used as a dependency but it is not used anymore.
`decompress-zip` is in the same situation.
Repositories will need to be archived.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
I removed its usage from `logic/account` and it was very hectic work. Would be glad if that dependency been completed removed.
