### ISSUE TITLE
API allows address with lowercase L when sending but not when filtering

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#1638]
### Expected behavior
Address ending in `l` should be equivalent to ending in `L` because it is the case in sending transactions.

E.g.
https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584L
and
https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584l
should be the same

### Actual behavior
https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584L returns correctly filtered transactions

https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584l returns empty list

### Steps to reproduce
Compare
https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584L
and
https://testnet.lisk.io/api/transactions?recipientId=12530546017554603584l

### Which version(s) does this affect? (Environment, OS, etc...)

It affects both Lisk Core 0.9.X and 1.0.0

**Comment by 4miners** [comment]
Address should always end with uppercase `L`, inconsistency will be enforced in https://github.com/LiskHQ/lisk/issues/1639
