### ISSUE TITLE
Can't restart lisk after creating a dapp

### ISSUE THREAD

**Issue by oelmekki** [LiskHQ/lisk#164]
Hi,

I've been trying to play with lisk, but I just can't go pass the app 
creation through `lisk-cli`: when I restart lisk, it will refuse to 
start with an error.

```
$ node app.js
info 2016-05-28 20:10:51 Lisk started: 0.0.0.0:7000
NOTICE:  relation "blocks" already exists, skipping
NOTICE:  relation "trs" already exists, skipping
[plus many more pg warnings]
NOTICE:  relation "dapps_name" already exists, skipping
log 2016-05-28 20:10:52 error error: Unknown transaction type: 9
log 2016-05-28 20:10:52 error error: ERROR:  duplicate key value violates unique constraint "blocks_height"
DETAIL:  Key (height)=(1) already exists.
log 2016-05-28 20:10:52 error tx: INSERT INTO "blocks"("id","version","timestamp","height","previousBlock","numberOfTransactions","totalAmount","totalFee"
,"reward","payloadLength","payloadHash","generatorPublicKey","blockSignature") VALUES ('16943551226118820306',0,0,1,null,104,10000000000000000,0,0,20492,'
\xc8afab5a223e5601a0bc4aebadd8f7fc51648c244253cf29281f3dab1e01d840','\x7d56fccc6717d83d5bd1d67a9127767d3bf032a244a2a4f6b86245907bddd6a7','\xdc3debc85d526f
bc48febaa7876906e560ba80bb9af36c5545c006e005f67456f7cc4a91d0b4542b6d53993b42f5d95a728acd0024fb5e16323ca6699ee7e609')
error 2016-05-28 20:10:52 Error: Unknown transaction type: 9
fatal 2016-05-28 20:10:52 Blocks#saveBlock error
```

I'm using the lisk-0.2.3 downloaded from https://downloads.lisk.io/lisk/test/lisk-source.tar.gz

I would try sources from master branch, but it's unclear how to use 
testchain rather than mainchain.

I use this dummy repos as skeleton repos: https://github.com/oelmekki/test2

I've tried using docker image and following the doc for installing from 
sources, both give the same error.

I suppose it doesn't matter from there, but loading the frontend on 
localhost:7000 display the json result: 

```
{"success":false,"error":"Blockchain is loading"}
```

**Comment by kevinstl** [comment]
I'm experiencing the exact same error.

**Comment by m-schmoock** [comment]
This is due to the fact that your node already feed a postgreSQL database using his 'old' genesis block. (duplicate key value violates unique constraint "blocks_height"
DETAIL:  Key (height)=(1) already exists.)

In this case you need to drop the psql database and recreate it. After it the node should sync just fine and show your app in the webview:

    sudo -u postgres dropdb <DBNAME>
    sudo -u postgres createdb -O lisk <DBNAME>

I think this should be fixed in lisk-cli utility. It already ask for deleting "blockchain.db" (which imho should drop and recreate psql instead of deleting an otherwise non-existing file :D

**Comment by oelmekki** [comment]
Hi @m-schmoock ,

Thanks, it kind of helps :)

I don't have the insert error anymore, but it still won't start, with 
the following error:

```
info 2016-06-26 14:27:41 Lisk started: 0.0.0.0:7000
NOTICE:  view "blocks_list" does not exist, skipping
NOTICE:  view "full_blocks_list" does not exist, skipping
NOTICE:  view "trs_list" does not exist, skipping
log 2016-06-26 14:27:43 error error: Unknown transaction type: 9
error 2016-06-26 14:27:43 Error: Unknown transaction type: 9
fatal 2016-06-26 14:27:43 Blocks#saveBlock error
```

**Comment by m-schmoock** [comment]
hm... Did you restart the docker container after dropping/recreating the DB?
It looks like it did not restore the tables it needs, which it usually does when it finds an empty database.

**Comment by oelmekki** [comment]
Oh, my bad then, sorry :)

I actually removed the `start_lisk` script in the container, thinking 
making it create the database and download the blockchain was meant 
only for first run, and I replaced it with a script that would just 
start the database and the node server.

I'll give it an other try, thanks! :+1:

**Comment by fix** [comment]
What the status of this issue?

**Comment by ShineKami** [comment]
I now everything works without problems.
Lisk-0.3.2b (testnet), lisk-cli 1.1.3

**Comment by karmacoma** [comment]
Closing due to: #560
