### ISSUE TITLE
Update the unit tests for db repos to test calls for pg-promise helpers namespace

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1649]
### Expected behavior

Should be able to stub `pg-promise` helpers namespace. 

```
sinonSandbox.spy(pgp.helpers, 'insert')
```

### Actual behavior

Currently we can't stub the helpers namespace due to which we are not testing helper functions calls. 

### Steps to reproduce

In any unit test file add this line
```
sinonSandbox.spy(db.$config.pgp.helpers, 'insert')
```
This will cause an error `TypeError: Cannot redefine property: insert`

### Fix
The issue is reported on `pg-promise` and is fixed. https://github.com/vitaly-t/pg-promise/issues/473. Need to upgrade `pg-promise` higher than `8.1.1` and go through all db repos unit tests to see such use cases.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
@vitaly-t I am working not this task and it seems upgrade to `8.2.1` still didn't solved the problem. 
```
console.log(db.$config.version);   // 8.2.1
console.log(db.$config.options.noLocking);  // true
sinonSandbox.spy(db.$config.pgp.helpers, 'insert');
```
Still getting same error: 
```
TypeError: Cannot redefine property: insert
```

**Comment by vitaly-t** [comment]
@nazarhussain I just did a quick test...

This one throws an error:

```js
const pgp = require('pg-promise')({});
const db = pgp('test');
db.$config.pgp.helpers.insert = 123;
```
and this one doesn't:

```js
const pgp = require('pg-promise')({
    noLocking: true
});
const db = pgp('test');
db.$config.pgp.helpers.insert = 123;
```

So the problem was fixed correctly. Not sure why the stubbing wouldn't work on your end...

**Comment by nazarhussain** [comment]
Ok I run this outside the app and its working as expected, now  need to look what's blocking this behavior inside our app code base. 

https://runkit.com/nazarhussain/5aaa8014ba34410012a86157

**Comment by nazarhussain** [comment]
The issue related to stubbing resolved by this change
https://github.com/LiskHQ/lisk/pull/1739/files#diff-adf057742c94318bbf06eb7ee29a72baL25
