### ISSUE TITLE
blockchain frozen

### ISSUE THREAD

**Issue by AxlSaddek** [LiskHQ/lisk#165]
Hi,

Sorry, I think I froze the blockchain, https://explorer.lisk.io/tx/7085895639065793685
Next time, I will try those things on testnet.

There is some checks missing on Recipient/Address length in transactions.

**Comment by karek314** [comment]
Already reported in #152

**Comment by Phoenix1969** [comment]
thank-you, a fix is in the works

**Comment by karmacoma** [comment]
Thank you for your patience. We have posted a new release which resolves this issue:

https://blog.lisk.io/lisk-v0-3-1-release-announcement-44e862406b77#.u0a9wahfc

Network health is now restored.

**Comment by karek314** [comment]
Afaik in Crypti there was check if recipient really exists, starting from Lisk 0.3.1 coins sent to random address for example 00123023400000L Will be destroyed as long someone does not generate wallet with address of "00123023400000L" ?
