### ISSUE TITLE
Docker mainnet image is trying to connect to testnet database

### ISSUE THREAD

**Issue by pablos91** [LiskHQ/lisk#1655]
### Expected behavior
Working docker mainnet image

### Actual behavior

```
[FTL] 2018-03-01 21:39:28 | Error: FATAL:  database "lisk_test" does not exist

    at Error (native)
```

### Steps to reproduce

Upgrade lisk docker container do 0.9.12 version with below commands:

```
docker pull lisk/mainnet
docker-compose up -d --no-deps --build lisk (from the compose directory)
```

### Which version(s) does this affect? (Environment, OS, etc...)

Linux Docker Image from docker hub

**Comment by pablos91** [comment]
reverting docker image to 0.9.11 solves the problem. please fix it guys ...

```
Database is ready.
[inf] 2018-03-01 21:45:39 | App connected with redis server
[inf] 2018-03-01 21:48:28 | Lisk started: 0.0.0.0:8000
[inf] 2018-03-01 21:48:28 | Modules ready and launched
[inf] 2018-03-01 21:48:44 | Blocks 5348166
[inf] 2018-03-01 21:48:44 | Genesis block matched with database
[inf] 2018-03-01 21:49:19 | Blockchain ready
[inf] 2018-03-01 21:49:20 | Imported peers from database - {"count":0}
[inf] 2018-03-01 21:49:21 | Starting sync
[inf] 2018-03-01 21:49:21 | Broadhash consensus now 0 %
```

**Comment by fchavant** [comment]
@pablos91 the issue you were encountering should be fixed now Make sure to pull the latest images (`lisk/mainnet:latest` or `lisk/mainnet:0.9.12`, whichever you are using).
Have a look at [lisk-docker#76](https://github.com/LiskHQ/lisk-docker/issues/76) and the documentation on the [Docker Hub](https://hub.docker.com/r/lisk/mainnet/) for more information.
