### ISSUE TITLE
Negative Blockchain  time stamp value in lisk client ui

### ISSUE THREAD

**Issue by Nerigal** [LiskHQ/lisk#167]
Minimum value should be 0 

http://i.imgur.com/HsVTibL.png

**Comment by TheGoldenEye** [comment]
Please check your local time. Seems, the time on your computer is some seconds late.

**Comment by Nerigal** [comment]
regardless of the client local time, the ui should display 0 at minimum..imo

**Comment by TheGoldenEye** [comment]
No, I don't think so. The client shows the time difference between the blocktime and the local time.
Let the time difference larger, e.g., 1 minute: Should the client show something like this?:
Height        Time
78306        0 sec ago
78305        0 sec ago
78304        0 sec ago
78303        0 sec ago
78302        0 sec ago
78301        0 sec ago
78300        9 sec ago
78299        19 sec ago

By the way, you can setup the client to show fill time:
![image](https://cloud.githubusercontent.com/assets/17945384/15783337/0654b6fc-29ae-11e6-9c5e-fb19ff7cf2ee.png)

... or you correct your local time ;)

**Comment by Nerigal** [comment]
so you expect every one in the world that use lisk client having perfect atomic time sync to avoid displaying negative time stamp value  ?

**Comment by TheGoldenEye** [comment]
I'm sure, not. But I think the solution is not good. 
Perhaps it is better, the client determines the correct time difference and adjusts ALL times shown.

**Comment by Nerigal** [comment]
unsigned_value = Math.abs(signed_value);

**Comment by TheGoldenEye** [comment]
Then you change -3s to 3s ???

**Comment by Nerigal** [comment]
http://jsfiddle.net/5UCy4/14/

**Comment by fix** [comment]
I agree, this is UX deceptive to show negative time. Also users do not care if this is acurate. Nerigal solution seems good to me. cc @karmacoma

**Comment by karmacoma** [comment]
Moved to: https://github.com/LiskHQ/lisk-ui/issues/74.
