### ISSUE TITLE
BuiltIn Extra HTTP Web Service for automatic HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#168]
We need an easy integrated way of serving 301 redirect to https trought http protocol

As I understand it, the lisk software open 1x http service and 1x https service.
The port used are already configurable in the config.json file. (for example, I use 8000 and 2443 using a prerouting rule to redirect 443 to 2443) 

Currently someone need to install nginx using something like:

server {
  listen 80;
  server_name lisk.mydomain.com;
  rewrite ^ https://$server_name$request_uri? permanent;
}

OR

server {
       listen         80;
       server_name    lisk.mydomain.com;
       return         301 https://$server_name$request_uri;
}

My idea would be to add another available port in the SSL section of the config.
like :

"ssl": {
    "options": {
      "port": 2443,
      "301port": 2080,
      ...
    }

And serve the 301 directly from lisk client (should be easier to do then rewrite I think)

That way a simple redirection from 80 -> 2080 would do the trick so evryone is always HTTPS without the need to install nginx, apache or else. (Using already built-in web client)

**Comment by ByronAP** [comment]
Just to weigh in here, I think it is better the way it is. If the install script installed NGINX it opens Lisk up to security issues. Setting up NGINX is very personal and should be used in conjunction with black and white lists that a appropriate for your machine along with other machine specifics such as ssl. If Lisk installed NGINX without knowing your exact whitelist, blacklist, ssl, and other settings there would be hell to pay.

**Comment by ByronAP** [comment]
Also NGINX is not available on every platform so another headache would be ensuring the machine is capable of running it.

**Comment by slasheks** [comment]
NGINX was a suggestion to address a larger issue, which is, serving a wallet by default un-encrypted. I agree with @Gr33nDrag0n69, we should look into a viable solution to prevent the wallet from being served over http. Perhaps this issue can spark a conversation to improve this. 

My take would be, separate the node sync service from the wallet, and only allow the wallet to be served over https, even generating a self-signed cert as part of the initial process, I think that is better than nothing. 

I believe there is another issue with this request (service separation).

**Comment by Gr33nDrag0n69** [comment]
ByronAp, I think you missed the point. I'm not saying to bundle nginx or apache. This is exactly what I want to remove as prerequisite to send 301 redirect on a http port. We should be able to serve the 301 redirect without any third party since the lisk client already have everything inside to server http.301 redirect. SLasheks you probably right, I didn't think of that but yes I think the switch is already there for that, just not functionnal yet. (not sure, didn't check for a while)

**Comment by staticinstance** [comment]
Do you mean something like this:


var https = require('https');
var fs = require('fs');
var options = {
    key: fs.readFileSync('./key.pem'),
    cert: fs.readFileSync('./cert.pem')
};

https.createServer(options, function (req, res) {
    res.end('secure!');
}).listen(443);

// Redirect from http port 80 to https
var http = require('http');
http.createServer(function (req, res) {
    res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
    res.end();
}).listen(80);

**Comment by staticinstance** [comment]
var https = require('https');
var fs = require('fs');
var options = {
key: fs.readFileSync('./key.pem'),
cert: fs.readFileSync('./cert.pem')
};

https.createServer(options, function (req, res) {
res.end('Secured Lisk ;)');
}).listen(443);

// Redirect from http port 80 to https
var http = require('http');
http.createServer(function (req, res) {
res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
res.end();
}).listen(80);

**Comment by staticinstance** [comment]
Do you mean something like this?

var https = require('https');
var fs = require('fs');
var options = {
key: fs.readFileSync('./key.pem'),
cert: fs.readFileSync('./cert.pem')
};

https.createServer(options, function (req, res) {
res.end('Secured Lisk ;)');
}).listen(443);

// Redirect from http port 80 to https
var http = require('http');
http.createServer(function (req, res) {
res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
res.end();
}).listen(80);

**Comment by Gr33nDrag0n69** [comment]
static instance, didn't check inner code of lisk but yes it would probably be something like that

**Comment by staticinstance** [comment]
It could work if the code checks to see if the cert exists, if it does then redirect to ssh otherwise just stay on http.  I'll see what I can do to work on this a bit.

**Comment by staticinstance** [comment]
currently working on #170

**Comment by fix** [comment]
The main issue here is that while the ip and the port is shared with peers, there is no information whether it is served via http or https, or even if this is a lite-client or not. This would need an upgrade of the database schema.

Mitigation would be to try to connect via https, if failed, use http, but it would add extra noise on the network.

**Comment by Isabello** [comment]
This is unnecessary. Users can implement Nginx if they desire this functionality. With the removal of Lisk-UI and the migration to websockets it becomes doubly unnecessary. I am closing this as `wontfix`.
