### ISSUE TITLE
Consistent usage of es6 features in modules implementation

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#1680]
Parent #1709
### Expected behavior
Use of es6 features in modules repo to make sure consistency and making use of the latest features.
### Actual behavior
Most of the modules implementations are not inline with the es6 features.
- [x] accounts.js
- [x] blocks.js
- [x] cache.js
- [x] dapps.js
- [x] delegates.js
- [x] loader.js
- [x] multisignatures.js
- [x] node.js
- [x] peers.js
- [x] rounds.js
- [x] signatures.js
- [x] system.js
- [x] transactions.js
- [x] transport.js
- [x] voters.js

blocks folder
- [x] api.js 
- [x] chain.js
- [x] process.js
- [x] utils.js
- [x] verify.js (waiting #1657 )
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by willclarktech** [comment]
This should probably be part of a new parent issue, rather than one regarding tests.
