### ISSUE TITLE
add "Good First Contribution" label

### ISSUE THREAD

**Issue by staticinstance** [LiskHQ/lisk#169]
Can a "Good First Contribution" label be added?  I believe it could help to promote Lisk and inspire people from the JS community to submit contributions.

**Comment by karmacoma** [comment]
We are mentioning every significant contribution in our release posts. So if you find, or resolve an issue, your contribution will likely be mentioned. For any persistent contributors, we will include in a contributors document on GitHub, with the possibility of a job offer if they are considered to be truly valuable :)

**Comment by staticinstance** [comment]
That sounds good.  However, what I meant to say was that issues could be tagged with an "Easy First Contribution" label so developers could know an easy entry point to start contributing to the app.

**Comment by karmacoma** [comment]
@staticinstance Okay done. I've added the label, and will make an effort to label the first good contribution as they arrive. We still need a contribution guide for developers, but we will handle that separately. Thanks for the idea 👍
