### ISSUE TITLE
Review the API documentation and prepare the publishable format

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1691]
We are in process of closure of `1.0.0`, so need to get ready to publish our API documentation to a publicly accessible location. For these: 

1. Need to review the documentation thoroughly to remove in inconsistency 
2. Add more conceptual details e.g. tag descriptions, endpoint descriptions 
3. Analyze & research the tool/process to convert specification to human readable format 
4. Develop mechanism to publish it to to docs.lisk.io automatically on release

**Comment by webmaster128** [comment]
When working on this, would it be possible to publish the documentation source code on Github? I am seeing a lot of documentations bug in the current website lisk.io/documentation and it would be super easy to fix those with PRs.
