### ISSUE TITLE
More then 101 votes for delegates possible

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#17]
After opening the client with the testnet genesis account (14837479272589364523L) there are 101 votes for the different genesisDelegates. I added a vote for my account (14837479272589364523L), so I had 102 in total. This should be a vote be too much...
The voted delegates are not shown, so I cannot remove votes.
see: http://i.imgur.com/JRkY2tH.png

**Comment by karmacoma** [comment]
This issue has now been resolved here: https://github.com/LiskHQ/lisk/issues/54
