### ISSUE TITLE
Bump API version to 1.0.24 and publish in Swagger Hub

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1706]
Update comes from #1621, #1675 and #1688 

### Which version(s) does this affect? (Environment, OS, etc...)

`1.0.0`

**Comment by willclarktech** [comment]
Is there any way to see changelogs for these api spec bumps?

**Comment by diego-G** [comment]
@willclarktech please compare versions https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.24
