### ISSUE TITLE
It's not possible to sort delegates by 'producedblocks'/'missedblocks' with api/delegates

### ISSUE THREAD

**Issue by biolypl** [LiskHQ/lisk#1716]
### Expected behavior
After query `https://wallet.mylisk.com/api/delegates?orderBy=producedblocks` I expect array of delegates sorted by number of produced blocks
### Actual behavior
I got error 'Invalid sort field'
### Steps to reproduce
Query Lisk `/api/delegates?orderBy=producedblocks`
### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core 0.9.12

**Comment by Mastermaulik** [comment]
@MaciejBaj @ManuGowda any updates on this bug? Please provide some details about this bug so that I can work on it.
