### ISSUE TITLE
Merge query generation with query methods

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1719]
Using the latest pg-promise 8.2.1, wrap all query-generating code into the query methods.

This will make sure that any error produced during the static query generation will become rejection of the query method, and not happen on the outside.

Just some places where it needs to be refactored:

**Potential bug examples**

Code below doesn't handle any query-generating errors, should they occur:

* https://github.com/LiskHQ/lisk/blob/development/db/repos/accounts.js#L258
* https://github.com/LiskHQ/lisk/blob/development/db/repos/accounts.js#L286
* https://github.com/LiskHQ/lisk/blob/development/db/repos/accounts.js#L479
* https://github.com/LiskHQ/lisk/blob/development/db/repos/accounts.js#L553
* https://github.com/LiskHQ/lisk/blob/development/db/repos/blocks.js#L310
* https://github.com/LiskHQ/lisk/blob/development/db/repos/transactions.dapp.js#L86
* https://github.com/LiskHQ/lisk/blob/development/db/repos/transactions.delegate.js#L73
* etc...

Not bugs, but need to be refactored:

* https://github.com/LiskHQ/lisk/blob/development/db/repos/peers.js#L92

**Comment by MaciejBaj** [comment]
Closed by #1721.
