### ISSUE TITLE
Add Google authenticator option to lisk wallet 

### ISSUE THREAD

**Issue by Nerigal** [LiskHQ/lisk#172]
it could be very interesting if the wallet could handle google authenticator to increase the security of the wallet login page

Thank you

**Comment by Gr33nDrag0n69** [comment]
In my opinion, I don't see how it is needed.
You can already have a 2nd passphrase over main passphrase.
2x 240 - 300 bits keys is way enought.

**Comment by karmacoma** [comment]
@Gr33nDrag0n69 is correct, the second passphrase already fulfils this purpose.
