### ISSUE TITLE
Installation fails - compiling libsodium

### ISSUE THREAD

**Issue by zapnap** [LiskHQ/lisk#1725]
Installation fails on both OS X and Ubuntu 16.04 LTE due to issues compiling libsodium. Note that sodium@2.0.3 (and 2.0.1 release) appear to compile locally without issue outside of the project, but Lisk's sodium package appears to be pegged to a fork of v2.0.1. Not sure why -- missing context -- so I figured I'd file an issue to report and inquire.

### Actual behavior

```
make[4]: *** No rule to make target `crypto_scalarmult/curve25519/sandy2x/sandy2x.S', needed by `crypto_scalarmult/curve25519/sandy2x/libsodium_la-sandy2x.lo'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [check-recursive] Error 1
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [libsodium] Error 2
/Users/nap/dev/lisk/lisk/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make libsodium exited with code 2
    at ChildProcess.<anonymous> (/Users/nap/dev/lisk/lisk/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
```

### Steps to reproduce

Follow instructions in README. Instructions differ somewhat from what's found on lisk.io/documentation for source installation but both result in the same error for me.

### Which version(s) does this affect? (Environment, OS, etc...)

Attempted to build on both OSX and Linux (Ubuntu 16.04 LTS). Same issue in both cases. node v6.12.1 and npm v5.3.0.

**Comment by sdrpa** [comment]
I confirm the same issue on macOS 10.13.3 on both master and development branches. node -v v6.12.3, npm -v3.10.10.

**Comment by zapnap** [comment]
fwiw I did ultimately get this running on a virgin Ubuntu 16.04 virtualbox (node 6.12.1 and npm 3.10.10)... but it still won't compile on OS X.

**Comment by sdrpa** [comment]
@zapnap @diego-G By accident I found it works correctly if path to lisk repo contains no whitespaces on macOS 10.13.3 node -v v6.12.3, npm -v v3.10.10. 
I renamed /Users/sdrpa/Lisk Development/lisk to /Users/sdrpa/Lisk/lisk and compilation worked without errors.

**Comment by camelash** [comment]
a

**Comment by webmaster128** [comment]
When I checkout https://github.com/LiskHQ/node-sodium.git in a path containing whitespaces and simply run `npm install` I get the error from above but also the error message

> configure: error: The build directory contains whitespaces - This can cause tests/installation to fail due to limitations of some libtool versions

This is from `deps/libsodium/configure.ac:44`, i.e. the libsodium build system. This is still [present in the current libsodium](https://github.com/jedisct1/libsodium/blob/28e62a6/configure.ac#L45).

Thus I'd call this a known limitation. Not very convenient but at least there is a proper error message.

**Comment by webmaster128** [comment]
The file [crypto_scalarmult/curve25519/sandy2x/sandy2x.S](https://github.com/LiskHQ/node-sodium/blob/895ac44/deps/libsodium/src/libsodium/crypto_scalarmult/curve25519/sandy2x/sandy2x.S) is part of the [node-sodium](https://github.com/LiskHQ/node-sodium) source code and Make should not need to create it.

Does

```
$ git clone https://github.com/LiskHQ/node-sodium.git
$ cd node-sodium
$ npm install
```

work on that OSX machine?

**Comment by webmaster128** [comment]
@zapnap What version of node is running on your OSX? Typically homebrew installs very new software. I have node 9.4.0 in my Mac. But [node-sodium is not compatible with node 9 yet](https://github.com/paixaop/node-sodium/issues/123).

**Comment by zapnap** [comment]
@webmaster128 node v6.12.1 and npm v5.3.0 installed using nvm as noted above.

**Comment by webmaster128** [comment]
Right it is there, sorry. Anyway, would be good to know if the error also occurs if you use the plain project, see https://github.com/LiskHQ/lisk/issues/1725#issuecomment-377830116

**Comment by zapnap** [comment]
@webmaster128 Compiling fine locally. And so is the main project (development branch) now; just pulled latest. Thanks for following up!
