### ISSUE TITLE
Refactor transaction pool removeUnconfirmedTransaction function

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1728]
### Expected behavior
1. Create a separate function to remove `UnconfirmedTransaction`, `QueuedTransaction` and `MultisignatureTransaction` transaction and update the same which is being called in `TransactionPool.prototype.undoUnconfirmedList` and `__private.expireTransactions` functions.
```
TransactionPool.prototype.removeTransactions = function(id) {
        self.removeUnconfirmedTransaction(id);
	self.removeQueuedTransaction(id);
	self.removeMultisignatureTransaction(id);
};
```

2. Update the `TransactionPool.prototype.removeUnconfirmedTransaction` function from the following
```
TransactionPool.prototype.removeUnconfirmedTransaction = function(id) {
	const index = self.unconfirmed.index[id];

	if (index !== undefined) {
		self.unconfirmed.transactions[index] = false;
		delete self.unconfirmed.index[id];
	}

	self.removeQueuedTransaction(id);
	self.removeMultisignatureTransaction(id);
};
```

to

```
TransactionPool.prototype.removeUnconfirmedTransaction = function(id) {
	const index = self.unconfirmed.index[id];

	if (index !== undefined) {
		self.unconfirmed.transactions[index] = false;
		delete self.unconfirmed.index[id];
	}
};
```

### Actual behavior
The `__private.expireTransactions` function is calling `self.removeUnconfirmedTransaction` which appears to be removing only `UnconfirmedTransaction` from the function name, but in the implementation it removes  `UnconfirmedTransaction`, `QueuedTransaction` and `MultisignatureTransaction`.

The possible reason behind this implementation is we have the logic to remove the unconfirmed transaction and we utilized this function to remove the following as well
```
self.removeQueuedTransaction(id);
self.removeMultisignatureTransaction(id);
```

**Comment by MaciejBaj** [comment]
The issue will become part of https://github.com/LiskHQ/lisk/issues/2209.
