### ISSUE TITLE
Remove unused helpers/constants variables

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1732]
### Expected behavior

All the variables presented in file https://github.com/LiskHQ/lisk/blob/1.0.0/helpers/constants.js should be documented, useful and utilised.

### Actual behavior

Some of them as `addressLength` or `maxAddressesLength` are not used at all.

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`

**Comment by vitaly-t** [comment]
Simply setting `no-unused-vars: "error"` in eslint config will do the trick.

**Comment by willclarktech** [comment]
See https://github.com/LiskHQ/lisk/blob/development/.eslintrc.json#L37

**Comment by vitaly-t** [comment]
> See https://github.com/LiskHQ/lisk/blob/development/.eslintrc.json#L37

That's a separate thing. See the differences:

* [no-unused-expressions](https://eslint.org/docs/rules/no-unused-expressions)
* [no-unused-vars](https://eslint.org/docs/rules/no-unused-vars)

**Comment by willclarktech** [comment]
Ah, sorry you're right. `no-unused-vars` is included in AirBnB's config: https://github.com/airbnb/javascript/blob/7ff6303513b46e8b7dd0bc03327b138a6db7b3b4/packages/eslint-config-airbnb-base/rules/variables.js#L39

The problem here is they're defined as properties on an object, which isn't caught by the rule.

**Comment by ManuGowda** [comment]
@diego-G @willclarktech the constants in https://github.com/LiskHQ/lisk/blob/1.0.0/helpers/constants.js are really not constants, as part of this issue, do we also consider changing them to `const` instead of var object structure?

**Comment by diego-G** [comment]
I'd say that would be another issue with a higher scope. I suggest to open a new one instead of fixing it here.
