### ISSUE TITLE
Add current time to node/status endpoint

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk#1733]
### Expected behavior

node/status endpoint should also return current time known by the node

### Actual behavior

node/status endpoint does not return current time

### Description

We have experienced timestamp in the future problems with clients that might be a few seconds in the future in comparison with the node they talk to. It would be great to have a comparison of timestamps in node/status so that clients are aware of any differences.

**Comment by SargeKhan** [comment]
This is a change in the API. Should it be added to minor release?

**Comment by diego-G** [comment]
@MaciejBaj shall we add the current time of the machine, the current timestamp regarding the Lisk Epoch or perhaps both?

**Comment by MaciejBaj** [comment]
@SargeKhan adding a new field to API doesn't break the API due to semver specification.

**Comment by MaciejBaj** [comment]
@diego-G the information will be potentially helpful to end users willing to send transactions. Lisk Core rejects transactions with the future timestamp: 
```
	if (slots.getSlotNumber(transaction.timestamp) > slots.getSlotNumber()) {
			return setImmediate(
				cb,
				'Invalid transaction timestamp. Timestamp is in the future'
			);
		}
```
And later on `getSlotNumber` function expects a time in seconds passed since Genesis Block.
So the answer is yes, we should return `epochTime`.
