### ISSUE TITLE
Non-deterministic tests

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#1737]
### Expected behavior

In order to make tests less brittle/more reliable, they should be deterministic.
We should use more hard-coded values and fixtures. Also, using hard-coded values makes the tests more readable.

See https://martinfowler.com/articles/nonDeterminism.html

### Actual behavior

Several of our tests (including unit tests) are non-deterministic; for example, we often use the `faker` module to generate random input values in tests - We don't seem to be logging those random inputs so even if a test case did fail because of a specific value, we would not be able to reproduce the failure - Which makes the test less trustworthy/useful.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by willclarktech** [comment]
The alternative would be to run further in the other direction and do more thorough property-based testing, e.g. using http://jsverify.github.io/.

**Comment by MaciejBaj** [comment]
It is definitely a good pattern to use, but it doesn't affect the unit tests to a noticeable extent. Closing for now.
