### ISSUE TITLE
Concerns about new API formats and backward compatibility.

### ISSUE THREAD

**Issue by hirishh** [LiskHQ/lisk#1748]
Hello,

I have some concerns about the delivery strategy of the new core 1.0 API. These new API are completely not compatible (aka **breaking backward compatibility**) with the old one.

Generally, in the industry, when a company of a REST based product delivers a new major version of the API, they create a v2/* path and they still keep the support on v1 API for a while. This will guarantee to customers and users enough time to migrate their tools/services with very limited disruption.

Not providing a backward compatibility solution, once on mainnet, **it will force everyone to stop their business**, develop and deploy a compatible version while creating a **disruption of their service**. Developing in testnet and be ready for the hardfork is not the correct approach to the problem. It's just a mitigation that, personally, I think is not enough.

I'm thinking about Exchanges for example. Or the hundreds of lisk tools around that are currently active (pools, tools, services).

Could LiskHQ clarify the delivery strategy?

**Comment by dakk** [comment]
A 6/12 month deprecation period could be a better strategy

**Comment by vekexasia** [comment]
I must agree on this. There are a lot of community built tools that rely on the old API schema.

I am also sure that a lot of businesses are using the apis too: exchanges for example

**Comment by MaciejBaj** [comment]
We will prepare migration guide for both 
1. Lisk Core API from 0.9.12 version to 1.0.0 
2. Lisk Elements moving to version 1.0.0 (especially helpful for clients like exchanges)
When Lisk Core Beta version will be released, it will give an opportunity to any 3rd party to try the migration on.
Hopefully, it solves your concerns.

**Comment by keyesdav** [comment]
Agree with op on this. Generally it is the job of the API owner to maintain
backwards compatibility, not the integrators. If you don't do this, you're
going discourage parties from investing in integrations. Maybe you get a
pass on this since you are releasing 1.0.0, but going forward you guys need
to take API backwards compatibility much more seriously.

I would suggest that you formalize your API compatibility policy. For
example, "API is guaranteed to be backwards compatible within all minor
releases of a major release, and incompatibilities will be announced three
minor releases before shipping."

**Comment by hirishh** [comment]
Totally agree with @keyesdav.

@MaciejBaj: migration guides is generally something that is concurrent *with* backward compatibility and a defined strategy for deprecation. 

This means that core 1.0.0 hard fork is going to create disruption. Basically, every actor in the lisk ecosystem must shut down their services/tools *at the same time* (that's why is important to maintain a deprecation period) in order to migrate to new API format. 

As @keyesdav just advised, it is better if LiskHQ will define strict guidelines about API formats and backward compatibility starting from 1.0.0

**Comment by webmaster128** [comment]
What happens when 1.0 is deployed on testnet? Do API users need to use a different API on testnet and on mainnet?

**Comment by hirishh** [comment]
@webmaster128 yep

**Comment by hirishh** [comment]
Well, Hard fork is done. I hope all the future modifications to API will be backward compatible or there will be a deprecation time.

I'll close this issue then. Best
