### ISSUE TITLE
Refactor lisk-core constants to use const, upper case with underscores

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#1774]
### Expected behavior
- The constants should be defined using `const` 
- The constants names should have an upper case with underscores for separators.
### Actual behavior
- Lisk-core constants are using `vars`, this would lead to the mutability of the constants and leading to change in behaviour in the application. 
- The constants are defined using lowercase with camelCase for separators.

### Steps to reproduce
```
var constants = require('../helpers/constants.js');
constants.activeDelegates = 300;
Now the activeDelegates count will be changed to 300 from 101.
```
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
Reopen, because it was closed automatically by mistake.

**Comment by MaciejBaj** [comment]
Consecutively in the whole application change var to const when possible, and var to let when it gets mutated.
