### ISSUE TITLE
NetworkHeight shows always zero

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#1778]
### Expected behavior

`height` & `networkHeight` should be ~ the same. 

### Actual behavior
This line is not properly working https://github.com/LiskHQ/lisk/blob/02d35b04afb2384db1e1b4257b0b8d202ea3fda5/modules/loader.js#L811 
```
{
    "meta": {},
    "data": {
        "broadhash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "consensus": 100,
        "height": 15024,
        "loaded": true,
        "networkHeight": 0,
        "syncing": false,
        "transactions": {
            "confirmed": 178,
            "unconfirmed": 0,
            "unprocessed": 0,
            "unsigned": 0,
            "total": 178
        }
    },
    "links": {}
}
```
### Steps to reproduce

`curl -X GET http://localhost:4000/api/node/status`

### Which version(s) does this affect? (Environment, OS, etc...)
`v1.0.0-alpha.1`

**Comment by 4miners** [comment]
@MaciejBaj @ManuGowda https://github.com/LiskHQ/lisk/pull/1790#discussion_r177736202
