### ISSUE TITLE
"Sign in with Trezor"

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#178]
It would be great to add possibility to add one click sign in with trezor hardware wallet like on mytrezor.com. User navigate to login.lisk.io, local node or lite client in future. Website authenticate with trezor pin, every transaction could be signed offline even with multi-signature for triple security. Keeping passphrase saved in plain text on computer is not best idea and reentering passphrase each time from memory decreases usability.

**Comment by Phoenix1969** [comment]
I think we would first need encompass multicurrency wallet to add lisk.

**Comment by fix** [comment]
This is more a lisk-ui issue, please @karek314 open a ticket on this repo.

Also there is js lib to use trezor in some app https://github.com/trezor/trezor.js

**Comment by karek314** [comment]
Started discussion in Trezor-mcu repo
https://github.com/trezor/trezor-mcu/issues/152

Moved to Lisk-Nano as it will be come main client ?
https://github.com/LiskHQ/lisk-nano/issues/32
