### ISSUE TITLE
Develop a strategy and related toolset to benchmark database layer

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1780]
We have to define a strategy/guideline/steps to benchmark current database layer. Most of our database interactions already been abstracted to individual SQL files, so we need to develop some toolset that helps us to monitor the performance of those SQLs. 

e.g. 

1. We define a threshold time for execution of any SQL, e.g. 100ms, if any SQL takes more time that should be identified 
2. During some certain set of operations, we should be aware that which SQL/QueryFile is executed most of the time. 

The outcome of that task would be: 

1. Some document to defining that strategy 
2. Code base / toolset to implement that strategy 
3. Measurable outcome from that toolset / code base for future reference 

Note: 

1. Here we are not discussing the database profiling on operating system level, we want similar on application level 
2. This task is initial step to further extend in stress testing for database layer 
3. This task is initial step for identification of bad performance queries for optimization process.

**Comment by vitaly-t** [comment]
This one could be an entry point:

https://github.com/LiskHQ/lisk/blob/4ebaa55f97da632c2a72a86716715ef3239a062e/db/index.js#L40

That's why I added it there in the first place.

**Comment by nazarhussain** [comment]
@vitaly-t 👍 I know this is the entry point we would be using. But I don't want to add boilerplate code to actual code base. So why I used word `toolset` here, I foresee some lib/tool outside our codebase to encapsulate every thing related to profiling/benchmarking, and hooked up only in development mode or on demand to production mode.

**Comment by vitaly-t** [comment]
For that there's a huge variety of tools to analyze performance of PostgreSQL. Just pick one.

**Comment by vitaly-t** [comment]
Interesting points to consider when analyzing how the database layer behaves underneath...

You can hook into the connection pool like this, and see what is going on:

```js
db.$pool.on('acquire', function () {
    // this.totalCount - number of connections currently consumed from the pool.
    // It will never exceed the maximum pool size set in the connection.

   // this.idleCount - number of idle connections in the pool

  // this.waitingCount - number of queries/tasks currently waiting for the next available connection
});
```

**Tips:**

* Big `waitingCount` will always be a bad sign, meaning the system is too busy in terms of the connectivity to be efficient.
* `totalCount` sitting at the maximum means the pool size is insufficient for the way it is used by the app.

**Comment by MaciejBaj** [comment]
Should be done no sooner than #1623. Hopefully, the benchmarking of API can cover DB queries analysis because of following the REST standards.

**Comment by nazarhussain** [comment]
Working to develop a strategy to identity any transaction which executes in more than provided threshold time. e.g. If we set threshold of 300ms and we run the application for few hours with stress test, our strategy at the end will list down all sql queries that took more than 300ms.

**Comment by nazarhussain** [comment]
Based on specs given below I benchmarked all the database queries in system; 

```
Version: 1.0.2
Network: mainnet
Instance Type: Digital Ocean Droplet
CPU: 1vCPU
RAM: 1GB
```

Here is the grouped result for each query run in the system. We can also see samples traces for slow transaction in each category. 

Name | Operation | Avg (ms) | Min (ms) | Max (ms)
-- | -- | -- | -- | --
Postgres trs_list select | select | 4,390 | 0.765 | 12,100
Postgres trs select | select | 3,990 | 0.294 | 13,200
Postgres other | other | 3,400 | 0.007 | 21,700
Postgres SELECT select | select | 751 | 0.010 | 90,800
Postgres rounds_rewards insert | insert | 701 | 0.005 | 1,990
Postgres delegates select | select | 442 | 1.42 | 3,280
Postgres blocks_list select | select | 383 | 0.915 | 3,210
Postgres insert | insert | 282 | 0.005 | 1,990
Postgres select | select | 278 | 0.010 | 90,800
Postgres mem_round insert | insert | 240 | 0.006 | 1,890
Postgres update | update | 199 | 0.006 | 2,500
Postgres mem_accounts update | update | 199 | 0.006 | 2,500
Postgres mem_accounts2delegates insert | insert | 150 | 0.007 | 415
Postgres mem_accounts select | select | 59.3 | 0.259 | 933
Postgres transfer insert | insert | 54.4 | 0.008 | 971
Postgres votes insert | insert | 47.6 | 19.9 | 75.4
Postgres mem_accounts insert | insert | 41.5 | 0.38 | 166
Postgres trs insert | insert | 40.8 | 0.015 | 579
Postgres mem_round select | select | 37.5 | 0.067 | 145
Postgres mem_accounts2delegates select | select | 32.3 | 0.522 | 4,240
Postgres mem_accounts2u_delegates insert | insert | 24.7 | 23.3 | 26.6
Postgres mem_round delete | delete | 12 | 0.748 | 27.4
Postgres delete | delete | 12 | 0.748 | 27.4
Postgres blocks insert | insert | 8.95 | 0.326 | 195
Postgres blocks select | select | 7.42 | 0.077 | 364


@MaciejBaj @diego-G @ManuGowda @4miners

**Comment by nazarhussain** [comment]
If you would be wondering about category `other` means. Here are some queries that counted under this category. 

21.7 seconds 
```sql
WITH delegate AS (SELECT 1 FROM mem_accounts m WHERE m."isDelegate" = 1 AND m."publicKey" = decode('9771b09041466268948626830cbfea5a043527f39174d70e11a80011f386bb57', 'hex') LIMIT 1), rewards AS (SELECT count(*), sum(reward) AS rewards, sum(fees) AS fees FROM rounds_rewards WHERE "publicKey" = decode('9771b09041466268948626830cbfea5a043527f39174d70e11a80011f386bb57', 'hex') AND ('0' IS NULL OR "timestamp" >= '0') AND ('72715687' IS NULL OR "timestamp" <= '72715687') ) SELECT (SELECT * FROM delegate) AS delegate, (SELECT count FROM rewards) AS count, (SELECT fees FROM rewards) AS fees, (SELECT rewards FROM rewards) AS rewards
```

17.2 seconds
```sql
WITH delegate AS (SELECT 1 FROM mem_accounts m WHERE m."isDelegate" = 1 AND m."publicKey" = decode('9771b09041466268948626830cbfea5a043527f39174d70e11a80011f386bb57', 'hex') LIMIT 1), rewards AS (SELECT count(*), sum(reward) AS rewards, sum(fees) AS fees FROM rounds_rewards WHERE "publicKey" = decode('9771b09041466268948626830cbfea5a043527f39174d70e11a80011f386bb57', 'hex') AND ('0' IS NULL OR "timestamp" >= '0') AND ('72715669' IS NULL OR "timestamp" <= '72715669') ) SELECT (SELECT * FROM delegate) AS delegate, (SELECT count FROM rewards) AS count, (SELECT fees FROM rewards) AS fees, (SELECT rewards FROM rewards) AS rewards
```

**Comment by vitaly-t** [comment]
I think you guys need to start looking at rewriting things with JSON queries. This is what I would be doing, if I had enough time. JSON queries is what made the core optimization in PostgreSQL 10.0, they can be real kick-ass replacing `JOIN`-queries on the client side.

The implication of such change is big, it means joining the logic of multiple queries into one where possible, which requires some prior analysis, and good understanding of the query logic that's used.

**Comment by nazarhussain** [comment]
Hi @vitaly-t, we had been doing internal discussions on refactoring of the db layer. That may also include JSON queries, but not confirmed for now.

**Comment by vitaly-t** [comment]
A simple example of moving from JOIN-s and into JSON-queries: https://stackoverflow.com/questions/39805736/get-join-table-as-array-of-results-with-postgresql-nodejs

**Comment by vitaly-t** [comment]
@nazarhussain Ok, good to know, it's good to keep all options open :wink:
