### ISSUE TITLE
Transactions are put in wrong queue when delete 2 blocks in a row

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1782]
### Expected behavior
- Delete one block with transactions type `0` - transactions are put back in `queued` list
- Delete another one block with transactions type `0 `- transactions should be put back in `queued` list
### Actual behavior
- Delete one block with transactions type `0` - transactions are put back in `queued` list
- Delete another one block with transactions type `0` - transactions are put back in `multisignatures` queue instead of `queued` due to presence of `signatures` property that is an empty array.

It happens because after delete first block - second one is loaded from database and get through normalization functions.
### Steps to reproduce
Run functional system rounds tests.
### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`, probably also `0.9.12`

**Comment by Tschakki** [comment]
The bug is also present in `0.9.12`
