### ISSUE TITLE
Version column in peers table expects shorter length value 

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk#1786]
### Expected behavior
The node should shut down correctly.
### Actual behavior
Node hangs because it tries to save the a too long "version" into database.
### Steps to reproduce
start a node with at least one peer and shutdown the node
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-alpha.2
linux
Devnet

**Comment by vitaly-t** [comment]
Writing invalid data into the database may be a precursor to a problem that follows, but the operation on its own cannot hang Node.js, it always throws an error about data format compliance.

**Comment by 4miners** [comment]
@vitaly-t Node means application, not Node.js - and ofc it's possible, for example if we not call a callback in case of error. ;)

**Comment by vitaly-t** [comment]
@4miners Ah, the slight difference makes all the sense 😄
