### ISSUE TITLE
Failed to find common block with: xxx

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#1789]
### Expected behavior
Common block check should not fail with schema check for all peers.

### Actual behavior
```
[ERR] 2018-03-26 13:29:24 | Expected type string but found type null
[ERR] 2018-03-26 13:29:24 | Failed to find common block with: xxx.xxx.xxx.xx:5000
[ERR] 2018-03-26 13:29:24 | Expected type string but found type null
```
### Steps to reproduce
N/A

### Which version(s) does this affect? (Environment, OS, etc...)
v1.0.0-alpha.2

**Comment by MaciejBaj** [comment]
It should be hard to recreate - from my perspective the issue is unlikely to be a problem. Needs further investigation.
