### ISSUE TITLE
Unrequired  query complexity in get_blocks_for_transport

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1794]
### Expected behavior
We should have simple queries.

### Actual behavior
We have made get_blocks_for_transport query complicated without any reason. Since blocks ids are always unique, grouping blocks with ids will return the same result. So, the following query can be refactored:
```
SELECT max(height) AS height, id, "previousBlock", "timestamp"
FROM blocks
WHERE id IN ($1:csv)
GROUP BY id
ORDER BY height DESC
```
to:
```
SELECT height, id, "previousBlock", "timestamp"
FROM blocks
WHERE id IN ($1:csv)
ORDER BY height DESC
```
### Steps to reproduce
N/A

**Comment by 4miners** [comment]
This issue is no longer valid, as refactor was done in https://github.com/LiskHQ/lisk/issues/1795
