### ISSUE TITLE
Can't get all 101 votes making just one call

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#1800]
### Expected behavior
I want to get the list of votes using `/votes?address=:address&limit=101`
As each address can have up to 101 votes, I reckon it makes sense to allow to get all 101 votes at once instead of limiting to 100.

### Actual behavior
It currently return an error 

> "Value 101 is greater than maximum 100"

Meaning I need to make two different calls in order to get all 101 votes.

### Steps to reproduce
Call `/votes?address=:address&limit=101` where :address is any valid address

### Which version(s) does this affect? (Environment, OS, etc...)
Version 1.0.0-alpha.3

**Comment by willclarktech** [comment]
The reasoning for this change is analogous to https://github.com/LiskHQ/lisk/issues/1500

**Comment by lsilvs** [comment]
Following the same reasoning mentioned in the description, the endpoint `/delegates/forgers` should also have its limit increased to **101**.
