### ISSUE TITLE
GET api/delegates/forgers returns invalid information

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1813]
### Expected behavior
Even if we set the limit to 100, next forgers list should only return forgers until the end of the current round.
### Actual behavior
If the number of blocks left in the round is less than the limit parameter, API returns ${limit} no. of delegates with their slots. So, all the block forger entries after the last block of the round are invalid, since we calculate the delegate list at the beginning of the new round.      
### Steps to reproduce
Request /api/delegates/forgers endpoint.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
We don't really know wen round will end, so that behavior is kind of expected one. ;)

**Comment by MaciejBaj** [comment]
Not an issue. Closing.
