### ISSUE TITLE
Forever not restarting when node exit anormally

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#182]
Is there a reason for this? I would try to restart the app.js anyway, or?

**Comment by karmacoma** [comment]
@fix Please explain what you mean. Do you mean restart command does not work when node is stopped?

**Comment by fix** [comment]
yes the forever does not restart the app.js

**Comment by karmacoma** [comment]
@Isabello Please can you take a look. I think this is normal behaviour in the case of forever.

**Comment by Isabello** [comment]
This is standard functionality for Forever. Forever is just used to keep
the process running and simplify the process to get nodejs running by
providing easy to use argument flags. It is not a solution that will
automatically restart the process when it fails. It looks like there might
be a way to restart node from inside the code using forever-monitor.

Please review below to see if this is something we can leverage.

https://github.com/foreverjs/forever-monitor

In some cases, we don't want to be automatically restarting node if it
crashes.
1: if a config.json is configured incorrectly it would continuously restart.
2: The node does not have enough memory and restarting repeatedly is just a
bandaid for poor resourcing, possibly leading to database corruption
requiring manual intervention.



2016-06-10 10:04 GMT-05:00 Oliver Beddows <notifications@github.com>:

**Comment by fix** [comment]
ah ok, i thought forever by default would restart in case of crash.

I agree, in some cases (due to installer bad configuration), we should not restart.
Otherwise, we should send a special exit number meaning "ok something wrong happened we need to restart" that is caught by forever.

We could imagine sending an exit meaning "ok rebuild that blockchain" in case of fork 3 for instance.

I don't know enough forever though.

**Comment by Isabello** [comment]
It would be nice to accomplish this from forever for sure but I am not
familiar also. Its possible to do this sort of thing from a utility like
Monit. I am looking at providing instructions and an installation utility
for Monit as a service to end users running active delegates.

2016-06-10 10:29 GMT-05:00 François-Xavier Thoorens <
notifications@github.com>:

**Comment by fix** [comment]
closing it as won't fix
