### ISSUE TITLE
Reconsider fixed node version

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#1824]
### Expected behavior

I can use my systems default node installation

### Actual behavior

node version in package.json is fixed to 6.12.3

### Steps to reproduce

See [package.json](https://github.com/LiskHQ/lisk/blob/0f8a54d/package.json#L18)

### Which version(s) does this affect? (Environment, OS, etc...)

Ubuntu 17.10, Ubuntu 18.10 LTS

----------------

When working with lisk core, I cannot build the docs or run a Lisk node using current Ubuntu's default node installation (node v6.11.4 for Ubuntu 17.10 and node v6.12.0 for Ubuntu 18.10).

This is a big issue since I need to manually install the node environment which comes for free from my package management. Using node from the repos ensures it runs great on the operating system and will update automatically.

[This change](https://github.com/LiskHQ/lisk/commit/72c669092c9e51426e9487bc7d8ccc0433b35e2a) fixes the node version for no clear reason.

I don't think the application should care too much about the VM running it. Leave it up to the system administrator to do package management. If there is a feature in node.js required to run the Lisk, just set the minimal node version in package.json at a major level, not at a patch level, e.g. ">=6.11". This will ensure that it is possible to upgrade node in case of security fixes without the need to upgrade Lisk.

Please don't ask system administrators to run random shell scripts from URLs just to install this hacky NVM.

**Comment by webmaster128** [comment]
I just realized that npm does not really care for the setting in the engines:

> Unless the user has set the engine-strict config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

https://docs.npmjs.com/files/package.json

But the issue occurs when using yarn:

```
$ yarn install
yarn install v1.5.1
info No lockfile found.
[1/5] Validating package.json...
error lisk@0.9.8: The engine "node" is incompatible with this module. Expected version "=6.12.3".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/home/simon/nobackup/lisk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

So one could argue that yarn does not conform to npm's specifications. On the other hand is the engines advise set in Lisk core unnecessary strict.

**Comment by karmacoma** [comment]
@webmaster128 Agree with your thoughts. To give context, the approach we have taken thus far was centered around how we prepared packages with node and other binary deps already included. This was intended to help the end-user more over the developer working on Lisk Core by providing an out-of-the-box environment that was consistent across the network.

We also have to be careful when moving forward with new versions of node in case of upstream API changes between major versions. For this reason we are attempting to be so restrictive. However, we should definitely fix `package.json` to allow patch releases and only restrict to a major/minor version.

**Comment by MaciejBaj** [comment]
Hey, we described the Node support policy here - https://github.com/LiskHQ/lisk/issues/2239.
While testing we are checking the support for a specific version and can only guarantee that, that's why it's fixed. The decision was made by @LiskHQ/standards team and reflected in the template repository - https://github.com/LiskHQ/lisk-template/blob/development/package.json#L20

I think it's ok to leave a fixed Node version as it is. If we go for allowing Node.js patch releases being re-installed automatically, we are loosing the control on versioning of the builds we're publishing - theoretically a build created for Node 6.14.1 might not work, whereas 6.14.2 does - they both would have the same Lisk Core version tag, let's say `1.2.0` with a version set as `"node": "6.14.*"`.
