### ISSUE TITLE
http api is missing current delegates count

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#1833]
Since /api/delegates/count is no longer available and i didn't found anything similar in https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.26#/ i propose to add current delegates count in api/node/status

**Comment by lsilvs** [comment]
I would suggest to return this information along with the meta data of `/delegates` endpoint.
The same way we do for `/transactions` which returns a meta object with _offset_, _limit_ and _count_

**Comment by diego-G** [comment]
@karek314 @lsilvs we are already in deep discussion about this point in particular. I close this issue because it is duplicated of #1461. 
I also linked to another one quite important which is in the middle of the way to achieve your request #1780.
