### ISSUE TITLE
Install instructions for Mac are incorrect

### ISSUE THREAD

**Issue by intelage-steve** [LiskHQ/lisk#1838]
### Expected behavior
Lisk installs correctly as documented

### Actual behavior
This step: 'initdb /usr/local/var/postgres -E utf8' is incorrect.  The initdb executable/script is nowhere to be found after installing postgresql.

### Steps to reproduce
On a clean Mac just follow the instructions for install. You will be stuck.

### Which version(s) does this affect? (Environment, OS, etc...)
Latest instructions version on the Lisk githumb

**Comment by Tschakki** [comment]
Hi @intelage-steve,

seems like it can't find the correct path for the command for some reason. Can you please run `locate initdb`? This will give you the absolute path to run the command. 
If you enter `echo $PATH` in your terminal, you see a list of all paths that will be searched when you enter an executable command in your terminal.
Updating your path variable to match with at least one of the paths displayed by `locate initdb` should fix the problem.
I'm pretty sure this is not a general step you need to do to install postgresql on a mac, but this could be something for our troubleshooting section in the future.
Hope this helps!

**Comment by MaciejBaj** [comment]
@intelage-steve fell free to reopen of the explanation provided by @Tschakki is not enough.
