### ISSUE TITLE
Make webSocket task dependent on database

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1839]
### Expected behavior
If node is unable to connect to database on startup, it should not load websockets, and cleanly exit.
### Actual behavior
Even when unable to connect to db, we initialize socket cluster and make connections with peers.
### Steps to reproduce
Kill postgres server, and start the application.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by SargeKhan** [comment]
@MaciejBaj, close this issue?

**Comment by SargeKhan** [comment]
Closed by #1890
