### ISSUE TITLE
Inconsistent response for /transactions endpoint 

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#1884]
### Expected behavior
Given I make the following calls:

`/transactions?blockId=:blockId&sort=timestamp:desc&offset=0&limit=51` and
`/transactions?blockId=:blockId&sort=timestamp:desc&offset=50&limit=51`

I expect the last item returned by the first call to be the same as the first item returned by the second call.

### Actual behavior
It is not.

### Steps to reproduce
Using the following [test database](https://downloads.lisk.io/lisk-explorer/dev/blockchain_explorer.db.gz):

Compare the [first call](http://localhost:4000/api/transactions?blockId=6524861224470851795&sort=timestamp:desc&offset=0&limit=51) with the [second call](http://localhost:4000/api/transactions?blockId=6524861224470851795&sort=timestamp:desc&offset=50&limit=51)

### Which version(s) does this affect? (Environment, OS, etc...)
v1.0.0-beta.5

**Comment by diego-G** [comment]
Your calls are getting transactions with timestamp 0. What we need is a second default `sort` parameter as a *tiebreaker*.

**Comment by lsilvs** [comment]
Maybe it's a good idea to introduce this second default `sort` for all endpoints that have sorting option.
