### ISSUE TITLE
Fix logging of database events received from pgMonitor 

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1885]
### Expected behavior
Log levels for database events are decided by `db.logEvents` property, and application should log to file and console based on event types specified in the property. 
### Actual behavior
The application uses database logger with configuration based on application events (debug, trace, info) which have no one-to-one mapping with dblog events. 
### Steps to reproduce
Look at the db log file.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by nazarhussain** [comment]
@SargeKhan Both are not related to each other. System log levels are special kind of levels with a kind of inheritance. e.g. if you set it to `debug` it will also show you `info` and `error`. 

But DB log events are just events, whichever event you want to log, you can specify in the list and it will be logged on system logger `info` level. We can update if we need to set a specific log level for db events.
