### ISSUE TITLE
Prepush hook for husky throws error on untracked file in directory

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#1902]
### Expected behavior
Prepush should only stop from pushing if there are some errors in the commits being added.
### Actual behavior
It also throws errors for untracted files. 
### Steps to reproduce
Create an untracted file in repo folder with some eslint errors, and try pushing.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by SargeKhan** [comment]
I know --no-verify option bypasses husky checks but i don't like it.

**Comment by willclarktech** [comment]
We should be able to use https://github.com/okonet/lint-staged

**Comment by SargeKhan** [comment]
secondly, there is another issue in the same ballpark. git pre-commit hooks don't allow partially staging files anymore. Like, if I stage a file partially using `git add -p` and then run `git commit` it runs pre-commit hooks and adds the whole file to the commit. (Even though I had partially added the file). Do you think `lint-staged` can solve that issue as well?
