### ISSUE TITLE
Reviving destroyed sockets memory leak

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#1907]
### Expected behavior

Outbound client sockets should not cause a memory leak.

### Actual behavior

When the socket is destroyed, it gets removed from the clients list but it is not always removed from the peer.socket property so it's still possible to send messages to it - So it's possible that a socket can become reactivated even though it's no longer attached to a peer.

### Steps to reproduce

Test on beta net with lots of connections and disconnections.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by MaciejBaj** [comment]
## Parent #1882
