### ISSUE TITLE
lisk.sh status: shows wrong height when sync'ing

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk#1914]
### Expected behavior
Shouldn't `bash lisk.sh status` always output current block, even when sync'ing?

### Actual behavior
I rebuilded from block zero and `bash lisk.sh status` always shows `Current Block Height: 27429`

### Steps to reproduce
Rebuild and do `bash lisk.sh status`

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0 beta 6

**Comment by nazarhussain** [comment]
@punkr0ck We are using a direct query to the database to check the current block height. 

```
select height from blocks order by height desc limit 1;
```

So as far syncing process is working fine and blocks are syncing then `bash lisk.sh status` will always show accurate block height. 

So it seems your syncing process is stuck at some point. Please create a new issue referring the syncing process issue along with debug level logging. 

Furthermore If you face any isssue with `lisk.sh` script, then report it on https://github.com/LiskHQ/lisk-scripts
