### ISSUE TITLE
1.0.0-beta.6 does not find any good peer

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#1915]
### Expected behaviour

I can sync using 1.0.0-beta.6 from source.

### Actual behaviour

I cannot sync due to

> Sync timer - Failed to find enough good peers

after a lot of

> [Outbound socket :: error] Peer error from 94.237.65.179 - Socket connection closed with status code 4103 and reason: Expected version: >=1.0.0-beta.6 but received: 1.0.0-beta.2

When checking [the full log](https://gist.github.com/webmaster128/9e9be84fb0216ee5c9229a8a6b7eb5a8), you can see that each IP address of the default peer list

```json
[
  { "ip": "94.237.41.99", "wsPort": 5001 },
  { "ip": "209.50.52.217", "wsPort": 5001 },
  { "ip": "94.237.26.150", "wsPort": 5001 },
  { "ip": "83.136.249.102", "wsPort": 5001 },
  { "ip": "94.237.65.179", "wsPort": 5001 }
]
```

is running 1.0.0-beta.2 and thus is not a good peer.

### Steps to reproduce

Install a fresh 1.0.0-beta.6 node from source

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0-beta.6 on branch testnet-development

**Comment by webmaster128** [comment]
It turns out that my client claimed to be 1.0.0-beta.2 because the config file update is not on branch testnet-development. See https://github.com/LiskHQ/lisk/compare/testnet-development...v1.0.0-beta.6

By the way: why is the client version part of the config file and not part of the code itself? I think a config file should remain unchanged when the node is upgraded.

**Comment by 4miners** [comment]
@webmaster128 Thanks for feedback, I'll open separate issue to move `version` and `minVersion` to constants.
