### ISSUE TITLE
Funded addresses with lowercased "l" can not be found

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#192]
If funds are sent to an address, e.g. `14035611446748562777l` instead of `14035611446748562777L`, the API call `https://login.lisk.io/api/accounts?address=14035611446748562777L` yields an error that account doesn't exist.

**Comment by fix** [comment]
ah you mean the address are saved as they are sent in case of cold wallet?

**Comment by karmacoma** [comment]
Yes this is what I mean. So should be an easy fix.
