### ISSUE TITLE
Make PUT /node/status/forging idempotent

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#1956]
### Expected behavior

[PUT requests are idempotent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT)

### Actual behavior

The current implementation of PUT /node/status/forging is a toggle function. The same request is sent to activate and deactivate forging. This is a problem because you do not know in advance, which action you are doing. It becomes of practical importance when you are thinking of network issues and request retries. Every sane HTTP client would retry a PUT request when it does not get a response. But when a request does not return data, you do not know if the action was performed on the server or not.

Requesting the forging state in advance is no reliable solution also because the state may have changed between the status request and the toggle request. 

### Steps to reproduce

See https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.26#/Delegates/updateForgingStatus

### Which version(s) does this affect? (Environment, OS, etc...)

API version 1.0.26

----------------------------

Since PUT is a method to override a resource, there is a simple way to fix this. We already have a `forging` field in the response, which can be used for requests as well.

Enable forging:

```
PUT /node/status/forging
{
  "decryptionKey": "happy tree friends",
  "publicKey": "968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b",
  "forging": true
}
```
Disable forging:

```
PUT /node/status/forging
{
  "decryptionKey": "happy tree friends",
  "publicKey": "968ba2fa993ea9dc27ed740da0daf49eddd740dbd7cb1cb4fc5db3a20baf341b",
  "forging": false
}
```

A request where `forging` is unset then must result in HTTP 400 Bad Request or maybe HTTP 422 Unprocessable Entity.

**Comment by nazarhussain** [comment]
As per our request validation layer if `forging` is unset while required will return automatically to 400 status code.

**Comment by webmaster128** [comment]
> As per our request validation layer if forging is unset while required will return automatically to 400 status code.

i.e. you just need to mark the field as required?

**Comment by nazarhussain** [comment]
Yes

**Comment by simonmorgenthaler** [comment]
I agree, this API call should be adapted. the suggestion from @webmaster128 looks good to me
