### ISSUE TITLE
Solutions to improve Lisk DPoS comment

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk#1980]
I'm with Karek and everyone on this except 202 isn't a prime number.
I think 199, or 211 would work though.
We could test this on yet another net to see just how high we could push that number and still reach consensus. I'd be willing to run a couple dozen nodes or more to help explore this.

**Comment by webmaster128** [comment]
Is this a comment on https://github.com/LiskHQ/lisk/issues/353?

**Comment by 4miners** [comment]
Closing that as duplicate to https://github.com/LiskHQ/lisk/issues/353
