### ISSUE TITLE
Move istanbul-middleware to devDependencies

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1999]
### Expected behavior
Snyk warns about dependencies used in production.

### Actual behavior
`istanbul-middleware` is a development dependency.

**Comment by SargeKhan** [comment]
istanbul-middleware has not been updated for 3+ years, and I have not found a library with similar functionality. On top of that, istanbul is also deprecated since it doesn't work with `async/await`. I suggest we skip snyk warning for this particular dependency right now, and fix the root cause.

**Comment by SargeKhan** [comment]
Another option is to remove istanbul-middleware dependency completely. But a downside of that would be that we'd be unable to get any coverage metric from our functional API tests. @MaciejBaj @willclarktech

**Comment by willclarktech** [comment]
What do we use the functional coverage reports for?

**Comment by willclarktech** [comment]
Yes. What actions do we take based on the reports we generate when running functional tests?

**Comment by diego-G** [comment]
Title and description updated. The decision is to remove the dependency due to maintainer's inactivity. Besides, the provided feature is not widely used among the team either.

**Comment by MaciejBaj** [comment]
The issue was about moving `istanbul-middleware` to devDependencies only to get rid of `snyk` notifications. If removing of functional tests coverage supposed to be a goal here, it should be opened as a separate issue and discussed first. 

From my side - I still think that getting coverage of functional tests is valuable and can help to spot the parts of the code of particular modules which are unused/uncovered. Gathering the coverage shouldn't be removed because a dependency is not maintained anymore.

Merging the functional and unit coverage into one and what should be displayed in the global coverage indicator is also a separate matter here.
