### ISSUE TITLE
Active delegates and forging

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#20]
If the active delegate, which should forge the next block, is not ready or not forging, then the next available delegate should forge the block  **immediately**. Currently it seems there is a kind of timeout. In the example below only 2 of the 101 active delagates are forging. The result are blocktimes up to ten minutes.
![image](https://cloud.githubusercontent.com/assets/17945384/14066021/8955129e-f43f-11e5-8fce-f47188528f5b.png)

**Comment by fix** [comment]
Closing it. This is linked to issues to prevent fork 1 and propagation time amongs delegate.
