### ISSUE TITLE
Integration test peer nodes should only have seed nodes in peer list

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2003]
### Expected behavior
In order to simulate the real network, there should be a seed node and rest all other nodes in the network should connect to the seed node and sync. 
### Actual behavior
Currently, all the peers(5000-5009) is having the full peer list in there `config.json`.
### Steps to reproduce
1) Run integration test
2) Navigate to `test/integration/configs/config.node-0.json`, in the `peers/list` section of the configuration you can see we have list of all the peers. 
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by MaciejBaj** [comment]
Can be done as part of #2125.
