### ISSUE TITLE
Migration from 0.9.* to 1.0.0 version guidelines 

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2004]
Provide migration from `0.9.*` to `1.0.0` version guidelines.

**Comment by nazarhussain** [comment]
The guidelines are created under documentation `/documentation/lisk-core/upgrade/binary`. Need to review it there.

**Comment by Isabello** [comment]
Would be good to have a working link to review.

**Comment by nazarhussain** [comment]
@Isabello You are right. Will publish those documentation soon.

**Comment by MaciejBaj** [comment]
https://lisk.io/documentation/lisk-core/upgrade/migration
