### ISSUE TITLE
Port the feature of blackList for P2P layer to web sockets

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2010]
### Expected behaviour
We can blacklist any IP to connect on P2P layer. It is specified in configuration. 

https://github.com/LiskHQ/lisk/blob/20d0bbab7bc5874b802344a1c31a8cdabea7dcd9/config.json#L92-L94

Previously in `0.9.x` versions it was used in `/peer*` endpoints for http APIs. But its never been ported to websockets. 

### Actual behavior
Currently its been applied on HTTP APIs which is supposed not to be P2P layer communication. HTTP Layer already have a ip whitelist feature. 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0.0`

**Comment by 4miners** [comment]
@maciej It's not a bug, why we planned that for `1.0.0`?

**Comment by nazarhussain** [comment]
@4miners Its a feature available in `0.9.x` and it was not ported to P2P layer when we converted it to websockets.

**Comment by 4miners** [comment]
Sorry, it was a typo, I wanted to mention @MaciejBaj ofc.
