### ISSUE TITLE
If a peer object for a specific nonce already exists and has a socket, destroy the socket

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#2012]
### Expected behavior

If two peer objects with the same nonce are added to the peer manager and the previous peer object's socket exists, then destroy the socket from the existing peer.

### Actual behavior

It's possible for two peer objects with the same nonce can get added to the peer manager and that causes the socket on the old peer object to leak.

### Steps to reproduce

Check nodes on betanet. 

### Which version(s) does this affect? (Environment, OS, etc...)

Latest betanet.

**Comment by pcdinh** [comment]
It should help https://github.com/LiskHQ/lisk/issues/1882 too
