### ISSUE TITLE
Remove version fields from config.json

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#2019]
### Expected behavior

config.json should be user generated and fixed across multiple Lisk core versions

### Actual behavior

config.json contains version numbers. Version numbers are semantically not a configuration but a property of the deployed software. With version numbers in config.json, decoupling of software installation and configuration is not possible.

### Steps to reproduce

See field `version` and `minVersion` in https://github.com/LiskHQ/lisk/blob/1.0.0-beta.8/config.json

### Which version(s) does this affect? (Environment, OS, etc...)

All versions of Lisk core I am aware of

----------------

##  Additional background 

When deploying software on multiple servers using automated deployment tools (like e.g. Ansible), as an administrator you want to customize your configuration file on your own and have full control over the file. There should not be any reason to change the configuration file when updating other than new *required* fields are added. In this case the software can just error out on the start and print an error such as "field xy missing".

**Comment by 4miners** [comment]
@MaciejBaj Can we include that in `1.0.0`, as fix is easy and valuable.

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/pull/2196
