### ISSUE TITLE
Nightly builds issues

### ISSUE THREAD

**Issue by abelboldu** [LiskHQ/lisk#2027]
### Expected behavior

Clean and proper versioned nightly builds

### Actual behavior

- Nightly tarballs are being generated from the 1.0.0 branch, but with 0.9.8 versioning that comes from config.json, probably related with https://github.com/LiskHQ/lisk/issues/2019

- The libraries imported from https://github.com/LiskHQ/lisk-jenkins make use of `/tmp` which is not the standard way for jenkins, leaving all the workspaces behind.
 
- The imported library is hardcoded to `lisk-jenkins@nh-lisk-build` which is not a master or default branch, it should be merged in `lisk-jenkins` first.

- Build branch hardcoded to 1.0.0

### Steps to reproduce

See Jenkins logs of nightly builds

### Which version(s) does this affect? (Environment, OS, etc...)

All lisk branches with `Jenkinsfile.nightly-build`

**Comment by fchavant** [comment]
In this particular case I don't think it makes sense to reuse code from LiskHQ/lisk-jenkins: the `liskBuild` function that's defined there is pretty specific to lisk-migration and only makes nightly builds more complex.

**Comment by abelboldu** [comment]
Can we revert  to a version without LiskHQ/lisk-jenkins then? I think it will make things easier for both @nazarhussain

**Comment by nazarhussain** [comment]
@fchavant Please highlight something in`liskBuild` which is specific to lisk-migration? `liskBuild` function was written actually has nothing to do itself. Its all using standard `build.sh`. If you can highlight something specific, wen can update and make it more generalized.

**Comment by fchavant** [comment]
@nazarhussain here is a couple: 
- having logic to distinguish between 0.9.x and 1.0.x (nightly builds will only happen for >=1.0.0)
- assuming the correct version number can be found in `config.json` (see description)

**Comment by nazarhussain** [comment]
What ever logic is in `liskBuild` function is useful for building any lisk-core branch. Its not specific to lisk-migration. You can use same method further for building any branch in any jenkins file. As using it in nightly build. 

The differences `0.9.x` and `1.0.x` configuration is because we have some file naming convention differences between both versions. But again that's nothing which is specific to lisk-migration.

**Comment by abelboldu** [comment]
@nazarhussain Since this is merged to `lisk-jenkins` now, we need to change the hardcoded `nh-lisk-build` branch to `master`
