### ISSUE TITLE
There is Bug about config.json

### ISSUE THREAD

**Issue by deanrobin** [LiskHQ/lisk#2028]
I run application with this command
`node app.js -p 7001 -a $IP -c config.json`
And then, I kill this 
I run aplication with this command again.
But it said `Failed to validate config data [ { code: 'INVALID_TYPE',
    params: [ 'integer', 'string' ],
    message: 'Expected type integer but found type string',
    path: '#/port',
    schemaId: 'appCon' } ]
`
I saw my config.json,  the port is "7001", is String not Integer
So, I think may be this is application write this in config.json , right?!

**Comment by nazarhussain** [comment]
@deanrobin Which version or branch you are referring to? In current development branch there is no config option `port` available.

**Comment by deanrobin** [comment]
git -> master.

**Comment by pcdinh** [comment]
@deanrobin Don't check out `master`. `development` is the branch you may want to use

**Comment by deanrobin** [comment]
@pcdinh friend, but READ.md it say, git checkout master....

**Comment by nazarhussain** [comment]
@deanrobin Yes the master branch will also work, without problem. its the version running on the mainnet. The error explains that you set `port` configuration value in `config.json` as string. It should be integer instead. Please double check and confirm.

**Comment by nazarhussain** [comment]
@deanrobin As we didn't get further information from you, so closing this issue. If you still face same problem, please reopen the issue with more details.
