### ISSUE TITLE
Fix unreachable peers code of self-update

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2029]
### Expected behavior
The intended use `me` functions was `library.logic.peers.me()`
### Actual behavior
In `__private.updatePeerStatus` we are using undefined function `self.me().nonce` where `me` function is undefined.
### Steps to reproduce
https://github.com/LiskHQ/lisk/blob/6951f0d307e223073d8e9839c5ffbceb0f51eccf/modules/peers.js#L277
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
@ManuGowda Please look at `Peers.prototype.acceptable` function, that function should be responsible for filtering out our own node from peers that we accept, so it should never appear in peers manager. Maybe something isn't working there. I don't know what is the purpose of having status `BANNED` that is only used to prevent reconnecting with itself, looks like wrong logic.

**Comment by ManuGowda** [comment]
@4miners that's correct, we call `Peers.prototype.acceptable` during the discovery process https://github.com/LiskHQ/lisk/blob/6951f0d307e223073d8e9839c5ffbceb0f51eccf/modules/peers.js#L799, however, when we do `updatePeers` https://github.com/LiskHQ/lisk/blob/6951f0d307e223073d8e9839c5ffbceb0f51eccf/modules/peers.js#L815 we call `library.logic.peers.list` which will give list of all the available peers, including ourself too if my understanding is correct here, if so then what I have mentioned in the issue is that we are trying to update ourself by checking `rpc.status` https://github.com/LiskHQ/lisk/blob/6951f0d307e223073d8e9839c5ffbceb0f51eccf/modules/peers.js#L829
To conclude:
- The `updatePeers` in `peersDiscoveryAndUpdate` should only update `acceptable` peers
