### ISSUE TITLE
Don't charge a fee for optional data field

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#2033]
### Expected behavior
Optional data field should not cost anything extra, because almost nobody will use it if it does. The fee makes this feature almost useless. 

It also makes worse UX because we have to explain this to the users as they are not used to this from traditional banking. 

### Actual behavior
Optional data field requested in https://github.com/LiskHQ/lisk/issues/26 and added in https://github.com/LiskHQ/lisk/pull/470 adds 0.1 LSK fee on top of the 0.1 LSK fee of type 0 transaction.

I see that the fee is there because of storing additional data on the blockchain, but users already pay 0.1 LSK for the transaction which is IMO more than enough to prevent from spamming the blockchain. If I wanted to spam the blockchain I think that adding two transactions for 0.2 LSK will add more data than 1 transaction with 64 char data field for 0.2 LSK.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core 1.0.0

**Comment by webmaster128** [comment]
Adding a cost for type 0 asset data is also inconsistent with type 1/2/3/4/5, where asset data is included. So from the standpoint of elegant technical design, this proposal makes perfect sense.

**Comment by karmacoma** [comment]
@slaweet I agree with this proposal / reversal. Much appreciated.

@webmaster128 Also agree current approach is inconsistent with how we will deal with data in other transaction types. Therefore would be nonsensical to keep as is.

Assuming that this change will affect both Lisk Core and Elements, we should look to implement it ahead of the next `1.0.0` beta candidate @MaciejBaj @willclarktech.

**Comment by IkerAlus** [comment]
This issue will be (practically) irrelevant with the release of the new fee system. 

In that case, (minimum possible) fees are given by the size of the transaction regardless the transaction type (for most of the cases). If the user makes use entirely of this data field, he will pay, at least:

`(type 0 size  + data field size) x min.fee`

Hence he will pay `(data field size) x min.fee` more than normal type 0 transactions. In normal network situation, this will be many orders of magnitude less than 0.1LSK

It is a matter of time convenience to make the reversal now or just wait for the new fee system.

**Comment by webmaster128** [comment]
Great simplification – congratz and thanks!

Would it be possible to respawn Betanet after this change top avoid caring around a special rule (0.2 fee type 0 transactions) that will never be needed in a production network?
