### ISSUE TITLE
networkHeight 0 sometimes

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#2057]
### Expected behavior
networkHeight in the api `/api/node/status` should always be correct. On forging- and non-forging-nodes

### Actual behavior
networkHeight is sometimes 0

![networkheight1](https://user-images.githubusercontent.com/10214886/40491606-d13c2466-5f6e-11e8-874b-771e8f7b2c13.png)
![networkheight2](https://user-images.githubusercontent.com/10214886/40491607-d15c7360-5f6e-11e8-9f61-53e73c345df1.png)
![networkheight3](https://user-images.githubusercontent.com/10214886/40492199-4368e69a-5f70-11e8-99f6-a13f0aa08e82.png)

### Steps to reproduce
call `/api/node/status`, check `networkHeight` every few seconds

### Which version(s) does this affect? (Environment, OS, etc...)
beta7

**Comment by MaciejBaj** [comment]
Changes are done and merged to Version 1.0.0-beta.8 which is still not released to Betanet.
Closed by https://github.com/LiskHQ/lisk/pull/2006.
