### ISSUE TITLE
Forging status broken after resync with beta7

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#2058]
### Expected behavior

`curl http://localhost:5000/api/node/status/forging` returns data

### Actual behavior

```
$ curl http://localhost:5000/api/node/status/forging
{}
$ curl -v http://localhost:5000/api/node/status/forging
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5000 (#0)
> GET /api/node/status/forging HTTP/1.1
> Host: localhost:5000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< X-Frame-Options: DENY
< Content-Security-Policy: frame-ancestors 'none'
< X-RateLimit-Limit: 0
< X-RateLimit-Remaining: 0
< Access-Control-Allow-Origin: *
< content-type: application/json
< Vary: Accept-Encoding
< Date: Thu, 24 May 2018 14:40:15 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{}
```

### Steps to reproduce

I upgraded to beta7 using the source installation (at 8f629b2aedb85f456d6df0ca947b7c1e5c6c5de7). After that core decided to sync from 0 by itself. After that, the situation above occurred. This happened on 2 different nodes.

### Which version(s) does this affect? (Environment, OS, etc...)

beta7, source installation, Node v8.10.0, Ubuntu 18.04 LTS

**Comment by webmaster128** [comment]
Node.prototype.internal.getForgingStatus does not set an error variable into the callback function in case of an error -.- (https://github.com/LiskHQ/lisk/blob/v1.0.0-beta.7/modules/node.js#L90)

**Comment by webmaster128** [comment]
@4miners you are right, the core update did override my config and I forgot to insert my secret again. As you said, and error message is required. This would have saved me a lot of time and frustration.

HTTP 200 and the result body "{}" is not a valid response according to the [documentation](https://app.swaggerhub.com/apis/LiskHQ/Lisk/1.0.26#/Delegates/getForgingStatus). Even the empty list is expected to return

```
{
  "data": [
  ],
  "meta": {},
  "links": {}
}
```

**Comment by 4miners** [comment]
Yep, I agree. Would be nice to return proper error message in case of empty list in config.

**Comment by webmaster128** [comment]
Great! So this is why we're beta testing :) Thanks and good night

**Comment by shuse2** [comment]
I think it's better to return empty array as document says, if the response is empty.
I dont think REST API returns an error when it's empty.  (if it's expecting list)

**Comment by webmaster128** [comment]
Given that the endpoint returns a status list of delegates configured delegates, @shuse2 is probably right. I missed the point that the API is made for more than one delegates.

**Comment by nazarhussain** [comment]
I believe we settled to a conclusion that in case of empty configurations the API should return an empty array response. Which is a the current behavior already. So we can close this issue. 

@4miners @webmaster128 @MaciejBaj

**Comment by webmaster128** [comment]
If nothing changes in the meantime, we get {}, which is not an empty list.

**Comment by MaciejBaj** [comment]
Check @ManuGowda if still present on 1.0.0-beta.9

**Comment by ManuGowda** [comment]
@MaciejBaj @nazarhussain @4miners I have tested this issue on `1.0.0-rc.1` when the delegate list is empty, then endpoint `http://localhost:4000/api/node/status/forging` returns `{}` response. 
This happens when any result is an empty list `[]` https://github.com/LiskHQ/lisk/blob/development/api/fittings/lisk_response_formatter.js#L48

I am going to make a fix [here](https://github.com/LiskHQ/lisk/blob/development/api/fittings/lisk_response_formatter.js#L48) 
From
```
if (_.isEmpty(context.input)) {
			context.headers = { 'content-type': 'application/json' };
			next(null, {});
			return;
		}
```
To
```
if (_.isEmpty(context.input)) {
			context.headers = { 'content-type': 'application/json' };
			next(null, {
				meta: {},
				data: context.input,
				links: {},
			});
			return;
		}
```

This will make response consistant across all the APIs to return the common properties when the result is empty. Let me know if you have any feedback
