### ISSUE TITLE
Installing the SDK example app on a x64 Linux system crashes

### ISSUE THREAD

**Issue by m-schmoock** [LiskHQ/lisk#206]
After cleanly installing a dapp on a Linux node the JavaScrip VM sub-process of that app crashes fatally. The main nodejs procress keeps running but the app is not usable in this state since it never calls `setReady`. Thats why the logs keep showing `DApps#onNewBlock error: - "Application not ready"` repeatedly. The dapps fatal error message is:

    FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope

I think I have tracked this down to the native binary of the `"usage": "=0.7.1"` module (package.json).

**Comment by karmacoma** [comment]
I have fixed this issue yesterday: https://github.com/LiskHQ/lisk-node/issues/2. I still need to compile new builds of lisk-node and I will add to downloads.lisk.io.

**Comment by m-schmoock** [comment]
Uhh.. sorry for the double post :D

**Comment by karmacoma** [comment]
No problem, you are doing good work.

Currently compilation is handled by: https://github.com/LiskHQ/lisk-build with binaries downloaded at build time of docker image.

**Comment by m-schmoock** [comment]
I see...  we need automated builds using Travis or something. Its really helpful to have all the recent changes in a dev build whenever code is merged. 

The build.sh script fails in trying to download:

   https://downloads.lisk.io/lisk/main/0.3.1/0.3.1.tar.gz
   -> 404

I think the config.sh is broken: `LISK_FILE=$VERSION.tar.gz` should be `LISK_FILE="$BUILD_NAME.tar.gz"`

**Comment by karmacoma** [comment]
I have fixed broken link. Sorry about that.

Yes in future, I hope to have automated build / test using travis in place.
