### ISSUE TITLE
[Feature Request] Use a PM2 JSON/JS configuration file instead of starting it manually

### ISSUE THREAD

**Issue by skatcat31** [LiskHQ/lisk#2062]
### Expected Enhancement

Loading the process becomes MUCH easier to manage with a PM2 JSON since now you merely need a script to start the server by navigating to install and calling `pm2 start ${file}.json`

### Documentation

http://pm2.keymetrics.io/docs/usage/application-declaration/#json-format

### Steps to introduce

- [ ] Create and test PM2 JSON
- [ ] Update documentation
- [ ] Update deployment plans with a PM2 Save command: http://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#related-commands

### Which version(s) does this affect? (Environment, OS, etc...)

Any compatible with PM2

### Why?

I run several NodeJS projects that was use PM2 to manage and one of the best ways we've found to handle starting, stopping, and referring to the process is a PM2.json, since then if we don't know the name of the process, but we do know the folder, we can instead tell it to start, stop, or gracefulReload the .json file instead. It makes it easier to bring new developers into the life cycle, and often is more manageable for scripts since they are no independent of a variable name, and are instead dependent on a consistent file

**Comment by nazarhussain** [comment]
@skatcat31 We already using the `pm2`, its just not packaged in the main repo. Instead part of seperate repo and addd during build process.

https://github.com/LiskHQ/lisk-scripts/blob/development/packaged/etc/pm2-lisk.json

**Comment by skatcat31** [comment]
ah. Administrative repo used for full build. Makes sense. Which of the repos would be a good entry point for following from a SA point of view?

**Comment by nazarhussain** [comment]
http://github.com/LiskHQ/lisk-scripts
https://github.com/LiskHQ/lisk-build
https://github.com/LiskHQ/lisk-docker

**Comment by nazarhussain** [comment]
@skatcat31 I am closing this issue, if you have any suggestion to PM2 related stuff, please create in respective repo. If any suggestion is related to Lisk Core, please create seperate issue or reopen.
