### ISSUE TITLE
Not possible to search for {transactions,accounts} entities

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk#2067]
### Expected behavior

- API provides an endpoint that allows to search for delegates usernames:
```
/api/delegates/search?q=username&orderBy=producedblocks:desc
```
- It will be ideal that these endpoints are provided also for other entities e.g {transactions,accounts}
```
/api/accounts/search?address=address
/api/transactions/search?id=id
```
this way wallets or other web-clients would be able to implement traditional features such as autosuggest/autocompletion, when searching for entities within Lisk.

### Actual behavior
- ATM there is only search endpoint for delegates
https://lisk.io/documentation/api-reference/lisk-api-0-9/delegates
### Which version(s) does this affect? (Environment, OS, etc...)
- all environments,
- version 0.9.0
- triggered by (https://github.com/LiskHQ/lisk-hub/issues/745)

**Comment by nazarhussain** [comment]
For delegate username autocomplete makes sense, as its a user provided data and specially limited dataset. But for accounts addresses and transaction ids I don' think there is a valuable use case to provide autocomplete. 

Even If we target we would be able to do it in `1.0.x` not in `0.9.x`.

**Comment by MaciejBaj** [comment]
Extending the API functionalities is not the primary behaviour of what Lisk Core is supposed to do. Being a network client is. Ideally, separate services could ship functionalities like mentioned fuzzy transactions/accounts search based on a network node blockchain.

**Comment by MichalTuleja** [comment]
I see here a candidate for a new functionality of Lisk Service.
Although it may be hard to implement it using the standard REST API, the direct database access should make it possible.

**Comment by MichalTuleja** [comment]
Done. You can close this issue, the discussion will be continued in the lisk-service repository.
