### ISSUE TITLE
PUT /api/transactions: It is possible to send integers in base 10 (decimal), base 16 (hex), base 8 (octal).

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk#207]
`PUT /api/transactions`

It is possible to send integers in base 10 (decimal), base 16 (hex), base 8 (octal).

In my opinion we should standardize and only accept integers in base 10.

**Comment by karmacoma** [comment]
Closing due to: https://github.com/LiskHQ/lisk/issues/457
