### ISSUE TITLE
Adjust the frequency of P2P discovery

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#2076]
### Description
In order to calculate the correct consensus, keeping up with the information of peers is important.

### Actual behavior
We update peer information actively every 30 seconds.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by MaciejBaj** [comment]
We will not proceed with that solution in favour of adjusting 'broadcastLimit' and 'maxRelays' constants.
