### ISSUE TITLE
Investigate maxRelays and broadcastLimit numbers

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2077]
### Parent #2080

**Comment by 4miners** [comment]
@MaciejBaj Are you sure that adjusting those params is a proper way to fix our current issues? It works fine on `0.9.x`.

**Comment by MaciejBaj** [comment]
@4miners the P2P protocol is not compatible with 0.9.x - there is a difference between how the headers are being propagated. It's worth to simulate what's the ratio of reached peers during broadcasts while adjusting maxRelays and broadcastLimit parameters.

**Comment by nazarhussain** [comment]
@SargeKhan @MaciejBaj Here is the results of the combinations of different values in an emulated environment. 

![diagram](https://user-images.githubusercontent.com/112468/40778346-2262fb64-64d1-11e8-9d74-0b69821ddc68.png)

- X-Axis shows the increase in relay limit. 
- Y-Axis shows the percentage of network which missed the blocks
- Diagram is based on network of 250 peers

**Comment by 4miners** [comment]
@MaciejBaj Max relays and broadcast are for blocks, have nothing to do with headers.

@nazarhussain Very nice graph, thanks for the effort to create it. So looks like with current settings (relay: `2`, broadcast: `20`) more than 1/3 of the network should never get a block? Can you create another graph using `0.9.x` version to compare the behavior?

**Comment by MaciejBaj** [comment]
Closes #2078, #2076, #2073.
