### ISSUE TITLE
Investigate removing updateMyself (push) and only use peer.rpc.status (pull) to get peer broadhash consensus

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#2083]
### Expected behavior

Peer headers should be updated correctly so that the up-to-date broadhash consensus can be established by the time a block needs to be forged.

Since we've changed the broadcasting approach (to not restrict based on broadhash), it's no longer necessary to receive peer headers in realtime (as soon as a peer receives a new block) - In theory, this means that we no longer need peers to call updateMyself on each other.

### Actual behavior

Now we have two mechanisms to allow a node to receive peer headers in order to track the consensus %: `updateMyself` (push) and `peer.rpc.status` (pull).

- When a new block is received by a node, `updateMyself` is used to tell peers about our headers (with updated broadhash) but it doesn't work correctly now because it only reaches 100 peers. 
- On an interval, `peer.rpc.status` is invoked on all peers to get their latest headers but currently the interval is too long (30 seconds) which means that it will miss some peer broadhash updates because (ideally) each peer's broadhash changes every 10 seconds.

### Which version(s) does this affect? (Environment, OS, etc...)

1.0.0

**Comment by Slamper** [comment]
I think this should probably be prioritized since this is also a security relevant topic.

If a network has `n=100` members and an attacker sets up `d=n*100` dummy nodes the chance is only ~1% that the updateMyself call reaches the healthy nodes. 

In this case the broadhash consensus could be severely influenced and lowered since healthy nodes will only update each other every 30 seconds.

In the current core 1.0 this could lead to missed blocks and a possiblity for an attacker to halt the network.

**Comment by jondubois** [comment]
@Slamper, that's a good point.

There was some discussion about this issue internally a couple of weeks ago and we had identified two potential solutions to the problem:

1. Remove `updateMyself` and increase the interval which calls `rpc.status` on all peers (this is the approach recommended by this issue).
2. Keep `updateMyself` but make it so that it reaches ALL peers instead of just 100.

Both approaches should solve the root issue. My motivation for wanting to remove `updateMyself` entirely was to reduce code complexity.

I've raised this issue again with the team.

**Comment by jondubois** [comment]
Note that we have managed to fix the underlying issue without removing `updateMyself` a while ago and that fix still seems to be working well.

Without going into too much detail, based on our current peer selection and consensus algorithms, `updateMyself` offers some benefits over calling 'rpc.status' on all of our peers. Once we have revised peer selection, then we should reconsider this issue.

**Comment by jondubois** [comment]
Closing this issue since it will be addressed as part of upcoming changes to peer selection.
