### ISSUE TITLE
Move and improve log messages for fork scenarios

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#2084]
### Expected behavior
We should only log that we are deleting blocks when we've done all validations for the incoming block.
### Actual behavior
We log `Last block and parent loses` and `Last block stands` before actually validating the block. Which means that we may not delete the block, but we log these messages.
### Steps to reproduce
Look at the logs.
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
I don't really like the fix, because those logs:
- not mean that we are deleting any blocks at all (there is another log for that)
- now when verification fails we don't know for which fork it was.
