### ISSUE TITLE
Allow maximum peers to be configured at runtime

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#21]
With reference to the following forum post: https://forum.lisk.io/viewtopic.php?f=13&t=108

Currently the maximum number of peers is hard-coded to 100 peers.

Rather than hard-coding the limit, we should allow it to be configured within a sensible range.

**Comment by mrv777** [comment]
I'm guessing: https://github.com/LiskHQ/lisk/blob/0d6c94768f212a23687fa58d8faae4782ede3b37/helpers/constants.js#L7

**Comment by Isabello** [comment]
This was implemented in 0.4.0, but is no longer necessary going forward. This one should be closed, I think.

**Comment by karmacoma** [comment]
@Isabello Agree, we will close then.
