### ISSUE TITLE
start app.js issue

### ISSUE THREAD

**Issue by lhfly5201314** [LiskHQ/lisk#2122]
I run the command ' node app.js ' after I installed the dependencies.
But nothing happens.No any output,even the error...
Does anyone could tell me why???

**Comment by nazarhussain** [comment]
@lhfly5201314 Please check `consoleLogLevel`  in your `config.json`. Probably it would be `none` by default, set it to `debug` to see lot of output in terminal. 

Additionally you can see logs directly into `logs/lisk.log` file even if console log level is none.
