### ISSUE TITLE
Remove dependency of "round" from "summedRound"

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2129]
### Expected behavior
`round` is a dependent value o f `height`. While we are passing a block with certain height, we should not explicitly pass the `round` to `summedRound` method. It can lead to some logical misunderstanding to sum a block height for wrong round. 

### Actual behavior
We are passing `round` as scope param to `summedRound`.

https://github.com/LiskHQ/lisk/blob/b68dce3247ec10b36022d97e8bd6862237b724b8/modules/rounds.js#L389-L393

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment]
`round` is calculated directly from `block.height` when we create `Round` instance, so in actual scope we will have always round that match actual block (which is also part of the scope). We're passing entire scope there - as long as we didn't overwrite `round` or `block` everything is safe. If we overwrite then we're doomed anyway.

I don't really see a point with calculating `round` from `block.height` every time that we need to use it.

**Comment by MaciejBaj** [comment]
@4miners @nazarhussain please work out the solution here.

**Comment by nazarhussain** [comment]
@4miners I agree, because the `summedRound` is a `private` method so, it can't be called out of round module context. So I am good with it.

**Comment by 4miners** [comment]
@nazarhussain Thanks. 👍
