### ISSUE TITLE
Rewrite all database logic to follow pg-promise best practices

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#213]
~~under modules/block.js~~
~~This way we can throw an error an prevent from rewinding already applied transactions.~~

Edited by @karmacoma.

If a node is interrupted during block processing i.e. due to reload, there is a high probability of partial writes to the database, leading to corruption of memory tables and a break in consensus with the rest of network. This eventually results in a fork cause 3.

**Solution**: Rewrite database logic so that block save, block application, and round tick are all encompassed within an atomic database transaction that can be easily rolled back upon interruption or error.

This should better ensure data integrity across nodes on the network.

**Comment by karmacoma** [comment]
Above commit, is not a complete solution. Next step is to ensure block, transactions and memory table writes are all within atomic db transaction(s).

**Comment by karmacoma** [comment]
Shifting this issue up a gear. Logic rewrite will provide better use of shared connections from pool and make block processing fully atomic as originally intended.

**Comment by karmacoma** [comment]
Closing and moving to here: https://github.com/LiskHQ/lisk/issues/302
