### ISSUE TITLE
Cannot submit dapp zipfile links containing non alphanumeric chars

### ISSUE THREAD

**Issue by m-schmoock** [LiskHQ/lisk#214]
If one tries to submit an dapp link that contains characters like "_"  , i.e. "https://example.com/test_123.zip" , the submission will fail with the GUI error message:

```
Your application link is invalid. It has to start with "http://" and end with ".zip"!
```

I think the regex validator is broken here, correct?

**Comment by karmacoma** [comment]
Closing due to: #560
