### ISSUE TITLE
Can not get unconfirmed transactions in testnet. Using /api/transactions/unconfirmed and /api/transactions/unconfirmed/get .

### ISSUE THREAD

**Issue by tomokazukozuma** [LiskHQ/lisk#2159]
### Expected behavior
1. I send transaction on testnet using Lisk Nano .
2. Call api `/api/transactions/unconfirmed` before the transaction is confirmed.
3. Unconfirmed transaction was get.

### Actual behavior
Can not get unconfirmed transaction.
/unconfirmed -> `{"success":true,"transactions":[],"count":0}`
/unconfirmed/get?id=<id> -> `{"success":false,"error":"Transaction not found"}`

### Which version(s) does this affect? (Environment, OS, etc...)
Docker image: lisk/testnet:latest

**Comment by tomokazukozuma** [comment]
@4miners No I didnt.
Is this API documented? I could not find this api.

**Comment by tomokazukozuma** [comment]
I did call `/api/transactions/unprocessed`
but api result is 
{"success":false,"error":"API endpoint not found"}

**Comment by tomokazukozuma** [comment]
@shuse2 
I am implementing Lisk wallet and I just want to get the transaction before it is included in the block.

**Comment by Nazgolze** [comment]
@tomokazukozuma 1.0 api documentation is here: https://lisk.io/documentation/lisk-core/user-guide/api/1-0.

I think the endpoint you're looking for is /api/node/transactions/unconfirmed.

At the moment, betanet is our 1.0 network, but in 2 days, we migrate 1.0 to testnet

**Comment by tomokazukozuma** [comment]
@Nazgolze Thanks!
I will try execute api when betanet is released.

**Comment by 4miners** [comment]
@tomokazukozuma Sorry, for current version you should try `/api/transactions/queued`. Transaction first go there and then is moved to `/api/transactions/unconfirmed` (so basically you should always query both for transaction that is not yet confirmed). There is also another endpoint `/api/transactions/multisignatures` which returns transactions related to multisignature accounts.
