### ISSUE TITLE
Set "lisk" user for database if its empty during migration 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2178]
### Expected behavior
There must be a username for database set at the end of migration process. If not set it tries to load `USER` env variable. Which is not available when lisk scripts are started from the some non-interactive shell. 

### Actual behavior
Version `0.9.x` had behavior to use `lisk` username if there is no username set in `config.json`. This behavior is changed in `1.0.x`. Not sure the which cause this behavioral change, `pg-promise` may be looked into it. 

### Steps to fix
Update the `update_config.js` script to set user to `lisk` if there is no user after the final configuration is generated. 

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.x

**Comment by nazarhussain** [comment]
@fchavant @ManuGowda Created the issue based on discussion we had on configuration migration.

**Comment by nazarhussain** [comment]
@fchavant Can we make sure that `USER` variable was not set in lisk-scripts for 0.9.x releases.

**Comment by ManuGowda** [comment]
@nazarhussain I had discussion with @fchavant about the env variable `USER` was not set in `lisk-scripts for 0.9.x releases`.

**Comment by Nazgolze** [comment]
Closed by #2227 / #2229 / #2240
