### ISSUE TITLE
networkHeight in /api/node/status is wrong

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#2179]
### Expected behavior
networkHeight should give the *correct* height of the network, meaning the height with the highest consensus or in other words with the most nodes behind it. I use this to verify if my nodes are on the "correct" height.

### Actual behavior
currently networkHeight seems to be the highest height seen in the network, even if it is only a single forked node on this height, which is wrong in my opinion.

### Steps to reproduce
directly after the fork on testnet at block 5594490, networkHeight was 5594683 for a long time, because 2 peers were on this height. See network monitor:
![wrong_networkheight](https://user-images.githubusercontent.com/10214886/42034608-e1fc3362-7ae0-11e8-8b42-a63d6299de59.png)

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-rc1 (testnet)

**Comment by MaciejBaj** [comment]
networkHeight is now calculated as follows:
1. Get all connected peers
2. Limit your findings up to 100 peers
3. Within 100 peers look for matching `broadhash` peers first, fill up to 100 with unmatching 
4. Group peers by height
5. Pick the most popular height among grouped peers

@simonmorgenthale basing on screenshot from Lisk Explorer you attached, it might be that your node was connected to 2 peers only.
