### ISSUE TITLE
balances never confirm in the api

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#219]
balances are always unconfirmed 

https://liskwallet.info/api/accounts/?address=10935914903312367881L
https://liskwallet.info/api/accounts/?address=5566846547481905162L

Haven't looked at the code yet but one would think it would not be in the unconfirmed after n confirmations. So I assume the api is just not checking the confirmations. Unless there is some other logic here that I don't understand.

**Comment by karmacoma** [comment]
It appears unconfirmed transactions are not being broadcasted to other peers, for them to be included in a block by an active delegate.

Closing this issue, as quite confident it is related to: #238, which we are aiming to resolve in 0.3.2.

**Comment by ByronAP** [comment]
I think you are confused as the 2 are not related at all.

**Comment by ByronAP** [comment]
The balances shown in the above links have been confirmed on the chain and are spendable. It seems as if it is just the api that never shows any balance as ever being confirmed. Please reopen!

**Comment by karmacoma** [comment]
Okay, my apologies, it appears you are talking about something else.

If you mean `unconfirmedBalance` should eventually become zero, then there is a misunderstanding of it's purpose.

The `unconfirmedBalance` property is incremented or decremented as unconfirmed transactions are applied or rolled back within the database. Once said transactions are included in a block and confirmed, the `balance` will receive the same application of events. Therefore, if `unconfirmedBalance` and `balance` are both equal, then this would indicate there are no transactions pending confirmation. Meaning all is good.

Example:

1. User sends transaction from `accountA` to `accountB`
2. Unconfirmed transaction is applied, affecting `unconfirmedBalance` on `accountA` and `accountB`
3. Unconfirmed transaction is included in next block and confirmed, and applying same changes to `balance` on both `accountA` and `accountB`
4. `unconfirmedBalance` and `balance` are now equal (balanced)

Looking at both of the links you provided, all balances are equal and therefore up-to-date. 

Throughout all of the memory table logic, this same design pattern is applied, so it is consistent behavior from the point of view of Lisk.

**Comment by ByronAP** [comment]
Thank you for the clarification. Perhaps the name should be changed.

**Comment by karmacoma** [comment]
No problem. Thanks for your continued input, it's very much appreciated.

I think for now the naming is logical enough. I think in this case, some documentation would be of most benefit, which is something we will look to do.
