### ISSUE TITLE
Cannot read property 'senderPublicKey' of undefined

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#22]
Encountered the following fatal error, halting node:

```
fatal 2016-03-31 10:29:49 Domain master { message: 'Cannot read property \'senderPublicKey\' of undefined',
  stack: 'TypeError: Cannot read property \'senderPublicKey\' of undefined\n    at v.processUnconfirmedTransaction (/root/lisk/install/app.js:11:132)\n    at /root/lisk/install/app.js:8:14722\n    at /root/lisk/install/node_modules/async/lib/async.js:181:20\n    at iterate (/root/lisk/install/node_modules/async/lib/async.js:262:13)\n    at /root/lisk/install/node_modules/async/lib/async.js:274:29\n    at /root/lisk/install/node_modules/async/lib/async.js:44:16\n    at Immediate._onImmediate (/root/lisk/install/app.js:11:371)\n    at processImmediate [as _immediateCallback] (timers.js:367:17)' }
```

**Comment by fix** [comment]
issue likely here
https://github.com/LiskHQ/lisk/blob/50283284c35389a46191fcbab318cf9cb4678292/modules/transactions.js#L351

I checked source code, there is no check if transaction exists before calling the function:
- https://github.com/LiskHQ/lisk/blob/377e4b908e99adfeeb1d68f628d223030ebe4be7/modules/loader.js#L190
- https://github.com/LiskHQ/lisk/blob/377e4b908e99adfeeb1d68f628d223030ebe4be7/modules/loader.js#L159
