### ISSUE TITLE
Move all scripts to task runner grunt

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2206]
### Expected behavior
We have a task runner in place. So all generally used tasks should be run through `grunt`

### Actual behavior
Currently we have different scripts file to maintain different tasks 

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.x

**Comment by nazarhussain** [comment]
@diego-G @MaciejBaj I revisited my thoughts on the issue. Currently we have `update_config.js`, `generate_config.js` and `console.js`. Console already bound with `npm run console`. So moving `generate_config` and `update_config` to grunt tasks, will create another dependency on `grunt`. While currently these can be run directly from `node script`. What do you guys think?

**Comment by diego-G** [comment]
What's the problem of having a new dependency on `Grunt`? The idea is to use only one folder for scripts/tasks. @nazarhussain Are you able to move everything to `Grunt` even `console.js`?

**Comment by nazarhussain** [comment]
@diego-G Yes I can move every thing to grunt tasks. Having new dependency means one must need `grunt` to run those scripts, while now they can run with simply having `node` (although other dependencies required e.g. lodash etc`).

Its up-to @MaciejBaj to confirm to do it or not.

**Comment by MaciejBaj** [comment]
I am skeptical about moving the script tasks to Grunt if they can be simply handled by node. It makes the whole process simpler. 

It seems that the current 'mocha' task is hard to detach from Grunt, but the whole `Gruntfile.js` looks relatively simple right now. I would rather leave it like this and keep the scripts excetable from `package.json` directly.
