### ISSUE TITLE
Use available task runner instead of raw scripts 

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2211]
### Expected behavior
We have `grunt` in our project configured as task runner. So for any utility task we should use it. 

### Actual behavior
Currently there are few scripts which behaving like utility tasks but are available as raw scripts and run directly through `node`. 

`scripts/console.js`
`scripts/generate_config.js`
`scripts/update_config.js`

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.x

**Comment by MaciejBaj** [comment]
For the same reasons as described in https://github.com/LiskHQ/lisk/issues/2206, the issue can be closed. We rather keep them being run as Node scripts directly.
