### ISSUE TITLE
Core 1.0.0-rc.1 unable to migrate a 0.9 snapshot

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk#2214]
### Expected behavior
- Should be able to perform a stable migration
### Actual behavior
- Some exceptions due to:

```
lisk_1  | [ERR] 2018-07-10 09:26:46 | BatchError: duplicate key value violates unique constraint "blocks_height"
```
cause the node to not perform migration and therefore crashes and is not longer able to process further requests.
### Steps to reproduce
- Go to the following job, and trigger a build.
- https://jenkins.lisk.io/job/lisk-hub/job/PR-972/
- https://github.com/LiskHQ/lisk-hub/pull/972
details:
- https://jenkins.lisk.io/job/lisk-hub/job/PR-972/33/consoleFull

### Which version(s) does this affect? (Environment, OS, etc...)

- linux, jenkins, lisk-hub workspace

**Comment by 4miners** [comment]
Cannot reproduce locally, sorry - looks like some issue with configuration.

**Comment by MaciejBaj** [comment]
The Jenkins job @faival pointed out was using Testnet genesis_block.json to load a development snapshot.
