### ISSUE TITLE
Add ENV variables support for few configuration option

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2225]
### Expected behavior
We should specify many configuration option through `ENV` variables. That is required to have a configureable docker image (template file, confd and invocation (in run.sh) must be removed from the docker image)

### Actual behavior
Currently we support some subset of configuration options to be set through the ENV variables. https://github.com/LiskHQ/lisk/tree/1.1.0#command-line-options, which are not enough to run a docker image

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.x

**Comment by nazarhussain** [comment]
After discussion among @fchavant and @diego-G we decided to move this issue to `1.2.0` or later. As in `1.1.0` we had came across of an alternative solution to keep the template file for docker. 

@diego-G Need to provide the most common configuration options that our app will support in addition to already supported 5 `env` variables.  https://github.com/LiskHQ/lisk/tree/1.1.0#command-line-options

We will support short listed configuration options through env variables and for rest of the detailed configuration user have to use its own custom config file in docker.

**Comment by fchavant** [comment]
@nazarhussain at the very least we need to be able to set:
`.consoleLogLevel`, `.db.host`, `.cacheEnabled`, `.db.user`, `.db.password` and `.api.access.public`.

**Comment by diego-G** [comment]
`fileLogLevel`, `consoleLogLevel`, `cacheEnabled`, `db.host`, `db.user`, `db.password`, `api.access.public`, `forging.access.whitelist[]`, `forging.delegates[]`, `peers.list[]`. The last three are arrays as you can appreciate. They might include several elements.
