### ISSUE TITLE
Update forging doc - Lisk Core

### ISSUE THREAD

**Issue by guillaumeLamanda** [LiskHQ/lisk#2226]
Hi ! 👋 

While I was configuring my delegate node on the testnet, I get stuck on the "Forging configuration" step. 
Doc just specify the content of the object, but it not tell us how to generate the *encryptedPassphrase*. This informations is only available on the *migration guide*.

### Expected behavior
- Follow the Lisk Core documentation for configuring a delegate node

### Actual behavior
- Follow the Lisk Core Doc
- Find the missing parts in migration guide (personnaly, I had to ask to the lisk.chat community)

### Steps to reproduce
- Try to configure a delegate node only with the lisk core documentation.

### Which version(s) does this affect? (Environment, OS, etc...)
testnet 1.0.0-rc0

Thanks for all the work you are doing out there !

**Comment by Tschakki** [comment]
Hi @guillaumeLamanda !

Thank you for spotting this!
We will soon update the documentation to a newer version that will explain how to enable/disable forging for Lisk Core in detail :-)

Cheers!

**Comment by diego-G** [comment]
Already fixed and documentation update release before `1.0.0-rc.2` reaches testnet.
