### ISSUE TITLE
Roadmap to upgrade Node.js from v6.14.3 to v10 LTS

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2239]
### Expected behavior
- Upgrade Node.js from `v6.14.3` to `v8.11.3`
- Once `sodium-native` build is stable with Node.js `v10.x.x`, upgrade Node.js version to LTS `v10.x.x`

#### Note:
No backward compatibility support for the previous version of Node.js after the upgrade.

**Comment by 4miners** [comment]
For reference: https://github.com/LiskHQ/lisk/issues/2135

**Comment by willclarktech** [comment]
@ManuGowda Perhaps it's worth adding semver major/minor requirements to these changes?

**Comment by ManuGowda** [comment]
@willclarktech as per the discussion with @MaciejBaj we decided to keep the backward compatibility support of LTS versions, to not end up in instability on minor versions of the software. @MaciejBaj whats your opinion on this comment?

**Comment by willclarktech** [comment]
My point is just that removing support for Node versions is probably a major change, whereas adding support is probably a minor change, and it would be helpful to see this directly in the issue description.

**Comment by ManuGowda** [comment]
- Lisk Core will support only one Node version at the time.
- Lisk Core Node version announcements issue will have to be adjusted LiskHQ/lisk: Issue #2239
- Lisk Core 1.2.0 package.json will have to be changed to support one Node.js version only -https://github.com/LiskHQ/lisk/blob/development/package.json#L19
- Lisk Core Jenkins file will have to be adjusted to run all the tests of the development branch (1.3.0 version) against Node 8 - LiskHQ/lisk: Pull Request 2395

**Comment by willclarktech** [comment]
@ManuGowda As mentioned before, I believe upgrading Node.js to a new major version will require a major version bump for our software: if we require users to use the new major version, then they cannot simply install our new software and run it on their existing setup.

**Comment by diego-G** [comment]
For reference : `sodium-native` is successfully building on Node 10 & 11 https://travis-ci.org/sodium-friends/sodium-native

**Comment by diego-G** [comment]
Replaced by #2647
