### ISSUE TITLE
built in script to backup database

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#224]
It would be nice if there was a built in script we could run that would cc the current db and also a restore command. This would make it possible to restore from a local copy instead of downloading the entire chain from peers or bootstrap. This shouldn't be too hard as the script can stop Lisk and then restart it once the operation is complete.

**Comment by Isabello** [comment]
I have already written a script that deals with this feature. However, just taking snapshots and restoring them introduces a variety of issues, including memory table corruption. Currently, its not safe to restore snapshots in an unverified fashion, as in, restored and then config.json set with verifyOnLoad = true to rebuild memory tables from the existing database.

Snapshots must be able to rebuild to current height from the database and rejoin the chain before they can be deemed safe for use, even locally.

**Comment by ByronAP** [comment]
Do you have a copy of your script I could look at? because I personally don't see why some minimal checking wouldn't alleviate most issues that you mention.

**Comment by Isabello** [comment]
Minimal checking is not really going to help. The whole chain has to be verified to prevent potential corruption issues from being introduced.

**Comment by ByronAP** [comment]
I understand and this is a risk but if the snapshot is good then it's a non issue, if the snapshot is bad the user will find out soon enough as it wouldn't sync to current

**Comment by Isabello** [comment]
The snapshot has to be verified from 0 rebuilding all the tables from that point in order to be "good". Just restoring it and saying "oh the tables are good" is not good enough.

**Comment by karmacoma** [comment]
There is a new snapshot facility to be introduced in 0.3.2. To use it you simply add the following command switch when starting the client, putting it in a snapshot mode.

```
node app.js --snapshot <round>
```

e.g. to verify the blockchain up to end of round 1000:

```
node app.js --snapshot 1000
```

Note: Any blocks after round 1000 will be deleted, including all transactions. This allows snapshots to be open cleanly onto next round, with votes closed off from previous round.

**Comment by karmacoma** [comment]
Moved to https://github.com/LiskHQ/lisk-build/issues/30 where our provisioning scripts reside.
