### ISSUE TITLE
Add height range to blockVersions in exceptions (testnet)

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#2246]
### Expected behavior
When migration height is picked proper height range should be added to `blockVersions` in exceptions for version `0`.
### Actual behavior
There is nothing added yet.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0-rc.2

**Comment by MaciejBaj** [comment]
Closed by #2296
