### ISSUE TITLE
Set default db user to 'lisk'

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk#2248]
lisk-scripts in 1.1 and later sets DB_USER based solely on what's in the config

**Comment by Tschakki** [comment]
These changes require the README.md to be updated.
Please change the prerequisites like in https://lisk.io/documentation/lisk-core/setup/pre-install/source

We could also think of adding a troubleshooting case and different solutions for `error: role "lisk" does not exist` to the docs, e.g. coldstart or changing db username manually in config

**Comment by diego-G** [comment]
Thanks @Tschakki. Could you please open a PR against `1.1.0` to update the README?

**Comment by diego-G** [comment]
Readme needs to be updated.
