### ISSUE TITLE
Unable to authenticate Sudo.

### ISSUE THREAD

**Issue by got3nks** [LiskHQ/lisk#2256]
While the new installer is not supposed to require Sudo, as in the documentation:

`The lisk user itself does not need any sudo rights to run Lisk Core.`

The installation script won't work without Sudo rights:

```
Checking prerequisites:
curl is installed.					Passed
Tar is installed.					Passed
Wget is installed.					Passed
Sudo is installed.					Passed
Please provide sudo password for validation
Sorry, user lisk may not run sudo on ******.
**Unable to authenticate Sudo.					Failed**

Please follow the Prerequisites at: https://docs.lisk.io/docs/core-pre-installation-binary
```

**Comment by MaciejBaj** [comment]
Please open the issue on https://github.com/LiskHQ/lisk-scripts

Please specify more details to help us track the issue cause - which network did you try to run, which version of script and lisk-core did you try to install. Thanks.

**Comment by Nazgolze** [comment]
https://downloads.lisk.io/lisk/main/installLisk.sh still has sudo (mainnet)
0.9.x versions require it yet, sudo is removed when installing 1.0

**Comment by got3nks** [comment]
@MaciejBaj done: https://github.com/LiskHQ/lisk-scripts/issues/118
I'm trying to install on Ubuntu Server 18.04 the latest version of Lisk core (wget https://downloads.lisk.io/lisk/main/installLisk.sh) as described in the documentation.

**Comment by Nazgolze** [comment]
@got3nks you can install 1.0 for testnet, it hasn't been released on mainnet yet.
This version of installLisk.sh will work for installing lisk core 1.0 for testnet: https://origin-downloads.lisk.io/lisk/test/installLisk.sh

**Comment by Nazgolze** [comment]
Closing this issue since https://github.com/LiskHQ/lisk-scripts/issues/118 has been created
