### ISSUE TITLE
Please, fix UI on API 1.0 documentation page

### ISSUE THREAD

**Issue by charlesmanson13** [LiskHQ/lisk#2259]
https://lisk.io/documentation/lisk-core/user-guide/api/1-0

There are too many nested scrollboxes, can you make flat page?

**Comment by nazarhussain** [comment]
I don't know how to link external JS file in the CMS we are using. But this will solve the problem. 

https://github.com/davidjbradshaw/iframe-resizer

```
<style>#swaggerIframe{width: 1px;min-width: 100%;}</style>
<iframe id="swaggerIframe" src=" /assets/swagger-ui/index.html?url=https://testnet.lisk.io/api/spec" scrolling="no"></iframe>
<script>iFrameResize({log:true}, '#swaggerIframe')</script>
```

**Comment by MaciejBaj** [comment]
We will try to improve the documentation UX in the following version.

**Comment by Tschakki** [comment]
API page is now updated, double scrollbars are removed: https://lisk.io/documentation/lisk-core/user-guide/api/1-0

I think this can be closed.
