### ISSUE TITLE
Upgrade lisk-elements dependency to latest version

### ISSUE THREAD

**Issue by jondubois** [LiskHQ/lisk#2266]
### Expected behavior

We should be using a new version of lisk-elements which doesn't use the `js-nacl` dependency (which is causing problems with our node's cleanup-on-exit logic).

### Actual behavior

The `lisk-elements` version `1.0.0-beta.4` which is currently being used for lisk-core 1.x has a dependency `js-nacl` which is causing issues with our process exit strategy. See https://github.com/LiskHQ/lisk/pull/2260#issuecomment-408852057

The latest version of `lisk-elements` no longer has `js-nacl` as a dependency so this will solve the issue of `js-nacl` interfering with our process exit cleanup mechanism.

### Steps to reproduce

Run `npm ls js-nacl` in bash while inside the Lisk core working directory.
It shouldn't be a dependency of Lisk core.

### Which version(s) does this affect? (Environment, OS, etc...)

1.x

**Comment by willclarktech** [comment]
Current prerelease is `lisk-elements@1.0.0-rc.1`.

**Comment by MaciejBaj** [comment]
Lisk Elements was merged in v1.0.0 version - https://github.com/LiskHQ/lisk/pull/2284
