### ISSUE TITLE
 Lisk.sh error

### ISSUE THREAD

**Issue by qq5254232** [LiskHQ/lisk#2279]
error:
lisk@fengqun:~/lisk-test$ ./lisk.sh lisk
Error: Unrecognized command.

Available commands are: start stop start_node stop_node start_db stop_db reload rebuild coldstart logs lisky status help

Command Options for Lisk.sh

All options may be passed [-p <PM2-config.json>]

start_node                         Starts a Nodejs process for Lisk
start                                 Starts the Nodejs process and PostgreSQL Database for Lisk
stop_node                             Stops a Nodejs process for Lisk
stop                                  Stop the Nodejs process and PostgreSQL Database for Lisk
reload                                Restarts the Nodejs process for Lisk
rebuild [-u URL] [-f file.db.gz] [-0] Rebuilds the PostgreSQL database
start_db                              Starts the PostgreSQL database
stop_db                               Stops the PostgreSQL database
coldstart                             Creates the PostgreSQL database and configures config.json for Lisk
lisk                                  Launches Lisk-commander
logs                                  Displays and tails logs for Lisk
status                                Displays the status of the PID associated with Lisk
help                                  Displays this message
lisk@fengqun:~/lisk-test$ ss -ntlp

**Comment by MaciejBaj** [comment]
As written in your debug message:
> Available commands are: start stop start_node stop_node start_db stop_db reload rebuild coldstart logs lisky status help

so it might be `./lisk.sh start` depends of what you want to do.

If you have some following problems try on our gitter https://gitter.im/LiskHQ/lisk
