### ISSUE TITLE
Increase default number of transactions from public API to 25

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#2293]
### Expected behavior

Accessing the transactions endpoint should give all transactions in a block by default. Especially if the `blockId` query is used.

### Actual behavior

The default is 10.

### Steps to reproduce

Access the transactions endpoint and specify the block ID of a full block.

### Which version(s) does this affect? (Environment, OS, etc...)
 
1.0.0+

**Comment by nazarhussain** [comment]
You can already do it by passing `limit` param to the API. I don't think setting `limit` conditionally based on different parameters is a good idea.

**Comment by MaciejBaj** [comment]
@willclarktech do you feel like passing `limit` as @nazarhussain suggests covers the issue? Setting the `limit` from 10 to 25 doesn't really solve anything, it would return nice results only for full blocks.

**Comment by willclarktech** [comment]
@MaciejBaj This was an issue created after feedback from an exchange (and I told them of course about the `limit` parameter). I don't have a strong opinion about the best solution here.

**Comment by MaciejBaj** [comment]
I am not finding strong arguments for implementing the changes. Closing the issue.
