### ISSUE TITLE
Node only (without web interface)

### ISSUE THREAD

**Issue by punkrock** [LiskHQ/lisk#23]
It would be a useful to implement an option which allows delegates to lock-down nodes for a single purpose only. Just a node. No web interface. No user interaction from the outside.

**Comment by mrv777** [comment]
I'm still learning the code here and don't have a test environment to try this, but I'm wondering if this line would be a quick way to disable the wallet ui on a node:
https://github.com/LiskHQ/lisk/blob/development/app.js#L290

**Comment by fix** [comment]
There are config flags to disable UI or API
