### ISSUE TITLE
unconfirmed transaction stuck in node

### ISSUE THREAD

**Issue by ByronAP** [LiskHQ/lisk#230]
I noticed a transaction (type 4 add sig) that was constantly sitting as unconfirmed. It appears as if on occasion a transaction will get stuck on a node. A reboot of my testnode cleared out the offending transaction.

the offending data:
{"amount":"0","companyGeneratorPublicKey":null,"confirmations":null,"fee":"1500000000","id":"9082231970708809096","recipientId":null,"senderId":"6573868316532588354L","senderPublicKey":"7beb5f1e8592022fe5272b45eeeda6a1b6923a801af6e1790933cc6a78ed95a1","signature":"43609ade6e344031ca5c93b12c694d79040e4ed37fff9288cc3709b65b4e62a21ec6107d6a2697e3dba490e9fe5161acbeab13887cbbee42cc8edc7a9184400c","signSignature":"05aeadaf4e85c97723a3603a848d1ff227c98d00a8245aaf438343115395650d1694e4cf88b0a7e314c56537949106f11f84f29952d318d2b0bbcc95e343ae02","subtype":null,"timestamp":"2441150","type":"4"}

not sure if this is a bug or just a one off incident

**Comment by fix** [comment]
Yes i see it as well, for some (unknown) reason it is stuck,an never included in a block.

**Comment by fix** [comment]
on a side note rebooting a node will clera off the tx form your stack but you will likely get it back from another node. This is what happens to me

**Comment by karek314** [comment]
After quick look on pasted data it seems -> **"recipientId":null** is source of the problem. I think it's also security issue, network can be possibly spammed with tons of invalid transactions.

**Comment by fix** [comment]
yes i agree if the reason of this transaction can be reproduced, it is a security issue.

As for recipinetId there are already some transactions with no recipientId (Second Signature Creation and Delegate Registration) so i am not sure this is the reason, but could be as i have no idea yet

**Comment by karmacoma** [comment]
It is normal behavior for a multi-signature transaction to remain on the unconfirmed transaction stack until it has been signed by a minimum of multi-signature group members. It can also be accessed via `/api/multisignatures/pending?publicKey`. Once the transaction has received a minimum of signatures it will be classed as **ready** and included in the next available block.
