### ISSUE TITLE
Implement API rate limiting

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#231]
A lot of simultaneous api calls to /api/transactions?limit=100 cause very high CPU load on the targeted machine. Could it be possible to prevent a node from forging by "occupying" it with such useless work when it should forge a block?

**Comment by karek314** [comment]
As far i checked delegates hosted by lisk team are safe due blocked public api. But obviously it needs to be fixed and forging delegates needs to become public asap. I would suggest not only improve efficiency of this endpoint but also introduce connections limit per ip to node.

**Comment by Gr33nDrag0n69** [comment]
The idea is true, but for me it's not a big issue since public API can be blocked on forging delegate nodes. Why do you say forging delegate should become public ?

**Comment by karek314** [comment]
Sorry you probably misunderstood me, i mean forging needs to become public. Since currently its centralised under lisk team. And making public api available or not on forging delegate should be left to operator.

**Comment by mfressdorf** [comment]
A rate limit on API calls would be a good suggestion. Have a look at: https://www.npmjs.com/package/express-rate-limit a more solid, strict integration with Redis could be implemented later on.

**Comment by fix** [comment]
At some point we will need to throttle all API call, to prevent such attack.

**Comment by Doweig** [comment]
Limiting requests per IP wouldn't do a good job against DDOS in my opinion as most full nodes will have small hardware anyways.

Is it possible to cache the response? Locally in the nodejs or even redis (sounds like overkill in this case)
If cache is older than X seconds than ignore and build a fresh response.

Can then use NODE_ENV to decide to cache or not:
