### ISSUE TITLE
Wrong logic in update_config.js breaks 1.0.0-rc.2 reinstall

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#2317]
### Expected behavior

It should be possible to run `installLisk.sh upgrade` from version `X` to version `X` (for instance to upgrade to a newer build of `1.0.0-rc.2`); this as been the case in the past.

### Actual behavior

The logic in [update_config.js](https://github.com/LiskHQ/lisk/blob/v1.0.0-rc.2/scripts/update_config.js#L70) will work when upgrading `0.9.16 to 1.0.0-rc.1` and `1.0.0-rc.1` to `1.0.0-rc.2` but *not* when upgrading `1.0.0-rc.2` to `1.0.0-rc.2`.

### Steps to reproduce

```
bash installLisk.sh install -r test
bash installLisk.sh upgrade -r test -d /home/lisk -0 no
```

Application will not start any more; `config.json` will contain several `null` values.

### Which version(s) does this affect? (Environment, OS, etc...)

`v1.0.0-rc.2`

**Comment by MaciejBaj** [comment]
@fchavant `bash installLisk.sh install -r test` is not running update_config.js script - https://github.com/LiskHQ/lisk-scripts/blob/development/downloaded/installLisk.sh#L131.
You won't break the config.json by simply installing the latest version if it doesn't exist before.

**Comment by fchavant** [comment]
@MaciejBaj correct, that's why the reproduction steps are:
```
bash installLisk.sh install -r test
bash installLisk.sh upgrade -r test -d /home/lisk -0 no
```

**Comment by MaciejBaj** [comment]
The current 'update_config.js' script is designed to support only last recent version deployed on the network to the one being released. The script cannot be run trying to update config.json do the same version. The multi-version support is being added in https://github.com/LiskHQ/lisk/issues/2278.

For the sanity of re-install builds of 1.0.0 release let's the introduce the check in `lisk-scripts` before trying to migrate config.json for the same version - https://github.com/LiskHQ/lisk-scripts/issues/129.
