### ISSUE TITLE
Use DNS name instead of IP addresses for seed nodes in config.json

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#2320]
### Expected behavior

`config.json` uses DNS name for seed nodes.
Rationale: DNS names give us more flexibility and are not bound to a particular service provider.

### Actual behavior

IP addresses are being used.

### Steps to reproduce

Look at https://github.com/LiskHQ/lisk/blob/1.2.0/config/mainnet/config.json#L10

### Which version(s) does this affect? (Environment, OS, etc...)

All versions of lisk core up until now.

**Comment by jondubois** [comment]
I created a new PR https://github.com/LiskHQ/lisk/pull/2325 and cherry-picked the commits from this PR so we could potentially close this PR and use the other one instead (they both reference the same issue number).
