### ISSUE TITLE
Unable to broadcast signed tx using public API

### ISSUE THREAD

**Issue by tudorconstantin** [LiskHQ/lisk#2328]
### Expected behavior
Should be able to broadcast a signed transfer transaction using a public API

### Actual behavior
I'm getting the error `Error: Status 500 : An unknown error has occurred.` when trying to broadcast a seemingly validly signed transfer transaction

### Steps to reproduce
This is a snippet that reproduces the issue:

````
const lisk = require('lisk-elements').default;
const axios = require('axios');

//tx created and signed using lisk-elements. Lisk commander's `verify transaction ...` says it's a valid one.
const tx = JSON.parse('{"amount":"10000000","recipientId":"1674320727697413691L","senderPublicKey":"174a0b86fa86dbb5ac6c532bd651c25ac2930eae2ec06ee1f32cec5b05b60871","timestamp":70899177,"type":0,"fee":"10000000","recipientPublicKey":null,"asset":{},"signature":"9a473dce049721633299c98a7eaef71885252dd8e029ff5aa9fb04fa9c304a55348409c0404b57ef7bd4d447c17e7ac11b2e29b44ffe6ea7f3382f5ed632d804","id":"5174888275269436853"}');

//Variant 1: trying to broadcast it using the lisk-elements API
const client = lisk.APIClient.createMainnetAPIClient();

client.transactions.broadcast(tx)
  .then(resp => {
    console.log('1. broadcat success? ', resp)
  })
  .catch( err => {
    console.log('1. broadcast error: ', err);
    /*
    output:
    1. broadcast error:  Error: Status 500 : An unknown error has occurred.
    */
  });

//Variant 2: trying to broadcast it "manually", using axios

//Random public node. The behavior is the same for every node.
const node = 'https://node04.lisk.io:443';

axios.post(`${node}/api/transactions`, tx)
  .then(resp => {
    console.log('2. broadcat success? ', resp['data'])
  })
  .catch( err => {
    console.log('2. broadcast error: ', err);
    /*
    output:
    2. broadcast error:  { Error: Request failed with status code 500
      .
      .
      .
    */
  });
````

## Update. Broadcasting the tx from lisk commander doesn't work either:

When trying to broadcast the transaction from lisk commander, I also get the error:

`{"error":"Could not broadcast transaction: Status 500 : An unknown error has occurred."}`

**Comment by shuse2** [comment]
Hi @tudorconstantin 
For `lisk-elements`, lisk-core is not migrated to 1.0, so `const client = lisk.APIClient.createMainnetAPIClient();`  is not valid yet.
If you want to test the transaction, please use the testnet by `createTestnetAPIClient`

**Comment by tudorconstantin** [comment]
Hi @shuse2,

I don't really care what I have to use - be that `lisk.APIClient.createMainnetAPIClient();`, or axios, to submit transactions manually. 

I am trying to sign transactions and broadcast them, programatically. The transactions are valid (the lisk commander confirms this), so the signing part seems to work, but the network refuses them.

Is there a way today to accomplish this? (I assume there is, since I just withdraw some LSK from an exchange and they sent it to me. I doubt they did it manually).

If the `APIClient` method doesn't work right now, what path should I go on?

**Comment by tudorconstantin** [comment]
Ah, I see. 
Thank you very much for the explanation. 
Then I'll wait until next week and try again after the main net upgrade.

Thanks again, and wish you all good luck in making the upgrade a complete success.
