### ISSUE TITLE
/api/accounts/top setting flag

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#234]
I suggest to move top accounts setting on/off flag to config instead
`TOP=true node app.js`
Or keep it this way with possibility to overwrite with value kept in config.json

**Comment by Gr33nDrag0n69** [comment]
I agree all settings should be defined via the config file.

**Comment by fix** [comment]
The reason it is set, is the implementation is not good and too long to compute.

see #233

closing it as duplicate

**Comment by fix** [comment]
labeled won't fix since the flag will be removed
