### ISSUE TITLE
lisk_bridge.sh is broken

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#2345]
### Expected behavior
Script should check, if it was called from a directory other than lisk_home

### Actual behavior
The check is broken, the script terminates immediately

### Which version(s) does this affect? (Environment, OS, etc...)
https://downloads.lisk.io/lisk/main/lisk_bridge.sh

line 65f of https://downloads.lisk.io/lisk/main/lisk_bridge.sh is broken:
is:
`ABSOLUTE_LISK_HOME=$(cd -P "$LISK_HOME")`
`ABSOLUTE_CWD=$(cd -P "$PWD")`
should be:
`ABSOLUTE_LISK_HOME=$(cd -P "$LISK_HOME" && pwd)`
`ABSOLUTE_CWD=$(cd -P "$PWD" && pwd)`

**Comment by MaciejBaj** [comment]
Issue to be raised on https://github.com/LiskHQ/lisk-scripts, @Nazgolze already uploaded the fix on  https://downloads.lisk.io.  Thank for reporting.
