### ISSUE TITLE
Poor performance of GET /api/node/status

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#2348]
### Expected behavior
Performance of API `GET /api/node/status` should be satisfactory (under 1 second). 

### Actual behavior
We run some benchmarks with following spec:  

```
CPU: 1vCPU (Digital Ocean) 
RAM: 1 GB Memory
Disk: 25 GB Disk
Connections: 10 
Time: 30s
```
And got the following results;

```
Fastest: 3.17
Slowest: 5.34
Average: 4.36
```

### Steps to reproduce
Query endpoints mentioned above.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.1 (after indexes)

**Comment by nazarhussain** [comment]
We're getting a performance hit here because it executes internally a query which performs `COUNT` on `trs` table, which comes with a cost.
https://github.com/LiskHQ/lisk/blob/63805fbdd88a9fba85ac58aca06c5fca948fbad8/api/controllers/node.js#L103

**Comment by MaciejBaj** [comment]
Not to break API so far the best solution is to cache the confirmed transactions count results after the first hit and invalidate after a new block gets applied or deleted.

**Comment by 4miners** [comment]
I would like to propose following solution:
- when calling the endpoint for the first time - store transactions count together with actual block height (`modules.blocks.lastBlock.get().height`) as an object in the memory 
- when calling the endpoint for the next time - check if block height changed - if so, re-execute the query and update the count together with new block height

Please review, @nazarhussain.

**Comment by nazarhussain** [comment]
I was just thinking over the idea, in the above solution, we have to recompute the transaction count cache every 10sec, while most of the time its not required due to empty blocks. So we need to think of any other way to actually utilize that cache for longer time.
