### ISSUE TITLE
Poor performance of GET /api/delegates/[address]/forging_statistics

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2352]
### Expected behavior
Performance of API `GET /api/delegates/[address]/forging_statistics` should be satisfactory (under 1 second). 

### Actual behavior
We run some benchmarks with following spec:  

```
CPU: 1vCPU (Digital Ocean) 
RAM: 1 GB Memory
Disk: 25 GB Disk
Connections: 10 
Time: 30s
```
And got the following results;

```
Fastest: 8.23
Slowest: 8.91
Average: 9.74
```

### Steps to reproduce
Query endpoints mentioned above.

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.1 (after indexes)

**Comment by 4miners** [comment]
The main reason for introducing this endpoint (together with new `rounds_rewards` table) was to allow getting forging statistics for the period of time, for example, last month, last week, etc. This endpoint is not a reliable one for getting total forging statistics (from all time), as the underlying query is performing [aggregate function](https://www.postgresql.org/docs/9.6/static/functions-aggregate.html) `SUM` on two columns over large data set (~6M records and growing). Please also see my comment here: https://github.com/LiskHQ/lisk-private/issues/73#issuecomment-414262338

I would recommend taking the following approach for now:

When a user (not providing `fromTimestamp` or `fromTimestamp` provided is equal to Lisk epoch) and (`toTimestamp` is also not provided or is greater or equal to last block timestamp) - this means that user requested statistics for all time
https://github.com/LiskHQ/lisk/blob/63805fbdd88a9fba85ac58aca06c5fca948fbad8/api/controllers/delegates.js#L129-L132
For this we can just query `mem_accounts` and get columns `rewards` and `fees`, the results for a particular delegate are the same:
`mem_accounts`:
```
    rewards     |     fees     
----------------+--------------
 24128500000000 | 284136733031
(1 row)
```
`rounds_rewards` (aggregate_blocks_reward):
```
 delegate | count |     fees     |    rewards     
----------+-------+--------------+----------------
        1 | 53107 | 284136733031 | 24128500000000
(1 row)
```
Please review the approach, @nazarhussain.
