### ISSUE TITLE
Implement API versioning

### ISSUE THREAD

**Issue by mfressdorf** [LiskHQ/lisk#236]
As development and use of the Lisk APIs progresses, App developers need to be sure the implementation details of the API do not change. Since this is rather unrealistic, a proper versioning of the API is needed to gracefully introduce new changes.

For Reference:  
http://stackoverflow.com/questions/389169/best-practices-for-api-versioning
http://www.lexicalscope.com/blog/2012/03/12/how-are-rest-apis-versioned

**Comment by fix** [comment]
Agree on this. We will likely mirror the current api to api/v1/ and then deprecate it

**Comment by fix** [comment]
@karmacoma maybe we should mirror the current API (i mean the one for 0.3.3) to /api/v1 and then start maybe a v2 from now on following closely the RESTFUL best practices

**Comment by Isabello** [comment]
We will be using versioning in the URL as follows:

https://login.lisk.io/api/v1/accounts

etc

**Comment by lirantal** [comment]
If API versioning is still relevant take a look at https://github.com/lirantal/express-version-route
I'd be happy to help with a PR to add it in.

**Comment by karmacoma** [comment]
Closing issue, as no longer a priority. Cancelled from parent #225. We may revisit later.
