### ISSUE TITLE
/api/blocks/?generatorPublicKey= returns delegate when no pk provided

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#2364]
### Expected behaviour
When PK is not provided in this GET request
`/api/blocks/?generatorPublicKey=&limit=100&offset=0&orderBy=height:desc`
It should return error that no PK provided

### Actual behaviour
It does return latest blocks 

### Steps to reproduce
GET /api/blocks/?generatorPublicKey=&limit=100&offset=0&orderBy=height:desc

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.1

**Comment by MaciejBaj** [comment]
Not specyfying the custom filters isn't an error. Not specified custom fileters are ignored while returning a result. The behaviour is correct.
