### ISSUE TITLE
Sends never hit the blockchain / Can't resend since LISK thinks the coins are gone.

### ISSUE THREAD

**Issue by Crypto2** [LiskHQ/lisk#238]
There is a pretty major bug sending funds via the RPC API where the send never makes it into the blockchain, but LISK won't let you send the coins again since it thinks they are gone.

To reproduce, starting with an account with say 7.5 LSK in it:
1. Send 5 LSK from account, LISK returns success and a TX ID. TX never makes it into blockchain (seems to be a random but annoying occurrence.)
2. After waiting a while and seeing it didn't confirm, try sending the 5 LSK again. API returns "Account has no LISK".
3. The account balance returned via the API and block explorer: 7.50000000 so on some level it knows there are coins in the account.

This is a pretty major issue since when a user does a withdrawal from their account that doesn't go through then it's just stuck and nothing I can do to help them.

**Comment by horsecoin** [comment]
I am having this issue with the web wallet https://login.lisk.io
I was in the middle of my steemit.com blog Lisk Review [](https://steemit.com/lisk/@coininstant/the-very-first-lisk-web-wallet-review) and when I tried to send 5 coins from the web wallet they disappeared from my balance even though they are still in my account. [](https://steemit.com/lisk/@coininstant/the-very-first-lisk-web-wallet-review)

**Comment by fix** [comment]
yes, This bug is fixed in the coming version. If the node detected that it is in a unsync state (which is the case on login.lisk.io) the txs is locked and sometimes never brodcasts. If you switch to another web wallet, the fund should be free to use.

I advise to be patient and wait for the next release 0.3.2 otherwise you may double spend your lisk.

**Comment by MaxKK** [comment]
>I advise to be patient and wait for the next release 0.3.2 otherwise you may double spend your lisk.

Everyone who is confusing the "double spend" term here, it's not what you think it is. @fix only meant that you can send out a transaction twice by mistake, if you have enough funds both transactions will be valid. It's not a double spend bug or attack!

Please read: https://www.reddit.com/r/Lisk/comments/4u2ooq/ok_unless_lisk_goes_up_90_in_the_next_7_days_im/d5mxgvu

**Comment by fix** [comment]
yes thanks @MaxKK for clarifying, this is not "double spend" attack.

**Comment by ByronAP** [comment]
#219 is not related to this. #219 appears to be an api or calculation issue not a broadcasting issue.
