### ISSUE TITLE
Remove Peers Blacklist from Network Test suite

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2386]
### Expected behavior
Peers Blacklist can be removed from the network test suite of Lisk Core and included as a part of QA. It will make the overall feature tests more reliable and easier to maintain as the current tests need to be further improved - it closes #2331.

### Which version(s) does this affect? (Environment, OS, etc...)
`>= 1.0.0`

**Comment by jondubois** [comment]
This issue depends on the work involved in fixing: https://github.com/LiskHQ/lisk/issues/2276
If resolving https://github.com/LiskHQ/lisk/issues/2276 is too difficult, then we should just remove the blacklist tests, otherwise we keep them.

**Comment by jondubois** [comment]
Fixing https://github.com/LiskHQ/lisk/issues/2276 was not difficult, tests are stable so we can close this issue.
