### ISSUE TITLE
Get delegates API call is returning wrong data.

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#239]
Based on the documentation: (https://lisk.io/documentation?i=lisk-docs/APIReference#get-account), 
a call to "GET /api/accounts/delegates?address=address" should return the delegate information. The call return the same data like the API call for voters of one account "GET /api/accounts/delegates/?address=address" 

Ether the documentaiton is wrong or the API implementation is having a mistake

**Comment by vrlc92** [comment]
If you want to get the delegate information,
try this way: https://login.lisk.io/api/delegates/get?username=vrlc92

The URLs you sent are equal and returns the votes by address.

**Comment by karmacoma** [comment]
Closing and moving here: https://github.com/LiskHQ/lisk-docs/issues/12. We will fix asap.
