### ISSUE TITLE
Votes should get chanceled after xxxxx blocks

### ISSUE THREAD

**Issue by ducktank1990** [LiskHQ/lisk#2394]
### Expected behavior
If a delegate is doing bad work or stop forging for some days he should be outvoted fast

### Actual behavior
If a delegate is doing bad work or stop forging the process of unvoting took too long 

### Reason
There are a lot frozen accounts and the motivation of voting is not big enough
Also vote fee is to expensive atm 

### Solution
Votings get chanceled after xxxx blocks

### Pros
- steady voting per account would increase the dynamic of the system
- increasing frozen voter accounts dont make the 101 dynamic more sluggish

**Comment by revaen** [comment]
The issue with this idea is that some pools demand to vote all the required delegates. So if you don't vote for all delegates in their pool you will get a penalty or you don't get the reward. These pools have their own rules.

**Comment by revaen** [comment]
I am not sure if a lot of voters will unvote the 'bad' delegate. 

Suppose you mean it is not up to the voters but to coding.
So you are saying that LiskHQ has to make a code that the 'bad' delegates get eliminated. Than this could better be answered by LiskHQ if it possible and if they like the idea.

**Comment by ducktank1990** [comment]
wrote this idea in https://github.com/LiskHQ/lisk/issues/353
sorry did not saw issue 353
