### ISSUE TITLE
Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#2399]
I have noticed these transactions repeatedly appearing in logs of lisk core 1.0.2. If there are invalid transactions, why these aren't removed from transaction pool, but instead being processed over and over?
<pre>
[ERR] 2018-09-15 14:03:29 | Failed to process / verify unconfirmed transaction: 9746187269880959999 - Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)
[ERR] 2018-09-15 14:03:29 | Failed to process / verify unconfirmed transaction: 4215816149701806074 - Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)
[ERR] 2018-09-15 14:03:29 | Failed to process / verify unconfirmed transaction: 17288658123640526454 - Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)
[ERR] 2018-09-15 14:03:29 | Failed to process / verify unconfirmed transaction: 11454646359746869396 - Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)
[ERR] 2018-09-15 14:03:29 | Failed to process / verify unconfirmed transaction: 6999971149623611760 - Failed to validate transaction schema: Array items are not unique (indexes 0 and 1)
</pre>

**Comment by MaciejBaj** [comment]
Hey, @karek314 the issue is fixed here but scheduled for 1.2.0: #2254
