### ISSUE TITLE
Implement automated API documentation and playground

### ISSUE THREAD

**Issue by mfressdorf** [LiskHQ/lisk#240]
Would be cool to have a [swagger.io](http://swagger.io/) like API documentation and playground (swagger-ui). This can be integrated with refactoring #225 and versioning #236 of the API.

Also helps with keeping the documentation up to date.

**Comment by diego-G** [comment]
I would like to push this issue into the direction of Postman. It is much more

**Comment by Tosch110** [comment]
/delegates endpoint is missing parameters limit and offset

**Comment by Tosch110** [comment]
/dapps endpoint is missing parameters limit and offset

Apart from this, is transactionId = dappId?

**Comment by Tosch110** [comment]
I am also proposing to query dapps by name

**Comment by Tosch110** [comment]
We should have a discussion on how the `sort` parameter works. Imo an array with strings ['+category'] is not an optimal solution.

**Comment by karmacoma** [comment]
The proposed documentation and playground becomes available once https://github.com/LiskHQ/lisk/issues/899 is closed.
