### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Nazgolze** [LiskHQ/lisk#2400]
Create Makefile that supplants lisk-build

**Comment by Nazgolze** [comment]
This Makefile will build a binary release like lisk-build currently does, building the dependencies as well (libreadline7, jq, postgres, etc)

**Comment by fchavant** [comment]
In a first step we can migrate the current `build.sh` from LiskHQ/lisk-build with minimal changes.
The only issue is `grunt release` being a prerequisite (needs Node.JS which we get only later in `build.sh`); it only executes a few shell commands however and so could be replaced by a `Makefile`.
