### ISSUE TITLE
Maintain delegates list in memory

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#2421]
### Expected behavior
Maintain a copy of shuffled delegates list in the node's memory and reuse it during the same round instead of calling `generateDelegateList` multiple times.
### Actual behavior
Function `generateDelegateList` is responsible for generating a shuffled list of delegates for a particular round, it performs following operations:
- Grab a list of 101 delegates ordered by `vote ASC, "publicKey" DESC` from `mem_accounts` table
- Shuffle the list using round number as seed, it performs SHA-256 operation 21 times.

Currently `generateDelegateList` is called in a many places:
- `modules.blocks.process->onReceiveBlock`, when the block is in fork 1 or 5 states.
- `modules.blocks.verify->processBlock`, for every block.
- `modules.delegates->__private.forge`, when there is forging enabled - every second under until block appear in the current slot window.
- `modules.delegates->getForgers`, every time when the corresponding API endpoint is called.
- `modules.rounds->__private.getOutsiders`, every time when a round is finished.

As you can see above, this function is used heavy across the application, which results in an unnecessary decrease of the overall performance.
### Steps to reproduce
N/A
### Which version(s) does this affect? (Environment, OS, etc...)
`>= 1.0.0`

**Comment by 4miners** [comment]
Reopened again, this time due to not enough rounds in exceptions for testnet, sorry. 😢

**Comment by yatki** [comment]
@4miners could you share new round numbers ?
