### ISSUE TITLE
Unify indexOf & includes usage in exception handling

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2436]
### Expected behavior
Exceptions handling must be consistent across the application and specially the transaction types. e.g.  Consistently use of exception in `verify` and `apply*` methods.  

### Actual behavior

Currently handling of exceptions is done on random places and in different patterns. 

https://github.com/LiskHQ/lisk/blob/4ae8553042b93d3e7ce41c11a7d910fef24ba644/logic/multisignature.js#L140-L142

https://github.com/LiskHQ/lisk/blob/4ae8553042b93d3e7ce41c11a7d910fef24ba644/logic/vote.js#L251-L254

### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0

**Comment by yatki** [comment]
After discussing with @nazarhussain, I decided that we can't combine all exception handling into a central logic due to complexity of the current architecture. I only replaced inconsistent `indexOf` usages and used `includes` in all checks. I'm updating the issue title accordingly.
