### ISSUE TITLE
Update config don't check LISK_NETWORK env variable 

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2437]
### Expected behavior
`update_config.js` should migrate the exisisting config according to environment properly.
### Actual behavior
`update_config.js` fails to migrate the config while upgrading from `1.0.x` to `1.1.x` as the logic only check for default config rather than environment specific 
https://github.com/LiskHQ/lisk/blob/4ae8553042b93d3e7ce41c11a7d910fef24ba644/scripts/update_config.js#L66

When a unified config is generated by merging new config with default config for a testnet enviornament, insted of loading testnet config, it takes default config resulting in invalid config data.
https://github.com/LiskHQ/lisk/blob/4ae8553042b93d3e7ce41c11a7d910fef24ba644/scripts/update_config.js#L62-L68
### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0

**Comment by nazarhussain** [comment]
@ManuGowda Here is the log while I run the script. 


```
➜  lisk git:(1.1.0) ✗ node scripts/update_config.js ../lisk-1.0.0/config.json config/testnet/config.json
Running config migration from 1.0.x to 1.1.x
Starting configuration migration...

Changes summary: 
Skipped: wsPort = 8001 -> 7001
Skipped: httpPort = 8000 -> 7000
Deleted: version = "1.0.3"
Deleted: minVersion = ">=1.0.0"
Skipped: db.database = lisk_main -> lisk_test
Skipped: db.user =  -> lisk
Skipped: peers.list = Addition -> [object Object]
Skipped: peers.list = Addition -> [object Object]
Skipped: peers.list = Addition -> [object Object]
Skipped: peers.list = Addition -> [object Object]
Skipped: peers.list = Addition -> [object Object]
Skipped: peers.list.4.ip = 209.50.49.23 -> 94.237.30.23
Skipped: peers.list.4.wsPort = 8001 -> 7001
Skipped: peers.list.3.ip = 94.237.24.199 -> 94.237.64.33
Skipped: peers.list.3.wsPort = 8001 -> 7001
Skipped: peers.list.2.ip = 94.237.28.66 -> 209.50.48.177
Skipped: peers.list.2.wsPort = 8001 -> 7001
Skipped: peers.list.1.ip = 83.136.249.76 -> 83.136.254.104
Skipped: peers.list.1.wsPort = 8001 -> 7001
Skipped: peers.list.0.ip = 83.136.254.92 -> 94.237.29.221
Skipped: peers.list.0.wsPort = 8001 -> 7001
  Added: peers.options.wsEngine = "sc-uws"
Deleted: nethash = "ed14889723f24ecc54871d058d98ce91ff2f973192075c0155ba2b7b70ad2511"

Writing updated configuration to config/testnet/config.json

```
