### ISSUE TITLE
add log file rotation

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#245]
I have some node running for 60 days with 15GB+ app.log file
I want to keep the level of logging at high rate especially on testnet
I think it would be great if the client handle this for end-user.

i solve it for myself using:

sed -r -i 's/^LOG_FILE=.*/LOG_FILE="\/var\/log\/lisk\/app.log"/g' /opt/lisk/client/lisk.sh

mkdir /var/log/lisk
touch /var/log/lisk/log.json
touch /var/log/lisk/app.log
chown -R ${GLOBAL[lisk_user]}:${GLOBAL[lisk_user]} /var/log/lisk
chmod 700 /var/log/lisk
chmod 600 /var/log/lisk/log.json
chmod 600 /var/log/lisk/app.log

cat > /etc/logrotate.d/lisk-log-json << EOF_lisk-log-json_logrotate
/var/log/lisk/log.json {
su ${GLOBAL[lisk_user]} ${GLOBAL[lisk_user]}
weekly
dateext
copytruncate
missingok
rotate 2
compress
delaycompress
notifempty
}
EOF_lisk-log-json_logrotate

chmod 644 /etc/logrotate.d/lisk-log-json

cat > /etc/logrotate.d/lisk-app-log << EOF_lisk-app-log_logrotate
/var/log/lisk/app.log {
su ${GLOBAL[lisk_user]} ${GLOBAL[lisk_user]}
weekly
dateext
copytruncate
missingok
rotate 2
compress
delaycompress
notifempty
}
EOF_lisk-app-log_logrotate

chmod 644 /etc/logrotate.d/lisk-app-log

**Comment by Gr33nDrag0n69** [comment]
Maybe give a look to this npm module:

https://www.npmjs.com/package/logrotator

**Comment by Isabello** [comment]
This is on my list to implement. Or provide documentation to implement
since We don't want to be in the business of managing users operating
systems when possible.

2016-08-10 13:18 GMT-05:00 Gr33nDrag0n <notifications@github.com>:

**Comment by Gr33nDrag0n69** [comment]
ok adding a switch for setup in lisk install script like you did for ntp ?

**Comment by Isabello** [comment]
probably yes. or a standalone interested users can execute if they want it.

2016-08-10 13:21 GMT-05:00 Gr33nDrag0n <notifications@github.com>:

**Comment by Gr33nDrag0n69** [comment]
great ! I think it's just what's missing for end user not so familiar with lisk or linux log management.

**Comment by Gr33nDrag0n69** [comment]
When you say:
We don't want to be in the business of managing users operating systems when possible.

I agree but lisk logs are under ./logs/ directory so in a way they are part of the software too.
Keeping size of the lisk directory could also be considered "internal stuff" in that acse

**Comment by Gr33nDrag0n69** [comment]
The only problem I can see with bash level log rotate is the day we don't need to use it for weeks/months because forking issue is finally solved, the log will still grow to necessary size.

Except if the script is using linux logrotate to do the job and is just a tool to create the necessary files for logrotate ...

**Comment by Isabello** [comment]
Current play would be to leverage the OS level application using a template
for lisk itself.

2016-08-12 9:33 GMT-05:00 Gr33nDrag0n <notifications@github.com>:

**Comment by Doweig** [comment]
Convention would be to let the system handle this no? An APP handling it's own log rotation seems like a weird concept to me.
Update the documentation/install script with the snippet from @Gr33nDrag0n69 sounds good to me

**Comment by Isabello** [comment]
This has been moved to lisk-build: https://github.com/LiskHQ/lisk-build/issues/51
