### ISSUE TITLE
Update script adds null value to api whitelist array

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2459]
### Expected behavior
config should have correct values insted of `null` when its not expected.
### Actual behavior
A `null` value is added to `whiteList` array as the ip `127.0.0.1` already exists in default config, the custom config contains `null` value due to the way update script merges the config.
```
"whiteList": [
        null,
	"62.23.239.233"
]
```
### Steps to reproduce
Upgrade node from `1.0.0-rc.x` to `1.1.0-rc.0`
### Which version(s) does this affect? (Environment, OS, etc...)
1.1.0

**Comment by MaciejBaj** [comment]
We need to verify if Node behaves normally when 'null' values are present in whiteList config.
