### ISSUE TITLE
dapp : Application level API's not working

### ISSUE THREAD

**Issue by KBC-Systems** [LiskHQ/lisk#246]
dapp Application level API's not working. Getting API result as {"error":"Application not ready","success":false} **## bug**

error log
[ERR] 2016-08-04 11:57:00 | DApps#onNewBlock error: - Application not ready

**Comment by fix** [comment]
Hi KBC-Systems

Thanks for the bug report, could you put the 50 previous lines from the log as well, as they may more accurate on the error.

**Comment by KBC-Systems** [comment]
HI,

Here, It is.

[inf] 2016-08-04 11:54:32 | Checking blockchain on 31.187.70.101:7000
[inf] 2016-08-04 11:54:39 | Received new block id: 5236100749334742612 height: 339706 round: 3364 slot: 620248 reward: 500000000
[inf] 2016-08-04 11:54:39 | Received new block id: 5236100749334742612 height: 339706 round: 3364 slot: 620248 reward: 500000000
[ERR] 2016-08-04 11:54:40 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:54:42 | Checking blockchain on 212.24.104.140:7000
[inf] 2016-08-04 11:54:50 | Received new block id: 8338440206128879966 height: 339707 round: 3364 slot: 620249 reward: 500000000
[ERR] 2016-08-04 11:54:50 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:54:51 | Checking blockchain on 46.101.183.94:7000
[inf] 2016-08-04 11:55:00 | Received new block id: 14485279593065487752 height: 339708 round: 3364 slot: 620250 reward: 500000000
[ERR] 2016-08-04 11:55:00 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:55:00 | Checking blockchain on 66.11.122.218:7000
[WRN] 2016-08-04 11:55:04 | Removing peer POST http://212.24.96.252:7000/peer/blocks
[inf] 2016-08-04 11:55:09 | Checking blockchain on 94.237.25.110:7000
[inf] 2016-08-04 11:55:10 | Received new block id: 2132941594298347970 height: 339709 round: 3364 slot: 620251 reward: 500000000
[ERR] 2016-08-04 11:55:10 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:55:18 | Checking blockchain on 185.34.136.145:7000
[inf] 2016-08-04 11:55:28 | Checking blockchain on 188.213.175.162:7000
[inf] 2016-08-04 11:55:37 | Checking blockchain on 212.24.105.228:7000
[inf] 2016-08-04 11:55:46 | Checking blockchain on 45.63.58.209:7000
[inf] 2016-08-04 11:55:50 | Received new block id: 8553405758790644245 height: 339710 round: 3364 slot: 620255 reward: 500000000
[ERR] 2016-08-04 11:55:50 | DApps#onNewBlock error: - Application not ready
[WRN] 2016-08-04 11:55:50 | Removing peer POST http://130.0.60.20:7000/peer/blocks
[inf] 2016-08-04 11:55:55 | Checking blockchain on 176.37.205.45:7000
[inf] 2016-08-04 11:56:04 | Checking blockchain on 13.82.31.30:7000
[inf] 2016-08-04 11:56:10 | Received new block id: 1465813426631229007 height: 339711 round: 3364 slot: 620257 reward: 500000000
[ERR] 2016-08-04 11:56:10 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:56:14 | Checking blockchain on 198.211.121.66:7000
[inf] 2016-08-04 11:56:19 | Received new block id: 3436971666923505395 height: 339712 round: 3364 slot: 620258 reward: 500000000
[inf] 2016-08-04 11:56:19 | Received new block id: 3436971666923505395 height: 339712 round: 3364 slot: 620258 reward: 500000000
[inf] 2016-08-04 11:56:20 | Received new block id: 3436971666923505395 height: 339712 round: 3364 slot: 620258 reward: 500000000
[ERR] 2016-08-04 11:56:20 | DApps#onNewBlock error: - Application not ready
[WRN] 2016-08-04 11:56:20 | Main queue - 54
[WRN] 2016-08-04 11:56:20 | Main queue - 53
[WRN] 2016-08-04 11:56:20 | Main queue - 52
[WRN] 2016-08-04 11:56:20 | Main queue - 51
[WRN] 2016-08-04 11:56:20 | Main queue - 51
[WRN] 2016-08-04 11:56:20 | Main queue - 50
[WRN] 2016-08-04 11:56:20 | Main queue - 50
[WRN] 2016-08-04 11:56:20 | Main queue - 50
[inf] 2016-08-04 11:56:23 | Checking blockchain on 92.222.83.189:7000
[inf] 2016-08-04 11:56:30 | Received new block id: 12204549870291754498 height: 339713 round: 3364 slot: 620259 reward: 500000000
[ERR] 2016-08-04 11:56:30 | DApps#onNewBlock error: - Application not ready
[inf] 2016-08-04 11:56:32 | Checking blockchain on 46.101.253.214:7000
[inf] 2016-08-04 11:56:40 | Received new block id: 6130146861493922153 height: 339714 round: 3364 slot: 620260 reward: 500000000
[ERR] 2016-08-04 11:56:40 | DApps#onNewBlock error: - Application not ready
[WRN] 2016-08-04 11:56:40 | Removing peer POST http://130.0.60.20:7000/peer/blocks
[inf] 2016-08-04 11:56:41 | Checking blockchain on 31.187.70.66:7000
[inf] 2016-08-04 11:56:50 | Checking blockchain on 107.170.139.206:7000
[inf] 2016-08-04 11:56:59 | Checking blockchain on 146.185.128.191:7000
[inf] 2016-08-04 11:57:00 | Received new block id: 13035332356374383683 height: 339715 round: 3364 slot: 620262 reward: 500000000
[ERR] 2016-08-04 11:57:00 | DApps#onNewBlock error: - Application not ready

**Comment by fix** [comment]
ah! are you using the last version 0.3.2 ?

**Comment by KBC-Systems** [comment]
Yes. We are using 0.3.2

**Comment by KBC-Systems** [comment]
It is as well not working with 0.3.1

**Comment by fix** [comment]
ok. from the logs it sounds the sidechain is not forging at all because you are running on testnet. Can you try to create a local testnet instead, it should work then.

**Comment by KBC-Systems** [comment]
Sure, Thanks.

**Comment by fix** [comment]
let me know. Anyway we should fix it somehow. But for dev it is advised to create a local node, and then register your dapp on testnet only for "real" scale test for public trial.

**Comment by KBC-Systems** [comment]
Ok. Will create and check with local testnet first.

**Comment by KBC-Systems** [comment]
Hey, 

We have checked with local testnode as well; application level API is not working.

You can have look for messaging app using below URL:
http://149.56.46.111:7000/dapps/14602496231523117483/index1.html

Where we have used suggested format for calling application level API's as given in Messaging app doc. on lisk.io. 'api/dapps/[appid]/api/'

I have also checked with different apps like 'guestbook' and 'paperwallet' none of the application is able use application level API's to insert and fetch data into and from database.

**Comment by ccooper21** [comment]
@KBC-Systems, I have been experimenting with Lisk dapps over the last two weeks, and have the example Guestbook application working using recent Github code.  I may not know what I'm talking about yet, but I'm guessing that you have some sort of configuration problem.  One big difference I see between your log and my log, is that when using the genesis block that I generated for my application I don't see any messages in the log like, `Received new block id: 8553405758790644245 height: 339710 round: 3364 slot: 620255 reward: 500000000`.  In other words, I don't see any traffic or block exchange with the public `testnet` blockchain.  Rather, I'm seeing messages like, `Forged new block id: 5381775828589269741 height: 524 round: 6 slot: 782511 reward: 0` which I'm thinking is in reference to either my application's side chain or local `testnet`.  I have yet to figure out if these are one and the same, and what their relationship is to the public `testnet` blockchain.

**Comment by karmacoma** [comment]
Closing due to: #560
