### ISSUE TITLE
0.3.2 syncing still remains highly unstable.

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#248]
After upgrade to 0.3.2 i have been forced to re-sync from scratch due fork cause:3. I have did upgrade with
`bash installLisk.sh upgrade`
But i have also updated installLish.sh after 0.3.2 has been released, then during upgrade node stucked with fork:3

Then i was forced to resync and syncing was quite fast for first 100k blocks, then it become again highly slow, slower then 10s per new block. But restart did help for around 10k blocks and now it's still very slow, node is not synced after more than 15h.

**Comment by karmacoma** [comment]
There is significant work-in-progress towards improving syncing, likely to be introduced in `0.3.3`. Please see branches: https://github.com/LiskHQ/lisk/tree/improve-peers-connectivity, https://github.com/LiskHQ/lisk/tree/rewrite-processBlock.
