### ISSUE TITLE
Multi-signature transaction process after long delay

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2489]
### Expected behavior
When a 1000 multi-signature transactions sent to process it should get confirmed within `>=40 and <=60` blocks.
### Actual behavior
Currently on alphanet `1.2.0-alpha.1` when we send 1000 multi-signature transactions as part of stress test a last 100/200 multi-signature transactions are processed after a long delay, the first 800 were processed with full blocks and the rest 200 takes a long time to process meaning several 100 blocks.

Reference:
Here is the end of processing muti-signature transaction http://alphanet-seed-01.liskdev.net:6040/block/770161081904199981
After a while it processed 25 transactions http://alphanet-seed-01.liskdev.net:6040/block/17369599963050370292
some more time later it processed again 25 http://alphanet-seed-01.liskdev.net:6040/block/17369599963050370292
and there are still 140 transactions in unsigned queue.
### Steps to reproduce
http://alphanet-seed-01.liskdev.net:6040/networkMonitor
login to any of the machine on `alphanet` the `debug` logs are enabled.

**Comment by ManuGowda** [comment]
After the detailed debugging and investigation found out the bug associated with the `multi-signature` transaction processing, the `checkConfirmed` function logic was changed in `1.2.0` where the logic was changed to 
https://github.com/LiskHQ/lisk/blob/7eb913eb8f89f9bbd9107f25905e8d4cc4a4f69b/logic/transaction.js#L287-L299

The logic here checking if the transaction is exists or `transaction.id` exists.
```
if (!transaction || !transaction.id) { 
 		return setImmediate(cb, 'Invalid transaction id', false); 
 	} 
```

Since `signature` transaction doesn't have `id` attribute insted has `transactionId` the if condition was evaluting to true resulting in return immediatly with `(err,false)`.

Here is the sample object
`
{\"transactionId\":\"17855938143472026471\",\"publicKey\":\"bf38236c718b568d0d598ede088c5b48ffcd68fdae3a0354f72ebf02767f8f37\",\"signature\":\"a326e31aca7056b95993ec475d7f031d18803ac110bb705f9e56ed8129229b990e516ea6857e0891734a3218624e8f6992c3ef128339bc4fbc497f20bf245909\",\"relays\":1}"
`

After commenting out line `return setImmediate(cb, 'Invalid transaction id', false); ` the multi-signature transaction processed without any issues, so we need fix the code changes in `checkConfirmed` and also needs to evaluate sql https://github.com/LiskHQ/lisk/blob/development/db/sql/transactions/count_by_id.sql as the `countById` takes `id` as the parameter and in this case we are passing `transactionId` which is invalid.

Next Steps:
Code changes with tests to cover all the scenarios(Type 0-5 Trx) realted to `checkConfirmed`

**Comment by MaciejBaj** [comment]
Transactions are being broadcasted only when they're unconfirmed:
```
return library.logic.transaction.checkConfirmed(
			transaction,
			(err, isConfirmed) => setImmediate(cb, null, !err && !isConfirmed)
		);
```
That means, that while passing signature with optional parameter `signature.transactionId` the check for confirmed transaction can never succeed as the field `transactionId` is never used in `count_by_id.sql` query invoked inside `checkConfirmed`:
```
/*
  DESCRIPTION: Counts transactions by Id

  PARAMETERS:
      - id: trs id
*/

SELECT count(*)
FROM trs
WHERE id = ${id}
```
The signatures are being broadcasted without checking, if a transaction that their attempting to sign is already confirmed or not.

**Comment by ManuGowda** [comment]
@MaciejBaj @nazarhussain @4miners I have a concern regarding function `filterTransaction` in 
https://github.com/LiskHQ/lisk/blob/7eb913eb8f89f9bbd9107f25905e8d4cc4a4f69b/logic/broadcaster.js#L253-L264

if the transaction is in pool
```
if (modules.transactions.transactionInPool(transaction.id)) {
			return setImmediate(cb, null, true);
		}
``` 
it returns true
if the transaction is confirmed it returns false
```
return library.logic.transaction.checkConfirmed(
			transaction,
			(err, isConfirmed) => setImmediate(cb, null, !err && !isConfirmed)
		);
```
I am not sure if my understanding is incorrect or the logic, if the transaction confirmed in database the following statement `setImmediate(cb, null, !err && !isConfirmed)` will return `cb, null, false` which should be `cb, null, true`?

**Comment by diego-G** [comment]
Regression was introduced by PR https://github.com/LiskHQ/lisk/pull/2299 which was producing a deep behavioural change. Besides, the issue's purpose wasn't what the PR does.
@MaciejBaj I suggest to revert those commits and reopened https://github.com/LiskHQ/lisk/issues/1822 to simply change the function's name if it is really needed.
