### ISSUE TITLE
Improving network stability

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#25]
these codes: https://github.com/LiskHQ/lisk/blob/bcfbba7628e8707aa8609fa3cd8a051874ec9342/modules/blocks.js#L1145
https://github.com/LiskHQ/lisk/blob/0210b792780cfda27a69a666c931fa6213aea7cd/modules/loader.js
https://github.com/LiskHQ/lisk/blob/0210b792780cfda27a69a666c931fa6213aea7cd/modules/delegates.js#L458

should be improved in order to prevent from network subnetworking, where peers are stuck in a fork thinking they are synced.

One way is to add a (previousBlockTime-currentServerTime) and check how big it is against the 10s blocktime (needs optimisation testing....). If too big, assign sync to true and look for new peers with higher block-height.

also this blocktime height estimation could be useful for the server to be aware of the network health (how many missed blocks for instance).

**Comment by karmacoma** [comment]
@fix We currently have a problem where out of sync nodes are broadcasting floods of unconfirmed transactions without end.

Example shown is based on improved logging changes made, but happening on a greater scale:

```
log 2016-04-08 15:59:43 Received transaction 10999706733807438160 from peer 159.203.38.14:7000
error 2016-04-08 15:59:43 Confirmed transaction 10999706733807438160 already exists
log 2016-04-08 15:59:44 Received transaction 10999706733807438160 from peer 91.92.109.141:7000
error 2016-04-08 15:59:44 Confirmed transaction 10999706733807438160 already exists
log 2016-04-08 15:59:44 Received transaction 10999706733807438160 from peer 87.100.131.44:7000
error 2016-04-08 15:59:44 Confirmed transaction 10999706733807438160 already exists
log 2016-04-08 15:59:44 Received transaction 10999706733807438160 from peer 104.236.2.111:7000
error 2016-04-08 15:59:44 Confirmed transaction 10999706733807438160 already exists
```

This is the issue behind the balance queue issues people are reporting.

The posted unconfirmed transactions come from the unsynced node here: https://github.com/LiskHQ/lisk/blob/development/modules/transport.js#L634

So I will be taking your suggestion on board, as it will hopefully resolve the stuck peer issue and the problem described above. Thanks 👍

**Comment by fix** [comment]
After reflexion, there is another possibility to radically improve the protocol, including the block height (instead of the timestamp?) to improve reliability. This way there is no ambiguity to know if the block forger was legit or not. The other advantage is that it is timeproof. I think the server time won't be of importance anymore.
