### ISSUE TITLE
installLisk.sh upgrade

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#250]
**installLisk.sh** upgrade indirectly caused blockchain fork:3 i guess. Since i have did upgrade before, **backup** directory has been already created and i couldn't upgrade again due error with mkdir, there should be check if **backup** directory already exists to remove it or not.
Also i have noticed that i can upgrade the same version and it will always remove current lisk and install again (the same version) there should be check if current version matches or not latest released.

Not sure if this is correct repo, but couldn't find repository with this script.

**Comment by karmacoma** [comment]
Provisioning scripts are maintained here: https://github.com/LiskHQ/lisk-build.

Please report the issue there, and we will look to resolve it. Thank you 👍
