### ISSUE TITLE
Syncing node - progress indicator is missing

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#251]
While node is syncing there should be progress indicator with current local height and current network height, maybe also some fancy progress bar.

**Comment by karmacoma** [comment]
There is a percentage progress indicator in the user-interface, but I agree we should yield more information about sync progress.

Please report this issue here: https://github.com/LiskHQ/lisk-ui.

**Comment by karek314** [comment]
I think it still relates to some background changes, since there are no endpoint for this. I have found that it returns only current local height while it should return current local height, last seen network height and possibly some other statistics.
