### ISSUE TITLE
[Testnet 0.3.2a] Cannot read property 'senderPublicKey' of undefined

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk#253]
Lisk crash after the following:

[FTL] 2016-08-07 06:09:31 | System error - {"message":"Cannot read property 'senderPublicKey' of undefined","stack":"TypeError: Cannot read property 'senderPublicKey' of undefined\n    at /lisk-test/app.js:8:22913\n    at lisk-test/node_modules/async/lib/async.js:181:20\n    at iterate /lisk-test/node_modules/async/lib/async.js:262:13)\n    at Immediate.<anonymous> (/lisk-test/node_modules/async/lib/async.js:274:29)\n    at Immediate._onImmediate (/lisk-test/node_modules/async/lib/async.js:44:16)\n    at processImmediate [as _immediateCallback](timers.js:367:17)"}

first seen on 0.3.2a

**Comment by Isabello** [comment]
Is this still an issue on 0.4.x @slasheks ?

**Comment by slasheks** [comment]
just encountered the issue in 0.5.0b
```
[dbg] 2016-11-05 19:46:16 | Applying unconfirmed transaction - 9082231970708809096
/opt/lisk/lisk-0.5.0b-Linux-x86_64/node_modules/js-nacl/lib/nacl_factory.js:27
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
                                                                    ^
TypeError: Cannot read property 'senderPublicKey' of undefined
    at /opt/lisk/lisk-0.5.0b-Linux-x86_64/app.js:7:25745
    at /opt/lisk/lisk-0.5.0b-Linux-x86_64/node_modules/async/dist/async.js:3047:20
    at replenish (/opt/lisk/lisk-0.5.0b-Linux-x86_64/node_modules/async/dist/async.js:884:21)
    at Immediate.iterateeCallback (/opt/lisk/lisk-0.5.0b-Linux-x86_64/node_modules/async/dist/async.js:869:21)
    at Immediate.<anonymous> (/opt/lisk/lisk-0.5.0b-Linux-x86_64/node_modules/async/dist/async.js:847:20)
    at Immediate.immediate._onImmediate (timers.js:418:16)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
error: Forever detected script exited with code: 7
```

**Comment by karmacoma** [comment]
@slasheks @Isabello: We need to reproduce this in development i.e. from source. The binary release stack trace does not provide the right information to debug this issue.
