### ISSUE TITLE
Transactions made are not always included in the 'block/change' socket event on Testnet

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk#2533]
### Steps to reproduce

**Reproducible not every single time**
1. Connect to socket.io of Lisk Core on Testnet, e.g. `wss://testnet.lisk.io/socket.io/?EIO=3&transport=websocket`
1. Send a transaction from account A to account B
1. Check the 'transations/change' socket event is there
1. Wait for the next 'blocks/change' socket event

### Actual result
Block hasn't your transaction
In fact, tx was successfully confirmed
Hub relies on contents of the block to update account's current balance.
Therefore some users are complaining
![image](https://user-images.githubusercontent.com/6704159/48056300-c4156e80-e1b1-11e8-89d8-b378892838f1.png)

### Expected result
Transactions should always be included in the propagated 'blocks/change' event

### Version
1.2-rc.1

Look there is no totalAmount

![image](https://user-images.githubusercontent.com/6704159/48055902-f4104200-e1b0-11e8-83de-9e3f266f8f3d.png)

**Comment by 4miners** [comment]
@Efefefef Thanks for the report. This issue is related to https://github.com/LiskHQ/lisk/issues/2403. Currently the `blocks/change` event is not always emited, in your screenshot there is a missing one between 10:33:36 and 10:33:50. It will be automatically fixed once #2403 is fixed.
