### ISSUE TITLE
Missing ssl dir key and cert in config.json after upgrade to 1.2.0

### ISSUE THREAD

**Issue by Splatters-lsk** [LiskHQ/lisk#2539]
### Expected behavior
After the upgrade the content of the config.json should be migrated in total to the new version of the core 

**Before upgrade**
![ssl before](https://user-images.githubusercontent.com/44343272/48224569-74de6200-e39a-11e8-8bc5-eb8928a8f78b.JPG)

### Actual behavior
after upgrade my config.json lost the dir for the ssl cert and key

**After upgrade**
![ssl after](https://user-images.githubusercontent.com/44343272/48224579-7d369d00-e39a-11e8-84b2-c14a8ff984d0.jpg)

### Steps to reproduce
upgrade the node and check in the config.json if you still have the cert dir .

I had to put manually those dir to allow my nodes to sync and forge again. 

Same problem with 2 of my nodes upgraded.

### Which version(s) does this affect? (Environment, OS, etc...)
core 1.2.0

**Comment by karek314** [comment]
This time my config was spared from destruction, did you upgraded your InstallLisk script?

**Comment by Splatters-lsk** [comment]
I didn't upgrade to the new releases of today yet. But yes I alway download the new installLisk script

**Comment by karek314** [comment]
I had some issues in past when I was missing **jq** package installed.

**Comment by Splatters-lsk** [comment]
I dunno, never had this problem before. Now I'll upgrade to 1.2.1 and I'll see what will happen

**Comment by Splatters-lsk** [comment]
It hasn't happen with upgrade on 1.2.1. I close it.
