### ISSUE TITLE
Make use of sinon.test to avoid cascading failures

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2548]
### Expected behavior

When using spies, stubs or mocks, function should be wrapped in `sinon.test`. This allows to use Sinon's automatic clean-up functionality. Without it, if tests fail before the test-doubles are cleaned up, it can cause a cascading failure - more test failures resulting from the initial failure. Cascading failures can easily mask the real source of the problem, so we want to avoid them where possible.

```
it('should call save once', sinon.test(function() {
  var save = this.spy(Database, 'save');

  setupNewUser({ name: 'test' }, function() { });

  sinon.assert.calledOnce(save);
}));
```

### Actual behavior

```
it('should call save once', function() {
  var save = sinon.spy(Database, 'save');

  setupNewUser({ name: 'test' }, function() { });

  save.restore();
  sinon.assert.calledOnce(save);
});
```

### Which version(s) does this affect? (Environment, OS, etc...)
`1.0+`

**Comment by yatki** [comment]
sinon-test is a separate package now. It's not supported in sinon package. I don't see a value in using this at the moment. 

So I'm closing the issue.
