### ISSUE TITLE
Verify genesis block matches connected database on startup

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#255]
When creating new local testnets, switching genesis blocks during development, a big ugly error is raised if the genesis block defined in `genesisBlock.json` does not match that of the connected database. We should therefore add the necessary checks and handle the error more gracefully.

**Comment by karmacoma** [comment]
Fixing as part of mainchain stablisation milestone to protect against database corruptions, which might result from launching client with a different genesis to that in database.

**Comment by karmacoma** [comment]
@SherlockStd It appears you have changed the genesis block (maybe for dapp development using lisk cli). If so you will need to drop and recreate the `lisk_test` database, as currently it does not match.

**Comment by SherlockStd** [comment]
@karmacoma thanks but how can I rebuilt the db ? Do I need to rebuilt it manually ? :fearful:

**Comment by SherlockStd** [comment]
@karmacoma I found this file I search a way to generate the db and insert the genesis block is that it ? https://github.com/LiskHQ/lisk-dapps-sdk/blob/development/blockchain.json

**Comment by SherlockStd** [comment]
https://lisk.io/documentation?i=lisk-dapps-docs/Sidechain

**Comment by SherlockStd** [comment]
Got it we need to empty the database like this (cd lisk directory, lisk-main or lisk-test by default) : 

Run postregsql command prompt :
```bash
pgsql/bin/psql lisk_test # or lisk_main if on mainnet
```

Truncate all tables : 

```sql
TRUNCATE TABLE blocks CASCADE;
TRUNCATE TABLE dapps CASCADE;
TRUNCATE TABLE delegates CASCADE;
TRUNCATE TABLE forks_stat CASCADE;
TRUNCATE TABLE intransfer CASCADE;
TRUNCATE TABLE mem_accounts CASCADE;
TRUNCATE TABLE mem_accounts2delegates CASCADE;
TRUNCATE TABLE mem_accounts2multisignatures CASCADE;
TRUNCATE TABLE mem_accounts2u_delegates CASCADE;
TRUNCATE TABLE mem_accounts2u_multisignatures CASCADE;
TRUNCATE TABLE mem_round CASCADE;
TRUNCATE TABLE migrations CASCADE;
TRUNCATE TABLE multisignatures CASCADE;
TRUNCATE TABLE outtransfer CASCADE;
TRUNCATE TABLE peers CASCADE;
TRUNCATE TABLE peers_dapp CASCADE;
TRUNCATE TABLE signatures CASCADE;
TRUNCATE TABLE trs CASCADE;
TRUNCATE TABLE votes CASCADE;
```

Relaunch lisk, it will populate all tables : 
```bash
bash lisk.sh start
```

**Comment by SherlockStd** [comment]
I'm making a pull request on tutorial :)

**Comment by karmacoma** [comment]
@SherlockStd Yes these commands are fine. I think issue is related to https://github.com/LiskHQ/lisk-cli/issues/6.

**Comment by SherlockStd** [comment]
Yes
