### ISSUE TITLE
Use UNLOGGED Tables for huge performance gain during snapshotting

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2556]
### Advantage 

In PostgreSQL there is a feature of `UNLOGGED` [tables](https://www.postgresql.org/docs/11/sql-createtable.html). These tables can result into huge  performance gains. Some of the benchmarks state that it can result into **15x performance** gain on write queries. https://www.depesz.com/2011/01/03/waiting-for-9-1-unlogged-tables/

More details about usage of UNLOGGED tables can also be found on the link 
https://www.compose.com/articles/faster-performance-with-unlogged-tables-in-postgresql/

### Caveat 
Such `UNLOGGED` tables are low in resilience, means a system crash can cause in non-persistence data state. 

### Usage 

Our explicit use case for snapshotting exactly matches to the limitation. So we can use that limitation in our advantage. If our snapshotting fails in between we always rebuild the accounts data, so using `UNLOGGED` accounts table will exactly match for us. We can sacrifice a small resilience to gain 15x performance gain. 

https://blog.4xxi.com/sacrificing-resilience-for-performance-with-postgresql-wal-unlogged-tables-d8db7253160b

The implementation can follow these guidelines;

1. On start of the snapshot process, convert accounts tables to `UNLOGGED`.
2. Do the normal snapshotting process 
3. Once snapshotting process complete, convert tables back to normal tables. 
4. While node start in normal mode, check if tables are still `UNLOGGED` which leads to fact that last snapshotting process was unsuccessful. 
5. In that case prompt the user about state of system and ask him to run the snapshot again or rebuild from snapshot. 
6. Rebuild form snapshot step is already part of our business logic. 

I believe with this small change we can gain 15x performance gain for snapshotting. I would not recommend it for current syncing process. 

With this solution we can resolve https://github.com/LiskHQ/lisk/issues/1843

**Comment by pablitovicente** [comment]
Command: `time node app.js -n testnet -s 200`

LOGGED NO FKs 	| LOGGED FKs 		| UNLOGGED NO FKs	| UNLOGGED FKs
real	6m8.201s	| real	6m6.320s	| real	5m34.037s	| real	5m47.180s
user	2m21.330s	| user	2m23.355s	| user	2m21.527s	| user	2m24.381s
sys	0m11.713s	| sys	0m11.785s	| sys	0m11.600s	| sys	0m11.870s

Notes: FKs refer to the FK in mem_accounts2u_delegates and mem_accounts2u_multisignatures

**Comment by pablitovicente** [comment]
After more tests (even with simple scripts inserting only data and no performing other operations) there is not a significant improvement for our use case.

**Comment by pablitovicente** [comment]
After running several tests I was not able to get huge performance improvements for our use case. we're not constantly hitting the same table or groups the tables fast enough for this to make a huge difference and even when simulating such scenario -inserting 200K rows in the same table- I was not able to get huge performance gains by using unlogged tables.
