### ISSUE TITLE
"approval" correct in /api/delegates/get, but wrong in delegateMonitor

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#256]
Tested with delegate 'isabella':
The following calls are used to verify the "approval" (they should obviously be all the same)

Api (probably wrong calculation)
https://testnet.lisk.io/api/delegates/get?username=isabella -> 3.06

DelegateMonitor shows this:
https://testnet-explorer.lisk.io/delegateMonitor -> 3.13

Calculating the voting power manually from all voters:
https://testnet.lisk.io/api/delegates/voters?publicKey=eaa049295d96618c51eb30deffe7fc2cc8bfc13190cb97f3b513dd060b000a46 -> 3.131736

**Comment by Gr33nDrag0n69** [comment]
Just making a cross-reference to a bug filled in lisk-explorer possibly related.
https://github.com/LiskHQ/lisk-explorer/issues/11

**Comment by simonmorgenthaler** [comment]
the api call /delegates/get makes the correct calculation (delegateMonitor is wrong) including the additionally forged Lisk. On the testnet, right now around 2.2 mio LSK are created additionally through forging. If you calculate the voting power for isabella  based on 100 mio lisk you get 3.13% (which is wrong), if you calculate based on 102.2 mio, you get 3.06% (which is correct)

**Comment by karmacoma** [comment]
Closing the issue here, as it appears a problem which resides in lisk-explorer. We will fix there instead: https://github.com/LiskHQ/lisk-explorer/issues/11.
