### ISSUE TITLE
Improve verification process performance when synchronising

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2564]
### Expected behavior

Synchronisation leverages the system to catch the best height as soon as possible.

### Actual behavior

Synchronisation is using 25% or less of CPU. One of the bottlenecks is the verification process. The functions below executed synchronously instead of using background threads for instance, await for completion and then proceed with result. Or even better, spawn threads with batched sets of blocks.

https://github.com/LiskHQ/lisk/blob/8f7de3963eaa48a6e2d8b081de37921b85911a53/modules/blocks/verify.js#L318
https://github.com/LiskHQ/lisk/blob/8f7de3963eaa48a6e2d8b081de37921b85911a53/modules/blocks/verify.js#L507

Extracted from: https://github.com/LiskHQ/lisk/issues/2384

### Which version(s) does this affect? (Environment, OS, etc...)

`1+`

**Comment by MaciejBaj** [comment]
The verification process will be improved significantly after the [milestone](https://github.com/LiskHQ/lisk-elements/milestone/12) on Lisk Elements is completed and the modules utilized in Lisk Core.
