### ISSUE TITLE
Add snapshot argument that defaults to highest possible round

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#258]
When performing a snapshot, if the given round is higher than which is stored on disk, the highest possible round is chosen. However, it would be more reliable if the administrator can indicate the snapshot always defaults to the highest possible round, e.g. `--snapshot highest`.

**Comment by Gr33nDrag0n69** [comment]
I think this should be re-checked.

See https://github.com/LiskHQ/lisk-build/issues/39
