### ISSUE TITLE
Set build constants in Dockerfile

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2584]
### Expected behavior
API node/constants should have values for `build` and `commit` for docker nodes.
### Actual behavior
API node/constants responds with empty values for `build` and `commit` http://167.99.47.154:7000/api/node/constants
```
{
"meta": {},
"data": {
"build": "",
"commit": "",
"epoch": "2016-05-24T17:00:00.000Z",
"fees": {
"send": "10000000",
"vote": "100000000",
"secondSignature": "500000000",
"delegate": "2500000000",
"multisignature": "500000000",
"dappRegistration": "2500000000",
"dappWithdrawal": "10000000",
"dappDeposit": "10000000"
},
"nethash": "da3ed6a45429278bac2666961289ca17ad86595d33b31037615d4b8e8f158bba",
"nonce": "5jkWS7yG9W6FANte",
"milestone": "2",
"reward": "300000000",
"supply": "12949137100000000",
"version": "1.3.0-rc.0"
},
"links": {}
}
```
### Steps to reproduce
1) Deploy docker container for any lisk node version
2) Make API call to "/api/node/constants"
3) Obsereve empty values for `build` and `commit` 
### Which version(s) does this affect? (Environment, OS, etc...)
`>=v1.3.0`, Docker

**Comment by fchavant** [comment]
This cannot be truly solved without fixing https://github.com/LiskHQ/lisk/issues/2588
