### ISSUE TITLE
Update Node.js to version 8.14.0

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#2601]
### Expected behavior
We should update to Node.js version 8.14.0 - the newest security update:
https://nodejs.org/en/blog/release/v8.14.0.

NodeJS v8.14.0 is the required version for the core that includes fixes for two DoS attacks.

### Actual behavior
We are using version 8.13.0

### Which version(s) does this affect? (Environment, OS, etc...)
Core 1.4

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/commit/0370ec25d5cc01ffca59374b079827c7e6134fa8.
