### ISSUE TITLE
Remove 'version' from config.json, put the Lisk-version in the code

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#261]
Imho it doesn't make sense to have the Lisk-version configurable in the config.json. It should be fix in the code. This way we can be sure that the shown versions are the correct ones. Now we can't be sure, because the delegate can put whatever he want's in the config file.

**Comment by fix** [comment]
Well since it is open-source javascript code, everybody can change the version, wherever it is.

There is an alternative ticket whose purpose is to check the codebase against some "officialy" published checksum that would prevent from attacks.

see #53

Closing this issue in favor of the latter
