### ISSUE TITLE
lisk-core-network tests create log files under wrong path

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#2633]
### Expected behavior
Log file is written to a predefined location so that is can be archived (and shown in the Jenkins UI for troubleshooting)

### Actual behavior
Log file is created under `$PWD/$PWD/test/network/utils/networkTestsLogger.log` e.g.:
`/home/lisk/workspace/lisk-core-network_PR-2597/home/lisk/workspace/lisk-core-network_PR-2597/test/network/utils/networkTestsLogger.logs` (notice the duplicate `home/lisk/workspace/lisk-core-network_PR-2597`)

### Steps to reproduce
Run `npm test -- mocha:extensive` like `Jenkinsfile.network` does.

### Which version(s) does this affect? (Environment, OS, etc...)
`lisk-core-networks` test in Jenkins

**Comment by MaciejBaj** [comment]
Closed by #d815a7f.
