### ISSUE TITLE
Sends result in error: "Account not found"

### ISSUE THREAD

**Issue by Crypto2** [LiskHQ/lisk#264]
This is an issue we are running in to from time to time, trying to send coins results in the error "Account not found". We checked the account balance just before sending so the account definitely exists.

**Comment by fix** [comment]
How did you get this error: using the LISK-UI or other clients. Can you be more detailed on your settings?

The reasons for this error can be:
- typo in address
- connected node not in sync
- wrong passphrase

**Comment by Crypto2** [comment]
This is via the API, https://lisk.io/documentation?i=lisk-docs/APIReference#send-transaction
It works most of the time, just not for some addresses for some reason. We aren't using a second secret or anything special.

**Comment by karmacoma** [comment]
@Crypto2 Using the current implementation, the simplest solution right now is to call: `POST /api/accounts/open` for the sender's account, before `PUT /api/transactions`. This sets the public key on the memory table of the local node if it does not exist. Not perfect I know, but it should work reliably.

You can also use https://github.com/LiskHQ/lisk-js, and post locally signed transactions to `POST /peer/transactions`. This is the most secure and reliable method for sending transactions.

**Comment by karmacoma** [comment]
@Crypto2 I will be resolving this issue soon, to avoid the need to call `/api/accounts/open`. For now though, the above works for me.
