### ISSUE TITLE
Upgrade Node.js version from 8.14.0 to 10.14.1

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2647]
### Expected behavior
We should upgrade Node.js to version `v10.14.1(LTS)` since the current major version enters into maintenance next January 2019.

### Actual behavior
Lisk Core runs on Node `v8.14.0(LTS)`

TODO list:
- [x] Update Dockerfile
- [x] Update `package.json`
- [x] Update readme
- [x] Update `.npmrc`
- [x] Replace WSEngine by default `ws`

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Core  `v1.5`

**Comment by shuse2** [comment]
@diego-G can you describe whats the main difference from v8 to v10?
What's the breaking change between them?
