### ISSUE TITLE
Add possibility to combine api parameters with AND instead of only OR

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#265]
The api calls with multiple parameters (for example /api/transactions) state in the documentation "All parameters join by 'OR'". Wouldn't it make more sense to join them by AND? This would allow to use type=0&senderId=xxx to get only the send transactions of a specific account. By joining the parameters with OR, this is not possible.
Even better would be if you could decide from case to case, by adding an additional parameter "joining=and|or".

**Comment by simonmorgenthaler** [comment]
Such changes could potentially break a lot of 3rd-party-tools/-scripts/-developments. You should plan, implement and communicate such changes pretty carefully

**Comment by karmacoma** [comment]
@simonmorgenthaler Yes for sure it would be a breaking change, but if well documented a welcome one. It won't be a top priority, but we will do.
