### ISSUE TITLE
Fix misuse of sort method while updating delegates list cache

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#2652]
### Expected behavior
I expect `updateDelegateListCache` to keep the last two rounds list when the cache already have two lists and another one is given.

### Actual behavior
By default `sort()` method sorts values as strings what can cause the `updateDelegateListCache` to not behaviour as expected.

### Steps to reproduce
Run `[9, 10, 11].sort().slice(-2)`
I expected to get [10, 11] but I get [ 11, 9 ] instead.

To fix it we have to use:
```
.sort((a, b) => a - b)
```

### Which version(s) does this affect? (Environment, OS, etc...)
1.4

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/pull/2654.
