### ISSUE TITLE
Refactor data persistence layer to improve quality and usability

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2669]
Need to improve/refactor these points; 

- Remove any `Promise.resolve` from `then` blocks, and instead return value. 
- Always use `async` methods in tests, and only use `done` syntax when explicitly required. 
- Add usage of `Symbol` to conventions list
- Remove schema file added mistakenly 
- Replace `fieldSet` convention by boolean flag `extended` to make it easy to use 
- Update the sql file names according to above point for extended fields 
- Reuse the common logic for `get` and `getOne` 
- Rename `overrideDefaultOptions` to `extendDefaultOptions`
- Use Object spread instead of `Object.assign`
- Refactor `pgp` specific result specifiers to optimize the implementation
- Export all methods as `async` from entities which return Promise
- Initialize the storage in app.js add keep it under scope

**Comment by lsilvs** [comment]
Suggestion for `Reuse the common logic for get and getOne`

Add `expectedResult = 'any'` to `defaultOptions`

Then:
```
get(filters = {}, options = {}, tx) {
	this.validateFilters(filters);
	this.validateOptions(options);

	const mergedFilters = this.mergeFilters(filters);
	const parsedFilters = this.parseFilters(mergedFilters);
	const parsedOptions = _.defaults(
		{},
		_.pick(options, ['limit', 'offset', 'fieldSet']),
		_.pick(this.defaultOptions, ['limit', 'offset', 'fieldSet'])
	);

	const params = Object.assign(
		{},
		{ limit: parsedOptions.limit, offset: parsedOptions.offset },
		{ parsedFilters }
	);

	return this.adapter.executeFile(
		{
			[this.FIELD_SET_SIMPLE]: this.SQLs.selectSimple,
		}[parsedOptions.fieldSet],
		params,
		{ expectedResult: options.expectedResult },
		tx
	);
}

getOne(filters, options = {}, tx) {
	options.expectedResult = 'one';
	return this.get(filters, options, tx);
}
```
