### ISSUE TITLE
Wallets system error (on two wallets at the same time)

### ISSUE THREAD

**Issue by zachmian** [LiskHQ/lisk#267]
I had some problems with my lisk wallets. I have two wallets which are base of my exchange service.
Today at 10 am both of wallets have stopped working. 
Log from one of them: http://pastebin.com/RecK5T9L

**Comment by zachmian** [comment]
Same problem occurred for me today on both wallets.
Log: http://pastebin.com/i0kJJgUR

**Comment by Isabello** [comment]
There was a hotfix update that resolves the issue you are having. Please update to 0.3.3 and rebuild using the current validated snapshot.
