### ISSUE TITLE
[Error: ERROR:  could not read block 8 in file "base/57640/58259

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#268]
```
lisk_user@develop-desktop:~/lisk-main$ bash lisk.sh logs
[log] 2016-09-04 08:00:48 | error - query: BEGIN; UPDATE "peers" SET "state" = 1, "clock" = NULL WHERE "state" != 0; COMMIT;
[FTL] 2016-09-04 08:00:48 | { [Error: ERROR:  could not read block 8 in file "base/57640/58259": read only 0 of 8192 bytes
]
  severity: 'ERROR',
  sqlState: 'XX001',
  messagePrimary: 'could not read block 8 in file "base/57640/58259": read only 0 of 8192 bytes',
  sourceFile: 'md.c',
  sourceLine: '728',
  sourceFunction: 'mdread' }
[log] 2016-09-04 08:00:51 | GET /api/loader/status/sync from 127.0.0.1

```
After upgrade to 0.3.3

**Comment by karek314** [comment]
Seems like old installLisk.sh function "upgrade" actually did not upgrade to 0.3.3 but just reinstalled. after downloading new installLisk.sh upgrade was successful and node started correctly.

**Comment by karmacoma** [comment]
@karek314 I am assuming the first issue is now resolved by using a newer installLisk.sh. The second issue could be as a result of inconsistent memory tables. This issue should be improved when we resolve #213 in the next release cycle.
