### ISSUE TITLE
Error: listen EADDRINUSE - after dapp crashed

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#27]
Domain master { message: 'listen EADDRINUSE',
  stack: 'Error: listen EADDRINUSE\n    at exports._errnoException (util.js:746:11)\n    at Server._listen2 (net.js:1158:14)\n    at listen (net.js:1184:10)\n    at net.js:1282:9\n    at dns.js:85:18\n    at process._tickDomainCallback (node.js:381:11)\n    at Function.Module.runMain (module.js:503:11)\n    at startup (node.js:129:16)\n    at node.js:814:3' }

It seems like sqlite is still running, after forcing sqlite to quit. Node starts correctly.

**Comment by fix** [comment]
This is because the dapp crash but the node processus is still running and block the port. Maybe we should be sure the app.id is still not running before starting again.

**Comment by fix** [comment]
I close it since not applicable anymore
