### ISSUE TITLE
Prevent tx from being sent from 6566229458323231555L

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#270]
Funds are lost https://explorer.lisk.io/tx/4090216588756030897

**Comment by karek314** [comment]
Could you please include more details what happened ? And why you propose hardcoding possibility to prevent sending funds to this address ? If anyone wants burn their money, it should be possible.

**Comment by TheGoldenEye** [comment]
This is the genesis address

**Comment by Isabello** [comment]
I agree with the other posts. We should allow burning funds to this address.

**Comment by karmacoma** [comment]
I agree with leaving this as a burn address. If anything we should hard code it so funds can never be moved out again.

**Comment by karmacoma** [comment]
We can allow funds to be sent to this address, and ensure refunds can never leave again after genesis.
