### ISSUE TITLE
Database gets exhausted when enabling forging on several delegates 

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2747]
### Expected behavior

Database handles several calls like for example enabling forging on 10 delegates.

### Actual behavior
Database gets exhausted, throws errors and restarts when enabling several delegates at once.

For reference: [db_error.log](https://github.com/LiskHQ/lisk/files/2763726/db_error.log)

### Steps to reproduce

`npm test -- mocha:default:network`

### Which version(s) does this affect? (Environment, OS, etc...)
[feature/extensible-data-persistence-model](https://github.com/LiskHQ/lisk/tree/feature/extensible-data-persistence-model)

**Comment by pablitovicente** [comment]
@diego-G @MaciejBaj I can confirm this is fixed by https://github.com/LiskHQ/lisk/pull/2753 . Can you guys test and let me know so I can close this one?

**Comment by MaciejBaj** [comment]
Thanks, @pablitovicente. Let's close it.
