### ISSUE TITLE
Split binaries and database - moving lisk caused issue

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#275]
After successfully moved entire lisk to another storage. Each log in to user associated to Lisk i see error
`-bash: /home/lisk_user/lisk-main/env.sh: No such file or directory`

as i have mentioned before it would be lovely to easily split executable with data, as i prefer move data directories to other drive.

**Comment by TheGoldenEye** [comment]
The env.sh was not found, because you removed the ~/lisk-main folder.
Please check your ~/.bash_profile or similar, there you should find the call

**Comment by karek314** [comment]
Yes i can read that, i have fixed that before, im not asking for help but reporting this as issue strictly related to sticking data and binaries, it would be great to set data directory in config.

**Comment by Isabello** [comment]
This is a lisk build issue, not a core issue.
