### ISSUE TITLE
Restructure the file directories for components, modules and framework files

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2762]
### Expected behavior
The top level directory structure should be 
```
/framework
    src/
        /components
            /storage
            /cache
            /logger
            /system
        /modules
            /chain
            /http_api
        controller.js
        bus.js
        application.js
/src
    /config
    index.js
/docker
/build
/test
    framework/
package.json
```
Same structure should be followed in the `test` directory as well. Later when decided we will make each sub directory under `components`, `modules` and `framework` as seperate `npm package` choose to convert it to a mono repo or move them to seperate repositories. 

### Actual behavior
Currently files directories are distributed among `modules`, `logic`, `helpers` directories, this structure is dedicated for `chain` module. 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6`

**Comment by nazarhussain** [comment]
After discussion we decided go with one package.json file and above update file structure for `1.6` release.

**Comment by shuse2** [comment]
if `/src` is inside of framework then `test` should be also in the same layer, too?
