### ISSUE TITLE
Bug: Snapshot round parsing error in v0.4.0a on testnet

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#277]
For testing, I try to use a small round number for snapshot. i.e. 10
Look like there is parsing error in app.js that start the snapshot on highest round anyway whatever the round int value i use...

**Comment by karmacoma** [comment]
@Gr33nDrag0n69 

For me it is working on 0.4.0b:

```
[inf] 2016-09-19 14:18:52 | Lisk started: 0.0.0.0:7000
[inf] 2016-09-19 14:18:54 | Modules ready and launched
[inf] 2016-09-19 14:18:54 | Blocks 2794
[inf] 2016-09-19 14:18:54 | Snapshot mode enabled
[inf] 2016-09-19 14:18:54 | Snapshotting to end of round: 10
[WRN] 2016-09-19 14:18:54 | Blocks verification enabled
[WRN] 2016-09-19 14:18:54 | Recreating memory tables
NOTICE:  relation "mem_accounts" already exists, skipping
NOTICE:  relation "mem_accounts_balance" already exists, skipping
NOTICE:  relation "mem_round" already exists, skipping
NOTICE:  relation "mem_accounts2delegates" already exists, skipping
NOTICE:  relation "mem_accounts2u_delegates" already exists, skipping
NOTICE:  relation "mem_accounts2multisignatures" already exists, skipping
NOTICE:  relation "mem_accounts2u_multisignatures" already exists, skipping
[inf] 2016-09-19 14:18:54 | Rebuilding blockchain, current block height: 0
[inf] 2016-09-19 14:19:14 | Snapshot finished
[inf] 2016-09-19 14:19:14 | Cleaning up...
[inf] 2016-09-19 14:19:14 | Cleaned up successfully
```

Can you also confirm?

**Comment by Gr33nDrag0n69** [comment]
I didn't had time yesterday. I will test it tonight and post back with the results. ( in about 8 hours ... )

**Comment by Gr33nDrag0n69** [comment]
In fact, I'll re-test mostly everything snapshot related.

**Comment by Gr33nDrag0n69** [comment]
# Test 1

`bash /opt/lisk/client/lisk_snapshot.sh -t /opt/lisk/client/snapshot.json -s /opt/lisk/client/config.json -b /opt/lisk/backup -d 3 -r 10`

* -r 10 didn't worked, it used highest round
* snapshot completed succesfully
* snapshot was 4 times slower with v0.4.0b over v0.3.3

# Test 2

```
bash lisk.sh snapshot -s 10 -c snapshot.json
```

* -s 10 worked, so lisk issue can be closed. I will open a new issue on lisk-build for lisk_snapshot.sh
