### ISSUE TITLE
Update the configuration files to group all configuration of HTTP API module

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#2773]
### Expected behavior
All the configuration for any module should be grouped as single object under `modules` key in the config file. 

Also need to write the config migration steps to reflect the change. 

### Actual behavior
Currently some values are spliced apart as `httpPort`, `address`, `api` and `trustProxy`

**Comment by MaciejBaj** [comment]
Will be done as part of https://github.com/LiskHQ/lisk/issues/2577.
