### ISSUE TITLE
"undefined is not a function" after last update

### ISSUE THREAD

**Issue by zachmian** [LiskHQ/lisk#278]
2 days ago I installed the lastest update.
Couple hours later my wallet stopped working and gave me that log:
# lisk.log

[inf] 2016-09-19 15:28:59 | Rebuilding blockchain, current block height:
295000
[inf] 2016-09-19 15:33:53 | Rebuilding blockchain, current block height:
300000
[inf] 2016-09-19 15:49:31 | Rebuilding blockchain, current block height:
305000
[ERR] 2016-09-19 15:49:33 | [object Object]
# lisk_main.app.log

[inf] 2016-09-19 15:49:31 | Rebuilding blockchain, current block height:
305000
[ERR] 2016-09-19 15:49:33 | { message: 'Account has no LISK:
13664378840326092228',
  transaction:
   { id: '13664378840326092228',
     height: 305054,
     blockId: '16309756583564062898',
     type: 0,
     timestamp: 3234203,
     senderPublicKey:
'c54f24a34ec79112f03e38f67c1360d99e50878ac84d92354ace3a1fc6efd829',
     requesterPublicKey: null,
     senderId: '10717211890737506516L',
     recipientId: '13892601275403076526L',
     amount: 3085000000,
     fee: 10000000,
     signature:
'1cdb8c44358d9d7fc9b6a52f8f0ba3f7e3dd6ac59db4b3171ee20f72f832072754551d490c2c13317cfb373c28b0380122d42b4b31d05e7419495eb2b2815f0c',
     signSignature: null,
     signatures: [],
     confirmations: NaN,
     asset: {} },
  block:
   { id: '16309756583564062898',
     version: 0,
     timestamp: 3234210,
     height: 305054,
     previousBlock: '9798739111499546001',
     numberOfTransactions: 1,
     totalAmount: 3085000000,
     totalFee: 10000000,
     reward: 0,
     payloadLength: 117,
     payloadHash:
'c435008628a0a1bddf8d22968d31ab2cb6ef58e491763f873bc2330774337ce2',
     generatorPublicKey:
'2be0301710d1295f9afeba6c469f7447e6915e3e63fcbdd69c3fa54a50184803',
     generatorId: '11174765922843392359L',
     blockSignature:
'7059fe01d34de4281612f016faea505e07c14e85116de33b292f97c20cc8bc99d3faa5beff67a5afa8e07070d60c6c8e7d2e635ac386b7975cd9079cd548b50a',
     confirmations: NaN,
     totalForged: '10000000',
     transactions: [ [Object] ] } }
/home/crypto/lisk/lisk-main/node_modules/js-nacl/lib/nacl_factory.js:27
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw
ex}}));Mod
                                                                    ^
TypeError: undefined is not a function
    at /home/crypto/lisk/lisk-main/app.js:3:14877
    at /home/crypto/lisk/lisk-main/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous>
(/home/crypto/lisk/lisk-main/node_modules/async/lib/async.js:264:21)
    at Immediate.<anonymous>
(/home/crypto/lisk/lisk-main/node_modules/async/lib/async.js:44:16)
    at Immediate.immediate._onImmediate (timers.js:418:16)
    at processImmediate [as _immediateCallback](timers.js:367:17)
error: Forever detected script exited with code: 7

The error occures every time I try to run wallet.

**Comment by karmacoma** [comment]
@zachmian: Do you still have this problem? I have been unable to reproduce until now.
