### ISSUE TITLE
peer/transactions : Sending the same tx twice, gives me an error on the first request and success on subsequent requests.

### ISSUE THREAD

**Issue by ferni** [LiskHQ/lisk#279]
Using the peer/transactions api, as found here: https://github.com/LiskHQ/lisk-js#sending-transaction-on-the-server

Submitting this transaction: 
`{"type":0,"amount":444,"fee":10000000,"recipientId":"17408578967974500157L","timestamp":10289544,"asset":{},"senderPublicKey":"3fcb47511d80ad0cc8adbacd444ea747f59420fb8887672e859794f5e2b87325","signature":"06e0904ac5bc4a0ae488672da57c5b95dd44157b3ad8d27279492f819a344b9b4e41cafafeb9540cdb5b41ff890a440dcead4292486e6d5444443828a35f4d06","id":"13817920469495604420"}`

I get the error "Account has no lisk".

But if I send the exact same transaction immediately after, I get a success response. And all the subsequent requests with that transaction gives me a success response as well. However, looking at the lisk block explorer I see that no transaction took place.

**Comment by karmacoma** [comment]
@ferni Okay thank you for reporting. I'm working on a solution to this that will be included in the upcoming `0.4.0` release.
