### ISSUE TITLE
Security: "Add X-XSS-Protection Header"

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#280]
Using nginx, I tested
`add_header X-XSS-Protection "1; mode=block";`
on lisk and lisk-explorer

Results:
- break testnet-explorer but not web wallet on firefox
- doesn't break anything on chrome

So maybe it could be added in lisk safely for more security.

**Comment by 4miners** [comment]
That is only applicable to `lisk-ui`, and that component will be removed in `1.0.0`.
