### ISSUE TITLE
Review NewRelic after cache was extracted as a component

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#2801]
### Expected behavior

Core is able to send data to NewRelic. The dependency should be also updated to the latest version https://github.com/LiskHQ/lisk-newrelic/pull/8

### Actual behavior

https://github.com/LiskHQ/lisk/blob/4743ea9eb1f740db705715067ff60f4708441418/helpers/newrelic_lisk.js#L28

### Which version(s) does this affect? (Environment, OS, etc...)

`1.6`

**Comment by shuse2** [comment]
Closed by #3228
