### ISSUE TITLE
include in blockchain the apps icon/image

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#281]
The image elements in the application section of web wallet are hosted from http links that point outside the lisk ecosystem.

A mid-term improvement could be to add a standardized app icon/image format that could be encoded (like base64 data) and stored in the blockchain. The image in the client would be serve by the lisk node app directly

**Comment by Gr33nDrag0n69** [comment]
finally isaw that there is already 1 of the 4 app on testnet that is not http or https. the feature is already there ?

**Comment by MaxKK** [comment]
If there is no image specified this image is being used: https://login.lisk.io/images/dappIcon.png

The problem is, that the images people used are offline. Often they just typed in dead links like "http://df.jpg" to prevent checks which are in place.

I will check something. Thanks. :)

**Comment by MaxKK** [comment]
I will close the issue here, because it's an UI enhancement. Check this issue.

https://github.com/LiskHQ/lisk-ui/issues/78
