### ISSUE TITLE
Invalid API node status response

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2816]
### Expected behavior
API `node/status` should have valid response with `consensus` and the `transactions` details.
### Actual behavior
API `node/status` shows invalid `consensus` and the `transactions` section doesn't show any transaction related info like `confirmed`, `unconfirmed`, `unprocessed`, `unsigned`, `total`.

```
{
  "meta": {},
  "data": {
    "broadhash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "consensus": 2,
    "currentTime": 1549290218167,
    "secondsSinceEpoch": 85181018,
    "height": 7423963,
    "loaded": true,
    "networkHeight": 7423963,
    "syncing": false,
    "transactions": {
      "confirmed": null,
      "unconfirmed": 0,
      "unprocessed": 0,
      "unsigned": 0,
      "total": 0
    }
  },
  "links": {}
}
```
### Steps to reproduce
`http://104.248.197.221:7000/api/node/status`
### Which version(s) does this affect? (Environment, OS, etc...)
1.5.0

**Comment by limiaspasdaniel** [comment]
This issue seems to be fixed by [this PR](https://github.com/LiskHQ/lisk/pull/2796) which was initially ready for 1.6. Should we merge it against 1.5 instead @MaciejBaj?

**Comment by MaciejBaj** [comment]
Merged into development https://github.com/LiskHQ/lisk/commit/8d5c787fe16f9571d7baf707540e8fda61a31491
