### ISSUE TITLE
API Performance degrade

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2817]
### Expected behavior
API Performance should be tolerant`(100-600ms)`.
### Actual behavior
Following API Performance have been degraded
`GET dapps`
`POST signatures`
`GET voters`
`GET accounts`
### Steps to reproduce
https://rpm.newrelic.com/accounts/2081667/applications/130457745/transactions?tw%5Bend%5D=1549281180&tw%5Bstart%5D=1549259580
### Which version(s) does this affect? (Environment, OS, etc...)
1.5.0

**Comment by nazarhussain** [comment]
@ManuGowda NewRelic doest not hold the data for long, to better maintain out github history we should post the results from NewRelic directly to issue as well.

**Comment by MaciejBaj** [comment]
We will fix the API performance degradation by implementing the transactions dependent table refactor and performing the SQL queries on `trs.asset` field stored in JSON format. This refactor was initially scheduled to be done in Lisk Core v1.6, but as it fixes the performance degradation problem as well as refactors the DB structure, we decided to do it now, as part of Lisk Core v1.5 release.
