### ISSUE TITLE
Update Content-Security-Policy Header

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#282]
lisk web client already include the CSP header with the value of
`frame-ancestors 'none'`

Using nginx, firefox and chrome, I've created this more restrictive working value:

```
frame-ancestors 'none'; default-src 'self'; script-src 'self'; connect-src 'self' wss://* https://*.lisk.io; img-src http: https: data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com
```

**Comment by 4miners** [comment]
That is only applicable to `lisk-ui`, and that component will be removed in `1.0.0`.
