### ISSUE TITLE
Refactor verifying multi-signatures for transactions and use the new StateStore and transactions library

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#2825]
### Expected behavior
In the current implementation, multi signatures are verified by calling the `verifySignature` function.

### Actual behavior
In this issue, the verification of the multi signatures should be refactored and the application should use StateStore and verifySignature methods defined in the lisk-element transactions library.

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by pablitovicente** [comment]
Update processSignatureForMultisignatureAccountCreation() to use elements
