### ISSUE TITLE
Remove tables and columns related to unconfirmed state from the database

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#2827]
### Expected behavior
Transactions will be applied to the unconfirmed state in memory. Therefore, the unconfirmed tables and columns are not needed in the database and should be removed.
### Actual behavior
The transactions are applied to the unconfirmed state and the tables and columns for managing unconfirmed state exist in the database.
### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by shuse2** [comment]
Temporally create fake function to replace the usage of unconfirmed state handling.
