### ISSUE TITLE
Remove usages of applying transaction to unconfirmed state from the application

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#2828]
### Expected behavior
Applying transactions to the unconfirmed state in the database is a step which should be removed and replaced with applying transactions in memory using state store.
### Actual behavior
In lisk-core, the application calls applyUnconfirmed step for transactions in multiple places which is not required.

**Comment by pablitovicente** [comment]
This was re-applied in https://github.com/LiskHQ/lisk/pull/3144
