### ISSUE TITLE
[0.3.4 - main] - Interval longer than 10s

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#283]
In past 2 weeks i have noticed that some blocks are missed, since community forging is still disabled it remains unknown for me whats happening.

example here
<img width="465" alt="screen shot 2016-09-26 at 16 43 07" src="https://cloud.githubusercontent.com/assets/9548618/18838683/920b7442-8408-11e6-9491-59f4644177b3.png">

i haven't checked actual timestamps on those blocks, not sure if it's issue related to node backend or just timestamp. I have noticed that already couple times during past 2 weeks.

**Comment by karmacoma** [comment]
@karek314 It is likely because one or more nodes running individual delegates are being rebuilt due to a fork in the memory tables. Hence the reason why we have not enabled community forging yet. Once we complete the mainchain stablisation milestone, this problem will be much less.

**Comment by karek314** [comment]
Okay, im reporting since imo it is a little more often than before, noticeable more often.

**Comment by karmacoma** [comment]
@karek314 Thanks for reporting, we are working relentlessly to stabilize the client. Please check out the latest `0.4.0d` release candidate on the testnet, where much progress has been made.
