### ISSUE TITLE
Move TOP=true param. to config.json

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#285]
In order to activate this functionality on the lisk client. The parameter must be pass to nodejs from command line. It would be great if this parameter could be moved to the config.json file with a false value by default. It would prevent having to modify lisk.sh every time I update to enable this functionality for lisk-explorer. (Or any other 3rd party apps wanting to access this functionality.)

**Comment by Isabello** [comment]
Can you provide some detail about this flag and what it does?

**Comment by Gr33nDrag0n69** [comment]
In order for this page of lisk-explorer to work as expected, I need to do the following modification in lisk.sh each upgrade. I don't wan't to use a sed replace for it since I feel that this particulatr line starting lisk app.js can be modified anytime. Using a jq command would make it simpler and cleaner.

`https://testnet-explorer.lisknode.io/topAccounts`

```
vi lisk.sh
#--------------------------------------------------------------------
# In start_lisk() function, replace
forever start -u lisk -a -l $LOG_FILE --pidFile $PID_FILE -m 1 app.js -c $LISK_CONFIG &> /dev/null
# By
TOP=true forever start -u lisk -a -l $LOG_FILE --pidFile $PID_FILE -m 1 app.js -c $LISK_CONFIG &> /dev/null
#--------------------------------------------------------------------
```

**Comment by karmacoma** [comment]
@Gr33nDrag0n69: Thanks for your suggestion. Yes we will implement. I agree it would better to enable / disable this option within `config.json`, rather than as an environment variable.

**Comment by Gr33nDrag0n69** [comment]
@karmacoma thanxs greatly appreciated. It's the only option I know that can only be enabled from env. var. I don't know if there is others options but maybe check for that too while being at it. Moving all of them at once would probably save some time later.

**Comment by karek314** [comment]
Duplicated. I have already reported that one before
https://github.com/LiskHQ/lisk/issues/234

But there is flag - Won't fix.

**Comment by karmacoma** [comment]
@karek314 Okay this issue was closed, and should not have been. We will fix here now. Thanks 👍

**Comment by Isabello** [comment]
I will resolve this shortly.
