### ISSUE TITLE
API Accounts returns results for offset greater than the number for accounts exists

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2855]
### Expected behavior
API Accounts should not return results for offset greater than the number of accounts exists.
### Actual behavior
API Accounts returns results for offset greater than the number for accounts exists.
This behavior is not reproducible consistently, however, it was observed and the suspicious is on cache layer. 
### Steps to reproduce
Query accounts with offset more than accounts exist.
https://node.lisk.io/api/accounts?offset=445145

**Comment by limiaspasdaniel** [comment]
@ManuGowda double and triple checked this on 1.6 and current `development` branch and the issue seems to be fixed. I will close this issue
