### ISSUE TITLE
Use transactions elements for validating new multisignature from API and peers

### ISSUE THREAD

**Issue by mitsujutsu** [LiskHQ/lisk#2859]
### Expected behavior

As a part of incorporating transactions from lisk-elements, the steps involved in the validating incoming signature should be performed using transactions and transaction-pool libraries. 

### Actual behavior
Currently, uses the logic defined in the `logic/transactions` files.

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by pablitovicente** [comment]
For clarification the objective on this issue is to implement the validation using elements for arriving signatures which depends on the new transaction pool to be in place.

**Comment by mitsujutsu** [comment]
Closing this issue as it is a duplicate of #2825
