### ISSUE TITLE
Add API endpoint that returns the list of delegates for the current round

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#287]
This would allow users to see more exactly when a delegate should forge. It would maybe help also for debugging.

**Comment by karmacoma** [comment]
We can merge functionality from shift and include our own API tests. There are no tests afaik, so we can do our own in this case.

**Comment by karmacoma** [comment]
Resolved by https://github.com/LiskHQ/lisk/pull/317.
