### ISSUE TITLE
Update node.js in http_api module to use network module and fix the tests

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#2880]
### Description
Update the http_api/controller/node.js in chain module to use new network module created.
Also, it should remove the unused functions, and fix/remove tests related to the node.js.

### Dependent issue
#2874

**Comment by ishantiw** [comment]
After looking into `http_api/controller/node.js` it looks like most of the endpoints rely heavily on chain module for data. The only case where we could use network module is when we get node status, but that is also relying on chain module as its calculating last consensus, syncing and transactions (confirmed, unconfirmed, total, etc) which is not available in network module.
