### ISSUE TITLE
Update consensus calculation to use network module and fix the tests

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#2881]
### Description
Update the consensus calculation in /modules/peer.js to use new network module.
Also, it should remove the unused functions, and fix/remove tests related to the peer, and the file name will not be relevant anymore, so it should be update, too.

### Dependent issue
#2874

**Comment by jondubois** [comment]
Note that the `modules.peers.calculateConsensus()` function is also used inside `chain/submodules/loader.js`.
