### ISSUE TITLE
Test suite not working

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#2885]
### Expected behavior
To run the test suite

### Actual behavior
It crashes with the following error:
```
framework/src/modules/chain/helpers/slots.js:17
const { EPOCH_TIME, ACTIVE_DELEGATES } = global.constants;
```

### Steps to reproduce
`npm run test -- mocha:default:unit`

### Which version(s) does this affect? (Environment, OS, etc...)
development branch

**Comment by lsilvs** [comment]
Issue started after https://github.com/LiskHQ/lisk/commit/8d5c787fe16f9571d7baf707540e8fda61a31491

**Comment by limiaspasdaniel** [comment]
Fixed. Closing
