### ISSUE TITLE
Null character in Dapp registration crashes the application

### ISSUE THREAD

**Issue by lsilvs** [LiskHQ/lisk#2886]
### Expected behavior
Expect Dapp registration transaction to be rejected if using unicode null character (`\u0000`) in `tag` or `description` attributes.

### Actual behavior
The node will accept the transaction but will fail to save it to the database getting in a loop and preventing it to forge new blocks.

### Steps to reproduce
Post a Dapp registration transaction with `\u0000` in the `description` or `tag` attribute

### Which version(s) does this affect? (Environment, OS, etc...)
1.4

**Comment by MaciejBaj** [comment]
Fixed by https://github.com/LiskHQ/lisk/commit/5c7e2944383bf369f1343fba62c71e84de6f9664 and included as 1.4.1 Patch Release.
