### ISSUE TITLE
Remove Storage.instance to allow Storage component to be used by different modules

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk#2895]
### Expected behavior
Being able to use Storage component from different modules.
### Actual behavior
Storage instance is being cached and therefore it cannot be used on other modules because it's complaining that entities are already registered
### Which version(s) does this affect? (Environment, OS, etc...)
2770_Extract_api_codebase_to_module_htto_api

**Comment by nazarhussain** [comment]
Its because we try to register entities after creating the instance in the factory method. Since it cache the instance, it don't allow to register same entities again.
