### ISSUE TITLE
Inspect async/await usages in test hooks

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk#2901]
This issue is a follow up for https://github.com/LiskHQ/lisk/issues/2834. 

### Expected behavior
We should return Promises in async functions so they can be resolved.
### Actual behavior
We are returning Promises in sync functions thus they are not being awaited.

**Comment by diego-G** [comment]
For reference, AirBnB strongly discourages the use of an Eslint rule that might help to close this issue: https://eslint.org/docs/rules/require-await
https://github.com/airbnb/javascript/blob/070e6200bb6c70fa31470ed7a6294f2497468b44/packages/eslint-config-airbnb-base/rules/best-practices.js#L317

**Comment by yatki** [comment]
@diego-G I think we can close this issue. I don’t see this is a problem right now. I think it was a wrong assumption back then to think async await usage was causing some problems. So let's not lose time with this.
