### ISSUE TITLE
Config.json migration when updating

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk#291]
Plz forgive, didn't know where else to put this, but....
Just a gentle reminder that the upgrade script could use some migration code for the config.json file.
Updating and upgrading multiple nodes becomes a hefty chore when json customizations like ssl, forging and api options are needing altered after every update..
thx.

**Comment by Phoenix1969** [comment]
thx Isabella !

**Comment by Isabello** [comment]
This belongs on lisk-build.

**Comment by Isabello** [comment]
i will move there, just so you know :)

**Comment by Phoenix1969** [comment]
hmm yea i was there and so confused lol
