### ISSUE TITLE
Solve warnings: "Creating a duplicate QueryFile object for the same file"

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk#2911]
### Expected behavior
As stated in the here in `pg-promise` comments, we need to create only one QueryFile and reused it.

https://github.com/vitaly-t/pg-promise/blob/f91db5814017aa1717fedb8c48fa176ba29b81f7/lib/queryFile.js#L37-L39

### Actual behavior

We are creating QueryFile objects here: https://github.com/LiskHQ/lisk/blob/01c0125c589890e5e065dbc3ac942d9e1044c86f/framework/src/components/storage/adapters/pgp_adapter.js#L173

Which causes lots of warnings in the test output, which makes reading test output very hard:

![image](https://user-images.githubusercontent.com/26697004/53029310-d79acb80-3468-11e9-9302-44643e25be18.png)

### Steps to reproduce

run `npm test -- mocha:default:unit`

**Comment by pablitovicente** [comment]
This only happens with the migrations tests as the migrations are first ran when the sandbox starts. Will need some research to check how to deal with this as it's an edge case for this test only.

**Comment by yatki** [comment]
After having an STM with @nazarhussain and @lsilvs, we decided to keep current behaviour of creating a new PgAdapter instance per module. However, we will move the logic for keeping track of loaded sql files into PgAdapter class and have a global variable to cache loaded QueryFile objects.
