### ISSUE TITLE
Block synchronization gets stuck.

### ISSUE THREAD

**Issue by ferni** [LiskHQ/lisk#292]
The synchronization got stuck in a couple of nodes. Restarting lisk does not solve the problem (doing `bash lisk.sh stop` and `bash lisk.sh start` afterwards ). I really don't have more information about the reason.

**Comment by karmacoma** [comment]
@ferni: Please try the following:

1. Edit `config.json` and increase `poolSize` to 100.
2. Issue the `bash lisk.sh rebuild` command to resync the chain, starting from a snapshot.

Note: You can use `bash lisk.sh logs` to inspect the logs.

**Comment by digitron-lisk** [comment]
May be caused by the node talking to itself. I have seen it stuck in a loop where it was synching with 127.0.0.1. It's also talking to it's own external ip. I blacklisted both 127.0.0.1 and external ip.
