### ISSUE TITLE
Unable to Send Lisk: Expected type string but found type null

### ISSUE THREAD

**Issue by revelations86** [LiskHQ/lisk#293]
Hi,

I am attempting to send List from my address, but I keep getting an error of "Expected type string but found type null". If I try to send out from the Lisk Nano client, I get "Invalid transaction timestamp" error. Can you please tell me what I'm doing wrong and how to fix this?

**Comment by karmacoma** [comment]
Thanks for reporting this bug. The "Expected type string but found type null" error is a bug affecting accounts from which no funds have ever been sent.

This looks to be an issue in https://github.com/LiskHQ/lisk-ui, therefore have moved here: https://github.com/LiskHQ/lisk-ui/issues/75, and we will fix asap.

For Lisk Nano, please ensure your operating system clock is sync with the correct time. This should resolve the "Invalid transaction timestamp" error you are seeing.

Thanks for your patience.

**Comment by Phoenix1969** [comment]
cool
