### ISSUE TITLE
Update Account entity to insert/delete entries in dependent tables for memberPublicKeys and votedDelegatePublicKeys properties

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#2938]
### Expected behavior
The account entity should internally handle the logic for saving/deleting data from `mem_account2_delegates` and `mem_account2_multisignatures` tables.  
### Actual behavior
When an account is updated for `memberPublicKeys` and `votedDelegatePublicKeys`, the account entity simply ignores these properties. These properties are updated only using `account.merge` function defined in the logic/account file. 
### Which version(s) does this affect? (Environment, OS, etc...)
1.5

**Comment by pablitovicente** [comment]
-. Remove the calls in logic/accounts/merge() to `deleteDependentRecord` and `createDependentRecord`
-. Add call to `updateDependentRecords ` in entity/account/update
-. Add tests
