### ISSUE TITLE
Add jest tests to CI pipeline

### ISSUE THREAD

**Issue by yatki** [LiskHQ/lisk#2946]
### Expected behavior

- [x] We need to run Jest tests alongside with mocha tests on Jenkins.
- [x] We should be able to run jest tests and mocha test suites at once with a top level command. Eg `"npm test:unit": "run-p mocha:unit jest:unit"`
- [x] Merge code coverage from both test runners.

### Actual behavior

- Jenkinsfile is not configured to run Jest tests.
- We don't have a top level command to run test runners.

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by michielmulders** [comment]
Added `--passWithNotests` flag for `jest:integration` and `jest:functional` as the absense of tests makes Jenkins fail.

**Comment by michielmulders** [comment]
Jest added to Jenkins script and create a command that executes all tests for a certain type e.g. `unit`. However, using this command, the success/failure of the separate commands are lost between all the logs as they execute in parallel.

Todo @yatki 
- Work on merging code coverage
- Possibly move the `.code-coverage` from root to test as the coverage from Mocha is located under `/test`. If doing so, check Jenkins script cleanup function (`post step`) for the Jest steps as paths need to be changed.

We can safely remove the `--passWithNotests` flag in `package.json` script for running `Jest` tests whenever we have tests for each type (`functional` and `integration`).
