### ISSUE TITLE
Add parameter option to lisk rebuild to sync with specific nodes

### ISSUE THREAD

**Issue by Nerigal** [LiskHQ/lisk#296]
like example 

lisk rebuild --sync=33.33.33.33,44.44.44.44  etc.. 
where ips are nodes considered in good state to prevent the rebuild being contaminated with forked nodes or unhealthy 
this is more a suggestion

**Comment by Isabello** [comment]
you can already to do this by specifying only the node you want to connect to in config.json and removing all other peers.

**Comment by Nerigal** [comment]
i know but you don't want people , all over the network, to edit their config.json and so on.. forget it like that or such... the command sync on a target but could do it just during the sync.. then the node come back available for all the network.
in theory, once synced with a good version of the blockchain, the risk of being contaminated by other nodes is low.

**Comment by Isabello** [comment]
I don't think this particular issue is necessary to address with the new broadhash implementation. Nodes will always be trying to sync with the top height nodes

**Comment by MaciejBaj** [comment]
actually, now it is possible to start lisk with the 'peers' parameter where you can point nodes to sync exactly as you described (so, '--peers 33.33.33.33:3333,44.44.44.44:4444'). Nodes from parameter will overwrite peers specified in config.json. 
I could add another parameter for 'lisk.sh rebuild' task, so it will just pass the peers as an argument to the application while starting it. It should be the issue in https://github.com/LiskHQ/lisk-build then.

**Comment by 4miners** [comment]
Adding some peers as seeds will not force node to sync with them.
