### ISSUE TITLE
Improve peers selection reliability

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#297]
When selecting peers to either broadcast to or sync with. The current approach is to simply select 100 random peers from the peers table.

**Problem**

Many of the selected peers could be forked, syncing, or simply stuck, and are therefore not able to process and relay the latest blocks or transactions to other nodes, and also serve as bad candidates for sync selection. Broadcasting to these nodes leads to either a delay in chain propagation, or in the worst case scenario, failed propagation, and the thing all node operators loath to encounter: a **forked** node. Once the network has a number of **forked** nodes, especially those running delegates, then syncing back up with the chain head becomes close to impossible without mass intervention.

**Solution**

Add new **broadhash** and **height** system headers to each peer, which are transmitted along with every broadcast to other nodes. The **broadhash** being a sha256 hash of the last **n** blocks, that is seeded from the block **id** of each selected block. The **height** simply being the current block height of the peer.

With theses header in place, a broadcasting node is able to make a more informed decision on which peers to randomly select, based on whether they successfully received the last block, and were able to generate the same **broadhash** according to the current position of the chain. 

Example:

1. Peer forges or receives a new block
2. Peer then updates it's own broadhash
3. Peer broadcasts to a random selection of peers which received the last broadcast according to the **previous** broadhash

**Notes**

The **height** header serves as a secondary check on chain position, but also serves as a record of the last seen height for each peer. Therefore, providing a peer height is greater than the querying peer, it can be used to decide on "good" peers to sync with. Reducing the need to query peers individually for their position on the chain, and improving analysis of peers in `findGoodPeers`.

After a node completes a **sync** operation, it updates its system headers with its latest broadhash. If the node has reached the head of the chain, then it will be in-line for the next broadcast.

When there are no peers with a matching broadhash / height >= than own, then we populate list of peer candidates using random selection based simply on height >= than own.

The **broadhash** along with **height** is included in the request / response headers of the peers transport module, and is sweeped to the peers table every time it connects with other peers, or updates its listings.

**Comment by fix** [comment]
challenging your idea:
- What the broadhash add to the couple (height, block_id)? imho this couple is unique (being derived from previous block hash) ie if you match the same block_id, you are sure that you are on the same chain.
- The code (i have made) makes the assumption that "a random peer will provide a good view of a the main chain". Thinking about it, this is errorneous. The best view is stored inside the node peers table imo.

I think a node forging should NOT be responsible from providing internal state of its database. But this is the limit of DPoS. There is no interest for non delegate to run a full node. Maybe decoupling both process (forging and relaying tx, blocks) is a solution.

Cheers and great job btw

**Comment by karmacoma** [comment]
@fix Yes you are right, the coupling I was suggesting is not necessary, so have therefore simplified my implementation to use only ids. Thank you for pointing that out.

Having the height stored within the peers table makes it much easier to get a view on network status, and select a good peer. In order to get to this point, I had to refactor / rewrite the peers module quite heavily. The result being peer changes are swept to the database in batches. This has provided a massive reduction in resource usage of a node, especially during periods of high activity.

I agree, another solution would be to decouple certain functionalities into separate child processes, but for now this is quite a step forward.

Thanks again for your input 👍
