### ISSUE TITLE
API Peers accepts invalid parameters

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#2975]
### Expected behavior
API Peers should accept only valid parameters such as `OS`, `version`, `height` etc.
### Actual behavior
API Peers accepts parameters which are not valid, you can pass any parameter name to the API and it accepts.
### Steps to reproduce
http://167.99.47.154:7000/api/peers?really=?

**Comment by pablitovicente** [comment]
Peers uses the DB only on server load so the changes done to Peers in 1.5 might not be the reason. Maybe it was like this before? Possible to test on 1.4?

**Comment by nazarhussain** [comment]
That is a default behaviour starting from 1.0.0. Any request parameter which is does not exists will be ignored.

The parameters are get in the controllers `request.swagger.params` are the only one which are documented in swagger schema.

**Comment by nazarhussain** [comment]
We have a code available to check this stuff and interestingly its there for few endpoints. 

https://github.com/LiskHQ/lisk/blob/9bd1d7b2b16a59db07ee4bb9f6b82a3d73c4456c/framework/src/modules/chain/api/controllers/transactions.js#L61-L65

We should add it for every endpoint and better to move this logic to a fitting to behave as request middleware. 

This issue should be covered as improvement in general not related to any particular version.

**Comment by ishantiw** [comment]
It has already been fixed in https://github.com/LiskHQ/lisk/pull/3105 and the fix has been added to feature as well in #3180 . So this issue can be closed now.

**Comment by shuse2** [comment]
Closing since superceded by #3180
