### ISSUE TITLE
Group transaction actions on Chain module

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk#2992]
### Expected behavior
`getUnProcessedTransactions`, `getUnconfirmedTransactions`, `getMultisignatureTransactions ` should be merged in one action `getTransactionsFromPool` can be merged in one action `getTransactionsFromPool` and passed the type of transaction  wante to get from transaction pool.
### Actual behavior
There are many actions for transaction pool related logic which can be simplified.

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/pull/3048.
