### ISSUE TITLE
Move static values to top level Application

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk#2994]
### Expected behavior
These both `getLastCommit` and `getBuild ` are static values. These should move to top level `Application` and passed as configuration values to every module.
### Actual behavior
HTTP API has to use the channel to request this data from Chain module and this could be instead passed down from the application levels to each module to avoid this.

**Comment by shuse2** [comment]
superseded by #3036

**Comment by diego-G** [comment]
@shuse2 how is this superseded by #3036 ? I think this is a different independent issue.

**Comment by shuse2** [comment]
When we have application state, these should be in the state, which is top level application right?

**Comment by diego-G** [comment]
I don't see any comment added to the other issue or any change in the description. If we close without documenting, the idea will just vanish. I still think this has to be a separate issue and perhaps link it to the other as a child.
