### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#300]
```
[WRN] 2016-10-26 15:35:05 | DB queue - 315767
[WRN] 2016-10-26 15:35:08 | DB queue - 315775
[WRN] 2016-10-26 15:35:09 | DB queue - 315819
[WRN] 2016-10-26 15:35:11 | DB queue - 315820
[WRN] 2016-10-26 15:35:11 | Balance queue - 1873
[WRN] 2016-10-26 15:35:11 | Balance queue - 1872
[WRN] 2016-10-26 15:35:12 | DB queue - 315821
[WRN] 2016-10-26 15:35:15 | DB queue - 315826
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
error: Forever detected script was killed by signal: SIGABRT
```

I have noticed this twice, it seems there might be some sort of memory leak in those "DB/balance" queues. Since usually memory looks normal
<img width="822" alt="screen shot 2016-10-27 at 17 01 17" src="https://cloud.githubusercontent.com/assets/9548618/19772715/5a274142-9c67-11e6-8457-36e566759b26.png">

**Comment by karmacoma** [comment]
@karek314: Thanks for raising the issue. The next release has a many changes to the peers module which dramatically improves the database efficiency, and therefore eliminates queuing problem you have described. I'm working hard on it, and it will be released to alpha testers and the open testnet asap.

**Comment by karmacoma** [comment]
Closing here as resolved here: https://github.com/LiskHQ/lisk/issues/104
