### ISSUE TITLE
Merge coverage both Mocha and Jest

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk#3023]
### Expected behavior
Now, we store coverage results in two different places (root and `/test`).
Change paths to have them stored together and update Jenkins cleanup step (`post` step) for the Jest testing steps. In short, combine the results of both test suites.

### Actual behavior
Different folders, two reports.

### Steps to reproduce
`npm run jest:unit`
`npm test -- mocha:default:functional:get`

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

@yatki

**Comment by yatki** [comment]
This issue will be done as part of #2946
