### ISSUE TITLE
Refactor channel.invoke to not use callbacks as argument

### ISSUE THREAD

**Issue by michielmulders** [LiskHQ/lisk#3029]
### Expected behavior
Not send a callback function as second/third parameter with the `channel.invoke` call.
Use promisify instead to add a callback and refactor the receiving part to `try-catch` with `await`.

### Actual behavior
Current: https://github.com/LiskHQ/lisk/blob/development/framework/src/modules/http_api/controllers/signatures.js#L46

### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/pull/3032
