### ISSUE TITLE
Change system component to application state

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#3036]
### Overview
Replace the current system component, maintained by all of the modules independently by one global application state, which changes on can be subscribed on by all of the modules and changes to can be submitted after the proper authorization. 

### Rationale
Current system component definition based on LIP:

> **System**
This component will provide a central registry of up-to-date system information. Especially network height, nonce, broadhash, nethash and network specific constants. This component will use channels and events to make all instances of the component stay in sync in different modules.

There is a concern about keeping all of the system components created by each module independently in sync, especially by modules working on separate processes. For instance, when the flag “syncing” is not set at the same time in network and chain modules it is possible that a node will attempt to forge in chain module while syncing in network module at the same time which leads to the node staying on its own fork.

One source of truth about the application knowledge would introduce the possibility of reloading modules in runtime after the height (stored in applicationState) changes. It's one of the ways which is being discussed now internally to support the blockchain data compatibility with legacy protocols. 

Having the shared global state means that the additional information published by modules can be also stored in the applicationState and used by other modules in a flexible way.

### Specification
Variables currently stored by the system component should be included in the applicationState. 

The applicationState is global for the whole system and serves as one source of truth for all of the registered modules within the application.

The applicationState implemented by Lisk Framework controller is loosely inspired by [Redux](https://redux.js.org/).

#### Read
Every change to the applicationState triggers the `applicationState:updated` event, which can be subscribed on by any module. A module reacts then to the changes to only the module-relevant parts of the applicationStore which are updated by following the reduce pattern in `applicationState:updated` event handlers.

#### Write
Changes to the application state can be proposed by any module by calling `applicationState.dispatch` method. 

*Security* aspect cannot be overlooked and the write access of modifying particular variables critical to the blockchain sanity will be restricted to the **application controller** and **chain module** only. 

The following variables can only be assigned once after the application starts and only by **application controller**:
- os
- nonce
- version
- minVersion
- protocolVersion
- nethash

The following variables can only be modified by the **chain module**:
- height
- broadhash

All of the other modules (also the custom ones) can loosely add and modify the custom keys in the applicationState. 

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6.0`

**Comment by diego-G** [comment]
@MaciejBaj I mostly agree with this idea. But I still wonder about two things:
- What's System gonna be from now on: a component with redux? a module? anything else?
- Shall we include more variables like `consensus` and/or `lastBlock`?
