### ISSUE TITLE
DAPPS question :-)

### ISSUE THREAD

**Issue by przeor** [LiskHQ/lisk#305]
What are the most interesting LISK's DApps ?

Does anyone is working on any interesting project, currently?

**Comment by karmacoma** [comment]
@przeor Currently the Lisk application platform is not in a production ready state. We are first aiming towards completing our mainchain stablisation milestone: https://blog.lisk.io/lisk-development-roadmap-5afc4cd0612e#.pa4w4sv1o. Once this is out of the way, the platform will be further developed, and you should start to see the first applications being developed.

For the time being, please take a look at our forum: http://forum.lisk.io/viewforum.php?f=8&sid=2ff4e9ca5c93508f765c9d29d88a4e15 where the community is discussing their various proposals and ideas.
