### ISSUE TITLE
Unconfirmed transactions sent to syncing node do not get broadcast

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#309]
The following code fixes one problem in deflecting unconfirmed transactions while syncing, but results in no broadcast being made. In the event of a network pause, this can lead to critical problems after the 120 second block receipt timeout has expired.

https://github.com/LiskHQ/lisk/blob/6c8127762fc425f5e29e01b19b6b72b85ac58469/modules/transactions.js#L238

```js
// Ignore transaction when syncing
if (modules.loader.syncing()) {
    return setImmediate(cb);
}
```

**Comment by karmacoma** [comment]
Forthcoming version 0.6.0 includes a rewrite of transaction pool code, so for now we will only fix the existing implementation.

**Comment by karmacoma** [comment]
Initially the issues were interpreted as https://github.com/LiskHQ/lisk/issues/308 but my thinking and solution was wrong.

**Comment by vrlc92** [comment]
After an unsuccessful transaction when the network was stuck, the unconfirmed balance has increased by 0.1 lsk at every attempt to roll back this transaction. I just tried to update my voting list (fee: 0.1). Now it's back to normal.

**Comment by Blockwize** [comment]
6687808873757044786L is this a storage for your guys while this is getting sorted? A lot of lisk being sent here. I sent lisk to one of my accounts and somehow it's gone to here.

**Comment by karek314** [comment]
@Blockwize It appears its BloomBit exchange address "6687808873757044786L"

**Comment by Blockwize** [comment]
@karek314 how would they get hold of lisk from a transaction?

**Comment by karek314** [comment]
@Blockwize Not sure, provide your address and destination address, possibly tx id for further investigation, im not in charge of this. Ask @karmacoma
