### ISSUE TITLE
/api/accounts/getBalance call returns an invalid balance

### ISSUE THREAD

**Issue by SteveHadow** [LiskHQ/lisk#310]
After upgrading to v0.4.1, I've noticed an issue where the /api/accounts/getBalance call is reporting an improper balance after the client has been running for some time. Doing a `bash lisk.sh reload` on my client seems to solve the issue and reports a proper balance but about 24 hours later, the call is reporting a balance far higher than what actually exists in the address.

**Comment by Isabello** [comment]
This should no longer be an issue due to fixes present in 0.5.0.

**Comment by 4miners** [comment]
I did extensive testing and I cannot replicate it using current version, balances are fine.
