### ISSUE TITLE
Throw array of errors consistently

### ISSUE THREAD

**Issue by limiaspasdaniel** [LiskHQ/lisk#3106]
### Expected behavior
When propagating errors, an `Error` object should be thrown, not a string.

### Actual behavior
Throwing plain `strings` is spread across the code. Apart from not being encouraged, it's inconsistent as some new code is correctly throwing `Error` objects already. This causes logging problems and inconsistencies when catching those errors at an application level.

Related to: https://github.com/LiskHQ/lisk/issues/3092

### Which version(s) does this affect? (Environment, OS, etc...)
`development`

**Comment by MaciejBaj** [comment]
Superseded by #3152
