### ISSUE TITLE
lisk_snapshot.sh: dump directly from database

### ISSUE THREAD

**Issue by fchavant** [LiskHQ/lisk#3109]
### Expected behavior
- stop application
- copy database
- run on copy:
  - `TRUNCATE peers;`
  - `TRUNCATE mem_accounts2u_delegates;`
  - `TRUNCATE mem_accounts2u_multisignatures;`
- `pg_dump` the copy and `gzip` it

### Actual behavior
We run the application the application with the `-s` switch and wait for it to exit before creating a dump file.

### Steps to reproduce
Run `lisk_snapshot.sh`

### Which version(s) does this affect? (Environment, OS, etc...)
1.6

**Comment by MaciejBaj** [comment]
The direct cause of #3119.
