### ISSUE TITLE
API doesn't work when node is syncing

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#3140]
### Expected behavior

API answers read-only requests while syncing process is ongoing.

### Actual behavior

API throws errors if a request arrives while syncing process is ongoing.

### Which version(s) does this affect? (Environment, OS, etc...)

`1.5`

**Comment by michielmulders** [comment]
Not able to reproduce, likely that the wrong port was used for validating the GET request `4000 (devnet)` and `7000 (testnet`.

Verified that GET requests pass through on snapshot for `testnet` while snapshotting.
For other request, the correct `API access denied` gets thrown.
Labeled as `invalid` and closing.
