### ISSUE TITLE
Move broadhash computation logic from applicationState.update() to chain module

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#3141]
### Expected behavior

Application state class should be as simple as possible only managing the state and producing the events after updates.

### Actual behavior

Application state uses crypto library and blocks to calculate the broadhash. This should be performed in the chain module where the business logic belongs.

### Which version(s) does this affect? (Environment, OS, etc...)

`1.6`

**Comment by nazarhussain** [comment]
You can't move applications state to any other module. Rather you just need to move broad hash calculating logic to chain module and update the hardcoded broad hash and height for the state.
