### ISSUE TITLE
Add delegate forging statistics

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk#318]
In order to assist with delegate forging reward distribution, I think it would be helpful to extend the delegates forging API endpoint with forging statistics. 

GET /api/delegates/forging/delegateStatistics?username=username&day=05&month=05&year=2016
GET /api/delegates/forging/delegateStatistics?username=username&month=05&year=2016
GET /api/delegates/forging/delegateStatistics?username=username&year=2016

```
{
  "success": true,
  "sum": "Forged amount. Integer"
}
```

**Comment by dakk** [comment]
I think it's better to extend getForgedByAccount with two optional parameters "periodStart" and "periodEnd" that indicate the timeslice (in unixtime) of the query
