### ISSUE TITLE
Fix network tests for branch: feature/improve_transactions_processing_efficiency

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#3182]
### Expected behavior
The network tests are failing on the feature branch: `feature/improve_transactions_processing_efficiency`
### Actual behavior
The network tests should pass.

### Which version(s) does this affect? (Environment, OS, etc...)
feature/improve_transactions_processing_efficiency

**Comment by pablitovicente** [comment]
@SargeKhan I merged development that included some fixes to the pm2 configuration of network tests. They are running but it is left to check what tests might fail.

**Comment by pablitovicente** [comment]
I fixed network tests in #3190

**Comment by pablitovicente** [comment]
I can confirm that adding broadcasting to the transaction pool fixes network tests. The issue was that no transactions were being broadcasted hence tests were not passing. See https://github.com/LiskHQ/lisk/issues/3190 for details.
