### ISSUE TITLE
Fix fluctuating "Broadhash consensus"

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#319]
"Broadhash consensus" seems to fluctuate very much between 1% and 50%. If you are unlucky and you have a consensus of <10% at the time you should forge a block, you'll miss that block.
It happens quite often for me.
![image](https://cloud.githubusercontent.com/assets/10214886/20651958/4203b91e-b4f0-11e6-815d-e0d7b9a588d2.png)
The syncing mechanism doesn't fail and the node doesn't fork.

**Comment by karmacoma** [comment]
@simonmorgenthaler Thanks, working on it with priority. @Isabello debugged the code and we should have it fixed asap.
