### ISSUE TITLE
Make each component/module responsible for validation its configuration

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk#3196]
### Expected behavior
Each component and module should have own definition of the input, and validate according to the definition

### Actual behavior
Currently, it's not validating

### Parent
#3149 

### Which version(s) does this affect? (Environment, OS, etc...)
1.6-

**Comment by limiaspasdaniel** [comment]
Closing. Implemented in `feature/improve_overall_configuration` branch.
