### ISSUE TITLE
Crash - Error: write EPIPE

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#32]
```
warn 2016-04-04 15:48:41 Main queue 52
warn 2016-04-04 15:48:41 Main queue 51
warn 2016-04-04 15:48:41 Main queue 50
info 2016-04-04 15:48:43 Check blockchain on 207.7.93.100:7000 
log 2016-04-04 15:48:50 Recieved new block id: 13829360878945744520 height: 440620 slot: 3126173 reward: 500000000 
info 2016-04-04 15:48:50 Removing peer POST http://194.151.78.72:7000/peer/blocks 
info 2016-04-04 15:48:52 Check blockchain on 85.25.194.204:7000 
log 2016-04-04 15:49:00 Recieved new block id: 5608300980796720699 height: 440621 slot: 3126174 reward: 500000000 
Error: write EPIPE
bye bye

```

During normal usage with web interface

**Comment by fix** [comment]
Is it possible to reproduce it?

**Comment by fix** [comment]
ok EPIPE means here the connection has been closed unexpectedly with a peer, likely 85.25.194.204:7000 

It is normally caught to "remove the peer" from the peer list. I guess it will be really difficult to reproduce.

**Comment by karek314** [comment]
actually i have seen this couple times. I had some connectivity problems on that node, maybe way is to simulate connectivity problems and then monitor how it goes.

**Comment by fix** [comment]
I think this is fixed now wit last version. Please reopen if it happens again.
