### ISSUE TITLE
NewRelic throws errors on start

### ISSUE THREAD

**Issue by ManuGowda** [LiskHQ/lisk#3200]
### Expected behavior
NewRelic shouldn't throw any errors
### Actual behavior
```
Error: ENOENT: no such file or directory, scandir '/Users/manu/lisk_ecosystem/lisk/api/controllers/'
    at Object.readdirSync (fs.js:785:3)
    at LiskNewRelic.instrumentWeb (/Users/manu/lisk_ecosystem/lisk/node_modules/lisk-newrelic/src/index.js:75:6)
```
### Steps to reproduce
1) checkout tag `v1.6.0-alpha.0`
2) npm i
3) npm start
### Which version(s) does this affect? (Environment, OS, etc...)
1.6.0

**Comment by limiaspasdaniel** [comment]
Related to https://github.com/LiskHQ/lisk-newrelic/issues/11
