### ISSUE TITLE
Exit event does not kill all the processes

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#3201]
### Expected behavior

There are no running processes when the application stops.

### Actual behavior

One process remains running after application receives exit via CTRL+C. 

### Steps to reproduce

Run the application and press `CTRL+C`

### Which version(s) does this affect? (Environment, OS, etc...)
`1.6`

**Comment by shuse2** [comment]
Possibly duplicate/related to #3185

**Comment by nazarhussain** [comment]
That's a valid case and not handled during the loading/unloading of child_process modules.

If the remaining process is child process (most possible case) then we can fix it through passing `{ detached: false }` as third parameter of the `fork`. 

https://github.com/LiskHQ/lisk/blob/8f7ac1ce66e16616ecd38b7880d424630508b9ae/framework/src/controller/controller.js#L230

**Comment by lsilvs** [comment]
@nazarhussain The  `detached` options is `false` by default
REF.: https://github.com/nodejs/node/blob/v10.14.1/lib/child_process.js#L539

@diego-G I couldn't replicate this issue. Can you give more details, pls?

**Comment by nazarhussain** [comment]
Seems like known issue in NodeJS, and there is hack for it as well. 

https://github.com/nodejs/help/issues/1790#issuecomment-467391811

We still need to the way to gracefully cleanup when we run with npm.

**Comment by lsilvs** [comment]
@nazarhussain As discussed earlier, the above solution prevent the `httpAPI` module from loading properly.

The solution for now will be adding `process.on('disconnect')` in the child process.

I also created a new issue for the cleanup problem when running with npm: https://github.com/LiskHQ/lisk/issues/3210
