### ISSUE TITLE
Restrict 2x4mln LSK from voting

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#325]
IMHO @MaxKK  & @karmacoma  should be restricted from voting with their stake, for sake of decentralisation. If you 2 guys vote for 101 people, this will be actually Max and Olivier centralised application platform and Lisk will be nothing than buddy-2-buddy and vote swap network. My proposal is simply to blacklist voting from public addresses of initial Max & Olivier stake which is ~2x4mln LSK. Intentions doesn't matter, I'm aware you guys want best for Lisk, but this is step backwards.

**Comment by jfernanz** [comment]
Depriving members of the Lisk community from a freedom of vote is even more against decentralization.
