### ISSUE TITLE
if secret is given in config.json, the forging api endpoints do not work

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#326]
/api/delegates/forging/disable is not working
/api/delegates/forging/status returns always true
after a manual switch off the forging is automatically enabled

if no secret is given in config, api works as expected

Lisk v0.5.0 mainnet

**Comment by Isabello** [comment]
This is by design i believe. We check the configured variable every forging
cycle and enable it if its locally present.

Users asked for this feature...

**Comment by TheGoldenEye** [comment]
ok, I was just wondering why my failover scrip was not working
good to know :)

**Comment by Isabello** [comment]
Youre welcome. If you think we should revise logic we can revisit this in
the future.

**Comment by TheGoldenEye** [comment]
yep, but should be documented
