### ISSUE TITLE
Fork cause 5 causing network splits

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#327]
When a node receives a block at the same height it does a simple check here: https://github.com/LiskHQ/lisk/blob/development/modules/blocks.js#L1341

This code basically says take the newest block we have and throw the old block away. This is incorrect. We need to approach this issue with the logic that the old blocks should be kept in every situation, as they will have the most adoption on the network and be forged by the correct delegate.

the revised code would look like this:

 ```
if (block.id < __private.lastBlock.id) {
	if (block.timestamp < __private.lastBlock.timestamp) {
		library.logger.info('Last block loses');
		return self.deleteLastBlock(cb);
	} else {
		library.logger.info('Last block should not lose');
		return setImmediate(cb);
	}
} else {
	library.logger.info('Newly received block wins');
	return setImmediate(cb);
}
```

**Comment by karmacoma** [comment]
The following is a revised strategy courtesy of @4miners and @Isabello.

- Compare blocks based on timestamp, not block id.
- Warn when delegate detected forging on multiple nodes.
- Delete both last block and its parent on fork 1.
- Immediately receive block on fork 5 resolution.

**Comment by Isabello** [comment]
This issue is not resolved. However I have a proposal for it.

## Fixing fork cause 5 -- Double Forging

### What is double forging?

Double forging occurs when two or more nodes on the network have the same delegate(s) enabled to forge. This has the potential to create multiple blocks with the same parent id but a different blockId. While in most circumstances the blocks are the same, there are scenarios where the blockId can be different. In these scenarios we see chaos across the network with many nodes receiving and removing the blocks as they are broadcast due to the code for recovering from fork 5. There has been some code implemented to resolve this issue (found here: https://github.com/LiskHQ/lisk/blob/development/modules/blocks.js#L1356), it can also be considered unreliable and a bandaid for the greater issue.

### Why it happens.
In the current Lisk architecture a node will attempt to forge for every delegate enabled on it when that delegates slot occurs. This poses many dangers which are listed below

1. Non malicious double forging. An end user is running a failover script or configuring a delegate in config.json and it fails over within a slot causing two blocks to forge.
2. A malicious user double (or more) forges in a round by intentionally enabling forging on multiple nodes.

### What can be done to fix it?

One step to take in order to fix the issue of double forging is disallow failover during a slot. This decision would be somewhat unpopular as delegates would no longer to forge every block and potentially slow down the network. Since that is a step backwards from current stability and performance we need to look at other options.

Another proposed solution was to force nodes to register on the network when forging is enabled with some hashed identifying information so that only a small set of nodes could forge. This suggestion is related to preventing malicious users from forging on a large amount of nodes. This doesn't really help solve the root cause to fork 5 either. 

### So whats the real solution?

The real solution is quite simple. In the `config.json` it should be dfefined that there are `Forging Peers`. These are peers that are forging with the same key. Under this new architecture one node would act as the primary forging node. All other nodes would qualify as failover nodes, in order of priority. When it comes time to generate a block for the delegate slot, the primary attempts to do so. If it fails due to consensus, it will emit a signed message to the defined secondary node that it has failed and is passing the baton. The secondary node verifies this message and attempts to forge during the slot. This continues on down the line until either the block is forged, or no node forges a block.


**Example config.json**
```  
  "forging": {
        "force": false,
        "secret": [],
        "access": {
            "whiteList": [
                "127.0.0.1"
            ]
        }
        "peers": {
          "list": [
              {
                  "ip": "192.168.1.1",
                  "port": 8000
                  "priority": 0   // I forge first!
              },
              {
                  "ip": "192.168.1.2",
                  "port": 8000
                  "priority": 1 // I forge if the node above me fails!
              },
              {
                  "ip": "192.168.1.3",
                  "port": 8000
                  "priority": 2  // I forge if everyone else fails!
              }
          ]
        }
    },
```

This strategy will resolve Non-Malicious cause 5 situations but the solution only increases the difficulty to perform a double forging attack, not prevent it.

### So how do we fix that??

This solution is also pretty elegant. We extend the concept of hashing delegate information, except in this case the elected master node (priority 0) will generate a hash and signed message containing a list of nodes that are allowed to forge with its key. This data would need to be stored in a new table. 

```
Table "public.forging_hashes"
Column       | Type         | Modifiers
---------------+-----------------------+-----------
publicKey    | bytea        | 
hashed_nodes | bytea? text? | 
timestamp    | integer      | not null
```
In order to prevent an attack of updating this information via spamming, we also save a timestamp. This highest frequency of allowed updates should be no less than one round, after the first entry, which is given a free pass.

These entries must go through out the network to prevent malicious attacks, however since only the secret key owner (and their nodes) can decrypt these messages there is no risk to delegate security by IP addresses

The method for updating the network is difficult, since theres no transaction type that covers this and this transaction does not have a specific need to be inserted directly into the blockchain. I will leave this end of the discussion open to debate as I am unsure myself.

**Comment by Isabello** [comment]
Actually will reference in new issue.
