### ISSUE TITLE
Binary install script fails

### ISSUE THREAD

**Issue by Crypto2** [LiskHQ/lisk#331]
I'm trying to install Lisk with installLisk.sh (latest version downloaded today) and I just can't get it to succeed. I did do everything in the prerequisites list.

Command line: bash installLisk.sh install -d /home/lisk/LISK -r main
Checking prerequisites:
Curl is installed.                                      Passed
Tar is installed.                                       Passed
Wget is installed.                                      Passed
Sudo is installed.                                      Passed
Please provide sudo password for validation

Sudo authenticated.                                     Passed
All preqrequisites passed!
√ NTP is running

Downloading current Lisk binaries: lisk-Linux-x86_64.tar.gz

Checksum Passed!

Extracting Lisk binaries to /home/lisk/LISK/lisk-main

Cleaning up downloaded files

Coldstarting Lisk for the first time
√ Postgresql started successfully.
√ Postgresql user created successfully.
√ Postgresql database created successfully.
√ Using Local Snapshot.
Restoring blockchain with /home/lisk/LISK/lisk-main/etc/blockchain.db.gz
√ Blockchain restored successfully.
√ Crontab updated successfully.
√ Lisk started successfully.
√ Lisk is running as PID: 28371
Current Block Height: 1

Stopping Lisk to perform database tuning
√ Lisk stopped successfully.
√ Postgresql stopped successfully.

Executing database tuning operation
Updates completed

Configuring Logrotate for Lisk

Starting Lisk with all parameters in place
√ Lisk is not running.
√ Postgresql started successfully.
X Failed to create Postgresql database.

I'm not sure if it's the whole problem but it seems like somewhere along the line it loses the current username since I see errors like this in pgsql log:
ALTER USER  WITH PASSWORD 'password'
And in the generated config.json "user" in the "db" settings is blank as well.
(The USER environment variable is set normally.)

**Comment by Isabello** [comment]
Is your username, user?

**Comment by Crypto2** [comment]
The username is lisk
I have tried bash lisk.sh rebuild and bash lisk.sh coldstart as well and even setting the username to lisk in the config.json and doing the same but it always fails with:
Restoring blockchain with blockchain.db.gz
X Failed to restore blockchain.

**Comment by Isabello** [comment]
Do you have postgres installed at the os level?

**Comment by Crypto2** [comment]
Nope, just the one installLisk.sh installs.

**Comment by Isabello** [comment]
Ok well theres not enough information to troubleshoot this issue here.

I need you to post the pgsql.log from the logs folder

**Comment by Crypto2** [comment]
Here is the full log: http://pastebin.com/KZSyQYQw

Besides the user stuff I also see this, it was trying to allocate 17GB of RAM?

2016-12-02 02:07:27 UTC FATAL:  could not map anonymous shared memory: Cannot allocate memory
2016-12-02 02:07:27 UTC HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap space, or huge pages. To reduce the request size (currently 17305780224 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.

**Comment by Isabello** [comment]
You need to add swap to your node.

This issue is solved.

**Comment by Crypto2** [comment]
Since it's trying to allocate that much RAM my guess would be tune is trying to adjust parameters based on the idea that the whole machine is dedicated just to LISK? There should be an option for that somewhere so it doesn't go nuts.

**Comment by Isabello** [comment]
in general it works correctly. what are the exact system specs of your
machine? there are some edge cases where it fails in its current state.

you can just coldstart lisk afterwards to use the default database params
from postgres as a work around.

**Comment by Crypto2** [comment]
It's a Xeon E5-1630 v3 @ 3.70GHz with 64GB of RAM. It has ~32GB of RAM free.
I have tried coldstart but it fails at:
Restoring blockchain with blockchain.db.gz
X Failed to restore blockchain.

**Comment by Isabello** [comment]
Delete the data folder in the pgsql folder then coldstart. This will take
the default postgres params.

64gb systems are a definitely outlier and will have to be accounted fo in
the tuning script

**Comment by Isabello** [comment]
This is closed by https://github.com/LiskHQ/lisk-build/commit/8b2efb41a567f12d73142e4d6cfc6cc4a604f159
