### ISSUE TITLE
Improve broadhash consensus establishment

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#332]
Currently broadhash only queries 100 peers per the hardcoded constant. This mechanism needs to be modified in the following way:

1. All peers should be queried 
2. Peers that have a height which is behind by a large number (10+) should be ignored in establishing consensus
3. Peers that are offline should be excluded

Querying more peers will create some overhead but this should be acceptable since the result will present a better outlook of the network.

**Comment by Isabello** [comment]
The full network sweep should only occur directly before forging, each node can maintain its table outside of that for a general network picture using the limited system of 100 peers. Tthis number should be sized downwards as a result of this change, since only the forging node for the slot needs this complete picture. There would be a net decrease in network noise by reducing the amount of peers queried.

**Comment by Isabello** [comment]
Testing with a full sweep shows some rather unsettling things -- from Gitter

```
[dbg] 2016-12-06 01:14:00 | Listing 168 matched broadhash peers
[dbg] 2016-12-06 01:14:00 | Listing 155 unmatched broadhash peers
[dbg] 2016-12-06 01:14:00 | Listing 9 fallback peers
[dbg] 2016-12-06 01:14:00 | Listing 100 total peers
[dbg] 2016-12-06 01:14:00 | Block applied correctly with 0 transactions
[dbg] 2016-12-06 01:14:00 | System headers - {"os":"linux3.19.0-64-generic","version":"0.5.0","port":8000,"height":1491216,"nethash":"ed14889723f24ecc54871d058d98ce91ff2f973192075c0155ba2b7b70ad2511","broadhash":"9b545302b03d4d72778b8a6bd536fe17b9d62cedb8150b8f48ccaba0e9da749c","minVersion":"~0.5.0"}
[dbg] 2016-12-06 01:14:00 | Listing 100 matched broadhash peers
[dbg] 2016-12-06 01:14:00 | Listing 100 total peers
[inf] 2016-12-06 01:14:00 | Broadhash consensus now 100 %
```

doing a little debugging on broadhash by changing the consesus query before forging. with a full network view it looks like we barely have 51%
im not sure how much of an issue those 155 nodes are having, whether its one block behind, or they are on a fork
i think block propagation is the root cause here

we can see the numbers on the explorers, 80% of the network is in sync within 3 blocks of top height. if we can figure out make the 70% that are behind by 1-3 blocks sync there would better overall stability to the broadhash %
right before forging we do see them get closer to having full sync but there are still nodes behind that might be forging nodes. this is where low consensus missed blocks would come from

Second forged block
```
[dbg] 2016-12-06 01:34:50 | Listing 74 matched broadhash peers
[dbg] 2016-12-06 01:34:50 | Listing 247 unmatched broadhash peers
[dbg] 2016-12-06 01:34:50 | Listing 1 fallback peers
[dbg] 2016-12-06 01:34:50 | Listing 100 total peers
[dbg] 2016-12-06 01:34:50 | Block applied correctly with 0 transactions
[dbg] 2016-12-06 01:34:50 | System headers -
[dbg] 2016-12-06 01:34:50 | Listing 74 matched broadhash peers
[dbg] 2016-12-06 01:34:50 | Listing 26 unmatched broadhash peers
[dbg] 2016-12-06 01:34:50 | Listing 100 total peers
[inf] 2016-12-06 01:34:50 | Broadhash consensus now 74 %
[dbg] 2016-12-06 01:34:50 | Begin broadcast -[],"blockSignature":"e3817be7bcaa351b92586e1eaa750492ac36e3f69c23b68b5c79204c4c46871ca612cc3b198a2c7fbeb970c316e9c8270900a71541bb7673dfb37906661b4b0e","id":"7601044836296083784","height":1491337,"secondsAgo":0.12,"fresh":true,"relays":1}},"method":"POST","immediate":true}
[inf] 2016-12-06 01:34:50 | Forged new block id: 7601044836296083784 height: 1491337 round: 14766 slot: 1687889 reward:500000000
```

**Comment by karmacoma** [comment]
> All peers should be queried

Not sure how this would help. We only need to find _enough_ peers to establish a viewpoint on consensus. If there are not _enough_ acceptable peers i.e. with a broadhash match then there is another problem imo.

> Peers that have a height which is behind by a large number (10+) should be ignored in establishing consensus

This can be achieved by adding height clause to peers listing query, reflecting on height of own node: https://github.com/LiskHQ/lisk/blob/development/sql/peers.js#L19

> Peers that are offline should be excluded

Currently only banned peers are excluded. https://github.com/LiskHQ/lisk/blob/development/sql/peers.js#L23 Therefore agree on this one 👍

**Comment by Isabello** [comment]
Its not really consensus if we only look at a slice. We can see how using a slice causes issues on the existing network and using more data to validate would help prevent potential network schisms

**Comment by karmacoma** [comment]
Within a 10 second block time the number of peers that an individual node will _touch_ is limited, therefore widening the scope won't necessarily mean a more accurate picture. By using a slice we are getting an approximation on consensus based on likely number of peers _touched_, not whole network.

**Comment by karmacoma** [comment]
Decoupling @4miners ideas from #406:

Two options here:

- Check only peers who broadcasted us full blocks (100).
- Check all peers that we updated in last X seconds (MAX(timestamp)-X_seconds) and have data about them. Checking slice of network is not enough because relying on that can lead to network splits.
- Update consensus after every iteration of peer update loop, only for forging nodes.
- If consensus is too low - we should keep perform another update loop immediatelly during slot until consensus is reached.
- Do we need broadhash/consensus at all?

**Comment by MaciejBaj** [comment]
Changes introduced in 1.0.0 version are broadcasting headers in real-time after block application to the rest of Peers - https://github.com/LiskHQ/lisk/blob/development/modules/transport.js#L378.
