### ISSUE TITLE
Remove BanManager for some failures and improve peers failure handling

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#334]
In the current state of the software we utilize banning peers from interacting with nodes on certain conditions.

Invalid common block request, ban 10 min - This function should not ban. Instead, the peer should be left unbanned.

https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L113

EBLOCK - This occurs when we sync a process a block from a peer. The cause for invalid block is variable. Banning the peer is incorrect since we might be on a fork and the only way off is to do a common block check. Removing peers to sync with is detrimental and we should remove this ban. If we keep the ban, it should be reduced to 1 minute so we can mitigate ddos potential.

https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L163
https://github.com/LiskHQ/lisk/blob/46f451f24469a6e04714c3d688759bd31ba47cfe/modules/blocks.js#L885

ETRANSACTION - 10 minutes for a bad transaction is a long time. If we keep the ban, it should be reduced to 1 minute so we can mitigate ddos potential.
https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L443
https://github.com/LiskHQ/lisk/blob/ccd58052aa33148ab2652d97e0a85edcf8ffd016/modules/loader.js#L172

catch all? this should be remove peer instead. 

https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L575

BanManager function lives here:
https://github.com/LiskHQ/lisk/blob/aeea9655270fa12d90d8176eb36f0700866a4bed/modules/peers.js#L154

**Comment by 4miners** [comment]
I'll take that, permission granted from @Isabello.

**Comment by Isabello** [comment]
Thanks. I hope we can find a good solution to this problem.

**Comment by karmacoma** [comment]
> Invalid common block request, ban 10 min - This function should not ban. Instead, the peer should be left unbanned.

> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L113

I'm inclined to disagree. If after parsing received ids, we don't have anything valid, the request is erroneous and imo should be banned.

> EBLOCK - This occurs when we sync a process a block from a peer. The cause for invalid block is variable. Banning the peer is incorrect since we might be on a fork and the only way off is to do a common block check. Removing peers to sync with is detrimental and we should remove this ban. If we keep the ban, it should be reduced to 1 minute so we can mitigate ddos potential.

> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L163
> https://github.com/LiskHQ/lisk/blob/46f451f24469a6e04714c3d688759bd31ba47cfe/modules/blocks.js#L885

I disagree on first instance. If block does not pass object normalization test, then it is invalid from point of schema, not chain compatibility, therefore peer should be banned. The second instance where block is actually being processed, I agree.

> ETRANSACTION - 10 minutes for a bad transaction is a long time. If we keep the ban, it should be reduced to 1 minute so we can mitigate ddos potential.
> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L443
> https://github.com/LiskHQ/lisk/blob/ccd58052aa33148ab2652d97e0a85edcf8ffd016/modules/loader.js#L172

As with `EBLOCK`. I disagree for schema check. Agree for actual processing.

> catch all? this should be remove peer instead. 
> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L575

We remove the peer when it is deemed unavailable. For other response codes such as timeout, which could be temporary issue, we are less harsh. I don't see a problem here.

**Comment by Isabello** [comment]
> Invalid common block request, ban 10 min - This function should not ban. Instead, the peer should be left unbanned.
> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L113
> I'm inclined to disagree. If after parsing received ids, we don't have anything valid, the request is erroneous and imo should be banned.

If a node is banned for common block failure  and its not schema related, are we not removing a node that could help the fork node recover?

The other two are fine, keeping the bans for schema failures seems acceptable, but id still like to see the timer pushed down significantly to reduce the chance the node will end up in a segregated network of peers that were banned from the larger part of the network.

**Comment by karmacoma** [comment]
> If a node is banned for common block failure and its not schema related, are we not removing a node that could help the fork node recover?
> https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L113

In this case we are banning a peer when after parsing block ids against regular expressions, nothing is yielded. Therefore not an issue with chain compatibility at this stage, but invalid request parameters.

**Comment by Isabello** [comment]
Ok I am convinced
