### ISSUE TITLE
Improve peers metadata collection

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#335]
Currently we query 100 peers on the network for the block height of those peers at this endpoint `/peer/height`.  This is the wrong approach for establishing block height across the network. The reason why this is incorrect is there is another endpoint, `/list` we can use.

https://github.com/LiskHQ/lisk/blob/360c73a73ec7cb0ef184a4ea6a07a80e51c10860/modules/transport.js#L90
https://github.com/LiskHQ/lisk/blob/ccd58052aa33148ab2652d97e0a85edcf8ffd016/modules/peers.js#L256

At this endpoint we can see more than just the peer that is being queried, we can see what the peer knows about others. We can gain a more complete picture of peers through this endpoint by asking less peers a better question.

We could ask 20 peers for this endpoint and receive their data from system headers, and 20 peers worth of data from their database. This results in getting 420 peers worth of data for 20 queries. This would be a huge increase in visibility for the network to switch to this method of populating peers data.

**Comment by 4miners** [comment]
I've done assumption that in network we have 400 peers now.

20 queries asking for 20 peers will give us 193 peers (which is 48,25% network reach) and will take 6 sec (synchonous requests).
https://justpaste.it/110w0

Better results we can achieve asking for 100 peers at once:
10 = 279 peers (69,75% network reach) @ 4 sec
20 = 317 peers (79,25% network reach) @ 7 sec
https://justpaste.it/110vj

That can change ofc, because of peers order.

**Comment by karmacoma** [comment]
@Isabello @4miners Agree this approach would be more efficient as it allows for greater number of peers data to be gathered using less queries. Only problem I see is centralization of knowledge in terms of what one peer knows about others, and relying on it, rather than directly querying peer individually.

**Comment by Isabello** [comment]
We can have a loop that does network sweeps independent of the list query to round out the data and make it less centralized. So this way there would be  the list sweep to build the base picture and the height sweep would be used prior to consensus based actions.

**Comment by karmacoma** [comment]
The reason why I like the original approach, is that in my opinion you are guaranteed an accurate answer on (broadhash/height) from the directly queried node. Whereas asking nodes what they know about other nodes could be potentially false or invalid, potentially overwriting good information with bad.

I'm confident your proposal would increase efficiency, but not so sure on accuracy.

**Comment by karmacoma** [comment]
Decoupling @4miners ideas from #406:

Node should collect metadata about other peers:

- First we will use /peer/list to collect as much information from other nodes as we can. Query X nodes for 100 random peers every Y seconds.
- X and Y should be adjustable, forging nodes (maybe with active delegates only) need to query more peers more often to get better overview of network.
- Then check consistency between received data, if data for some peers are inconsistent - we should query those peers directly using for example /height endpoint. Ofc there should be a limit.
- Property state shouldn't be exposed to other peers, that is node-specific information and every node should determine it on his own.
- We need part of last block's header to be included in http headers (height, id, timestamp). We can compare it with our block at same height and detect that we are on fork or other node is on fork.
- We should save timestamp when we update peer data.
- We should save info if peer broadcasted us full block and check them all in priority.

**Comment by MaciejBaj** [comment]
All changes in headers are now updated real-time -https://github.com/LiskHQ/lisk/blob/development/modules/transport.js#L378.
