### ISSUE TITLE
Add /peers/count endpoint

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#337]
It would be useful to get real count of all currently connected peers
`/api/peers/count`

**Comment by dakk** [comment]
I could implement it if main-dev tells that this call is really needed

**Comment by karmacoma** [comment]
@dakk Sure go ahead, I think would be useful 👍

**Comment by dakk** [comment]
I'm on it

**Comment by dakk** [comment]
@karmacoma in your opinion, is it necessary to count peers in db with connected=2 or I need to ask to express how many connections are active in the last period?
In a REST environment "connected peers" could mean everything

**Comment by karmacoma** [comment]
@dakk For now I think it would good enough to simply count by status i.e. `0,1,2`.

Returning a result such as:

```js
{banned: 1, disconnected: 0, connected: 100}
```
