### ISSUE TITLE
Check if node is actually forging

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#338]
It would be useful to add endpoint to check if node is currently forging, doesn't matter if many delegates are forging on the same node. I simple need to check if current node is taking part of block generation process at time of check.

**Comment by Isabello** [comment]
what would this even do? this can already be checked using other end points.

**Comment by karek314** [comment]
for statistics purpose if current node is running ? If there is way, please tell. But as far as i've checked using current endpoint in that case would be overkill while i simply need bool yes or not. Current endpoint would require getting public key of account, checking if it's in top 101 and getting status if forging.

**Comment by karmacoma** [comment]
@karek314 For what reason do you need to know this information? It is unclear to me.

**Comment by 4miners** [comment]
It can be usefull for some statistics sites like @karek314 one (https://liskstats.net/). But in large network such endpoint can be a security risk for forging delegates - so I recommend closing that issue as wontfix.

**Comment by karek314** [comment]
@4miners It does not needs to be public, why just simply not add some endpoints accessible by user and password defined in config.
Simply:

- Allow such endpoints to be accessed locally only

- Add authentication for endpoints like this

That functionalities will be useful for other endpoints as well. Actually everything not related to node-2-node connectivity should be more or less limited by why i've said.

**Comment by 4miners** [comment]
Private endpoint is a good idea, I agree. There is already endpoint `/forging/status`, we can adapt that: https://github.com/LiskHQ/lisk/issues/360
