### ISSUE TITLE
Add latest commit used used to build in /api/peers/version

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#340]
```
{"success":true,"version":"0.5.0","build":"v06:02:05 30/11/2016\n"}
/api/peers/version
```

It's needed for [Lisk Network Stats](https://github.com/karek314/lisk-network-reporter) to use when there is not build info or just along with date to get exact version.

**Comment by Isabello** [comment]
There is only one release/build per revision. This is a waste to implement
and creates no benefit.

**Comment by karek314** [comment]
But there is no build informations specified when someone compile directly from repository and then statistics website is incomplete. This is relatively easy to implement.

**Comment by Isabello** [comment]
Can you give me an example or a pull request to implement this feature? I don't see it being easy unless we add functionality to check git log as part of core.

**Comment by karek314** [comment]
It can be done during building, stored in config then easily accessibly by node. I think this is simplest approach.

**Comment by Isabello** [comment]
we dont build the client if we run from source. so the build file is never populated on a source configured node.

**Comment by karek314** [comment]
There are few other ways
https://stackoverflow.com/questions/34518389/get-hash-of-most-recent-git-commit-in-node
