### ISSUE TITLE
Network connectivity channels

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#347]
I'vent checked lisk source code, but it seems it's working on normal http requests, wouldn't it be better to implement network connectivity additionally over websockets? Additionally limit connected peers to 15-25 per node, so network would be able to propagate data much, much faster and more reliably. Current propagation times are not good (many blocks are propagated in 1-2s, while IMO it should be less than 1s, possibly for most of network participants should be around or less 500ms.

I have also noticed that most nodes are usually "connected" to 100 or more peers, how it's being calculated ? If it's not websocket connection, then technically it can't be understood as connected, but maybe more like was connected in last N seconds?

**Comment by 4miners** [comment]
That "connected" status is based on last request to that peer - if it was successfull (and peer replied properly with valid data) or not.

**Comment by karmacoma** [comment]
Thanks @karek314. We will now handle this issue here: #409.
