### ISSUE TITLE
API : getTransactions with both senderId and recipientId parameters not working at all

### ISSUE THREAD

**Issue by SherlockStd** [LiskHQ/lisk#379]
In example :
https://login.lisk.io/api/transactions?senderId=9120485202270553493L&recipientId=7023069056644097238L

How can I do I absolutely need this to build the transparency reports tool :confused: ?

**Comment by SherlockStd** [comment]
Just see that : 
All parameters join by "OR".

Sorry

**Comment by 4miners** [comment]
Yep, I know, but such a search is useful and we need to allow it - so reopen. That endpoint should be redesigned at all.

**Comment by SherlockStd** [comment]
Done that, not optimized but will do the job for now https://github.com/SherlockStd/lisk-transparency-reports/blob/34eed483b99a4f3f6e182ab7a66a211c9cad9b8e/helpers/blockchain.js#L43-L69

**Comment by simonmorgenthaler** [comment]
Related to https://github.com/LiskHQ/lisk/issues/265
