### ISSUE TITLE
Remove all useless api that are duplicates of lisk-js functionalities

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#39]
Since you can create transactions using lisk-js, i would consider insecure and useless to keep them active.
Would also solve #10

list of apis to remove
- POST /api/account/open
- POST /api/accounts/generatePublicKey
- POST /api/delegates/forging/enable
- POST /api/delegates/forging/disable
- POST /api/multisignatures/sign
- PUT /api/accounts/delegates
- PUT /api/transactions
- PUT /api/signatures
- PUT /api/messages
- PUT /api/accounts/username
- PUT /api/contacts
- PUT /api/dapps
- PUT /api/multisignatures
- POST /api/multisignatures/sign

Not all are reflected in lisk-js I would advice to migrate al these API everything on lisk-js

**Comment by TheGoldenEye** [comment]
@fix 
Maybe a stupid question: How do you call a lisk-js function (e.g. open account) from the GUI? This code is running locally in the browser, the node code is running remotely on the node. No idea how this should work without api.

**Comment by fix** [comment]
@TheGoldenEye 
the open account does not do what it "means"

see https://github.com/LiskHQ/lisk/blob/0d6c94768f212a23687fa58d8faae4782ede3b37/modules/accounts.js#L306

Basically it just make the server aware of an account so it is loaded in the ram. For instance the faucet will raise an error before sending lisk if an account is not opened on the same server

But this is interface is issue. You can open cold wallet and send lisks posting a transaction to this wallet completely unknown to the blockchain.
