### ISSUE TITLE
Support multiple networks with one installation

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#398]
In our current implementation various files are required to be modified to change what network is able to be used.

These files are:
```
helpers/constants.js
helpers/exceptions.js
config.json
genesisBlock.json
```

The goal of this change is to simplify the use:

- the ease of running a node from source with any network from a single command, like `node app --mainnet`
- clarity of network - specific variables
- decreasing risk of making mistake while merging network specific files during releases

**Comment by MaciejBaj** [comment]
After 1.0.0 the list of "network-dependant files" shapes as follows:
- [ ] config.json
- [ ] genesis_block.json
- [ ] helpers/exceptions.js
- [ ] helpers/constants.js
- [ ] scripts/update_config.js

Keeping them on one branch would decrease possible confusion and risk connected with working and releasing next versions on different networks:
- Alphanet (Devnet),
- Betanet,
- Testnet,
- Mainnet.

Each change to "network-dependant file" would have to added to:
- feature branch (like `1.0.0-beta.9.0`).

**Comment by Isabello** [comment]
:)

2018-06-15 14:28 GMT+02:00 Maciej Baj <notifications@github.com>:

**Comment by diego-G** [comment]
Please guys, don't forget `helpers/milestones.js` and `genesis_delegates.js` when applies.
