### ISSUE TITLE
Rewrite peers module - phase one

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#409]
Decoupling @4miners ideas from #406:

Phase 1 of 2: Move peers management to memory instead of database.

**Comment by karmacoma** [comment]
> Move peers management to memory instead of database.

I think we should perform a dump and restore of peers to the database when shutting down and relaunching application. During application run-time we can persist in-memory only.

**Comment by mrv777** [comment]
> Change peers communication protocol from http to websockets

I'm still reading up on websockets and how it works, but curious what you plan to use for it.  This one looked interesting if it would be compatible: https://github.com/uWebSockets/uWebSockets

Seems very lightweight and fast

**Comment by Isabello** [comment]
uws is on our list of dependencies to move to ;)
