### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#41]
Today (5:11 UTC) somthing was wrong with my node. The node crashed, restarting was not possible because of IP addresses in use. If I look at the uptime values of the other delegates, almost all nodes were affected. Find my upstart log attached:

[lisk.log.txt](https://github.com/LiskHQ/lisk/files/207378/lisk.log.txt)

Unfortunately the logs.log is not available.

**Comment by fix** [comment]
Yes that means that the process has not ended properly as expected and is still using the port.

I don't see a fix for that.

**Comment by mrv777** [comment]
Would the issue brought up here resolve this, since it would attempt to kill lisk:
https://github.com/LiskHQ/lisk/issues/116

**Comment by fix** [comment]
yes i think it is fixed with last version of @Isabello lisk script, good catch!
