### ISSUE TITLE
Document source code using YUIDoc

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#413]
We should document the `lisk` source code using: http://yui.github.io/yuidoc/

New code can be documented immediately: http://yui.github.io/yuidoc/syntax/index.html

Existing code we cover here, module by module.

**Comment by LucasIsasmendi** [comment]
yuidoc does not allows to comment stand-alone functions, everything should be a `class` tag, can lead to misunderstanding.
https://github.com/yui/yuidoc/issues/25
My vote here goes to jsdoc, they have the `function` tag

**Comment by LucasIsasmendi** [comment]
Is not possible to load yuidoc over https:
https://github.com/yui/yuidoc/issues/386
> Since YUI has been deprecated, I think that this is highly unlikely to change.

Maybe we should close this issue and open a new one with "document source code using jsdoc syntax"

**Comment by karmacoma** [comment]
@LucasIsasmendi Yes agree, let's close it and reopen for JSDoc specifically.
