### ISSUE TITLE
Binaries looking for git commit info

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#418]
`fatal: Not a git repository (or any of the parent directories): .git`

Version check needs to be corrected to only run on source builds, this error appears sporadically in the logs of a binary build when it should not.

**Comment by 4miners** [comment]
I fixed that during rewrite of peers module: https://github.com/4miners/lisk/commit/901a28d27b0088ec0c5e26236f95e005a5d4a14b

**Comment by Isabello** [comment]
I know but i needed to log an issue before it became an issue on testnet :)

**Comment by 4miners** [comment]
Yep, just adding reference. :)

**Comment by karmacoma** [comment]
@4miners Great, please put these changes into a separate branch from peers module rewrite and submit as pull request. This way we can close more immediately. Thanks.

**Comment by 4miners** [comment]
Ok.
