### ISSUE TITLE
Popsicle Errors on ETIMEOUT

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#419]
`(node:96779) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): PopsicleError: Timeout of 5000ms exceeded`

We should gracefully handle these errors ourselves instead of allowing odd looking errors to enter into the logs.

**Comment by 4miners** [comment]
Also fixed during peers rewrite: https://github.com/4miners/lisk/commit/4c6b8351b05ffcb0b9affe8c698abc133b355857

**Comment by karmacoma** [comment]
@4miners Great, please put these changes into a separate branch from peers module rewrite and submit as pull request. This way we can close more immediately. Thanks.
