### ISSUE TITLE
can't update submodule

### ISSUE THREAD

**Issue by CryptoSiD** [LiskHQ/lisk#43]
sid@CryptoSiD:~/lisk# git submodule update
Cloning into 'public'...
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:LiskHQ/lisk-ui.git' into submodule path 'public' failed

**Comment by TheGoldenEye** [comment]
To access git repositories you need an git login and ssh login (with public key) enabled.
See https://lisk.io/documentation?i=lisk-docs/SourceInstall section "Problem 2"
