### ISSUE TITLE
issues with /api/peers/count

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#433]
In my tests
`curl -s localhost:7000/api/peers/count` returned `{"success":true,"connected":907,"disconnected":22,"banned":4}`
933 peers look too high to me. Is there a problem?

The same call on testnet.lisk.io resulted in 
`{"success":true,"connected":217,"disconnected":357,"banned":0}`

**Comment by simonmorgenthaler** [comment]
testreport: https://forum.lisk.io/viewtopic.php?f=28&t=1412&p=10451#p10451

**Comment by 4miners** [comment]
@simonmorgenthaler Please execute that sql query at your node for confirmation: `SELECT state, COUNT(1) FROM peers GROUP BY state;`

**Comment by simonmorgenthaler** [comment]
```
lisk_test=# SELECT state, COUNT(1) FROM peers GROUP BY state;
 state | count 
-------+-------
     2 |   839
     1 |    91
(2 rows)

```

**Comment by 4miners** [comment]
So that is not `/api/peers/count` issue, there is such amount of peers.
