### ISSUE TITLE
No hash entry in release file

### ISSUE THREAD

**Issue by CryptoSiD** [LiskHQ/lisk#44]
E: Failed to fetch http://archive.lisk.io/dists/lisk/Release  No Hash entry in Release file /var/lib/apt/lists/partial/archive.lisk.io_dists_lisk_Release which is considered strong enough for security purposes
E: Some index files failed to download. They have been ignored, or old ones used instead.

apt 1.2.10 (amd64)

**Comment by karmacoma** [comment]
Running `apt-get update` should normally resolve this. Looks to be a download/connection error.
