### ISSUE TITLE
Rewrite peers module - phase two

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#446]
Decoupling @4miners ideas from #406:

Phase 2 of 2: Change peers communication protocol from http to websockets.

**Comment by karmacoma** [comment]
See phase one: https://github.com/LiskHQ/lisk/issues/409

**Comment by karmacoma** [comment]
We are looking to utilize http://socketcluster.io/ which is base on: https://github.com/uWebSockets/uWebSockets.

By changing from the stateless http protocol to persistent socket connections, we aim to improve block / transaction propagations times, and the general efficiency of peer to peer communications.

**Comment by MaciejBaj** [comment]
For communication with peers, different process (worker) can be launched- it is easy to do with SocketCluster. SocketCluster very seems to be a very good choice in terms of scalability. However, it is not compatible with the WAMP protocol (such as AutobahnJS), and from the point of how peers communicating, RPC could be very useful. It addresses the problem of the response order in case of subscription to an event after peer sends many requests one by one. Merging ideas of WAMP protocol to introduce RPC with good performance of SocketCluster seems to be the best solution.

- [ ] small library to extend WebSocket Socket object with RPC methods 
- [ ] setup SocketCluster server and client in Lisk
- [ ] handshake between peers as WS middleware
- [ ] transactions broadcast and receiving as WS stream
- [ ] signatures broadcast and receiving as WS stream
- [ ] new block broadcast and receiving as WS stream
- [ ] ping peer as WS RPC method
- [ ] get height from peer as WS RPC method
- [ ] get common block from peer as WS RPC method
- [ ] load blocks from peer as WS RPC method
- [ ] load signatures from peer as WS RPC method
- [ ] load transactions from peer as WS RPC method
