### ISSUE TITLE
Impose hard limit on number of transactions inserted into each block

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#46]
It seems, since 8 hours only one delegate can forge blocks. CryptoDelegateNEW forges all blocks.
The block time is currently 10-20 minutes. This corresponds with issue #20.
Attached you can find the last hours of my log. It had a size of nearly 50 MB now (after more then one day running).

[logs.zip](https://github.com/LiskHQ/lisk/files/214348/logs.zip)

**Comment by TheGoldenEye** [comment]
After rebuild my node resynced to block 493592 (2016/04/12 05:51:30 UTC).
After this, no new block was generated (now it is 2 hours later)

**Comment by MaxKK** [comment]
Yes, during a stress test yesterday night an issue came forward, Oliver prepares a fixed version right now.
