### ISSUE TITLE
Auto-filling (suggestion) address when sending lisk

### ISSUE THREAD

**Issue by stenea** [LiskHQ/lisk#471]
When someone transfers lisks from his address to some other address s/he has to copy the address even if that address has a name. It would be helpful if the receipting address has a name to be served as autocompletion. To have the system coming up with suggestions as the sender is typing the name of the address.

![image](https://cloud.githubusercontent.com/assets/4835177/23853606/0254c41c-07f6-11e7-9017-473ecf74a2e4.png)

**Comment by karmacoma** [comment]
Good suggestion, we will keep in mind. However, closing the issue here as it is more applicable to our user-interface `lisk-ui`. Moved here for reference: https://github.com/LiskHQ/lisk-ui/issues/99

**Comment by stenea** [comment]
Thank you Oliver.
