### ISSUE TITLE
Syncing with itself re-occurring

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#488]
Problem when node enters indefinite loop of starting and finishing sync still happens. Node tries to sync with itself by it's public ip. This issue should have been fixed already as per PR i saw. I have also mentioned this problem in old issue here on github, but seems it didn't brought attention.

`bash lisk.sh reload`
Resolves issue immediately.

 **Version 0.7.0**

**Comment by 4miners** [comment]
Yep, I can confirm this.
For long term solution - random string (nonce) should be generated at node start and added to headers, then every peer should be checked against that nonce and rejected if nonces match.
