### ISSUE TITLE
403 forbidden error accessing web client

### ISSUE THREAD

**Issue by gitbase1** [LiskHQ/lisk#491]
Hi,

I'm using ubuntu and getting a 403 error.  

Failed to load resource: the server responded with a status of 403 (Forbidden)
http://myip:8000/api/accounts/open/ 

The initial screen loads, I'm able to enter my pass phrase, but doesn't proceed.  That's looking at the console. 

Thanks!

**Comment by Isabello** [comment]
See this link on how to configure API for remote hosts

https://github.com/LiskHQ/lisk-wiki/wiki/Configure-Lisk#4-access
