### ISSUE TITLE
Improve sync speed

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#498]
After tweaking sql performance sync speed should be improved, but hotfix https://github.com/LiskHQ/lisk/pull/454 became a bottleneck. There are some solutions for short term:
- Implement dynamic limit. Additional parameter can be added for max supported response body size (default: 2000000 bytes). Then our node send that param when call to `/peer/blocks`, remote node will determine dynamically how much blocks can send to us. So if blocks are empty - we will get much more blocks, and when they are full - less. Because of possible timeouts we shouldn't probably use all 2000000 bytes. 
- Second solution is to pull for few packs of blocks concurrently, but that probably will need some blocks pool (where pending blocks can be stored for later usage) to be implemented.

**Comment by 4miners** [comment]
That issue can help only for short term, and will improve performance only slightly - imo is not worth implementing anymore. We need another solution that can improve sync speed drastically and give us benefits for long time.

@SargeKhan Please close that issue if you agree.

**Comment by SargeKhan** [comment]
I agree that this issue can be closed. We are working on improving block processing efficiency which will automatically improve syncing speed. We can reopen this issue later after making those improvements and gathering statistics.
