### ISSUE TITLE
LISK Missing 

### ISSUE THREAD

**Issue by Lovetoday2020** [LiskHQ/lisk#503]
Hey guys can I send lisk token s to ethereum blockchain via freewallet.org???
Lost £10000 doing so any help would be much appreciated cheers

Hash I'd is showing on my wallet withdrawls but it's not showing on the ethereum blockchain.
If i type the # ID in to lisk I can see the transaction is complete with the funds in to some unknown lisk wallet can you help me out with an answer please?

#ID  1493344432819990629 you can track this through lisk blockchain

**Comment by Lovetoday2020** [comment]
![img-20170325-wa0011](https://cloud.githubusercontent.com/assets/26679468/24326285/13870b58-11a3-11e7-8bb7-cf7e0075eaea.jpg)

**Comment by Isabello** [comment]
We are not affiliated with that service. You would have to ask them where
your ethereum tokens. Additionally, once your funds are sent in a confirmed
transaction they become property of the account they were sent to and this
can't be reversed unless the owner of that account decides to return them.
