### ISSUE TITLE
Lisk crashes few seconds after start

### ISSUE THREAD

**Issue by corsaro1** [LiskHQ/lisk#505]
I noted often a small issue on my public lisk node on https://liskworld.info
It is hosted on Scaleway provider, 8 Dedicated x86, 64bit Cores
16GB memory, Ubuntu Xenial, 16.04 LTS.
When I start it, after few seconds, it always crashes, and it is virtually impossible to start it. So the only way I have to allow it to regularly start, is this:
- close 8000 port using iptables
- start the lisk node
- after about 5, 10 seconds, to reopen 8000 port
So doing, node starts regularly.
It is a public node, so api calls are opened to public. It is widely used from different guys for their tools, so I suspect that as soon as it starts, in the first seconds, the overload of api calls, crashes it.
I think it could help if lisk at start, for few seconds keeps the 8000 port closed, then open it after 5 or 10 seconds

**Comment by Isabello** [comment]
This is a fairly common issue on public API nodes since api calls are hitting the node before modules initialize. It happens on our explorer nodes too.

**Comment by MaciejBaj** [comment]
Simplest solution would be to extract the `express.listen` part from app.js as a seperate task, which will be run after modules are initialized as @Isabello suggests
