### ISSUE TITLE
More descriptive error message - "invalid transaction body"

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk#509]
Current behaviour:

When creating a transaction locally and sending it to the network, the answer I receive is:
{ request: { success: false, message: 'Invalid transaction body' } }
call endpoint is api/transactions, using the following transcation object:
`{ 
type: 0,
 amount: 100000000,
 fee: 10000000,
 recipientId: '13795892230918963229L',
 timestamp: 26514729,
 asset: {},
 senderPublicKey: 'f59df94e54ebe23a4cd50ec7186e8739980277527b0a02ed3fc4ab3e169a4380',
 signature: 'ae141cea38d75b00efeae8a98a62a087fde3f59f49f54c0bd83165c35d99b993ce787074d1cdba7d2db9f55427fe09a63fc9f66c6952c27b510d648be5ab570d',
 signSignature: 'b819df625370a20a8ab3193f03b37cb94fb0b0fe4f4d73805c48f471c5d5bfbf82c7417859e74bf484d99ee4ecb9f1a4ca76d2e67f2feaf37df0af4b887f1109',
 id: '18345444702940464495' 
}`

- It is not clear where this error is coming from.

Expected behaviour:

The error message could make a difference if signature of the transaction is wrong, maybe timestamp... giving a concrete error message would help debugging transcation objects.

**Comment by karmacoma** [comment]
Thanks @Tosch110. I agree the returned error message should be more descriptive of the actual problem occurred.
