### ISSUE TITLE
Dapp deposit fails 

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#51]
- Using Lisk v0.1.4, development branch
- I created a basic dapp using "lisk-cli dapps -a" without changes
- starting the node
- if I try to deposit the dapp using "lisk-cli dapps -d" (here with an amount of 100 LISK), the transaction seems successfull: 

```
$ lisk-cli dapps -d
? Enter secret ****
? Enter amount 10000000000
? DApp Id 16924003274252134805
? Enter secondary secret (if defined) 
? Host and port localhost:7000
null { success: true, transactionId: '13688217344496871545' }
13688217344496871545
```

The transaction is credited, but seconds later reverted. Only the fee was applied. See screenshot.
![image](https://cloud.githubusercontent.com/assets/17945384/14510093/f9037a98-01cf-11e6-8d72-9f4d303186e9.png)

**Comment by TheGoldenEye** [comment]
In one account the transferred Lisk are credited to the dapp account, but not withdrawn from the sender.
In another account the Lisk are withdrawn, but not credited.
I'll follow it up

**Comment by fix** [comment]
Hi @TheGoldenEye did you manage to reproduce it with 0.2.x ?

**Comment by TheGoldenEye** [comment]
I just got the dapp running again with 0.2.1.
I will theck the issue this weekend.

**Comment by TheGoldenEye** [comment]
This is an issue of the LiskHQ/lisk-dapps-sdk repo and should be solved there

**Comment by TheGoldenEye** [comment]
beside changes in LiskHQ/lisk-dapps-sdk the issue is LiskHQ/lisk related too
