### ISSUE TITLE
Typescript refactoring

### ISSUE THREAD

**Issue by ppetzold** [LiskHQ/lisk#518]
Hi folks,

What's actually your opinion about a Typescript refactoring? Are there any plans?

Cheers

**Comment by karmacoma** [comment]
Hi @ppetzold,

No concrete plans but definitely something we want to tackle. Until now, there were other priorities.

We will schedule for inclusion after `1.0.0` is out of the way I think.

Keeping the issue open as direct reminder. Thanks 👍

**Comment by kazzkiq** [comment]
Looking forward to this as it will help catching bugs, doing maintenance and enabling code completion/IntelliSense for those building dApps in the future.

Huge effort, though.

**Comment by willclarktech** [comment]
@kazzkiq We'll be implementing a type system in lisk-js first and use the experience to inform our decisions in other projects. If you have anything helpful to add to https://github.com/LiskHQ/lisk-js/issues/417 we'd love to hear it.

**Comment by goktugyil** [comment]
Any updates on the thoughts on Typescript refactoring since we're there now?

Also it sucks that refactoring gets harder and hader as more code gets written in JS. 😢

**Comment by willclarktech** [comment]
@goktugyil Nothing will change on this front before `1.0.0` is released.

**Comment by MaciejBaj** [comment]
Lisk Elements will be written in Typescript first - https://github.com/LiskHQ/lisk-elements/issues/417#issuecomment-420635666.

**Comment by MaciejBaj** [comment]
Moving to TypeScript is on Lisk Core Roadmap (https://lisk.io/roadmap). The issue will be closed and re-opened in a milestone form when after all of the modules will already be extracted from Lisk Core to Lisk Elements.
