### ISSUE TITLE
Change license from MIT to GPLv3

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#520]
As of `lisk` version `0.8.0`, we are changing the licensing scheme from [MIT](https://opensource.org/licenses/MIT) to to [GPLv3](https://opensource.org/licenses/GPL-3.0). 

The main reason for this change is to provide protection against the future use of `lisk` in a proprietary form, while at the same time maintaining all of the freedoms to use, change or share the project which are currently in-place.

For more information on GPLv3 please read: https://www.gnu.org/licenses/quick-guide-gplv3.html

Tasks:

- [x] Change license footer, with amendment to reflect change of license
- [x] Add license field to `package.json`
- [x] Add license badge to `README.md`
- [x] Include license file within project

**Comment by Isabello** [comment]
wooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

:)
