### ISSUE TITLE
config.json gets truncated if a masterpassword needs to be generated because it is empty in config.json

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#521]
When Lisk is started (in regular mode, or coldstarting) and the masterpassword is empty in config.json (this is the case after a fresh install) config.json gets truncated, meaning it is empty afterwards. Starting Lisk fails then obviously.

How to reproduce:
There are different ways, the easiest one is this:
* stop lisk
* empty the masterpassword in config.json -> "masterpassword": "",
* start lisk
starting fails. config.json is now empty.
verified in 0.8.0a alpha

**Comment by karmacoma** [comment]
Thanks @simonmorgenthaler. We are looking into it immediately, would be great to resolve this issue once and for all.

**Comment by MaciejBaj** [comment]
Problem occurs when access config.json file by both lisk app- [`fs.writeFile`](https://github.com/LiskHQ/lisk/blob/development/app.js#L165) and pm2 watch process. 

Update to reproduce methods:
1. start lisk using pm2 with [watch files param](https://github.com/LiskHQ/lisk-build/blob/development/etc/pm2-lisk.json) - `pm2 start $PATH_TO_PM2_CONFIG`
2. empty the masterpassword in config.json -> "masterpassword": ""
3. the file is empty

Possible solutions:
1. replace `fs.writeFile` with `fs.writeFileAsync` in `app.js`
2. add config.json to `ignore_watch` list in pm2-lisk.json in lisk-build https://github.com/LiskHQ/lisk-build/blob/development/etc/pm2-lisk.json#L11
