### ISSUE TITLE
Enhance delegate API for Lisk Nano 

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#524]
## Current behavior
Lisk Nano would currently have to use these APIs:
LIst delegates:
```
/api/delegates?limit=limit&offset=offset&orderBy=orderBy
```
Search delegates
```
/api/delegates/search?q=username&orderBy=producedblocks:desc
```
Get voted delegates
```
/api/accounts/delegates/?address=address
```
It would be usefull for Lisk Nano to have a single API end point.

## Desired behavior
I propose to add more optional parameters to the first API:
```
/api/delegates?limit=limit&offset=offset&orderBy=orderBy&username=username&address=address&filter=filter
```
Namely:
- `&username=username` would fuzzy filter on delegate username
- `&address=address` would add an additional field `voted` to the results, indicating of that delegate was voted from that address
- `&filter=filter` where `filter` is one or two of: `'active:true', 'active:false', 'voted:true', 'voted:false'`. I'm not sure/happy about the exact syntax of this feature, but I need to be able to filter by these.

**Comment by karmacoma** [comment]
See: https://github.com/LiskHQ/lisk/blob/development/modules/delegates.js#L293

And corresponding tests: https://github.com/LiskHQ/lisk/blob/development/test/api/delegates.js#L377

**Comment by karmacoma** [comment]
For `GET /delegates/search`

See: https://github.com/LiskHQ/lisk/blob/development/modules/delegates.js#L599

And corresponding tests: https://github.com/LiskHQ/lisk/blob/development/test/api/delegates.js#L743

**Comment by karmacoma** [comment]
For `GET /accounts/delegates`

See: https://github.com/LiskHQ/lisk/blob/development/modules/accounts.js#L241

We have not corresponding tests.

**Comment by karmacoma** [comment]
Since modularisation of API has been done now for `0.8.0`. I think also time to think about closing #225, i.e. redesign the API to follow REST standards.

**Comment by karmacoma** [comment]
@slaweet Not sure if a good idea to consolidate these API calls. I maybe see the reason for `listing`, `searching`. But not the votes a delegate has placed. This I feel should be in a separate call still.

Ideally:

- `GET /delegates`
- `GET /delegates/search`
- `GET /delegates/[username|address]/votes` OR `GET /delegates/votes?username=`
- `GET /delegates/[username|address]/voters`OR `GET /delegates/voters?username=`

**Comment by slaweet** [comment]
@karmacoma I can live with having votes separate, but I don't really see the difference between list and search.
Search is IMO just a list with some filter applied to it.
```
/api/delegates
/api/delegates?username=username
```

I don't really understand why the two functions you linked above are so different, as I'm not very familiar with nodejs. But in Django ORM it would be as simple as:
```
deleagtes = Delegate.objects.all()
if request.GET.username is not None:
    deleagtes = deleagtes.filter(username__contains=request.GET.username)
# rest of the code common to both cases
```

Over 300 people support this idea in this SO:
http://stackoverflow.com/questions/207477/restful-url-design-for-search

**Comment by karmacoma** [comment]
@slaweet Ok, I take your point on listing / search. As previously mentioned, it needs to be part of a more complete API re-design, i.e. conforming to a RESTful standard. We will aim to do it for the `1.0.0`. In the meantime, you might need to make a compromise and work with the current design limitations.

**Comment by slaweet** [comment]
I thought about the requirements and came to the conclusion about what the minimum requirements are and created a ticket for those:
https://github.com/LiskHQ/lisk/issues/533
I'll do all the other filtering client-side and won't display the total count of delegates matching the current filter

**Comment by karmacoma** [comment]
Closing in favour of #533
