### ISSUE TITLE
Signed and checksummed Lisk files

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk#53]
There should be a way for a delegate to check the integrity of the lisk core files and lisk itself before launching to prevent malicious modification of files and processes implemented in the client.

**Comment by fix** [comment]
agree :+1:

**Comment by Gr33nDrag0n69** [comment]
i think a simple md5 (or sha1 or sha256) checksum  like linux iso would be enought. like for lisk-Linux-x86_64.tar.gz  we have a file lisk-Linux-x86_64.tar.gz.md5

**Comment by Isabello** [comment]
I think what slaskeks is asking for is verification of all the files upon startup after a reboot rather than just checking the installation .tar.gz.

One possible way to keep the files safe would be tripwire, but I don't think we want to go that route...

**Comment by Gr33nDrag0n69** [comment]
Ok, i think .md5 on tar.gz would also be something to consider :)

How can this be implemented in the software itself ? (checksum verification)

if the software is hack the protection could be hack too !? if in run from the same user.

**Comment by Gr33nDrag0n69** [comment]
the only solution i can see is that the list of all files with the checksums should be off site from the server. the software could get that list... won't work :( soft can still be modified to get alternate list. I think the best bet would be to build a very simple yet well made howto and promote the implementation of it as best practice ...

**Comment by slasheks** [comment]
It is a combination request. A checksum file like Gr33nDtag0n suggests, to verify if the download was modified in transit, the file digitally signed to verify the author, and perhaps the most difficult part is modification check upon execution. Obfuscation helps, but it is not a deterrent. Perhaps the blockchain itself can be used as method of verification between releases.

**Comment by Gr33nDrag0n69** [comment]
that would be sick :)
lisk blockchain securing lisk software integrity

**Comment by fix** [comment]
what about a dapp for that? ;)

**Comment by fix** [comment]
but i agree with @Gr33nDrag0n69 a md5 is a good start and enough for now

**Comment by fix** [comment]
@Isabello is something possible? I cannot make my mind on how to do it

**Comment by Isabello** [comment]
I think validating app.js would be the best way to handle this issue. All of the core code is crunched down and put into there, so if app.js doesn't match the hash of what we expect (this could be inserted and checked in the block chain for example), the process with exit. This doesn't stop people from compiling their own clients but it would create an additional layer of validation for clients released by us.

**Comment by Isabello** [comment]
No matter what we do theres no way to completely secure the client against modification as long as the software is open source. Any thing we can do can be modified and undone. This is being closed as a `wontfix`. However, we will definitely improve the checking of binaries with SHA256 instead of MD5.
