### ISSUE TITLE
Add rate, approval and productivity to /api/delegates/search

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#533]
### Current behaviour
`/api/delegates/search` returns list of delegates that look like this:
```
{
"username": "genesis_1",
"address": "8273455169423958419L",
"publicKey": "9d3058175acab969f41ad9b86f7a2926c74258670fe56b37c429c01fca9f2f0f",
"vote": "9999982490000000",
"producedblocks": 263,
"missedblocks": 6
}
```

### Expected behaviour
`/api/delegates/search` returns list of delegates that look like this:
```
{
"username": "genesis_1",
"address": "8273455169423958419L",
"publicKey": "9d3058175acab969f41ad9b86f7a2926c74258670fe56b37c429c01fca9f2f0f",
"vote": "9999982490000000",
"producedblocks": 263,
"missedblocks": 6,
"rate": 59,
"approval": 100,
"productivity": 97.77
}
```
which is the same as `/api/delegates/`

**Comment by 4miners** [comment]
@slaweet 
- Added: `approval`, `productivity`, `voters_cnt`, `register_timestamp` with ability to order by those fields
- Increased limit of max returned delegates from `100` to `1000`

Btw, you can also use that endpoint for get all delegates with sort of hack - `q=%` ;)
