### ISSUE TITLE
Refactor round logic

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#543]
The following information defines how we will refactor rounds to be more efficient and provide greater security/consistency to the blockchain as a whole.

### Fees

At the end of a round, fees are tallied based off the rounds table. This table is populated with fee information per block containing transactions. This leads to a very high amount of entries during rounds with significant transaction volume. This mechanism is strictly a work around for properly querying the blockchain and splitting fees from the returned data.

Therefore, we will remove fees from the round table entirely and only query the past 101 blocks at the end of a round in order to generate the total amount of fees to split.

### Outsiders (Missed Blocks)

Upon forging a block, there is an entry inserted into rounds that tracks which delegates forged a block and which ones missed their block for the purposes of splitting fees and updating `missedblocks` totals. The solution to this is to remove outsiders from the rounds table and instead generate outsiders in the same way fees are split, from the past 101 blocks. The block chain has 100% of the information needed to furnish this data and is therefore more accurate/efficient to generate it from the existing blockchain data.

### Vote aggregation

In the current state votes are tallied at the end of the round and `mem_accounts` is subsequently updated. The new approach should be as follows:

1. During the round, any vote modifying transaction will update a new temporary table, `mem_votes`. This table will house the unconfirmed state of votes.
2. At the end of the round, all unconfirmed vote data will be placed into service on a new table, `mem_delegates`. This will decouple delegate specific information from `mem_accounts`.
3. At the end of the round, with all of the new vote data in place we will generate list of delegates of 1000 places in the future with the associated slot data. This will remove any performance impacts of calculating slot order every block, since the order will then be cemented in place.

### Block insertion

Currently, insertion of new blocks and the resulting round ticks and application of transactions to the memory tables are all handled via separate phases.

**Current Behavior:**

```
BEGIN
-> Insert block
-> Insert block.transactions
COMMIT

BEGIN
-> Apply round tick to memory tables
COMMIT

FOR transaction IN block.transactions
  BEGIN
  -> Apply transaction to memory tables
  COMMIT
END
```

This can result in leaving the memory tables in an inconsistent state if one of the phases fails to commit.

In order to create perfect consistency and ensure all operations are perform atomically, these phases will be refactored, and instead all database updates will be performed using internal database functions and triggers. This will create a single entry point, the insertion of blocks. This being the only mechanism that should change blockchain data in the database.

**Proposed Behavior:**

```
BEGIN
-> Insert block
  -> Trigger: Apply round tick to memory tables
-> Insert block.transactions
  -> Trigger: Apply transaction to memory tables
COMMIT
```

As all operations are contained within a single `BEGIN/COMMIT` db transaction, any error or failure occurring during the operation can be easily rolled back, keeping the memory tables in a consistent state.

Corresponds with #544

### Memory table changes

**NEW:** `mem_delegates` - This table will store all relevant delegate information and relieve `mem_accounts` of some expensive indexing operations.

- `publickey` - primary/foreign key relation to `mem_accounts`
- `username`
- `fees`
- `rewards`
- `votes`
- `u_votes` (possibly)
- `producedblocks`
- `missedblocks`

**NEW:**`mem_votes` - This table will aggregate all vote changes and subsequently be used to update mem_delegates vote totals.

- `u_votes`
- `publickey`

**NEW:**`mem_slots` - This table will provide a stable mechanism of slots and publicKeys of forgers at each timestamp.

- `publickey`
- `slot`

**REMOVE:** `mem_rounds`

**KEEP:** `round_fees` (possible rename to `mem_round_fees`)

### Resulting order

Round order will simplified to the following:

1. Update missed/produced blocks.
2. Calculate and split fees / rewards.
3. Update votes.
4. Calculate delegate order and store a list with slots.

From #449

**Comment by karmacoma** [comment]
Regarding Step 4. Calculate delegate order and store a list with slots. We can do the following:

```
BEGIN
-> Promise to save block
-> Promise to save block.transactions

On round finish:
-> Calculate slots, then Promise to populate `mem_slots`

-> Execute on promises
COMMIT
```

**Comment by 4miners** [comment]
Tasks list:
- [ ] Port `Delegates.prototype.generateDelegateList` from `modules/delegates.js` to postgres function
- [ ] Write tests for new postgres function
- [ ] Maintain one copy of shuffled delegates list in node memory (reuse during same round), maybe use postgres to node nofify feature for that? So postgres can notify all Lisk instances connected to database when round changes - to research.
- [ ] Create table `delegates` for storing delegates-related data
- [ ] Create SQL query/function to populate `delegates` table (based on actual blockchain, independent from `mem-accounts` if possible)
- [ ] Check that `delegates` table is consistent with existing `mem_accounts`
- [ ] Create triggers (insert, delete) for adding new delegates to `delegates` table (from `trs`,), we will maintain current mem_accounts fields (for example: `isDelegate`) until https://github.com/LiskHQ/lisk/issues/544 is resolved
- [ ] Write tests for those triggers
- [ ] Switch current endpoints to using new table
- [ ] Improve `rounds_fees` table (maybe add consistency checks)
- [ ] Research if we need rebuild `rounds_fees` table when revalidating blockchain
- [ ] Write tests for `rounds_fees` related postgres functions
- [ ] Research if we need `mem_votes`, `mem_slots` tables, implement if needed
- [ ] Rounds management in postgres
  - [ ] Update `mem_accounts`.`balance` using postgres triggers (maybe from `rounds_fees` table) (need to support rollback in case of delete of last block of round)
  - [ ] Update `delegates`.`votes` using postgres triggers (need to support rollback in case of delete of last block of round)
    - [ ] Create SQL query for getting `votes` changes for round
- [ ] Remove unused logic from code
- [ ] Manual testing (continuous)
