### ISSUE TITLE
bug with maxAmount in transactions endpoint

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#550]
check https://github.com/LiskHQ/lisk/blob/development/modules/transactions.js#L60
I think this
maxAmount:           '"t_amount" <= ${minAmount}',
should be changed to this:
maxAmount:           '"t_amount" <= ${maxAmount}',

**Comment by 4miners** [comment]
@simonmorgenthaler Yes, sure, thanks. :)
