### ISSUE TITLE
Change process.exit([code]) calls

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#554]
Replace `process.exit(number)` with `process.exitCode = number`
>  Calling **process.exit()** forces the process to exit before additional writes to stdout can be performed. The code should set the **process.exitCode** and allow the process to exit naturally by avoiding scheduling any additional work for the event loop

https://nodejs.org/api/process.html#process_process_exit_code

**Comment by 4miners** [comment]
Because of some issues we decided to reverse those changes for now, we will retry as part of `1.0.0.`.

**Comment by laszlolm** [comment]
@karmacoma Is there any help needed here?

**Comment by karmacoma** [comment]
@laszlolm Sure, you are welcome to help with this one. Please target any work against our `development` branch for inclusion in `1.0.0`.

**Comment by MaciejBaj** [comment]
Following issue has been opened: https://github.com/LiskHQ/lisk/issues/554.
