### ISSUE TITLE
Timestamp in pure unix

### ISSUE THREAD

**Issue by gab88slash** [LiskHQ/lisk#56]
now timestamps is a unix timestamp shifted of 1428544800 seconds.
It may better be to use a pure unix timestamp.

**Comment by TheGoldenEye** [comment]
The timestamp is usually the time since block 0, not the unix timestamp.This is true for all cryptos I know. So the mentioned offset is the unix timestamp of the genesis. 
Of course, Lisk could do it differently.

**Comment by Crypto2** [comment]
Unix timestamps are the norm, in fact the only other coin's API I know if that doesn't use them is NXT.

Not sure if it's a typo or just an accident but RE: this thread: https://forum.lisk.io/viewtopic.php?f=13&t=379 and this file: blob/development/helpers/slots.js
The date in the js file is May not April so the correct offset is 1464109200.

**Comment by fix** [comment]
I think this is fixed in the initial release, closing it
