### ISSUE TITLE
Remove selected dapps functionalties, pending rewrite

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#560]
For Lisk `1.0.0`, we will remove the following selected dapp related functionalities, pending a full rewrite.

**Functionalities to be removed:**

- Download
- Installation
- Uninstallation
- Process management (and sandboxing)
- Interprocess communication
- Peer to peer communication

**Functionalities to be kept:**

- Application registration
   (but only using `lisk-js`, therefore `PUT /dapps` will be removed)
- Application deposits
   (but only using `lisk-js`, therefore `PUT /dapps/transaction` will be removed)
- Application withdrawals
   (but only using `lisk-js`, therefore `PUT /dapps/withdrawal` will be removed)
- Getting an individual application registration
- Listing of registered applications
- Listing of application categories

Related issues:

- https://github.com/LiskHQ/lisk/issues/225
- https://github.com/LiskHQ/lisk/issues/457
- https://github.com/LiskHQ/lisk-js/issues/106
- https://github.com/LiskHQ/lisk-build/issues/160

**Comment by karmacoma** [comment]
@diego-G Please note, as part of closing this issue, https://github.com/LiskHQ/lisk-sandbox and https://github.com/LiskHQ/lisk-node will be discontinued and moved to @LiskArchive.

**Comment by karmacoma** [comment]
@diego-G Please note, the following related issue: https://github.com/LiskHQ/lisk-js/issues/106 in `lisk-js`.

**Comment by karmacoma** [comment]
@diego-G: Please note, the following related issue: https://github.com/LiskHQ/lisk-build/issues/160 in `lisk-build`.

**Comment by diego-G** [comment]
- [X] Remove Download
- [X] Remove Installation
- [X] Remove Uninstallation
- [X] Process management (and sandboxing)
- [ ] Interprocess communication
- [ ] Peer to peer communication
- [X] Remove dapps registration --> `PUT /dapps`
- [ ] Remove dapps deposits `PUT /dapps/transaction`
- [ ] Remove dapps withdrawals `PUT /dapps/withdrawal`
- [ ] Refactoring `GET /dapps`
- [ ] Refactoring `GET /dapps/:id`
- [ ] Refactoring `GET /dapps/categories`

**Comment by karmacoma** [comment]
Reopening due to premature API breakage and poor test coverage. Pull request incoming.
