### ISSUE TITLE
Unify callback position

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#576]
There are some places in `\app.js` where the call style is `new Object(scope, cb)` and others is  `new Object(cb, scope)`
Callback function should be placed at the last position in arguments of a function.

**Comment by oleblaesing** [comment]
Is anybody working in this issue, yet? I would like to start contributing with a simple task like this, while I get an overview over the codebase.

**Comment by 4miners** [comment]
@oleblaesing Sure, you're welcome to take that issue.

**Comment by Isabello** [comment]
Concuring with @4miners 

We cannot formally assign it to you currently but we have agreed that its ok for you to take this one.

**Comment by MaciejBaj** [comment]
Closed by https://github.com/LiskHQ/lisk/pull/628
