### ISSUE TITLE
delegate registration missing in forging panel

### ISSUE THREAD

**Issue by 2mdoty** [LiskHQ/lisk#58]
Delegate registration button missing in forging panel when registering a second delegate from web client. Workaround is to refresh the client web page before signing in to account. This has been persistent in Crypti as well. Behavior is in Firefox, Windows 7, not checked in other browsers or OS.

**Comment by karmacoma** [comment]
Moving issue to lisk-ui as this is a user-interface issue: https://github.com/LiskHQ/lisk-ui/issues/29
