### ISSUE TITLE
Disable Second Passphrase on Lisk

### ISSUE THREAD

**Issue by yelllowsin** [LiskHQ/lisk#581]
Any chance of disabling the second phrase password in the future? I missed my second key and thus i cannot move my coins anymore (my 14k Lisks are lost in the dust). Just in case you are planning in removing it to simplify the platform.

Thanks.

**Comment by Isabello** [comment]
Even to disable the feature on an account we would need you to validate the
second passphrase to do so.

**Comment by yelllowsin** [comment]
Hi, thanks for giving me a feedback. Actually if you or anyone has any other idea of how i could restore the access to my founds, i would really appreciate. This is my Lisk address which has the lisks: Address: 12396865480546198435L

I have the first key to access the account, but i also set a second passphrase and took a note of it. But when i tried to move them, i found out the second passphrase i had taken note did not work. So i must have taken a wrong note or something went wrong/bug and i did not notice.

I moved my funds from my ICO accounts which i have all the private keys to this one i mentioned before. Those ico accounts did not have a second passphrase set, so by providing these ICO keys it proves i am the owner of the funds.

I don't know what i do anymore, is there any chance to roll back those funds to my ICO accounts only with my first passphrase? Then i would have access to them again as i have the keys for these accounts. If you or anyone has any other idea, otherwise i will just give up trying and forget my Lisks and accept the loss.

Thanks, have a great day.

**Comment by Isabello** [comment]
We can't undo the registration of the second passphrase as its permanently in the chain at this point.
