### ISSUE TITLE
Modern ES6/ES2015 syntax

### ISSUE THREAD

**Issue by petermakowski** [LiskHQ/lisk#587]
Hi guys, as a JS developer I'm really excited about the idea of blockchain in JavaScript - just doing research on List at the moment, really cool stuff! Is there a particular reason why you don't use and haven't used from the beginning modern ES6/ES2015+ syntax and features (anywhere that I can find)?

Maybe it's my ignorance/some technical details that I'm not aware of, but remember being quite surprised when I saw Lisk for the first time. ES2015 was already widely-adopted at a time in the Open Source world, you'd expect JavaScript blockchain startup to be ahead of the curve.

My knowledge about blockchain is quite limited at the moment but I'd love to contribute to the project if you'd be open for that (like helping with refactoring to ES6).

**Comment by pcdinh** [comment]
> Is there a particular reason why you don't use and haven't used from the beginning modern ES6/ES2015+ syntax and features

LISK was written back to 2014 when ES6 is not available yet.

> but I'd love to contribute to the project if you'd be open for that

I do think that you can fork and make pull requests when your code is ready

**Comment by mpyw** [comment]
+1 :+1: 

I think it should be refactored until the next release of v1.0

**Comment by willclarktech** [comment]
We have recently created an eslint config (based on AirBnB's), which enforces ES6 features. Issue https://github.com/LiskHQ/lisk/issues/672 will update lisk core to these standards, but the current plan is to migrate the code right before the v1.0.0 release to avoid merge conflicts.

**Comment by karmacoma** [comment]
This issue will finally be resolved by: #672
