### ISSUE TITLE
some doubt about the security of lisk

### ISSUE THREAD

**Issue by liulinhui** [LiskHQ/lisk#588]
`__private.openAccount = function (secret, cb) {
	var hash = crypto.createHash('sha256').update(secret, 'utf8').digest();
        console.log(secret);`

so if I install one node,if someone login my node,i can get his secret, is this safe?

**Comment by 4miners** [comment]
@liulinhui Thank you for your question. Ofc it's not safe, you should never send secret to nodes you not trust. That will be solved with https://github.com/LiskHQ/lisk/issues/457. If you don't have further questions please close that issue.
