### ISSUE TITLE
app should shutdown nicely

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#59]
Otherwise, the blockchain.db is regularly messed up and need to be rebuilt from ground up.

Also the blockchain verification is far from optimised, with exponantial time computation...
So far the "verify" flag is forced in the code, even configured otherwise in config.json. Should be reverted asap in my opinion.

**Comment by sigwo** [comment]
Maybe wrap in Node.js native event system?

```javascript
process.on( 'SIGINT', function() {
  console.log( "\nGracefully shutting down from SIGINT (Ctrl-C)" );
  // some other closing procedures go here
  process.exit( );
})
```

**Comment by Phoenix1969** [comment]
yep, this happened to me just now... so upsetting after waiting hours for sync... all i did was enter the passphrase and restart, now back to scratch!

**Comment by LiskDevs** [comment]
Happened to me several times too

**Comment by Odsejen** [comment]
I found another strange issue with the blockchain.db, tried to make a backup from the *.db file, but even when i'm trying to make a backup (lisk is stopped before), it won't be in sync when i start it again, what means that the node will start from block Zero, the same issue of course when i'm trying to change the original blockchain.db with the backup.db file. I tried to reboot, before i'm doing the backup copy, but it makes no difference.
I think it's a strange issue, or i'm overseeing something?
Will continue to find more...

**Comment by mrv777** [comment]
Does this still apply with postgresql?

**Comment by Isabello** [comment]
This should no longer be an issue since it was related to SQLite.

**Comment by fix** [comment]
I think we can close it for now with the new version. Should it happen again, please reopen it
