### ISSUE TITLE
Better query concatenation

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#601]
form here: https://github.com/LiskHQ/lisk/blob/5e3a26da80ee9f8958ca6d552f111710122ef068/logic/account.js#L657

it will be better to make use of method [helper.concat](http://vitaly-t.github.io/pg-promise/helpers.html#.concat) within your `merge` method ;)

**Comment by 4miners** [comment]
@vitaly-t Thank you, we appreciate your feedback. 👍 
That function will be refactored/removed as part of `1.0.0`, so after that I will review if we still need to address that issue.

**Comment by 4miners** [comment]
Connected with: https://github.com/LiskHQ/lisk/issues/544

**Comment by karmacoma** [comment]
Closed by PR: https://github.com/LiskHQ/lisk/pull/1312
