### ISSUE TITLE
Do not use cache if Redis authentication failed

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#606]
Redis initialization always passes a password, even when its null. This causes redis to fail initialization and cause the node to stop functioning.

In order to fix this we need to sanitize the config passed to redis when starting the cache.

In addition, the default passwords should be removed in call cases.

**Comment by diego-G** [comment]
I clarify the scenario:
- Lisk config --> `"cacheEnabled": true`
- Redis --> `requirepass XXXX`
- Lisk Redis config : bad auth credentials
- Any API call using cache is not able to get the resouce (timeout)
