### ISSUE TITLE
Block verification - exception blockreward

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#607]
method verifyBlock() from `modules/blocks/verify` should check `logic/helpers/exceptions` for blockReward. Missed commit "Adding testnet specific blockReward exceptions."
This will go to 0.9.0, same change will be apply to #459

**Comment by Isabello** [comment]
This issue is not quite solved. The blockRewards field needs to be relocated to the top of the list so that its detected by github during a merge with testnet branches.
