### ISSUE TITLE
sqlite performance

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#61]
I don't expect sqlite be performant in a one year time. Related to #59

I think we should think about upgrading to a new db backend. Bitcoin and Ethereum are using leveldb https://github.com/bitcoin/bitcoin/tree/master/src/leveldb

I don't expect leveldb be that performant either because there will be a lot more blocks (and transactions?) than bitcoin.
I still don't understand why there is no use of "classical" db. Maybe security issues? Anyway, it should be thought about as soon as possible.

**Comment by karmacoma** [comment]
@fix I've been working on this particular issue over the past week or so. We will announce shortly.

**Comment by fix** [comment]
Nice! Can't wait to see it :)

**Comment by vrlc92** [comment]
Consider using MongoDB.

MongoDB is an open source, document-oriented NoSQL database. MongoDB stores data in JSON documents and contains built-in redundancy and high availability features.

"Sharding is the process of storing data records across multiple machines and is MongoDB’s approach to meeting the demands of data growth. As the size of the data increases, a single machine may not be sufficient to store the data nor provide an acceptable read and write throughput. Sharding solves the problem with horizontal scaling. With sharding, you add more machines to support data growth and the demands of read and write operations."

https://docs.mongodb.org/manual/sharding/

**Comment by fix** [comment]
I guess i can close the issue with the migration to pgsql. I am still perplex with the portability of the stack to desktop client.

**Comment by fix** [comment]
i guess we can close this one!
