### ISSUE TITLE
DPOS Rewards disparity

### ISSUE THREAD

**Issue by philhellmuthIE** [LiskHQ/lisk#618]
With current Lisk price of 3.10 $ delegates are earning almost 40000 $ a month which is pretty much insane when you know that their only expese are 2 VPS's 20$ each. When/if Lisk reaches 10$ and if the reward stays at 5 Lisk/block delegates will earn 125 000$. Just imagine Lisk at 50$, 100$...
With so big delegate rewards we're making a huge disbalance between 101 delegates and the rest of the community. 101 is getting rich and almost intouchable and this difference is only getting bigger. 
I would like to propose an improved (at least in my opinion) DPOS system.
In this system delegates would get around 3000 USDT monthly, and the rest of forget Lisk would go into the (community) pool which will get into DAO like function once the SDK is ready.
3000 USDT monthly for the delegate is good enough. If any delegate needs more or feels he has done more than those 3000 USDT he can make a proposal as well.
That DPOS system would grow prevent big differences in the community and leave everybody a chance to get into 101, because current delegates are making more wallet and can swap votes indefinitely with those huge earning.
Once the SDK is ready, Lisk community pool would have so much money that we will be able to push hundreds of projects at once. just imagine what will that do to Lisk price.

**Comment by Isabello** [comment]
We will never peg to USDT or another token that would directly provide outside influence into our technology. Changing rewards does nothing to improve the security or improve consensus. Moreover, anyone can get into the 101, whether its buying their way in through exchanges or building social capital and receiving community support.

I am labeling this issue as `wontfiix` as theres nothing broken, and theres no issue to solve.

**Comment by philhellmuthIE** [comment]
Btwn. Max told me to publish this as an issue.

Thanks Isabella for being against the good of Lisk.

**Comment by philhellmuthIE** [comment]
Btwn. The proposal is improving both security and consensus, you just need to be open minded to see what will happen in the future if same people keep getting huge rewards.
Its almost impossible to get into 101 now, and for buying yourself into 101 you need more than 500 000 dollars so please Isabella be more realistic.

**Comment by karek314** [comment]
@philhellmuthIE, check https://github.com/LiskHQ/lisk/issues/353 Everyone is welcome to propose something out there, what i have in mind is self regulated number of top delegates, however this introduce some other implications, but nothing what cannot be resolved one way or another. ex. unlimited number of votes but votes with desired priority, so when current forging delegates number decrease, only more important votes are taken in count. Problem you highlighted is important, but note that some % of delegates are actively contributing to entire ecosystem, not only good server and making sure that blocks are not missed. More serious problem is buddy-2-buddy schemes which are ruining dpos principles and shadow-delegates whose never been around but they are forging in 101, which i think are part of buddy-2-buddy schemes where multiple delegates are being maintained by same person.

**Comment by karmacoma** [comment]
Thanks for contributing to the discussion @philhellmuthIE. We will close this issue for now. If you want to add your thoughts to #353 please feel free.
