### ISSUE TITLE
[API] Long time to receive a response to the request: api/delegates/get?username=xyz

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk#62]
Long time to receive a response to the request. This time is over when I use "login.lisk.io/api".

* 159.203.166.60 (~157 ms): <img width="1261" alt="request_get_delegate_remote_server" src="https://cloud.githubusercontent.com/assets/937766/14763999/38433bca-097e-11e6-88b5-cfc582c81673.png">

* login.lisk.io (~ 23.15 s): <img width="1255" alt="request_get_delegate_login_lisk_io" src="https://cloud.githubusercontent.com/assets/937766/14763998/383e678a-097e-11e6-919d-31682660fc72.png">

**Comment by vrlc92** [comment]
The issue was solved with the new version (0.2.0).

I made a new test:

<img width="1257" alt="screen shot 2016-05-03 at 9 58 00 am" src="https://cloud.githubusercontent.com/assets/937766/14983884/33003506-1116-11e6-9c20-6c42650e39b7.png">

Thanks!

**Comment by karmacoma** [comment]
Thank you 👍
