### ISSUE TITLE
Disable console logging for production

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#620]
In production, we recommend the usage of PM2 to manage the process. This includes the management of console logs. However, we already use a file logger to handle logs and should therefore disable console logs in production builds. This means we need to have a function to allow `none` to be passed to the consoleLogLevel field.

This function should be disabled for config.json in testnet-development, testnet-master, and master branches.

**Comment by 5an1ty** [comment]
One line, one fix :).

https://github.com/LiskHQ/lisk/pull/621

**Comment by Isabello** [comment]
<3

On Jun 19, 2017 14:28, "Ruben Callewaert" <notifications@github.com> wrote:

One line, one fix :).

#621 <https://github.com/LiskHQ/lisk/pull/621>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LiskHQ/lisk/issues/620#issuecomment-309424905>, or mute
the thread
