### ISSUE TITLE
Better regular expression for vote in logic/vote -> verifyVote function

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#627]
In verifyVote function, we check the format of vote using `if (!/[-+]{1}[0-9a-z]{64}/.test(vote)) ` condition, we should update regular expression to only pass for hexadecimal strings.

**Comment by 4miners** [comment]
Yep, something like `/^[-+]{1}([A-Fa-f0-9]{2}){32}$/` or `/^[-+]{1}[A-Fa-f0-9]{64}$/`, unfortunatelly POSIX expressions are not supported and we cannot use `[[:xdigit:]]` :(
