### ISSUE TITLE
Node crash with the FTL error

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#629]
<code>
[FTL] 2017-06-25 10:23:08 | Domain transactions - {"message":"Cannot read property 'getTime' of undefined","stack":"TypeError: Cannot read property 'getTime' of undefined\n    at /opt/install/lisk-main/app.js:12:16957\n    at /opt/install/lisk-main/node_modules/async/dist/async.js:3025:16\n    at replenish (/opt/install/lisk-main/node_modules/async/dist/async.js:882:17)\n    at /opt/install/lisk-main/node_modules/async/dist/async.js:886:9\n    at eachLimit$1 (/opt/install/lisk-main/node_modules/async/dist/async.js:3114:22)\n    at Object.<anonymous> (/opt/install/lisk-main/node_modules/async/dist/async.js:918:16)\n    at Object.l.expireTransactions (/opt/install/lisk-main/app.js:12:16828)\n    at /opt/install/lisk-main/app.js:12:13762\n    at nextTask (/opt/install/lisk-main/node_modules/async/dist/async.js:5070:14)\n    at Immediate.<anonymous> (/opt/install/lisk-main/node_modules/async/dist/async.js:5064:13)"}
</code>

A restart is needed in order to have the node up and running

**Comment by 5an1ty** [comment]
Assign to me, I'm looking into it.

**Comment by 4miners** [comment]
@5an1ty Would be nice if we can get your feedback on https://github.com/LiskHQ/lisk/pull/636

**Comment by 4miners** [comment]
Fixed with https://github.com/LiskHQ/lisk/issues/636
