### ISSUE TITLE
After enabling the second passphrase no change or disabling possible

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#63]
After I have enabled the 2nd passphrase, i cannot disable / change it.
The menu item is gone.

![image](https://cloud.githubusercontent.com/assets/17945384/14770533/5c9117bc-0a74-11e6-9540-bc23654f7a95.png)

**Comment by MaxKK** [comment]
Yes, this is intended right now. Later on we might add this as a feature.

**Comment by Isabello** [comment]
By the nature of the blockchain removing second passphrase shouldn't be possible. This should be a `wont fix` issue because its 100% expected functionality.

**Comment by MaxKK** [comment]
@Isabello You are right. It would be a passphrase update and the client only accepts the last entry. However, we have to brainstorm if this makes sense or if it complicates the user experience.
