### ISSUE TITLE
Undefined getTime error on 0.9

### ISSUE THREAD

**Issue by dakk** [LiskHQ/lisk#631]
After installing 0.9, in the log appear frequently this error:

> Domain transactions - {"message":"Cannot read property 'getTime' of undefined","stack":"TypeError: Cannot read property 'getTime' of undefined\n    at /home/lisk/lisk-main/app.js:12:16957\n    at /home/lisk/lisk-main/node_modules/async/dist/async.js:3025:16\n    at replenish (/home/lisk/lisk-main/node_modules/async/dist/async.js:882:17)\n    at Immediate.iterateeCallback (/home/lisk/lisk-main/node_modules/async/dist/async.js:867:17)\n    at Immediate.<anonymous> (/home/lisk/lisk-main/node_modules/async/dist/async.js:840:16)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"}

**Comment by 4miners** [comment]
Closing as duplicate of https://github.com/LiskHQ/lisk/issues/629
