### ISSUE TITLE
Implement SyncOnly flag for firewalled clients

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#646]
In order to serve some of our client base who are behind firewalls, we should implement this flag to disable the majority of peers querying operations. These operations are unnecessary for a node not participating in the network due to being firewalled.

**Comment by 4miners** [comment]
@Isabello We already implemented possibility to disable broadcasts via issue https://github.com/LiskHQ/lisk/issues/1696 - it's now possible to disable it by setting `broadcasts`->`active` to `false` in `config.json`. When broadcast is disabled node will work in sync-only mode. I think current issue can be closed - please confirm that.

**Comment by Isabello** [comment]
IDK why you are asking me. I dont work on this software anymore.

It sounds like you have solved the issue, atleast.

One thing are these nodes getting put into tables and subsequently excised
from the network.

2018-07-09 14:47 GMT+02:00 Mariusz Serek <notifications@github.com>:

**Comment by 4miners** [comment]
Thank you.
