### ISSUE TITLE
Implement ForgingEnable flag

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#647]
In the interest of efficiency, nodes that are only serving public API functions should disable their forging thread. Its unneccessary to track broadhash and query the network as a whole if the node is not going to be actively forging. This is especially intended for nodes behind firewalls.

**Comment by 4miners** [comment]
We're not going to implement special flag for enabling/disabling forging feature. Instead it should be handled dynamically - it should be disabled when it's not required (no delegates in `config.json`). To achieve that we have issue https://github.com/LiskHQ/lisk/issues/1870 open, which is basically about refactoring the way how forge loop is handled.

Regarding nodes behind firewall, we added initial support for enabling bi-directional connections in issue https://github.com/LiskHQ/lisk/issues/2069, so after implementing that feature - will be possible to receive broadcasts for node that is not reachable from outside (public IP, blocked port for incoming connections, etc.).

I'm closing that issue, please feel free to reopen if you have any doubts.
