### ISSUE TITLE
Cannot read property \'map\' of undefined

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#65]
info 2016-04-27 15:02:24 Modules ready and launched 
info 2016-04-27 15:02:25 Blocks 583511 
info 2016-04-27 15:02:25 Current 0 
info 2016-04-27 15:02:41 Current 5000 
fatal 2016-04-27 15:02:58 Domain master { message: 'Cannot read property \'map\' of undefined',
  stack: 'TypeError: Cannot read property \'map\' of undefined\n    at /root/lisk-0.1.4-Linux-x86_64/app.js:7:28274\n    at j.<anonymous> (/root/lisk-0.1.4-Linux-x86_64/app.js:12:9733)\n    at Socket.onerror (/root/lisk-0.1.4-Linux-x86_64/node_modules/dblite/build/dblite.node.js:255:16)\n    at Socket.emit (events.js:107:17)\n    at onwriteError (_stream_writable.js:317:10)\n    at onwrite (_stream_writable.js:335:5)\n    at WritableState.onwrite (_stream_writable.js:105:5)\n    at fireErrorCallbacks (net.js:456:13)\n    at Socket._destroy (net.js:497:3)\n    at WriteWrap.afterWrite (net.js:779:10)' }

**Comment by karmacoma** [comment]
Closing this issue as it appears to relate to dblite, the library used to interface with SQLite. We have now switched databases to PostgreSQL, so this particular issue no longer applies.
