### ISSUE TITLE
Drop PostgreSQL native bindings

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#664]
Would be nice to drop `pg-native`, however research should be done how much it will affect performance.

**Comment by pcdinh** [comment]
What will it solve?

**Comment by 4miners** [comment]
@pcdinh There is no real issue with it, but there are some disadvantages: https://github.com/brianc/node-postgres#native-bindings

**Comment by vitaly-t** [comment]
@4miners Oliver asked me to look into this.

The link you provided to the disadvantages is no longer good, and the only API link that I can find is this one: https://node-postgres.com/features/native

If you can find the list of disadvantages, please post them here, and we will start from that :wink:

**Comment by nazarhussain** [comment]
I don't have exact information about using native bindings in javascript. But from a Ruby background I can say, native bindings are always more proficient. Using native bindings is a good to go approach in Ruby paradigm. Theoretically I can't see any disadvantage even in NodeJS.

**Comment by 4miners** [comment]
@vitaly-t https://github.com/brianc/node-postgres/commit/0c24ff3c12a2e1b2dd6d16a8192c64fd34dcd1e7#diff-04c6e90faac2675aa89e2176d2eec7d8L176

**Comment by vitaly-t** [comment]
@4miners I am well aware of the differences between the Native and JavaScript bindings. After all, I was the one who investigated and reported most of them. Here's just one example: https://github.com/brianc/node-postgres/issues/988

But none of those discrepancies affect us.

**Comment by karmacoma** [comment]
We will stick with the native bindings until there is stronger evidence dropping them would be beneficial.

**Comment by shuse2** [comment]
I think one of the drawback to use `pg-native` is the build flow.
In docker, You must have postgres client installed in the image same as the core.
Also, to install locally, we need install postgres first before `npm install`

**Comment by karmacoma** [comment]
Sounds like we can also simplify/update our build process in @LiskHQ/lisk-build.
