### ISSUE TITLE
gpu.js

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#669]
For any crypto-currency calculation, you should be using [gpu.js](https://github.com/gpujs/gpu.js), which can boost the performance a lot.

**Comment by dakk** [comment]
Lisk-node doesn't perform complex array calculations, so gpu support is useless; furthermore, lisk-node usally is executed on cloud VPSs, which have no gpus by default

**Comment by Isabello** [comment]
While an interesting idea, our targeted machine sets don't have GPUs like
stated above. This is something that would be useful down the road.

**Comment by 4miners** [comment]
@vitaly-t Interesting project, thanks for pointing it out. 👍
