### ISSUE TITLE
Accounts module and logic bugs

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#677]
**logic/accounts.js**
- `verifyPublicKey()` doesn't correctly check if passed parameter is in hex format. We expect `Buffer.from(publicKey, 'hex');' to throw in the case of none hex value but it doesn't.
- Issue with Object Normalization - We are using outdated format to define validation rules for the account object.

**modules/account.js**
- `Account.prototype.internal.count` always returns an error
- `Account.prototype.internal.getAllAccounts` also always returns:
```
{
  success: true,
  accounts: undefined
}
```

**Comment by Isabello** [comment]
PR that discovered these issues: https://github.com/LiskHQ/lisk/pull/644

**Comment by Isabello** [comment]
Closed by: #679
