### ISSUE TITLE
disable case-sensitive delegate

### ISSUE THREAD

**Issue by Stoner19** [LiskHQ/lisk#68]
We've already seen multiple incidents in which users have registered with another's nick/delegate name and changed nothing other than a upper or lower case letter. If case-sensitive letters for delegate names is disabled the we won't have to deal with as many issues of delegate impersonation.

**Comment by qtipwax** [comment]
Probably should combine these because seems to be the same enhancement?  Account name not case sensitive is already listed as an enhancement.

**Comment by karmacoma** [comment]
Yes there is already #8 which is also the same enhancement. We will resolve there. Will close as duplicate for now.
