### ISSUE TITLE
Add license headers to all files

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk#680]

**Comment by anonrose** [comment]
@willclarktech Same license found here? https://github.com/LiskHQ/lisk#license

**Comment by willclarktech** [comment]
@anonrose It should be just the header. @Isabello can you advise?

**Comment by karmacoma** [comment]
@willclarktech Should this be included as part of? https://github.com/LiskHQ/lisk/issues/672

**Comment by willclarktech** [comment]
@karmacoma Makes sense, I've added it to the tasklist.
