### ISSUE TITLE
List peers as normalised objects

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#681]
There is the remaining issue introduced by merging the Web Socket protocol change branch regarding returning of non-normalized peers from public `api/peers` and internal `list` endpoints.

### Current behaviour
`__private.getByFilter` and `Peers.prototype.list` functions exposed for external usage returns peers as `Peer` instances always.

### Expected behaviour
Provide parameter for `__private.getByFilter` and `Peers.prototype.list` functions to customize normalization of returning peers.

**Comment by karmacoma** [comment]
@MaciejBaj By normalised objects, you are referring to this behaviour?

https://github.com/LiskHQ/lisk/blob/development/logic/peer.js#L123
