### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#69]
about this code: https://github.com/LiskHQ/lisk/blob/0d6c94768f212a23687fa58d8faae4782ede3b37/helpers/database.js

you should move all that SQL into an external SQL file that starts with `BEGIN` and ends with `COMMIT`, and then use [Query Files](https://github.com/vitaly-t/pg-promise#query-files) to load it, and then execute it as one command.

**Comment by karmacoma** [comment]
@vitaly-t Thank you for the hint, much appreciated 👍

**Comment by vitaly-t** [comment]
@karmacoma you are welcome!

I've noticed that you haven't removed the loop there: https://github.com/LiskHQ/lisk/blob/development/helpers/database.js#L29

Which is now pointless, since you have just one file.

Also, it makes initializing the library and pg-monitor outside (globally) ;)
