### ISSUE TITLE
Unify JSDoc's parameters upper/lower cases

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#691]
There is an inconsistency across our code base in the way we are specifying parameters in JSDoc function descriptions. My suggestion is to use parameter types in the case specified by [JSDoc's documentation](http://usejsdoc.org/tags-type.html)

### Expected behaviour
- uppercase letters for `Object`, `Array` and custom types
- lowercase letters for `string`, `number`, `boolean`, `function`

### Current behaviour
inconsistent parameters description

**Comment by 4miners** [comment]
Would be nice to enforce it via https://github.com/gajus/eslint-plugin-jsdoc
