### ISSUE TITLE
Lisk.sh status should be more verbose

### ISSUE THREAD

**Issue by 4fryn** [LiskHQ/lisk#692]
$ bash lisk.sh status
    √ Lisk is running as PID: 11250
    Current Block Height:  2876743

It should also print out information about:

- [ ] node (ip, address, port, ssl, ...)
- [ ] network (testnet, main)
- [ ] health (connected peers, block number versus chain head)
- [ ] forging status (on, off, delegate)

**Comment by Isabello** [comment]
This is not the right repository for this issue.
