### ISSUE TITLE
Browserify Fails

### ISSUE THREAD

**Issue by whitj00** [LiskHQ/lisk#7]
Running "browserify:release" (browserify) task
>> /root/lisk/public/node_modules/bitcore-mnemonic/node_modules/bitcore/node_modules/bn.js/lib/bn.js:1338
>>     res = w === num ? 0 :
>>                          ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.

**Comment by karmacoma** [comment]
As per our chat discussion, this was because of a failed download while installing node modules.

Thanks for reporting the issue though :+1:
