### ISSUE TITLE
After enabling 2nd Passphrase it's impossible to vote 

### ISSUE THREAD

**Issue by pilldriver** [LiskHQ/lisk#70]
After enabling a 2nd passphrase in version 0.2.0 its impossible to vote or unvote.

**Comment by arisAlexis** [comment]
+1 . I personally tried to login with my second passphrase too but another user didn't so not sure if its the case.

screen freezes all browsers.

**Comment by Gr33nDrag0n69** [comment]
Using v0.2.0, i registered my delegate
I voted unvoted a couple of time it worked.
After I added a 2nd passphrase, when i vote / unvote
the screen goes with grey overlay and stay stucked there
I tried doing a transaction using 2nd passphrase (send lisk) and it worked. I retried vote after transaction without login out, it didn't change anything

**Comment by D4O** [comment]
had same issue, made 30 votes as delegate without 2nd passphrase
Then registered 2nd passphrase.
After that I could not get past confirm vote page. 
Window to enter 2nd passphrase prompt was suppose to pop up but didn't. 
Background with grey overlay stuck there. 
Could only navigate with keyboard not mouse. 
Sending coins still works with 2nd passphrase.

**Comment by eclipsun** [comment]
Same problem for me. Set 2nd passphrase and now unable too vote. Freezes with grey overlay.

**Comment by fix** [comment]
I managed to vote with my second passphrase with the mobile lite client, so i guess the UI issue only

**Comment by karmacoma** [comment]
I will fix issue later today. It's a UI issue for sure.

**Comment by karmacoma** [comment]
Closing issue here. I will resolve it in lisk-ui submodule: https://github.com/LiskHQ/lisk-ui/issues/30
