### ISSUE TITLE
Lisk API call api/accounts no longer returns username

### ISSUE THREAD

**Issue by mrv777** [LiskHQ/lisk#71]
Not sure if this was on purpose or an accident, but on 0.1.4 api/accounts returned the username of the account too, on 0.2.0 api/accounts no longer does

**Comment by karmacoma** [comment]
Usernames and contacts have been removed from the mainchain. They will be reintroduced at a later stage in the form of a dedicated sidechain. Please see: https://blog.lisk.io/lisk-the-first-modular-crypto-currency-dd3e8df87613#.9pb39dcwn. Note: Delegate names are still present.
