### ISSUE TITLE
Homepage says "Cannot GET /" after a reboot

### ISSUE THREAD

**Issue by metal494** [LiskHQ/lisk#72]
In the logs I get:
error error: could not connect to server: Connection refused
After a bash lisk.sh restart It becomes available again and loads fine, It seems the postgre DB dont load in time after a reboot (tested on two different vps), so I added a "sleep x" seconds to crontab job and still testing...

EDIT: Adding a 3 seconds sleep mitigate the problem, after many many tries it get a refused connection on reboot but then it loads normally (Cannot GET appears for a second refreshing the page many times on loading)

EDIT2: Adding a 5 seconds pause delay I dont get problems.

**Comment by fix** [comment]
try to add `sudo update-rc.d postgresql enable` on ubuntu, so postgresql restart at boot time

**Comment by fix** [comment]
it should be now fixed with last version 0.2.2 since postgresql is not a service anymore

**Comment by fix** [comment]
@metal494 can you update on this issue? Is the fix i proposed works?

**Comment by metal494** [comment]
As you said the new version is different, I dont have postgresql installed, and in the 0.2.1 I couldn't test your proposed fix. I think this problem dont happen anymore and the new lisk.sh address that issues.

**Comment by fix** [comment]
ok closing it

**Comment by VivekAusekar** [comment]
I have created basic application. and registered fro delegate also made vote for self and launched application. Enabled forging. It is forked name 'bitbooks'.

because i was facing some issues i have made resetup for testnet on my server. Currently I am facing issue 'Cannot GET /' on testnet. also not able to start lisk using cold start, rebuild as well as reload.

Any suggestions?

**Comment by metal494** [comment]
Delete the directory and start again, I was facing the same problem yesterday coldstart not working, I think it was a DB issue I couldn't find, in my crontab there was an error calling the old lisk method via root account, check permissions Lisk and all this process must be run on normal user not root

**Comment by VivekAusekar** [comment]
Thanks. Yes, It is DB issue, Postgres was not able to create db. Also lisk was not able to start, I have removed all Postgres packages, apache2 and reinstalled apache2 and new version of lisk. Killed all running processes also performed system reboot and Now its working fine.
