### ISSUE TITLE
Update `decryptAES256GCMWithPassword` in `lisk-cryptography`

### ISSUE THREAD

**Issue by mitsuaki-u** [LiskHQ/lisk#7205]
### Description

`decryptAES256GCMWithPassword` should be updated to decrypt `argon-2`

```
const decryptAES256GCMWithPassword
= (
   {
     encryptedPassphrase: EncryptedPassphraseObject,
     password: string,
   }
): string => 
```

### Acceptance Criteria

- Add unit tests

**Comment by Supportsteam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/
