### ISSUE TITLE
Standardise requirement of modules within tests

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#723]
In our unit tests, we are requiring `async` and `chai.expect` in `test/node.js`. However, we are also requiring separately in each test file. This is a unnecessary duplication.

Currently we are doing:

```js
var async = require('async');
var expect = require('chai').expect;
```

But in other tests we are doing:

```js
var node = require('../node.js');

node.async.each(array, function (item, eachCb) {}); 
node.expect(array).to.be.an('array');
```

As the `test/node.js` file is being included across our tests, it makes sense to access these modules from this central point.

**Comment by karmacoma** [comment]
Related to: #717

**Comment by MaciejBaj** [comment]
Including node.js file in any test enforces to have the lisk application running on port 4000 (`waitUntilBlockchainReady` function is always being executed after requiring the file). As it necessary in terms of running functional test, it is totally unusable while running unit tests. I would rather say to require libraries in every test file independent, regarding each of test needs. The libraries binded to `node` object so far: `lodash`, `popsicle`, `expect`, `chai`, `lisk-js`, `supertest`

**Comment by karmacoma** [comment]
@MaciejBaj We therefore need to split the test helper into separate modules, one per test type. Already suggested by @Isabello in #717, of which this is a child issue.

**Comment by karmacoma** [comment]
Closing in favour of #717
