### ISSUE TITLE
Add missing unit tests for `validators` module [API section]

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk#7264]
**Description**

**_registerValidatorKeys_**

- validatorAddress is shorter than 20 bytes (- returns False - no entry created in validators data and registered BLS keys substore)
-  validatorAddress is longer than 20 bytes (- returns False - no entry created in validators data and registered BLS keys substore)
 
 
-  generatorKey is shorter than 32 bytes - all other arguments are valid (- returns False, - no entry created in validators data and registered BLS keys substore)
-  generatorKey is longer than 32 bytes - all other arguments are valid" (- returns False - no entry created in validators data and registered BLS keys substore)

- BLSKey is shorter than 48 bytes - all other arguments are valid ( - returns False - no entry created in validators data and registered BLS keys substore)
- BLSKey is longer than 48 bytes - all other arguments are valid ( - returns False - no entry created in validators data and registered BLS keys substore)

***getValidatorAccount***
- Validators data substore has no entry for the input validatorAddress (returns an empty object)

***getGenesisData***
- call function (returns the genesis data)

***setValidatorBLSKey***

- Valid input - Validators data substore has an entry for the input validatorAddress. - BLS key of respecitve account is set to the predefined invalid BLS key - Input BLS key IS contained in the registered BLS keys substore (- returns False - no new state entries created or changed)
- Valid input - Validators data substore has an entry for the input validatorAddress, and the BLS key is NOT the predefined invalid BLS key (- returns False - no new state entries created or changed)

- validatorAddress is shorter than 20 bytes - all other arguments are valid (- returns False  - no new state entries created or changed)
- validatorAddress is longer than 20 bytes - all other arguments are valid (- returns False  - no new state entries created or changed)

- BLSKey is shorter than 48 bytes - all other arguments are valid (- returns False - no new state entries created or changed)
- BLSKey is longer than 48 bytes - all other arguments are valid (- returns False - no new state entries created or changed)

***setValidatorGeneratorKey***

- Valid input - Validators data substore has an entry for the input validatorAddress - Input generatorKey is different to the one in the validators data substore (- return True - respective generatorKey is updated)
- Valid input - Validators data substore has an entry for the input validatorAddress - Input generatorKey is the same as the one in the validators data substore (- return True)

- validatorAddress is shorter than 20 bytes (- returns False - no entry created in validators data and registered BLS keys substore)
- validatorAddress is longer than 20 bytes (- returns False - no entry created in validators data and registered BLS keys substore)

- generatorKey is shorter than 32 bytes - all other arguments are valid (- returns False, - no entry created in validators data and registered BLS keys substore)

- generatorKey is longer than 32 bytes - all other arguments are valid" (- returns False - no entry created in validators data and registered BLS keys substore)

***getAddressFromBLSKey***

- registered BLS keys substore has an entry for the input BLS key (- returns the corresponding address)
- registered BLS keys substore has no entry for the input BLS key (- return an error)
- BLSKey is shorter than 48 bytes - all other arguments are valid (- return an error)
- BLSKey is longer than 48 bytes - all other arguments are valid (- return an error)

***getGeneratorList***
- call function (returns the entry form the generator list substore)

***getSlotNumber***

- timestamp < genesisData.timestamp (throw an error)
- timestamp == genesisData.timestamp (return 0)
- timestamp == (genesisData.timestamp + x * BLOCK_TIME) for a positive integer x (return x)
- timestamp == (genesisData.timestamp + x * BLOCK_TIME - 1) for a positive integer x (return x-1)

***getSlotTime***

- slotNumber < 0 (throw an error)
- slotNumber = 0 (return genesisData.timestamp)
- slotNumber = x for a positive integer x (return genesisData.timestamp + BLOCK_TIME*x)

***getGeneratorAtTimestamp***

- timestamp < genesisData.timestamp (?) check `Validators Module` Google sheet for expected value
- timestamp = genesisData.timestamp (return generatorList.addresses[0])
- timestamp = genesisData.timestamp +BLOCK_TIME*(length of generator list + 2) (return generatorList.addresses[2])
- timestamp = genesisData.timestamp +BLOCK_TIME*(length of generator list + 2) -1 (return generatorList.addresses[1])

**Which version(s) does this affect? (Environment, OS, etc...)**
Lisk SDK `development` branch

**Comment by Incede** [comment]
Superseded by #7851
