### ISSUE TITLE
Fix registering delegate twice before confirmation

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#729]
Core is allowing two instantaneous registrations of the same delegate, validating them and causing a bug.

Here the related line:
https://github.com/LiskHQ/lisk/blob/28201773982425bfde2126bd471846a58fb05364/logic/delegate.js#L97

**Comment by karmacoma** [comment]
Closed by `0.9.10` patch release already. Merge is being ported into `1.0.0` here: https://github.com/LiskHQ/lisk/issues/909
