### ISSUE TITLE
Update lisk-js devDependency

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#737]
In order to get better aligned to the performed work by @Tosch110 and @willclarktech, we propose to create a new branch `1.0.0-dev` in `lisk-js` and update devDependencies in core.

**Comment by willclarktech** [comment]
`1.0.0-dev` has been created in `lisk-js`. As of now it's up to date with `1.0.0` but includes the build `dist-node` directory in version control, so that running `npm install` in core won't require a manual install/build step for `lisk-js`.
