### ISSUE TITLE
Getting LNK1181 error while installing dependency 

### ISSUE THREAD

**Issue by ashishghumnar** [LiskHQ/lisk#741]
Can some one help ?

LINK : fatal error LNK1181: cannot open input file 'libpq.lib' [..\node_modules\libpq\build\addon.vcxproj]

**Comment by 4miners** [comment]
@ashishghumnar Can you provide more details? Like operation system, node.js version, npm version.

**Comment by ashishghumnar** [comment]
Here are the details:

OS: Windows 10,  64-bit OS
Node Version : 6.10.1
npm version : 3.10.10
PostgreSQL : 6.2

**Comment by karmacoma** [comment]
Sorry, we do not currently support Windows as a platform for operating a Lisk node.
