### ISSUE TITLE
Regressions in multisignatures schema validations

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#744]
I've found several regressions/bugs introduced onto the branch 1.0.0. They are related to multisignatures schema validations. Below the expected use cases:
- **keysgroup** array: 
  - length between 1 and 15
  - sender not included
  - must use + operator not other
- **min** integer: 
  - between 2 and 16 
  - always smaller than or equal to keysgroup.length + 1
 
In order to help to fix the issue, I've identified some bugs listed below but there should be more:
- min should be between 2 and 16 instead of 1 and 16
- Using another operator throws an error
- Erroneous message `Invalid multisignature min. Must be less than keysgroup size`

Therefore, we need to revise all the checks and error messages.

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk/commit/c4eb55057fb5137e41c0da65ae86e1a5e2250f42
