### ISSUE TITLE
Transaction length check not applied on `chain_getTransactionByID` params { id:....}

### ISSUE THREAD

**Issue by sitetester** [LiskHQ/lisk#7491]
### Expected behavior
It should return JSON only for valid transaction ID (without extra character/number at the end)

### Actual behavior
Currently it returns JSON for ID with extra integer at the end also

### Steps to reproduce

- **Valid transaction ID**
<img width="1241" alt="chain_getTransactionByIDSMALL" src="https://user-images.githubusercontent.com/1403133/188687663-bed2a9d5-249b-491e-8ddf-aa312c08d749.png">

- **Invalid transaction ID** (note one extra `1` at the end)
<img width="1252" alt="chain_getTransactionByIDWithExra1" src="https://user-images.githubusercontent.com/1403133/188687479-747c11b8-39ce-4523-b447-af0611e20474.png">

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0

**Comment by Phanco** [comment]
It seems that this issue has been resolved:

By 26/Oct/2023
Calling with valid id and length: `2165aabd653f103fd214169c9830d36ddcfde25f0f09e4b3ebff5d777f0fb9ee`
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "chain_getTransactionByID",
    "params": {
        "id": "2165aabd653f103fd214169c9830d36ddcfde25f0f09e4b3ebff5d777f0fb9ee"
    }
}
```
Result:
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "module": "interoperability",
        "command": "registerSidechain",
        "params": "...",
        "nonce": "0",
        "fee": "2000000000",
        "senderPublicKey": "3a2e676e768c2bcd3e6419ef1b624cc56347c2a4e73d6d456ca13a5193735902",
        "signatures": [
            "..."
        ],
        "id": "2165aabd653f103fd214169c9830d36ddcfde25f0f09e4b3ebff5d777f0fb9ee"
    }
}
```

Calling with the above id, appending `1` to the end
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "chain_getTransactionByID",
    "params": {
        "id": "2165aabd653f103fd214169c9830d36ddcfde25f0f09e4b3ebff5d777f0fb9ee1"
    }
}
```
Result:
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "message": "Invalid parameters. id must be a valid hex string.",
        "code": -32600
    }
}
```

**Comment by Phanco** [comment]
@sitetester if confirm, this issue can be closed without code change :D
