### ISSUE TITLE
cannot start lisk version from github 

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#75]
lisk version 0.2.0
If I try to start the client I got the following error:
```
$ node app.js 
fatal 2016-04-30 20:27:33 Domain master { message: 'Cannot find module \'pg-native\'',
  stack: 'Error: Cannot find module \'pg-native\'\n    at Function.Module._resolveFilename (module.js:336:15)\n    at Function.Module._load (module.js:278:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at Object.<anonymous> (/home/jens/src/coins/lisk/lisk/node_modules/pg-promise/node_modules/pg/lib/native/index.js:1:76)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)' }
```
After this, the config.json file is empty

I restored the config.json file and installed the pg-native module.
Now I got an postgres authentication error

**Comment by karmacoma** [comment]
@TheGoldenEye pg-native requires some compilation of code, please check for any errors when running npm install. Also: `apt-get install libpq-dev` might help.

Regarding postgres authentication, make sure the password set when running the following command is the same as defined in config.json -> db -> password.

```
sudo -u postgres createuser --createdb --password $USER
```

**Comment by TheGoldenEye** [comment]
Thanks, succeeded. 
`apt-get install libpq-dev` was missing.

**Comment by vitaly-t** [comment]
I have just added a PR for better reference to pg-promise and its dependencies.

The latest 4.0.4, for example, fixes the issue of authentication under Node.js 6.x
