### ISSUE TITLE
Remove the usage of this variables in all transaction types

### ISSUE THREAD

**Issue by SargeKhan** [LiskHQ/lisk#750]
We call functions of transactions types by assigning the value of `this` variable from main `/logic/transaction.js` file. For example, [In multisignature transaction objectNormalize function](https://github.com/LiskHQ/lisk/blob/development/logic/multisignature.js#L352), we have:
```
Multisignature.prototype.objectNormalize = function (trs) {
	var report = library.schema.validate(trs.asset.multisignature, Multisignature.prototype.schema);

	if (!report) {
		throw 'Failed to validate multisignature schema: ' + this.scope.schema.getLastErrors().map(function (err) {
			return err.message;
		}).join(', ');
	}

	return trs;
};
```
We use `library.schema.validate` for generating report, whereas we use `this.scope.schema.` to get the errors. We do not define `this.scope` variable in `multisignature.js` file, it works because we call `objectNormalize` of multisignature trs from `logic/transaction.js` file which has already defined `this.scope` variable. It works, but it is inconsistent and makes the code hard to understand.

**Comment by igy254** [comment]
Hi, do you need help with this? I would love to get involved, and for start solve few easy problems.
