### ISSUE TITLE
Lisk documentation can't be updated

### ISSUE THREAD

**Issue by andreafspeziale** [LiskHQ/lisk#752]
Hi team,
recently the Lisk documentation has been updated and moved here https://docs.lisk.io/docs .

Great work.
I was trying to improve it, in particular I wanted to add an API call for Accounts that seems to be not reported:

Endpoint
/api/accounts?publicKey=publicKey

Code
https://github.com/LiskHQ/lisk/blob/development/schema/accounts.js#L53

Example
https://login.lisk.io/api/accounts?publicKey=e0f1c6cca365cd61bbb01cfb454828a698fa4b7170e85a597dde510567f9dda5

but when I'm trying to update / suggest the edit I get a blank page.
I don't know where to report this problem, hope you don't mind if I'm reporting it here.

This is a screenshot of the blank page using Chrome and Firefox too:

![schermata 2017-08-28 alle 17 47 05](https://user-images.githubusercontent.com/7680940/29781917-0e588d62-8c1b-11e7-9b67-8d68fee17d93.png)

**Comment by Isabello** [comment]
This is not the place for this. Please log a ticket on zendesk. https://lisk.zendesk.com/hc/en-us

**Comment by Isabello** [comment]
I have fixed this for you by the way.
