### ISSUE TITLE
Revert rounds rewrite changes

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#771]
Rounds rewrite is not so portable. Therefore we need to revert it and backport the changes to rounds done in Master, then reclaim desireable changes afterwards.

Task list:
- [ ] Write tests for rounds agains `master` branch https://github.com/LiskHQ/lisk/issues/774
- [ ] Revert PR https://github.com/LiskHQ/lisk/pull/597
- [ ] Backport changes to rounds from `master`
- [ ] Compare tests results
- [ ] Adjust other tests to comply with reverted code

**Comment by karmacoma** [comment]
My sincere apologies @4miners @Isabello, we won't revert these changes. They are very good.
