### ISSUE TITLE
previousBlock is null

### ISSUE THREAD

**Issue by slasheks** [LiskHQ/lisk#78]
After seeing previousBlock is null node stopped. 

```
480910 {"level":"info","message":"Looking for common block with 104.207.130.143:7000","timestamp":"2016-05-01 12:25:51"}
480911 {"level":"info","message":"Found common block 18188596760680562706 (at 14646) with peer 104.207.130.143:7000","timestamp":"20       16-05-01 12:25:51"}
480912 {"level":"error","message":"Blocks timer:","timestamp":"2016-05-01 12:25:51","data":"previousBlock is null"}
480913 {"level":"fatal","message":"System error","timestamp":"2016-05-01 12:25:51","data":{"message":"Cannot read property 'id' of u       ndefined","stack":"TypeError: Cannot read property 'id' of undefined\n    at Function.<anonymous> (/opt/lisk/lisk-Linux-x86_6       4/app.js:4:28400)\n    at f.__tick (/opt/lisk/lisk-Linux-x86_64/app.js:2:16066)\n    at d [as _onTimeout] (/opt/lisk/lisk-Lin       ux-x86_64/app.js:2:15786)\n    at Timer.listOnTimeout (timers.js:119:15)"}}
480914 {"level":"info","message":"Cleaning up...","timestamp":"2016-05-01 12:25:51"}
```

**Comment by Odsejen** [comment]
Got the same message at block 14646
log 2016-05-01 12:25:42 POST /peer/blocks from 194.116.72.38
log 2016-05-01 12:25:42 POST /peer/blocks from 52.63.172.41
info 201605-01 12:25:42 Found common block 18188596760680562706 (at 14646) with peer 52.63.172.41:7000
error 2016-05-01 12:25:42 Blocks timer: previousBlock is null

**Comment by cezarsn** [comment]
Also the timestamp create teh same issue

log 2016-05-01 17:00:58 POST /peer/blocks from 63.142.254.178
log 2016-05-01 17:00:58 POST /peer/blocks from 192.99.232.52
info 2016-05-01 17:00:58 Found common block 18188596760680562706 (at 14646) with peer 45.32.249.199:7000
error 2016-05-01 17:00:58 Blocks timer: previousBlock is null
fatal 2016-05-01 17:00:59 System error { message: 'Cannot read property \'timestamp\' of undefined',
  stack: 'TypeError: Cannot read property \'timestamp\' of undefined\n    at Object.u.loop (/opt/lisk/lisk-Linux-x86_64/app.js:7:6342)\n    at a [as _onTimeout] (/opt/lisk/lisk-Linux-x86_64/app.js:7:14254)\n    at Timer.listOnTimeout (timers.js:119:15)' }
info 2016-05-01 17:00:59 Cleaning up...
info 2016-05-01 17:00:59 Cleaned up successfully
error 2016-05-01 17:00:59 null

**Comment by fix** [comment]
i think this is fixed now
