### ISSUE TITLE
Error in parsing POST message 

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#79]
The server died with the following error:

log 2016-05-01 12:26:41 POST /peer/blocks from 194.135.92.93

fatal 2016-05-01 12:26:41 System error { message: 'Cannot read property \'id\' of undefined',
  stack: 'TypeError: Cannot read property \'id\' of undefined\n
  	at Function.<anonymous> (/opt/lisk/lisk-Linux-x86_64/app.js:4:28400)\n    
  	at f.__tick (/opt/lisk/lisk-Linux-x86_64/app.js:2:16066)\n
    at d [as _onTimeout] (/opt/lisk/lisk-Linux-x86_64/app.js:2:15786)\n    
  	at Timer.listOnTimeout (timers.js:119:15)' }

info 2016-05-01 12:26:41 Cleaning up...
log 2016-05-01 12:26:41 POST /peer/blocks from 84.200.32.172
info 2016-05-01 12:26:41 Cleaned up successfully
error 2016-05-01 12:26:41 null
error: Forever detected script exited with code: 1

Sorry ...can be archived ..there is already one filed with the same issue

**Comment by karmacoma** [comment]
Okay thanks for reporting 👍  I noticed the same issue during the fork we experienced. Closing this issue and will keep #78 open until resolved.
