### ISSUE TITLE
Tests skeletons 

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#792]
Many files are still missing unit tests. The good step before moving to actual testing would be to create a tests skeletons - empty tests descriptions with detailed specification of all possible actions. The task will be extremely helpful before moving to API Refactor #225, which will modify the modules files a lot. That's why creating skeletons for modules should have a priority.
Missing test files:

Modules: 
- [x] blocks/api
- [x] blocks/chain
- [x] blocks/utils
- [x] blocks
- [x] dapps
- [x] loader
- [x] multisignatures
- [x] signatures
- [x] system
- [ ] transport - https://github.com/LiskHQ/lisk/issues/838

**Comment by Isabello** [comment]
Closed since all skeletons were merged.

**Comment by Isabello** [comment]
Reopened, seems transport was missed

**Comment by Isabello** [comment]
Closed by : 8130018
