### ISSUE TITLE
Schema totalAmount should perform the check with Bignum

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#797]
RIght now, the schema check is useless. We need to change the totalAmount check in logic to use Bignum.

https://github.com/LiskHQ/lisk/blob/5694df5d734c9d5a5a4f32674ae57acfd476ded0/logic/transaction.js#L527

It should be completed with some unit tests addressing this part of the code.

**Comment by 4miners** [comment]
Will be solved as part of https://github.com/LiskHQ/lisk/issues/883
