### ISSUE TITLE
Delegate usernames should be case-insensitive

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#8]
Currently delegate usernames are **case-insenstive**, meaning for example, "MyDelegate" and "mydelegate" would result in two delegate usernames being registered. Needs to be fixed :)

**Comment by fix** [comment]
to be corrected: 
https://github.com/LiskHQ/lisk-cli/blob/development/helpers/block.js#L95

**Comment by mrv777** [comment]
Should you also enforce it in the database?
http://stackoverflow.com/questions/9046825/postgresql-auto-lowercase-text-while-or-before-inserting-to-a-column
