### ISSUE TITLE
Feature Request: Add log file path in the config.json file

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#80]
I heard that now logs won't be wiped anymore on service restart. I think default log can stay under the lisk client directory but it would be a nice feature that the path to the log file would be in the config.json. That way we can defined /var/log/lisk/lisk-client.log for logging and use the right partition for the logging. would also be simpler for logrotate implementation.

**Comment by karmacoma** [comment]
Thanks for the request @Gr33nDrag0n69 👍 

Issue now resolved in #84 by @TheGoldenEye
