### ISSUE TITLE
PUT /api/multisignatures problem

### ISSUE THREAD

**Issue by alesl** [LiskHQ/lisk#801]
I trying to create multisig account, transaction is accepted (I get successful response including 
transactionId), but transaction is never broadcasted/mined (I don't see it in explorer).

This is example request:
```
{
    "secret": "word1 word2 ...",
    "lifetime": 1,
    "min": 2,
    "keysgroup": ["+pubkey1", "+pubkey2"]
}
```

Am I doing something wrong?

**Comment by karmacoma** [comment]
Hi,

You are not doing anything wrong. Support for multisignature is limited to our backend API only at the moment.

Once processed the multisignature transaction is queued and waits there until it receives all signatures. You can access the transaction using the endpoint: `GET /api/transactions/multisignatures/get?id=transactionId`

In the current API, you can sign this transaction using: `POST /multisignatures/sign`

Note: In version `1.0.0` the API is being redesigned / streamlined. Therefore will soon change for the better.
