### ISSUE TITLE
After mocha blocks delayed execution due to invisible it blocks

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#803]
Due to the way we have defined `SchemaDynamicTest`, some `after` blocks are triggered at the end of the batch execution through grunt. 

We should either remove those brittle `after` blocks or change SchemaDynamicTest execution.

Related lines are:
https://github.com/LiskHQ/lisk/blob/5694df5d734c9d5a5a4f32674ae57acfd476ded0/test/unit/helpers/wsApi.js#L83
https://github.com/LiskHQ/lisk/blob/62235a4fca7405d991d9fc6558bfad294fd037e9/test/unit/logic/delegate.js#L451

**Comment by Isabello** [comment]
This should be changed because synced blocks will appear as invisible

**Comment by karmacoma** [comment]
Closed by: https://github.com/LiskHQ/lisk/pull/810
