### ISSUE TITLE
Standardise domain specific variable naming

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#826]
Domain specific variables should be standardised within the application code and tests.

For example, when referencing a transaction, we currently have a mix of:

```js
var transaction;
var trs;
var tx;
var t;
```

It would be better if we chose one and stuck with it throughout the whole code.

**Comment by 4miners** [comment]
I propose `tx` for transaction and `txs` for transactions.

**Comment by MaciejBaj** [comment]
Just `transaction` / `transactions` ?

**Comment by Isabello** [comment]
We will go with `transaction` and `transactions`

**Comment by diego-G** [comment]
To be more explicit about why we reopen the issue, we have recently introduced the concept `tx` related to http://vitaly-t.github.io/pg-promise/Database.html#tx . Then we need to clean the whole repository from the old tx concept. After we merged this PR, still just a few cases in constants as `maxTxsPerQueue`.

**Comment by willclarktech** [comment]
@MaciejBaj Should this issue be closed? #1785 addresses only "transactions" but there might be other terms with similar inconsistencies.

**Comment by diego-G** [comment]
@willclarktech like which ones? @ManuGowda and myself scanned the code several times.

**Comment by willclarktech** [comment]
@diego-G Actually `tx` and `transaction`. See https://github.com/LiskHQ/lisk/blob/development/test/unit/modules/blocks/chain.js
