### ISSUE TITLE
The lisk node should use another db

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#85]
Everything is my own opinion here but i would like to have answers to my concerns.

sqlite was obviously not good enough to power a crypto currency. Pgsql was chosen to solve (and it actually solves very well) the scalability issue. But is creates other one:
- portability: i don't how desktop client, meant for ease of use (installation) can be released. I don't see unsavvy people handling issues with pgsql installation running as a service. The desktop should be as easy to install as copy-paste a folder and clicking an executable to popup the client.
- security: similarly, the pgsql is running its own processus. It is easier for an attacker to change data if not properly secured. I am still talking about desktop client.
- heavy: Pgsql can be heavy, small devices (tablets) can suffer from using it.
- it would be more difficult to implement SPV, or other algo that basically explore the data, but don't want to fireup a database to stay in sync and work on it. See https://bitcoin.org/en/developer-guide#simplified-payment-verification-spv

My overall impression is we should think about a new storage system after mainnet launch. Leveldb is used by ETH and BTC, so it can be a good start.

Please comment!

**Comment by karmacoma** [comment]
Here are my comments:

* **Portability**: Yesterday, I compiled and tested PostgreSQL for ARM devices. I've also compiled versions for Linux, FreeBSD and Darwin: https://github.com/LiskHQ/lisk-build. Windows can be done too. A specially compiled version of PostgreSQL will ship with client as done with SQLite. I would say that's portable enough.
* **Security**: PostgreSQL has a good security/locking model already, it's just a question of implementing it.
* **Heavy**: After our tests performed yesterday. PostgresQL runs on the Raspberry Pi1 and Raspberry Pi2 very well indeed, dramatically better than SQLite ever could. Please test when I release binaries and you will see for yourself. For the first time Lisk is able to utilise all four-cores on a Pi2, the user-interface is snappy, and block processing is efficient. The user-experience is very good. I would have to say it's "lighter" on resources than SQLIte for our intended usage.
* We are not Bitcoin or Ethereum, there are very little points at the schema level to compare with. I also don't think comparisons can be made between a simple key/value store such as LevelDB and a fully-fledged relational database like PostgreSQL, or SQLite for that matter. For example, the Lisk database schema and all the underlying logic is not based around a key/value model but rather a relational one, and to move to one would be severely limiting for our primary use-case of running custom sidechains / dapps.

**Comment by fix** [comment]
Thanks @karmacoma for the reply. My comments here.

- When i say Portability, i am not saying that pgsql is not installable on every os. I am just saying that you install an extra service that will need to be managed. If you see the chat, some "tech" people experience issues with pgsql installation, let me tell you that it will be worse with "normal" people. Managing pgsql is a sport for the user (conflicting ports, process viability). Don't expect people to restart pgsql when they ill reboot, or shutdown via the program manager or the whole thing does not work. Believe me you will see lot's of thing going on... I am really not convinced yet. I hope i am wrong, i really want to see the desktop client out when mainnet is launched!
- Security. I put it here because of lack of my knowledge about how to deal with pg security. An audit from someone knowledgeable would be welcome.
- Heavy. First just look at `top` to see how many pgsql processes are around. And yes running on four core is heavy. Raspberry-pi does not have GUI, people won't run desktop client on a UI less OS, without other software running in parallel (emails, browsers, editors etc...). The point here is not to use all the resources, but the less possible...
- Yes, leveldb is nosql and i think you don't need sql for lisk (maybe i am wrong). This was a design from crypti. But look, the first thing you are doing is to create a layer to mimic mongodb query. SQL is overkilling here and making things more complicated than it should be. So the sdk is full of schema definition to deal with to ensure it works. And you can achieve classic sql query with (non performant) nosql. However to deal with transactions/blocks validation it is as performant as sql.

I have just come across a post about a lisk fork (called RISE) on BTC. One of the main item on the roadmap is to rewrite the db layer to use leveldb... I likely don't know enough crypti/lisk to really have my say but conceptually i really think lisk should be schemaless. Because the blockchain IS the database and any model not matching the "flat" architecture of the blockchain is an extra level of complexity.

Note i am not against sql database, there is some limitations in leveldb also (performance when database is getting big). It just needs more inquiries, and the choice was a bit made without the community awareness.
