### ISSUE TITLE
update npm to v5 & add package-lock.json - Subtask 687

### ISSUE THREAD

**Issue by Tschakki** [LiskHQ/lisk#850]
npm should be updated to version 5, which introduces the package-lock.json file.

The newly created lock file should be added to the repository.

See https://docs.npmjs.com/files/package-locks

Subtask of #687

**Comment by willclarktech** [comment]
@Tschakki @Isabello Consider making use of the `engines` section of `package.json`:
https://docs.npmjs.com/files/package.json#engines
