### ISSUE TITLE
Multisignature signers not having blockId associated in DB

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#853]
When a transaction is written to the blockchain, the sender has its publickey and blockId written to mem_accounts if it does not have these fields populated.

In the case of multisignature registration, the publicKey gets written for the signers, but not the blockId, which leaves them as virgin accounts in the db, even though they are not.

**Comment by karmacoma** [comment]
No longer applicable due to ongoing accounts ledger redesign in `1.0.0`.
