### ISSUE TITLE
Probable memory leak

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#86]
The memory used by the app is slightly the increasing memory used over time.

[
![lisk_0_2_0-ram-2](https://cloud.githubusercontent.com/assets/709388/14977456/4cdfcc0e-1114-11e6-816b-c8d0e5e235ff.png)
](url)

![lisk_0_2_1-cpu3](https://cloud.githubusercontent.com/assets/709388/15097605/c585446c-1520-11e6-9574-da11357a65db.png)

**Comment by viper-tkd** [comment]
It could be just the fact that the DB is growing over time. Does it go back down when you restart or it goes back up to the same level?

**Comment by fix** [comment]
updated with an extra graph, showting RAM used before forks...

**Comment by fix** [comment]
i think this is being fixed with fine tuning from @Isabello. should be better in next version. On watch

**Comment by fix** [comment]
closing it now since many release has been made. Please reopen if sensible.
