### ISSUE TITLE
Add functional tests for exceeding request rate limit

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#869]
Parrent issue: #225 

API Refactor specifies `429` code being returned after requests limit is exceeded. Current codebase already supports the feature, the tests are missing though. 

Tests for every modules endpoint should be added, that will check if a response with code `429` is being returned after exceeding the requests limit specified by `api.options.limits.max` in window of `api.options.limits.windowMs`.

**Comment by karmacoma** [comment]
As part of #899, @nazarhussain has written unit tests which already verify the rate limiting behaves as expected, therefore we won't add functional tests for this.
