### ISSUE TITLE
[API] Get peers list isn't working when using the "state" to filter

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk#87]
I called:

- http://liskbrasil.com/api/peers?state=2
{"success":false,"error":"Expected type string but found type integer"}

- http://liskbrasil.com/api/peers?state=connected
{"success":false,"error":"Peer not found"}

**Comment by karmacoma** [comment]
Thanks for reporting the issue 👍 

It has been resolved here: #77, and will be fixed in 0.2.1 to be released very soon.

**Comment by vrlc92** [comment]
Thanks! I had not seen who had a reported issue.
