### ISSUE TITLE
Idea to explore: letsencrypt client written for nodejs

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#88]
letsencrypt client written for nodejs
https://github.com/Daplie/letsencrypt-express
https://github.com/Daplie/letsencrypt-cli
Maybe the ssl cert generation and renewal in the lisk client could be implemented (as an option command).

**Comment by fix** [comment]
I wonder where you got this idea ;)

**Comment by pilldriver** [comment]
Already mentioned it a few times in chat but there is a tool called acme.sh:
https://github.com/Neilpang/acme.sh

It does standalone server cert issues without the need for apache, nginx etc and automatic renewal. 
Just follow the instructions, generate a standalone cert with the option --certhome /etc/ssl and use that cert location in your config.json.

**Comment by Gr33nDrag0n69** [comment]
https://github.com/certbot/certbot/wiki/Links
is a list of available client

I see 2 problem with auto-renewal
lestencrypt renewal must run as root
renewal must run on port 80 or 443 and this would need to stop lisk client and remove port redirection etc

problem 1 is solved with a sudo comand

problem 2 could be solved by using the port 80 instead of 443 for cert generation. so lisk have 443 redirected and 700 (8000)
and 80 isnt't touched. after renewal just restart lisk clisnt process for reloading of the certs

for reference, lets encrypt client switches:
# Port 80
#--standalone-supported-challenges http-01
# Port 443 (Default)
#--standalone-supported-challenges tls-sni-01

**Comment by pilldriver** [comment]
acme.sh uses nc and only port 80 is used for generation, also it has api integration for cloudflare so no need for open ports.

**Comment by fix** [comment]
@Isabello what about this, should this issue moved to lisk-build somehow?

**Comment by Isabello** [comment]
I am moving this to Lisk build. I will think about the best way to implement.
