### ISSUE TITLE
api/account/open should return username

### ISSUE THREAD

**Issue by fix** [LiskHQ/lisk#9]
Currently, when you open an account, you don't get back your username alongside address, publickey, etc... You likely need it.

Guess changes are to be done here:
https://github.com/LiskHQ/lisk/blob/development/modules/accounts.js#L361

**Comment by karmacoma** [comment]
Thanks for suggestion :+1: 

As per our discussion on chat, we are removing usernames / contacts from the core in favour of a richer implementation as a dapp. Longer term this will keep the main chain much leaner.
