### ISSUE TITLE
Error on validating the peers data 

### ISSUE THREAD

**Issue by cezarsn** [LiskHQ/lisk#90]
The software fail to validate the the ip addresses from the peer update on the request and try to insert bogus information into the database:

log 2016-05-03 22:03:38 GET /api/loader/status/sync from 217.162.254.145
log 2016-05-03 22:03:40 error error: ERROR:  invalid input syntax for type inet: "3232235798"
LINE 1: ...", "state", "os", "sharePort", "version") VALUES ('323223579...
                                                             ^
log 2016-05-03 22:03:40 error query: INSERT INTO peers ("ip", "port", "state", "os", "sharePort", "version") VALUES ('3232235798', 7000, 1, 'linux4.1.13-v7+', 1, '0.1.4') ON CONFLICT DO NOTHING;
error 2016-05-03 22:03:40 Peer#update error
log 2016-05-03 22:03:40 error error: ERROR:  invalid input syntax for type inet: "1519991372"
LINE 1: ...", "state", "os", "sharePort", "version") VALUES ('151999137...
                                                             ^
log 2016-05-03 22:03:40 error query: INSERT INTO peers ("ip", "port", "state", "os", "sharePort", "version") VALUES ('1519991372', 7000, 1, 'linux3.19.0-58-generic', 1, '0.1.2') ON CONFLICT DO NOTHING;
error 2016-05-03 22:03:40 Peer#update error

**Comment by karmacoma** [comment]
@cezarsn This issue is related to a change of column type when moving from SQLite to PostgreSQL.

Older versions of Lisk are using a different integer based format.

Thanks for reporting. We will fix by adding appropriate validations and tests.
