### ISSUE TITLE
Better checks if config.json is available and valid

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk#91]
If config.json isn't available at all, the output is missleading:
cc001@lisk-cc001:/opt/lisk/lisk$ ./lisk.sh coldstart
√ Postgres user created successfully.
√ Postgres database created successfully.
Downloading blockchain snapshot...
√ Blockchain snapshot downloaded successfully.
Restoring blockchain...
√ Blockchain restored successfully.
√ Crontab updated successfully.
√ Lisk started successfully.

./lisk.sh status shows the truth:
X Lisk is not running.

And in the log:
cc001@lisk-cc001:/opt/lisk/lisk$ ./lisk.sh logs
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at c (/opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:1:216)
    at b (/opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:1:1107)
    at Object.<anonymous> (/opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:12:14289)
    at c (/opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:1:477)
    at /opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:12:28516
    at Object.<anonymous> (/opt/lisk/lisk-0.2.1-Linux-x86_64/app.js:12:28554)
error: Forever detected script exited with code: 1

**Comment by mrv777** [comment]
I think it may be sufficient to add `check_status` instead of `echo "√ Lisk started successfully."`  
Maybe with a wait of a second to give it a chance to start

**Comment by fix** [comment]
Is this fixed @Isabello ? I think if not it should be moved to lisk-build

**Comment by karmacoma** [comment]
@simonmorgenthaler @Isabello Okay, I will add a json schema validation. We are using this kind of validation for everything from blocks to transactions, so no reason why we can't use for actual config: https://github.com/zaggino/z-schema
