### ISSUE TITLE
libpq5 dependency

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#94]
the libpq.so.5 in the pgsql/lib directory seems not to be loadable, although the LD_LIBRARY_PATH is correctly set.
```
fatal 2016-05-04 19:01:09 Domain master { message: 'libpq.so.5: cannot open shared object file: No such file or directory',
  stack: 'Error: libpq.so.5: cannot open shared object file: No such file or directory\n    at Error (native)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at bindings (/home/jens/lisk/lisk-0.2.1-Linux-x86_64/node_modules/pg-native/node_modules/libpq/node_modules/bindings/bindings.js:76:44)\n    at Object.<anonymous> (/home/jens/lisk/lisk-0.2.1-Linux-x86_64/node_modules/pg-native/node_modules/libpq/index.js:1:108)\n    at Module._compile (module.js:460:26)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)' }

```

A workaround is the installation of libpq5
`sudo apt-get install libpq5`

If the installation works without this, the library is left from the last postgres installation

**Comment by karmacoma** [comment]
Please can you say which CPU architecture you are using, and also the Ubuntu/Debian version? I would like to replicate this issue so I can resolve it. Thanks.

**Comment by fix** [comment]
- Did you check a md5 of the downloaded package. Looks like a bit shift or something like that.
- Other guess, how did you unpack? with root or other user?, maybe a chmod +x on the lob can solve the issue?

**Comment by TheGoldenEye** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```
```
$ uname -a
Linux vps30 2.6.32-042stab113.12 #1 SMP Fri Jan 22 16:04:50 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by TheGoldenEye** [comment]
```
$ ldd libpq.so.5.8
	linux-vdso.so.1 =>  (0x00007ffeba2ee000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9d06129000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9d05d63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9d06578000)

```

**Comment by TheGoldenEye** [comment]
@fix unpacked as user, access rights are ok

**Comment by TheGoldenEye** [comment]
I checked the issue on three of my vps. All Ubuntu x64, two V14.04.4, the last V16.04.
The behavior is the same everywhere. 
The postgres starts without problems. The node client cannot load libpq.so.5.8.

**Comment by fix** [comment]
interesting you are using kernel 2.6, that is likely the issue for me. Needs more digging though

**Comment by TheGoldenEye** [comment]
No fix, the 3rd vps has Ubuntu 16.04 with kernel 4.4. same issue there.
You cannot reproduce the behavior on your server? Could it be that you have installed the libpq5 package too?
The command "sudo apt-get purge postgresql*" has not uninstalled the postgres dependencies.
Try "sudo apt-get autoremove" to do this.

**Comment by fix** [comment]
No i have not seen (yet) this issue on my different linux. And from fresh VPS, so no pgsql.

What is the result of `ls -ail /home/jens/lisk/lisk-0.2.1-Linux-x86_64/pgsql/lib/`

**Comment by fix** [comment]
and what is the result of (when pgsql is stopped)
`pg_ctl -D /home/jens/lisk/lisk-0.2.1-Linux-x86_64/pgsql/data start &> /dev/null`

**Comment by karmacoma** [comment]
@TheGoldenEye If you do `source env.sh`. What is the output of `echo $LD_LIBRARY_PATH`, can you say? Thanks.

**Comment by TheGoldenEye** [comment]
ls -ail:
![image](https://cloud.githubusercontent.com/assets/17945384/15097983/d2dd3008-152e-11e6-818c-cd855b795437.png)

**Comment by TheGoldenEye** [comment]
@fix 
```
$ pg_ctl -D /home/jens/lisk/lisk-Linux-x86_64/pgsql/data start
server starting
jens@vmd12885:~/lisk/lisk-Linux-x86_64$ LOG:  database system was shut down at 2016-05-08 15:06:24 CEST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

```

**Comment by TheGoldenEye** [comment]
@karmacoma The LibraryPath is set
```
echo $LD_LIBRARY_PATH
/home/jens/lisk/lisk-Linux-x86_64/pgsql/lib:
```

**Comment by fix** [comment]
my $LD_LIBRARY_PATH is empty. The `pg_ctl` command is the one run from `bash lisk.sh start`. so it means the libpq is used to connect to the database from the node.

Did you install node on your own?

**Comment by TheGoldenEye** [comment]
The environment is set in the 5th line of the lisk.sh script. While running lisk.sh your LD_LIBRARY_PATH is set too. 
If I assume, that starting the postgres server uses the libpq5 from pgsql/lib, so the libpq5 should be loaded fine. The postgres database is running!
It is strange, why the libpq5 is not loadable from the lisk client.

No node or nodejs was not installed.

**Comment by fix** [comment]
i agree, this is weird, and the weirdest is that you reproduce it!

maybe more information on how you build your server, vps provider etc...

**Comment by TheGoldenEye** [comment]
The two older have a changing history, but the latest vps was newly setup for lisk 0.2.0. 
All servers had a postgres installation from the debian repos.
Ok, I will put the last server from scratch and will report.

**Comment by TheGoldenEye** [comment]
We are close to the solution.
After reinstalling the vps everything ran smoothly. Now I activated SSL and the error occur.
Background: To allow the node process opening the SSL port without administrative rights, I set the capabilities of the node binary:
`setcap cap_net_bind_service=+ep bin/node`

Maybe a process cannot load a shared object file if this was previously loaded by a process with other capabilities?

**Comment by fix** [comment]
ah, could be that setcap. I have no idea what capabilities is doing exactly, but reading the doc:
http://linux.die.net/man/7/capabilities

I have found a similar issue:
http://bugs.java.com/view_bug.do?bug_id=7157699

bottom-line: capable processus should load libraries from trusted path. It sounds your solution was the right one after all. The other possibility is to add the shipped lib to the trusted path...

**Comment by TheGoldenEye** [comment]
Ok, that seems to be the solution for the capabilities problem. I will try it later today.
Thanks for your help, @fix !

**Comment by TheGoldenEye** [comment]
Adding the pgsql/lib to the trusted pathes works.
Thanks all again!

**Comment by pilldriver** [comment]
Had the same problem on centos 7 but above fix did not work for me.

Changing the coldstart sequence to the code below (adding --locale=C to initdb and removing pg_ctl) worked for me:

`coldstart_lisk() {
  stop_lisk &> /dev/null
  stop_postgresql &> /dev/null
  rm -rf $DB_DATA
  #pg_ctl 
  initdb -D $DB_DATA --locale=C &> /dev/null
  start_postgresql
  sleep 1
  create_user
  create_database
  populate_database
  autostart_cron
  start_lisk
}`

**Comment by TheGoldenEye** [comment]
Seams to be another issue.
Have you called locale-gen ? e.g. "sudo locale-gen de_DE.UTF-8"
What was the exact error message?

**Comment by pilldriver** [comment]
Indeed, seems my OSX terminal was setting incorrect locale settings (LC_CTYPE)..

After changing “Set locale environment variables on startup”  in the terminal settings it seems fixed.
