### ISSUE TITLE
Endless loop when genesisBlock is altered

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk#946]
**Expected behaviour**
1. Service should send error message and stop.

**Actual behaviour**
1. The service, went to an endless loop, sending errors to lisk.log
2. There is an empty error, which prints the string null
```
[ERR] 2017-11-08 13:28:33 | Failed to match genesis block with database
[ERR] 2017-11-08 13:28:33 | null
```

**Steps to reproduce**

1. Edit genesisBlock.json
2. Find the following entry - located at the end of the file.
```
 "height": 1,
  "blockSignature": "c81204bf67474827fd98584e7787084957f42ce8041e713843dd2bb352b73e81143f68bd74b06da8372c43f5e26406c4e7250bbd790396d85dea50d448d62606",
  "id": “6524861224470851796"
```

3. Changed block signature id from “6524861224470851796" “6524861224470851795"
4. Restart the lisk service.
5. Check the logs.

**Comment by nazarhussain** [comment]
@yairlisk On which branch you got this issue? 

I tried to reproduce with following steps; 

1. git checkout 1.0.0
2. cp test/config.json test/genesisBlock.json .
3. Used above test/genesisBlock.json to speed up the blockchain startup 
4. npm start 
5. Now changed the blockSignature id in genesisBlock.json
6. Started the service again. 

It failed with following log messages:

```
[inf] 2017-11-10 15:16:59 | Lisk started: 0.0.0.0:4000
[inf] 2017-11-10 15:16:59 | Modules ready and launched
[inf] 2017-11-10 15:16:59 | Blocks 2
[ERR] 2017-11-10 15:16:59 | Failed to match genesis block with database
[inf] 2017-11-10 15:16:59 | Cleaning up...
[dbg] 2017-11-10 15:16:59 | Export peers to database failed: Peers list empty
[inf] 2017-11-10 15:16:59 | Cleaned up successfully
```
Its showing clearly an error about genesis block mismatch and failed to start. 

Please guide me further how to reproduce this issue, so I can debug it further.

**Comment by yairlisk** [comment]
Bug happens only on version: 0.9.10b

**Comment by 4miners** [comment]
That issue it related to pm2 and should be fixed in lisk-build, new issue: https://github.com/LiskHQ/lisk-build/issues/221
