### ISSUE TITLE
Disable type 6 and 7 transactions

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#951]
In 1.0.0 we should summarily reject these transactions upon receipt until the new implementation for dapps is complete.

**Comment by willclarktech** [comment]
Definitely type 5? People might want to reserve dapp names in advance.

**Comment by Isabello** [comment]
Yes including type 5.

**Comment by karmacoma** [comment]
Based on our discussion @Isabello we will exclude type 5 and only temporarily disable type 6 and 7.

**Comment by karmacoma** [comment]
Suspending until #972 is closed.

**Comment by karmacoma** [comment]
Awakening due to: https://github.com/LiskHQ/lisk/issues/1169
