### ISSUE TITLE
Lisk Nano desktop wallet does not show transferred tokens

### ISSUE THREAD

**Issue by isauditor** [LiskHQ/lisk#952]
Hello! On 10/17/2017 I downloaded the Lisk nano desktop wallet (previous version) and transferred my Lisk token balance from an exchange. Transaction was successful per the Exchange and Lisk Exploer and went to the intended wallet address. Next time when I logged in the wallet, the wallet showed a different address and zero transferred balance. I contacted Lisk Support via email and per their advise upgraded the wallet to the latest version and logged in again to find the same new address and 0 token balance. I was told by the Support that I must be using a different 12 word passphrase. But I generated only one passphrase when I initially downloaded and created the new wallet. It is the same passphrase but now it is logging me into a different wallet with a different address. Can somebody please help me have access to my tokens. Please advise. Thank you.

**Comment by karmacoma** [comment]
Please refer back Lisk Support, where we will try to help you further there. Thanks.

**Comment by isauditor** [comment]
Oliver:
Whom would you like me to get in touch with at the List Support to solve
the issue of my stuck Lisk tokens? Thank you.
