### ISSUE TITLE
registered wallet with a password now requires a passphrase to login

### ISSUE THREAD

**Issue by bananarepublick101** [LiskHQ/lisk#963]
Hi 
please help me clarifying if there have been any changes to the lisk nano wallet logins.
I clearly remember to have opened an account on the 17th of October 2017 using a normal password.
i've transferred my lisk to the wallet but now I cannot login anymore as it require a passphrase which i do not have.
Am I going crazy? was the login always with a passphrase?

thank you

**Comment by karmacoma** [comment]
Yes, login was always with a mnemonic passphrase.

For future reference `lisk-nano` related issues belong here: https://github.com/LiskHQ/lisk-nano where it belongs.
