### ISSUE TITLE
Lisk can not start correctly with test mode

### ISSUE THREAD

**Issue by stone2water** [LiskHQ/lisk#968]
Hi, 

We follow the steps of README to set up Lisk and run it in test mode. ideally, lisk should be listening on two ports,  one is for peer at 5000, and another is for http connection at 4000, however, we only see port 5000 is on, and port 4000 is not .

here is part of config.json:
"
{
    "port": 5000,
    "httpPort": 4000,
...
}
"

In my environment, only 5000 is listing, and 4000 does not. here the result of netstat:
"
ubuntu@VM-121-206-ubuntu:~$ sudo netstat -apn | grep node
tcp        0      0 127.0.0.1:53421         127.0.0.1:5432          ESTABLISHED 24834/node
tcp        0      0 127.0.0.1:53422         127.0.0.1:5432          ESTABLISHED 24834/node
tcp        0      0 127.0.0.1:55488         127.0.0.1:6380          ESTABLISHED 24834/node
tcp6       0      0 :::5000                 :::*                    LISTEN      24855/node
unix  2      [ ACC ]     STREAM     LISTENING     88470943 24847/node          /tmp/socketcluster/lisk_2b6a4939e2/b0
unix  3      [ ]         STREAM     CONNECTED     88470952 24847/node          /tmp/socketcluster/lisk_2b6a4939e2/b0
unix  3      [ ]         STREAM     CONNECTED     88470949 24861/node
unix  3      [ ]         STREAM     CONNECTED     88471895 24834/node
unix  3      [ ]         STREAM     CONNECTED     88471891 24834/node
unix  3      [ ]         STREAM     CONNECTED     88470948 24855/node
unix  3      [ ]         STREAM     CONNECTED     88471896 24855/node
unix  3      [ ]         STREAM     CONNECTED     88471892 24847/node
unix  3      [ ]         STREAM     CONNECTED     88470951 24861/node
"

and there is the log: 
"
(node:24834) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback was already called.
[inf] 2017-11-15 12:09:45 | pg-notify: Initial connection estabilished
[inf] 2017-11-15 12:09:45 | Socket Cluster ready for incoming connections
"

Is there any hint? 

Thanks a lot!

**Comment by 4miners** [comment]
@stone2water Thank you for reporting that. Which branch are you using?

**Comment by stone2water** [comment]
we are using branch 1.0.0-Holding_Zone

**Comment by karmacoma** [comment]
@stone2water The `1.0.0-Holding_Zone` branch was created as a container for some unit tests submitted by a @reasonthearchitect. If you are looking to track `1.0.0` development, then use our `1.0.0` release branch. Otherwise use our `master` branch to work off the latest release `0.9.10`.
