### ISSUE TITLE
Rewrite and extend rounds functional tests

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#969]
Tests for rounds-related SQL triggers needs to be rewritten and extended.

- [x] Test application environment before actual rounds tests
  - [x] Genesis block (with support for custom genesis block)
    - [x] Consistency
    - [x] Insertion
    - [x] Transactions
    - [x] Delegates table after insertion
    - [x] Accounts table after insertion
  - [x] modules.delegates.__private.delegatesList (leave as is)
- [x] Actual rounds tests
  - [x] Rewrite them to be more detailed and atomic. For example if we need forge a block with transaction - all steps should be tested, like:
    - if transaction is present in pool
    - if block was actually forged
    - if transaction was inserted to new block
    - if block and transaction are present in database
  - [x] Rewrite functions for calculating expected delegates and accounts state

**Comment by LucasIsasmendi** [comment]
Closed by #1169
