### ISSUE TITLE
Endpoint not found: Get signature, Register username, Send message.

### ISSUE THREAD

**Issue by vrlc92** [LiskHQ/lisk#97]
These endpoints are present in the documentation, but aren't present on the current version of the platform (0.2.1). 

**Get signature**
Get second signature of account.
GET /api/signatures/get?id=id

**Register username**
Register username.
PUT /api/accounts/username

**Send message**
Send message to recipient.
PUT /api/messages

**API Reference:**
https://lisk.io/documentation?i=lisk-docs/APIReference

**Comment by karmacoma** [comment]
Thanks for point out. Yes, our documentation needs to be updated to reflect recent changes.

```
GET /api/signatures/get?id=id
```

We will add.

```
PUT /api/accounts/username
```

Has been removed from the lisk core. The plan is to reimplement within an "Identity Dapp".

```
PUT /api/messages
```

We will remove. It points to an unimplemented feature.

**Comment by vrlc92** [comment]
Thanks!

I identified other endpoints:

**Removing**
Will return dapps that in uninstalling right now.
GET /api/dapps/removing

**Icon dapp**
Using to get icon of dapp from sia.
GET /api/dapps/icon

**Comment by karmacoma** [comment]
Issue closed in the relevant lisk-docs repository: https://github.com/LiskHQ/lisk-docs/issues/4.

Thanks @vrlc92 👍
