### ISSUE TITLE
Update README.md for 1.0.0

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk#970]
The current `README.md` is based on the `0.9.*` branch and needs to be updated to reflect changes made in `1.0.0`.

Parent: #1176

**Comment by pcdinh** [comment]
Why is it labelled "hard"?

**Comment by willclarktech** [comment]
@pcdinh The difficulty ratings are more a reflection of how long an issue is expected to take than of how tricky they are.

**Comment by karmacoma** [comment]
@Tschakki This issue is now part of #1176, which is responsible for porting changes from `0.9.11` to `1.0.0`.

Please ensure the recently improved section on tests is preserved: https://github.com/LiskHQ/lisk/tree/fd558c724843a12f8ca52b9a49072bf3d9a1d029#tests

Everything else should be directly portable from: https://github.com/LiskHQ/lisk/blob/74d2bebcc322658063f4766ed88bfa72021d5fcc/README.md
