### ISSUE TITLE
Extend accounts SQL functional tests

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#976]
Functional accounts SQL tests needs to be extended:

- [ ] Finish test cases for transactions type 1
- [ ] Add test cases for transactions type 2 to 7
- [ ] Add test cases for mixed transactions types
- [ ] Add tests for delete block case for all transaction types
- [ ] Add concurrency tests (including SQL transactions)

Parent: #972

**Comment by LucasIsasmendi** [comment]
Closed by #1169
