### ISSUE TITLE
Fix intermittent test failures related to data sorting

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#977]
**Expected behaviour** 
Sorting of data returned by database must match with the sorting to native javascript sort method. 

**Actual Behaviour** 
PostgreSQL sort data case insensitive while javascript sort lists by case sensitive manner. So while matching sorted result sets in test cases, they get failed. Since tests rely on randomly generated data, so this behaviour triggered only if data contains some capital or special character.

**Comment by diego-G** [comment]
The issue persists. It needs to be reviewed.
