### ISSUE TITLE
Fees not properly showing on forged blocks

### ISSUE THREAD

**Issue by Stoner19** [LiskHQ/lisk#98]
For the sake of continuity the fees for forged blocks should be rounded to the 8th decimal place. Currently on testnet version 0.2.1 forged blocks are showing 0 LISK earned from fees, but according to the wallet and forged balance there are fees that have been paid to the node.
![screen shot 2016-05-06 at 7 35 22 pm](https://cloud.githubusercontent.com/assets/8030643/15089514/d672f662-13c1-11e6-96c5-702d47786808.png)

![screen shot 2016-05-06 at 7 35 34 pm](https://cloud.githubusercontent.com/assets/8030643/15089515/d8ac919a-13c1-11e6-870d-f2bc95e5e4cc.png)

I understand that the fees are paid every 101 blocks (aka _forging round_), but shouldn't the fees paid still be showing on every 101st block?

**Comment by fix** [comment]
If there is no transaction in block, fee is 0. However the fees are collected for each blocks of the round and then redistributed to all forging delegates.

I am not sure there is an easy way to make it clear. But anyway i think this is an lisk-ui issue, not core issue.

**Comment by Stoner19** [comment]
yes, I agree that its probably just a UI bug, as fees are still paid properly.

**Comment by karmacoma** [comment]
Fees and Rewards are two different things in Lisk. Are you sure the fees are not showing in the UI?

![image](https://cloud.githubusercontent.com/assets/8068/15100655/042d3284-1570-11e6-9414-ea8710197b81.png)

**Comment by mrv777** [comment]
I wondering if it's a rounding issue in the UI?  As I don't believe I've ever seen the fee column ever have more then one decimal place.

and/or it has something to so with what fix mentioned, but can't find the code for that: 

> However the fees are collected for each blocks of the round and then redistributed to all forging delegates.

**Comment by fix** [comment]
per block you will never see other fees than the minimum one: 0.1 for sending lisk: 

100 = delegate registration
5 = extra signature registration
1 = vote
0.1 = send lisk

**Comment by Stoner19** [comment]
I understand that explanation about fees.

I guess what I am referencing is the additional fees paid to forging delegates this is split amongst them every block round (every 101 blocks), per this blog post: https://blog.lisk.io/explaining-lisk-forging-rewards-53d295066be2#.x68dv4362

"After one forging round (i.e. after 101 blocks) all transaction fees are equally distributed between participating delegates, and for every block individually forged, a reward is then issued."

Either way, the forged LISK balance is not equal to that of the list of transactions/earned LISK from forging, so something needs to be updated in the UI to correct this.

**Comment by fix** [comment]
Yes, but is difficult to say. We can divide the fee by 101, but then you have to be aware that you will get some fees from other blocks you have not forged...

I would rather stay to the current solution : you have forged 1 block associated with a reward (that you will receive) and you collected fees (that will be split between the 101 round delegates)

**Comment by fix** [comment]
maybe rename "Fee" to "Redistributed Fee"?

**Comment by karmacoma** [comment]
Fees are distributed equally according to participants in round, where the amounts are added to account balances of each delegate. Both the Fee and Reward are representative of the whole block, not the individual delegate's share.

It's not currently possible to indicate this information without redoing some computation of mem_rounds, which is an intensive process.

One option however would be to record the exact distribution in the another "mem" table, such as "mem_forged". We could then easily retrieve the exact amounts received for an individual or the whole group of delegates for a given block.

**Comment by fix** [comment]
moving label to enhancement

**Comment by fix** [comment]
@Stoner19 can you open this on lisk-ui instead. Closing this since not related to core.
