### ISSUE TITLE
Fix pending failing test for new transaction pool

### ISSUE THREAD

**Issue by LucasIsasmendi** [LiskHQ/lisk#980]
Parent: #972 

Failed local counters for getters:
- [x] getAll / by pool list / should be ok when check pool list unverified
- [x] getAll / by id (address) and publicKey / should be ok when sender account is valid
- [x] getAll / by id (address) and publicKey / should be ok when recipient account is valid
- [x] getAll / by id (address) and publicKey / should be ok when requester publicKey is valid
- [x] ready / method addReady/getReady / should be ok when check ready value decreased in 1

Missed property for getters:
- [x] ready / method addReady/getReady / should be ok when get transactions from ready with limit

Mocha after function
- [x] logger.debug.restore is not a function (**note**: restore is not part of our node spies)

**Comment by karmacoma** [comment]
Closed by #989
