### ISSUE TITLE
Add recipientPublicKey to transaction signature and properties

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#992]
Parent: #972 

In order to support sending by publicKey, we must allow the bytes to be evaluated and added to the signature, while honoring old transactions.

Transactions functions

**verify**
- [ ] validate recipientPublicKey against recipientId if present

**getBytes**
- [ ] Support recipientPublicKey, evaluate presence and signature if present. Needed for BC

**Comment by LucasIsasmendi** [comment]
Closed by #1169
