### ISSUE TITLE
Remove or refactor setSender, merge and mergeAccountAndGet related tests

### ISSUE THREAD

**Issue by Isabello** [LiskHQ/lisk#994]
Parent: #972 

Remove the tests for merge and mergeAccountAndGet. Refactor tests related to setSender

**mergeAccountAndGet**
- [ ] IN TRANSFER unit tests
- [ ] OUT TRANSFER unit tests

**merge**
- [ ] MULTISIGNATURE REGISTRATION unit tests

**getSender**
- [ ] BLOCKS/CHAIN unit tests
- [ ] BLOCKS/VERIFY unit tests
- [ ] SECOND_SIGNATURE unit tests
- [ ] DELEGATE REGISTRATION unit tests
- [ ] DELEGATE VOTE unit tests
- [ ] MULTISIGNATURE REGISTRATION unit tests

**Comment by LucasIsasmendi** [comment]
Closed by #1169
